chipsalliance/rocket-chip

Makefrag

to stdout by this line every time you do anything in the entire repo.

If you don't have spike-disasm in your path, your path is dumped

---

csrc/emulator.cc
csrc/htif_emulator.h
src/main/scala/Configs.scala
src/main/scala/RocketChip.scala
src/main/scala/Vlsi.scala

These changes implement memory-mapped IO in Rocket-Chip by generating a NASTI interconnect from an address map configuration. See the individual submodule PRs for more detailed change information.
[Uncore PR](https://github.com/ucb-bar/uncore/pull/4)
[Junctions PR](https://github.com/ucb-bar/junctions/pull/3)
[Rocket PR](https://github.com/ucb-bar/rocket/pull/11)

Implement NASTI-based Mem/IO interconnect

---

src/main/scala/Configs.scala

This has the rocket changes and some changes to Config.scala.
The main different is that BuildRoCC is now a Seq instead of an Option. In addition, we have two new parameters: RoccOpcodes, which specifies which instructions go to which accelerator, and RoccAcceleratorMemChannels, which specifies how many dmem channels to give each accelerator. The latter should be edited instead of modifying RoccNMemChannels directly.

implement support for multiple RoCC accelerators

---

.gitmodules
fsim/Makefile
regression/.gitignore
regression/Makefile

This should be pretty boring: it's almost all just regression changes.  I'm making a PR because there's two things that people might care about:
* riscv-tools bump (for the Spike NaN change)
* riscv-torture is added as a submodule of rocket-chip.
I added torture because the I want the nightlies to run it, and since different rocket-chip branches might need different tortures (hwacha needs esp-torture, for example) I think it's easiest to just track this like every other submodule.

Support torture regressions

---

src/main/scala/Testing.scala
src/main/scala/Vlsi.scala

This add some amount of Chisel 3 support -- the rest can be found at <http://www.dabbelt.com/~palmer/keep/chisel3-chip/>, but since the easiest way to make that work is to just break Chisel 2 support I'm not going to merge them for now (the buildbot will just patch things itself).

Chisel 3 support

---

Makefrag
csrc/htif_emulator.h
csrc/vcs_main.rocketTestHarness.cc
emulator/Makefile
fsim/Makefrag
src/main/scala/Configs.scala
src/main/scala/RocketChip.scala
src/main/scala/Testing.scala
src/main/scala/Vlsi.scala
vsim/Makefrag

@zhemao these aren't really related, but need to be ordered.

SCR file and NastiMemorySelector changes

---

.travis.yml
regression/Makefile
src/main/scala/Testing.scala

We used to have two regression scripts, now there's one.  This also allows caching of the riscv-tools builds, which should speed up the regressions a lot.

travis-ci.org improvements

---

.travis.yml
regression/Makefile
src/main/scala/Testing.scala

I believe with this Travis should actually work.

More travis fixing

---

src/main/scala/Configs.scala

RoCC PTW refactoring

---

src/main/scala/RocketChip.scala

https://github.com/ucb-bar/uncore/pull/28

Fix the SCR file for Chisel 3

---

.travis.yml
csrc/mm.cc
csrc/mm.h
csrc/mm_dramsim2.cc
csrc/mm_dramsim2.h
src/main/scala/TestBench.scala
src/main/scala/TestConfigs.scala

Until recently, we were assuming that the data channel in AXI was always right-justified. However, for narrow writes, the data must actually be aligned within the byte lanes. This commit changes some of the
converters in order to fix this issue.
Changes to junctions, uncore, and groundtest are on separate axi-fix branches as well.

Fix narrow read/write behavior for AXI converters

---

regression/Makefile

this makes it easier to test chisel3 builds
e.g. the local buildbot can now test a bunch of configs

add firrtl to regression makefile

---

src/main/scala/Configs.scala
vsrc/rocketTestHarness.v

This commit fixes a bug with the TL width adapter and also makes it easier to configure a different inner width for the L1 and L2 caches.

TL Width Fix

---

emulator/Makefrag-emulator
emulator/Makefrag-verilator

Thanks for adding verilator support @donggyukim.  This PR fixes a trivial Makefile problem.

fix make error mixing implicit and normal rules

---

emulator/Makefrag-verilator

These failed for Andrew earlier.  While it might be paranioa, there's
really no reason to build the man pages so we might as well not bother.

Don't build the Verilator man pages

---

csrc/vcs_main.rocketTestHarness.cc
vsim/Makefrag
vsrc/rocketTestHarness.v

Otherwise, we don't get coverage data from the simulator.

Exit from testbench, not C code

---

emulator/Makefrag-verilator
src/main/scala/Configs.scala
src/main/scala/Fpga.scala
src/main/scala/RocketChip.scala
src/main/scala/TestBench.scala
src/main/scala/TestConfigs.scala

The new packages are
* uncore.constants - The M_ and MT_ constants
* uncore.tilelink - TileLink channel definitions, arbiters, network channels, and interconnects
* uncore.coherence - Coherence policy, metadata, and directory definitions
* uncore.agents - L2 coherence agents: Cache, BroadcastHub, Bufferless, and MMIO manager
* uncore.converters - Converters to and from TileLink (AHB, NASTI, SMI)
* uncore.util - Misc. utilities

Refactor uncore to split into separate packages

---

regression/Makefile
src/main/scala/Configs.scala
src/main/scala/TestConfigs.scala

Finally got the bufferless broadcast hub fully working.

Fixing Bufferless Broadcast Hub

---

scripts/check_cache_trace.py
src/main/scala/Configs.scala

This fixes an issue with the L2WritebackUnit which was causing it to incorrectly get voluntary releases allocated to it.
It also adds buffering and locking to the TL -> AXI converter so that read responses cannot be interleaved with write responses.

Fix converter and L2

---

src/main/scala/Configs.scala
src/main/scala/RocketChip.scala

Backport AXI input and multiple output patches from star-chip.

Star chip port

---

src/main/scala/Configs.scala

Create seperate Mul/Div parameters instead of UseFastMulDiv

---

src/main/scala/Configs.scala
src/main/scala/RocketChip.scala

Support AXI from foreign clock domains

rocket: support asynchronous external busses

---

src/main/scala/TestConfigs.scala

This fixes the issue with back-to-back releases that we were seeing on the FPGA. Essentially, if an uncached get was made to block that's held modified in an L1, a probeCopy will be sent, which causes the  L1 to write out the data but not downgrade its state. This meant that the L1 could potentially perform a voluntary release of the same block, causing two releases with data to be sent to the Acquire tracker back-to-back. If the second release for a beat was accepted by the acquire tracker as the corresponding beat for the first release was being sent out to DRAM, the pending bit would get incorrectly cleared. Another issue that could occur would be if the second release beat is accepted while an outer release is in progress but before that particular beat has been sent. In that case, …

L2 back-to-back Release fix

---

regression/Makefile
src/main/scala/Configs.scala
src/main/scala/TestConfigs.scala
src/main/scala/Testing.scala

If NTiles == 1, only use MEI instead of MESI. Also create a configuration which can create a  ManagerToClientStatelessBridge. This is a more polished way of doing what is on the tutorial_demo branch.

Add ManagerToClientStatelessBridge

---

src/main/scala/Configs.scala
src/main/scala/RocketChip.scala

Needed for rocketchip emulations that have access to more memory. 
I don't know if this is how ya'll want to do this in the long run but maybe it's ok for now? 
[PR this for real this time]

make memsize configurable

---

coreplex/src/main/scala/Configs.scala
coreplex/src/main/scala/TestConfigs.scala
groundtest/src/main/scala/Tile.scala
groundtest/src/main/scala/TraceGen.scala
junctions/src/main/scala/addrmap.scala
rocket/src/main/scala/dcache.scala
rocket/src/main/scala/fpu.scala
rocket/src/main/scala/idecode.scala
rocket/src/main/scala/multiplier.scala
rocket/src/main/scala/nbdcache.scala
rocket/src/main/scala/rocket.scala
rocket/src/main/scala/tile.scala
rocket/src/main/scala/tlb.scala
src/main/scala/Configs.scala
src/main/scala/TestConfigs.scala
uncore/src/main/scala/agents/Cache.scala
uncore/src/main/scala/converters/Ahb.scala
uncore/src/main/scala/devices/Bram.scala
uncore/src/main/scala/util/AmoAlu.scala

... in the FPU, MulDiv, D$.
Also, remove parameters for immutable ISA constants.

Un-flatten some Rocket configuration parameters

---

vsim/Makefrag
vsrc/TestDriver.v

Minor test harness changes, Andrew has reviewed already
Should be able to fast-forward this one

Test harness fixes

---

emulator/Makefrag-verilator
src/main/scala/coreplex/Testing.scala
src/main/scala/rocketchip/Generator.scala
vsim/Makefrag-verilog

Remove deprecated call to chiselMain and useless Chisel2 args. Update arguments to sbt run.

Streamline the Generator App and associated utilities. 

---

src/main/scala/junctions/jtag.scala
src/main/scala/rocketchip/DebugTransport.scala
src/main/scala/rocketchip/RocketChip.scala
src/main/scala/rocketchip/TestHarness.scala
vsim/Makefrag
vsrc/jtag_vpi.v

to prevent code duplication for new testbenches

connect testharness components via member functions

---

vsim/Makefile
vsim/Makefrag
vsim/Makefrag-verilog
vsim/vlsi_mem_gen

This PR bumps FIRRTL to enable backend Sequential Memory descriptions.
@shunshou @yunsup I have rebased your earlier changes on top of master for this PR.

Bump FIRRTL for Sequential Memories

---

src/main/scala/junctions/addrmap.scala

now you can add them in any order.  there's an explicit check at the end to figure out whether there are overlapping regions.

relax contraint on adding AddrMapEntry to AddrMap

---

vsim/vlsi_mem_gen

fix null statement in vsli_mem_gen ala firrtl#264

---

src/main/scala/uncore/tilelink2/Bundles.scala
src/main/scala/uncore/tilelink2/Edges.scala
src/main/scala/uncore/tilelink2/Narrower.scala
src/main/scala/uncore/tilelink2/SRAM.scala
src/main/scala/uncore/tilelink2/WidthWidget.scala
src/main/scala/uncore/tilelink2/package.scala

Now supporting bidirectional width conversion between all sizes!

TL2 WidthWidget

---

src/main/scala/uncore/tilelink2/Bundles.scala
src/main/scala/uncore/tilelink2/RegField.scala

Add a Megan-approved RegField helper for interrupt-pending-style masks.

W1 to clear

---

src/main/scala/junctions/crossing.scala
src/main/scala/uncore/tilelink2/RegisterCrossing.scala
vsim/Makefrag
vsrc/ClockToSignal.v
vsrc/SignalToClock.v

This provides some common "utilities" (black box hacks) to do some clock/reset related things that aren't possible in Chisel.

Add some async/clock utilities

---

src/main/scala/rocketchip/Periphery.scala
src/main/scala/rocketchip/Top.scala
src/main/scala/rocketchip/Utils.scala
src/main/scala/uncore/devices/Prci.scala
src/main/scala/uncore/tilelink2/Nodes.scala
src/main/scala/uncore/tilelink2/Parameters.scala
src/main/scala/uncore/tilelink2/TLNodes.scala

Dynamically create address map and config string for all TL2 devices.

Tl2 addrmap

---

src/main/scala/rocketchip/Top.scala
src/main/scala/rocketchip/Utils.scala
src/main/scala/uncore/devices/Rom.scala
src/main/scala/uncore/tilelink2/SRAM.scala

TL2 ROM needs to be executable!

Rom executable

---

src/main/scala/rocketchip/BaseTop.scala
src/main/scala/rocketchip/Periphery.scala
src/main/scala/uncore/devices/Prci.scala
src/main/scala/uncore/tilelink2/Buffer.scala
src/main/scala/uncore/tilelink2/Example.scala
src/main/scala/uncore/tilelink2/Fragmenter.scala
src/main/scala/uncore/tilelink2/Fuzzer.scala
src/main/scala/uncore/tilelink2/HintHandler.scala
src/main/scala/uncore/tilelink2/RegField.scala
src/main/scala/uncore/tilelink2/RegMapper.scala
src/main/scala/uncore/tilelink2/RegisterRouterTest.scala
src/main/scala/uncore/tilelink2/WidthWidget.scala

Now that all the features we need are in, here are the future API changes we want.

Tl2 api changes

---

src/main/scala/uncore/tilelink2/Edges.scala
src/main/scala/uncore/tilelink2/Parameters.scala

@a0u Fixed maxLgSize, as requested

tilelink2: maxLgSize should be accurate

---

src/main/scala/rocketchip/Configs.scala

Make it convenient to switch periphery bus width.

rocketchip: add pbus width and AMO With classes

---

src/main/scala/rocketchip/BaseTop.scala
src/main/scala/rocketchip/Utils.scala

the interrupt ranges are now assigned deterministically.

Deterministic interrupt

---

src/main/scala/junctions/slowio.scala

This is a much more minimal change than before.
Previously, the SlowIO module had a set_divisor valid interface. Sends over it would update two shadow registers, which then get picked up on the falling edge of the clock.
In hurricane2, the host and divisor value will already be held in SCRs, so it doesn't really make sense to use a valid interface into another shadow register.
Instead, we just let the SCRs be the shadow registers and pass their value in directly. Also, I'm separating them out into two different inputs instead of a single combined 32-bit value from which we pick out two 16-bit values. It's less confusing this way. If we want to make sure we set them at the same time, we just merge them into a single status register and break them out accordingly.

Change the configuration interface of SlowIO

---

src/main/scala/uncore/tilelink2/AtomicAutomata.scala
src/main/scala/uncore/tilelink2/Buffer.scala
src/main/scala/uncore/tilelink2/Crossing.scala
src/main/scala/uncore/tilelink2/Fragmenter.scala
src/main/scala/uncore/tilelink2/HintHandler.scala
src/main/scala/uncore/tilelink2/Isolation.scala
src/main/scala/uncore/tilelink2/WidthWidget.scala
src/main/scala/uncore/tilelink2/package.scala

This branch adds a handy Isolation gate insertion module

Tl2 isolation

---

src/main/scala/uncore/tilelink2/Isolation.scala

@terpstra , I've cherry-picked a few of your safer-crossings, to get just the split direction isolation gates part.

tilelink2: split isolation gates by direction

---

src/main/scala/rocketchip/BaseTop.scala
src/main/scala/rocketchip/Configs.scala
src/main/scala/uncore/tilelink2/Nodes.scala

Allow TLMonitors to be globally disabled.

[tilelink2] allow TL monitors to be globally enabled or disabled

---

src/main/scala/uncore/axi4/Bundles.scala
src/main/scala/uncore/axi4/Nodes.scala
src/main/scala/uncore/axi4/Parameters.scala
src/main/scala/uncore/axi4/Protocol.scala
src/main/scala/uncore/axi4/RegisterRouter.scala
src/main/scala/uncore/axi4/SRAM.scala
src/main/scala/uncore/axi4/package.scala
src/main/scala/uncore/tilelink2/Edges.scala
src/main/scala/uncore/tilelink2/ToAXI4.scala
src/main/scala/uncore/tilelink2/package.scala
src/main/scala/util/PositionalMultiQueue.scala

Diplomacy style AXI4 now ready for bridging to PCIe.

axi4: diplomacy capable AXI4 with TL2 bridge

---

src/main/scala/regmapper/RegMapper.scala
src/main/scala/uncore/tilelink2/Arbiter.scala
src/main/scala/uncore/tilelink2/AtomicAutomata.scala
src/main/scala/uncore/tilelink2/Buffer.scala
src/main/scala/uncore/tilelink2/Bundles.scala
src/main/scala/uncore/tilelink2/Edges.scala
src/main/scala/uncore/tilelink2/Fragmenter.scala
src/main/scala/uncore/tilelink2/HintHandler.scala
src/main/scala/uncore/tilelink2/Monitor.scala
src/main/scala/uncore/tilelink2/Nodes.scala
src/main/scala/uncore/tilelink2/RAMModel.scala
src/main/scala/uncore/tilelink2/RegisterRouter.scala
src/main/scala/uncore/tilelink2/Repeater.scala
src/main/scala/uncore/tilelink2/ToAXI4.scala
src/main/scala/uncore/tilelink2/WidthWidget.scala
src/main/scala/uncore/tilelink2/Xbar.scala

We've decided to switch TL2 back to DecoupledIO.
This PR makes that happen.
I will rebase it against master once the Fragmenter PR is merged.

TL2 Decoupled

---

src/main/scala/rocket/icache.scala

initialize s2_hit to solve #401

---

.travis.yml

Don't mean to eat up travis bandwidth but shared branches sometimes get made.

Don't build any hurricane branches in travis

---

src/main/scala/uncore/axi4/Fragmenter.scala

This fixes a specification violation detected by VIP.

axi4: ensure we accept AR before reporting R

---

vsrc/TestDriver.v

Fix two more issues with Cadence Incisive compile. See commits for details on the warnings and errors fixed.

More Cadence Incisive fixes

---

src/main/scala/uncore/tilelink2/Parameters.scala

When there is only one manager, you still want to know if the address
was wrong on the link to that manager!

tilelink2 Parameters: fix {contains,supports}Safe

---

src/main/scala/rocketchip/BaseTop.scala
src/main/scala/rocketchip/Configs.scala
src/main/scala/rocketchip/Periphery.scala

Sometimes we have high performance devices that go inbetween.

rocketchip: include an socBus between l1tol2 and periphery

---

src/main/scala/util/AsyncQueue.scala

Without the fix, could cause spurious dequeue when no item is in the queue when reset on sending side.

Fixed AsyncFifo with reset messaging

---

Makefrag
emulator/Makefrag-verilator
vsim/Makefrag-verilog

Make all Chisel invocations depend on FIRRTL_JAR

---

src/main/scala/uncore/axi4/ToTL.scala
src/main/scala/uncore/tilelink2/Broadcast.scala
src/main/scala/uncore/tilelink2/Bundles.scala
src/main/scala/uncore/tilelink2/HintHandler.scala
src/main/scala/uncore/tilelink2/Monitor.scala
src/main/scala/uncore/tilelink2/Nodes.scala
src/main/scala/uncore/tilelink2/Parameters.scala
src/main/scala/uncore/tilelink2/RAMModel.scala
src/main/scala/uncore/tilelink2/ToAXI4.scala
src/main/scala/uncore/tilelink2/Xbar.scala

This PR adds a directory-less coherence manager for TL2.

Tl2 broadcast

---

src/main/scala/coreplex/BaseCoreplex.scala
src/main/scala/coreplex/Configs.scala
src/main/scala/coreplex/Coreplex.scala
src/main/scala/diplomacy/Parameters.scala
src/main/scala/uncore/tilelink2/Broadcast.scala
src/main/scala/uncore/tilelink2/Filter.scala
src/main/scala/uncore/tilelink2/Parameters.scala
src/main/scala/uncore/tilelink2/Xbar.scala

This PR adds the necessary pieces to enable a banked TL2 coherence for L2.

Tl2 address filtering

---

src/main/scala/coreplex/BaseCoreplex.scala
src/main/scala/coreplex/Coreplex.scala
src/main/scala/uncore/tilelink2/Broadcast.scala
src/main/scala/uncore/tilelink2/Filter.scala

A few improvements to the as yet unconnected TL2 broadcast hub.

Tl2 broadcast tweaks

---

src/main/scala/coreplex/Configs.scala
src/main/scala/rocketchip/Configs.scala

Here I'm upstreaming some of the configs that we created internally at SiFive but that only configure parameters related to the coreplex/rocket chip. Let me know if these are the right kinds of configs to make available in rocketchip or if there are changes we should make before merging.

Add various granular configs.

---

src/main/scala/coreplex/BaseCoreplex.scala
src/main/scala/coreplex/Coreplex.scala
src/main/scala/coreplex/RocketTiles.scala
src/main/scala/groundtest/TestHarness.scala
src/main/scala/groundtest/Top.scala
src/main/scala/rocketchip/BaseTop.scala
src/main/scala/rocketchip/ExampleTop.scala
src/main/scala/rocketchip/Periphery.scala
src/main/scala/rocketchip/RocketPlexMaster.scala
src/main/scala/rocketchip/TestHarness.scala
src/main/scala/rocketchip/Utils.scala
src/main/scala/uncore/devices/Plic.scala
src/main/scala/uncore/devices/Prci.scala
src/main/scala/uncore/tilelink2/Broadcast.scala
src/main/scala/uncore/tilelink2/SRAM.scala
src/main/scala/uncore/tilelink2/SourceShrinker.scala
src/main/scala/uncore/tilelink2/package.scala
src/main/scala/util/PositionalMultiQueue.scala

This PR re-adds AXI4 bus mastering to rocket.
Thus resolving #437.

Axi4 master

---

regression/Makefile
src/main/scala/coreplex/Configs.scala
src/main/scala/groundtest/Configs.scala
src/main/scala/rocketchip/Configs.scala
src/main/scala/rocketchip/Periphery.scala
src/main/scala/rocketchip/RISCVPlatform.scala
src/main/scala/uncore/axi4/Nodes.scala
src/main/scala/uncore/tilelink2/Nodes.scala
src/main/scala/util/Config.scala

A collection of small improvements needed to bootstrap our larger SoC project.

More configs

---

src/main/scala/coreplex/RocketTiles.scala

rocketchip: TileInterrupts needs a TLCacheEdge

---

src/main/scala/rocketchip/DebugTransport.scala
src/main/scala/util/AsyncBundle.scala

The DebugTransport was doing the crossing by hand and got the depth wrong.
Use the helper method instead.

Jtag depth 1

---

src/main/scala/rocket/rocc.scala
src/main/scala/rocket/tile.scala

Re-PR of #468 on ucb-bar branch

Rocc extends dcache params

---

src/main/scala/rocket/fpu.scala

@scottj97 caught this regression with testfloat.

Fix FEQ flag generation

---

src/main/scala/uncore/ahb/Bundles.scala
src/main/scala/uncore/ahb/Nodes.scala
src/main/scala/uncore/ahb/Parameters.scala
src/main/scala/uncore/ahb/Protocol.scala
src/main/scala/uncore/ahb/RegisterRouter.scala
src/main/scala/uncore/ahb/SRAM.scala
src/main/scala/uncore/ahb/Test.scala
src/main/scala/uncore/ahb/Xbar.scala
src/main/scala/uncore/ahb/package.scala
src/main/scala/uncore/tilelink2/ToAHB.scala
src/main/scala/unittest/Configs.scala

This adds a hopefully more reliable AHB adapter. This closes #383.

Diplomatic AHB

---

src/main/scala/uncore/ahb/SRAM.scala
src/main/scala/uncore/tilelink2/RegisterRouterTest.scala

I was overzealous in my hready fuzzing.

ahb: don't violate spec with SRAM fuzzing

---

src/main/scala/uncore/ahb/Bundles.scala
src/main/scala/uncore/ahb/Protocol.scala
src/main/scala/uncore/ahb/Xbar.scala
src/main/scala/uncore/apb/Bundles.scala
src/main/scala/uncore/apb/Nodes.scala
src/main/scala/uncore/apb/Parameters.scala
src/main/scala/uncore/apb/Protocol.scala
src/main/scala/uncore/apb/RegisterRouter.scala
src/main/scala/uncore/apb/SRAM.scala
src/main/scala/uncore/apb/Test.scala
src/main/scala/uncore/apb/Xbar.scala
src/main/scala/uncore/apb/package.scala
src/main/scala/uncore/tilelink2/ToAHB.scala
src/main/scala/uncore/tilelink2/ToAPB.scala
src/main/scala/unittest/Configs.scala

Sadly, APB devices still exist. Now we can control them.

Diplomatic apb

---

src/main/scala/rocket/btb.scala

Don't special-case power-of-2 replacement policy for BTB

---

project/build.properties

Update sbt to 13.12

---

regression/Makefile
src/main/scala/coreplex/Configs.scala
src/main/scala/coreplex/RocketTiles.scala
src/main/scala/rocket/Rocc.scala
src/main/scala/rocket/Tile.scala

Didn't test enough configs before merging #502 
Closes #517 hopefully.

Tile cake bugfixes

---

src/main/scala/diplomacy/LazyModule.scala

Now you can get nice names automagically for Seq[LazyModule]s

diplomacy: find names of LazyModules also in Seq() member values

---

src/main/scala/uncore/axi4/Buffer.scala
src/main/scala/uncore/axi4/Parameters.scala
src/main/scala/uncore/axi4/RegisterRouter.scala
src/main/scala/uncore/axi4/SRAM.scala
src/main/scala/uncore/axi4/ToTL.scala
src/main/scala/uncore/tilelink2/Buffer.scala
src/main/scala/uncore/tilelink2/Crossing.scala
src/main/scala/uncore/tilelink2/Nodes.scala
src/main/scala/uncore/tilelink2/RegisterRouter.scala
src/main/scala/uncore/tilelink2/ToAXI4.scala

There should not be a path from A=>D in the AXI converter.

Physical optimization

---

src/main/scala/coreplex/Configs.scala
src/main/scala/coreplex/Coreplex.scala
src/main/scala/coreplex/RocketTiles.scala
src/main/scala/rocket/Tile.scala
src/main/scala/rocketchip/RocketPlexMaster.scala

This moves us back to using a Config parameter to control the clocking of RocketTiles.

Rational default

---

src/main/scala/rocket/FPU.scala
src/main/scala/rocket/csr.scala
src/main/scala/util/Misc.scala

- FMIN/FMAX NaN behavior.  Issue description is here https://github.com/riscv/riscv-isa-sim/issues/76 and new test is here: https://github.com/riscv/riscv-tests/commit/367a13f0c2bd8d6e5a5ed71dbd3c9d46c6e21c3c
- xPIE setting on xRET.  Issue description is here https://github.com/riscv/riscv-isa-sim/issues/88

Two bug fixes

---

src/main/scala/diplomacy/Parameters.scala
src/main/scala/uncore/tilelink2/Edges.scala

Added range function in IdRange
Added source access function in TLEdge

Added access function

---

Makefrag
emulator/Makefrag-verilator
src/main/scala/coreplex/RISCVPlatform.scala
src/main/scala/groundtest/Generator.scala
src/main/scala/rocketchip/BaseTop.scala
src/main/scala/rocketchip/Generator.scala
src/main/scala/unittest/Generator.scala
src/main/scala/util/GeneratorUtils.scala
vsim/Makefrag
vsim/Makefrag-verilog

This makes it easier to create auxiliary files during elaboration.

Artefact output

---

README.md

As per https://github.com/ucb-bar/rocket-chip/pull/507

Update config override documentation

---

src/main/scala/uncore/ahb/Test.scala
src/main/scala/uncore/apb/Test.scala
src/main/scala/uncore/axi4/Test.scala
src/main/scala/uncore/tilelink2/AsyncCrossing.scala
src/main/scala/uncore/tilelink2/AtomicAutomata.scala
src/main/scala/uncore/tilelink2/Delayer.scala
src/main/scala/uncore/tilelink2/Fragmenter.scala
src/main/scala/uncore/tilelink2/Fuzzer.scala
src/main/scala/uncore/tilelink2/HintHandler.scala
src/main/scala/uncore/tilelink2/RegisterRouterTest.scala
src/main/scala/uncore/tilelink2/SRAM.scala
src/main/scala/uncore/tilelink2/WidthWidget.scala
src/main/scala/uncore/tilelink2/Xbar.scala

Add delays and noise into more unit level component tests.

Fuzzer enhancements

---

src/main/scala/junctions/hasti.scala

Fixed Hasti can't handle N masters to one slave #571

Fixed Hasti can't handle N masters to one slave

---

src/main/scala/coreplex/Configs.scala
src/main/scala/diplomacy/AddressDecoder.scala
src/main/scala/groundtest/DummyPTW.scala
src/main/scala/rocket/Arbiter.scala
src/main/scala/rocket/BTB.scala
src/main/scala/rocket/CSR.scala
src/main/scala/rocket/DCache.scala
src/main/scala/rocket/Events.scala
src/main/scala/rocket/Frontend.scala
src/main/scala/rocket/HellaCache.scala
src/main/scala/rocket/IBuf.scala
src/main/scala/rocket/ICache.scala
src/main/scala/rocket/IDecode.scala
src/main/scala/rocket/Instructions.scala
src/main/scala/rocket/Multiplier.scala
src/main/scala/rocket/NBDcache.scala
src/main/scala/rocket/PTW.scala
src/main/scala/rocket/Rocket.scala
src/main/scala/rocket/TLB.scala
src/main/scala/rocket/TLBPermissions.scala
src/main/scala/tile/Core.scala
src/main/scala/tile/FPU.scala
src/main/scala/uncore/devices/Debug.scala
src/main/scala/uncore/tilelink2/Edges.scala
src/main/scala/util/Counters.scala
src/main/scala/util/Package.scala

This brings rocket more-or-less in line with priv-1.10-draft.  It also contains some misc. fixes and improvements made along the way.

Privileged architecture updates

---

src/main/scala/uncore/ahb/Parameters.scala
src/main/scala/uncore/ahb/Test.scala
src/main/scala/uncore/ahb/ToTL.scala
src/main/scala/uncore/apb/Test.scala
src/main/scala/uncore/axi4/Test.scala
src/main/scala/uncore/tilelink2/Buffer.scala
src/main/scala/uncore/tilelink2/Parameters.scala
src/main/scala/uncore/tilelink2/TestRAM.scala
src/main/scala/unittest/Configs.scala

This PR adds the capability to master the TileLink bus from AHB.

AHB master port support

---

src/main/scala/uncore/ahb/ToTL.scala

If the master issues an illegal operation on the same cycle another illegal operation completes, the 1-cycle pause required by AHB gets lost.

AHBToTL: fix the order of updates to d_pause

---

src/main/scala/uncore/ahb/ToTL.scala

Hopefully this time the VIP is happy...

AHB error again

---

src/main/scala/rocket/DCache.scala
src/main/scala/rocket/NBDcache.scala
src/main/scala/uncore/devices/Clint.scala
src/main/scala/uncore/devices/Plic.scala
src/main/scala/uncore/tilelink2/Edges.scala
src/main/scala/uncore/tilelink2/Monitor.scala
src/main/scala/uncore/tilelink2/Parameters.scala
src/main/scala/uncore/tilelink2/RegisterRouter.scala

Update the Tilelink2 Monitor rules to match the current version of the specification.

Update monitor spec

---

src/main/scala/coreplex/RocketTiles.scala
src/main/scala/groundtest/Coreplex.scala
src/main/scala/rocket/DCache.scala
src/main/scala/rocket/HellaCache.scala
src/main/scala/uncore/tilelink2/FIFOFixer.scala
src/main/scala/uncore/tilelink2/Parameters.scala
src/main/scala/uncore/tilelink2/RAMModel.scala
src/main/scala/uncore/tilelink2/SourceShrinker.scala

Make it possible to have more than one outstanding MMIO operation with FIFO semantics.

TL pipeline MMIO

---

src/main/scala/rocket/CSR.scala

Don't trust LinkedHashMap.keys.map to provide a consistent order of traversal across module instantiations.
Even though the documentation says:
"The iterator and all traversal methods of this class visit elements in the order they were inserted."
...Scala!

rocket: avoid LinkedHashMap.keys to preserve traversal order

---

README_TRAVIS.md
src/main/scala/rocket/CSR.scala
src/main/scala/rocket/DCache.scala
src/main/scala/rocket/Frontend.scala
src/main/scala/rocket/HellaCache.scala
src/main/scala/rocket/IBuf.scala
src/main/scala/rocket/Instructions.scala
src/main/scala/rocket/NBDcache.scala
src/main/scala/rocket/PTW.scala
src/main/scala/rocket/Rocket.scala
src/main/scala/rocket/TLB.scala
src/main/scala/tile/Core.scala
src/main/scala/tile/Interrupts.scala
src/main/scala/uncore/tilelink2/Monitor.scala

- Make SEIP writable
- Add local interrupts
- Separate page faults from physical memory access exceptions
- Hard-wire UXL/SXL fields to 0
- Include @terpstra's fix to my DCache bug

Various priv-1.10 changes

---

csrc/emulator.cc
emulator/Makefrag-verilator
src/main/scala/coreplex/CoreplexNetwork.scala
src/main/scala/coreplex/RocketTiles.scala
src/main/scala/rocket/CSR.scala
src/main/scala/rocket/PMP.scala
src/main/scala/rocket/PTW.scala
src/main/scala/rocket/TLB.scala
src/main/scala/rocket/Tile.scala
src/main/scala/rocketchip/BaseTop.scala
src/main/scala/tile/BaseTile.scala
src/main/scala/tile/Interrupts.scala
vsim/Makefrag-verilog

The main purpose of this PR is to represent the new PMP encoding, and to fix one minor bug (the wrong exception cause was reported when page-table walks failed a PMP check).
This PR incorporates a few unrelated changes to help clean the Travis pipes:
- DTS changes (@terpstra)
- Local interrupt wiring in the coreplex (@hcook)
- Don't delete VPDs after SIGINT (@solomatnikov)
- Bump Firrtl (@jackkoenig)

New PMP encoding + potpourri

---

src/main/scala/rocket/Frontend.scala

Killing requests from s2 isn't correct, if !cpu.resp.ready, since the kill signal is delayed.  This allows I$ misses to be issued to invalid addresses.  Kill from s1 instead.  (QoR impact to be investigated, with patch possibly reworked.)

I$ bugfix, to be reworked

---

src/main/scala/rocket/Rocket.scala

This is a performance bug, not a correctness bug.  But randomly stalling
because of garbage bits coming out of the I$ should be avoided.
h/t @solomatnikov

Only set id_reg_fence when AMO/FENCE is actually executed

---

regression/Makefile
src/main/scala/rocket/Rocket.scala
src/main/scala/uncore/devices/debug/Debug.scala

Fixes some issues with Debug:
* Respond to NOPS in the 'Outer' part because Inner might be clock/power/reset gated
* Make HartID and HartSel a configurable mapping vs the identity mapping
* Use more reasonable values for the defaults of DATA and PROGBUF words

Debug tweaks

---

src/main/scala/rocket/Rocket.scala

The pipeline flush approach broke when I changed the pipeline stage
the flush happens from

Handle single-step with a pipeline stall, not a flush

---

regression/Makefile
src/main/scala/coreplex/Configs.scala
src/main/scala/uncore/devices/debug/Debug.scala

debug: Make it easier to override parts of the Default Debug Config

---

src/main/scala/rocket/CSR.scala

https://github.com/riscv/riscv-isa-manual/commit/4dcaa944ba40e074d25516a157fc37f7491b71cc
I also added a test, which does indeed pass, but I don't want to bump
riscv-tools for that alone:
https://github.com/riscv/riscv-tests/commit/ba6d88466a96ec3147b96a57f746a137085764f9

Add vectored interrupt support

---

src/main/scala/rocket/CSR.scala
src/main/scala/tile/FPU.scala

https://groups.google.com/a/groups.riscv.org/d/msg/isa-dev/_r7hBlzsEd8/cWPyJKMzCQAJ

Implement new FP encoding proposal

---

README.md

Tell people where to look to find package dependency information

Add pointers to package dependencies to README

---

src/main/scala/rocket/CSR.scala

https://github.com/riscv/riscv-isa-manual/commit/59d33f6b833d6499edfa825a204933098345d53d

Unconditionally write badaddr, possibly to zero

---

src/main/scala/jtag/JtagTap.scala
src/main/scala/jtag/JtagUtils.scala
src/main/scala/rocket/DCache.scala
src/main/scala/rocket/NBDcache.scala
src/main/scala/rocket/Rocket.scala
src/main/scala/rocket/TLB.scala
src/main/scala/rocketchip/DebugTransport.scala
src/main/scala/rocketchip/RISCVPlatform.scala
src/main/scala/rocketchip/TestHarness.scala
src/main/scala/tile/FPU.scala
src/main/scala/uncore/Consts.scala
src/main/scala/util/Package.scala

- Check that AMOLogical/AMOArithmetic is supported on uncacheable regions.
- When virtual addresses are wider than physical addresses, but virtual memory is turned off, verify that physical-address MSBs are zero, or raise an access exception.
- Two bonus unrelated commits: improve Seq UInt indexing QoR; fix a whitespace error.

TLB functionality improvements

---

regression/Makefile
src/main/scala/rocket/CSR.scala
src/main/scala/rocket/PMP.scala
src/main/scala/uncore/devices/debug/Debug.scala
src/main/scala/uncore/devices/debug/abstract_commands.scala

This brings the debug implementation in line with the debug spec:
- considers transfer bit and does a NOOP for the abstract command if it is not set
- doesn't have a preexec bit or associated logic
- makes the progbuf and data registers be adjacent in memory so that they can be used for either purpose

More Debug Updates to bring in line with spec

---

src/main/scala/coreplex/Configs.scala
src/main/scala/coreplex/RocketTiles.scala
src/main/scala/util/RationalCrossing.scala

Make it possible to configure things badly.

coreplex: make rational+synchronous crossing configurable

---

src/main/scala/uncore/tilelink2/WidthWidget.scala

Let me know if this recovers the area for you, please.

tilelink2: help tools save some registers in the WidthWidget

---

src/main/scala/uncore/ahb/SRAM.scala
src/main/scala/uncore/axi4/Parameters.scala
src/main/scala/uncore/tilelink2/Parameters.scala

* More verbosity
* Make AHB SRAM response fuzzing off by default

Miscellaneous uncore cleanups

---

src/main/scala/util/AsyncQueue.scala

This option reduces the number of wires that cross the clock boundary.
This can be a useful feature if the clock boundary coincides with
a voltage boundary, in which case the number of level shifters is reduced.
However, this introduces a path that crosses from sink->source->sink domain,
so the option is disabled by default.
The attached image should clarify the design choice.

Add narrowData option to AsyncQueue.

---

src/main/scala/uncore/devices/debug/Debug.scala

This allows Abstract Commands to complete *correctly* even if a following command causes a BUSY error.

debug: Prevent writes to DATA/PROGBUF when busy

---

src/main/scala/rocket/ICache.scala

An incorrectly-set ready signal caused bad data to be read from the RAM.

Fix ITIM loads

---

src/main/scala/rocket/ICache.scala
src/main/scala/uncore/axi4/ToTL.scala

Issue lots of outstanding AXI writes and eventually it will stop responding altogether.
Wes fixed today.

Wes's fix for AXI2TL timeout when writes backed up

---

src/main/scala/rocket/PTW.scala

https://github.com/riscv/riscv-isa-manual/commit/5a32fe87820f2f0f7ffab16a4a33906e78e26abb

Check PPN LSBs for superpage PTEs

---

src/main/scala/uncore/axi4/Deinterleaver.scala
src/main/scala/uncore/axi4/IdIndexer.scala
src/main/scala/uncore/axi4/Parameters.scala
src/main/scala/uncore/axi4/SRAM.scala
src/main/scala/uncore/axi4/Test.scala
src/main/scala/uncore/tilelink2/Fragmenter.scala
src/main/scala/uncore/tilelink2/ToAXI4.scala

A single AXI4 ID does not guarantee no response interleaving. This PR tries to disentangle the requirements and achieve AXI4-lite without big buffers.

axi4: Support AXI4-Lite properly

---

src/main/scala/rocket/CSR.scala

https://github.com/riscv/riscv-isa-manual/commit/137812654e54e5d765e21909679a2a24a38be123

Support vectored stvec interrupts, too

---

src/main/scala/rocket/Tile.scala

As discussed, the updated DTS for our cores.

DTS tweaks

---

project/build.scala
src/main/scala/uncore/tilelink2/SRAM.scala

@hcook @mwachs5 This is how to apply chiselName to a LazyModule. If you dare!

build: include chiselName and give an example of using it

---

src/main/scala/uncore/tilelink2/RationalCrossing.scala
src/main/scala/util/ClockDivider.scala
src/main/scala/util/RationalCrossing.scala
vsim/Makefrag
vsrc/ClockDivider3.v

(actually we always supported this, but since I hadn't tested it yet, i told everyone it only did 1:N and N:1)

RationalCrossing: now supporting true rational N:M crossings

---

regression/Makefile
src/main/scala/uncore/ahb/Test.scala
src/main/scala/uncore/apb/Test.scala
src/main/scala/uncore/axi4/Test.scala
src/main/scala/uncore/devices/Rom.scala
src/main/scala/uncore/tilelink2/Arbiter.scala
src/main/scala/uncore/tilelink2/AsyncCrossing.scala
src/main/scala/uncore/tilelink2/AtomicAutomata.scala
src/main/scala/uncore/tilelink2/Fragmenter.scala
src/main/scala/uncore/tilelink2/Fuzzer.scala
src/main/scala/uncore/tilelink2/HintHandler.scala
src/main/scala/uncore/tilelink2/Nodes.scala
src/main/scala/uncore/tilelink2/RationalCrossing.scala
src/main/scala/uncore/tilelink2/RegisterRouterTest.scala
src/main/scala/uncore/tilelink2/SRAM.scala
src/main/scala/uncore/tilelink2/TestRAM.scala
src/main/scala/uncore/tilelink2/WidthWidget.scala
src/main/scala/uncore/tilelink2/Xbar.scala
src/main/scala/unittest/Configs.scala

This PR makes unit tests run times manageable.

Unit test speedup

---

.travis.yml
Makefrag

The idea is to let us avoid building the tools
for each SUITE
see https://blog.travis-ci.com/2017-05-11-introducing-build-stages for more info

try using a new travis staging feature

---

.travis.yml

Attempt to fix travis non-sense stages issue

dont use env to force caches to be the same

---

vsrc/plusarg_reader.v

Make plusarg_reader default args work with VCS

---

src/main/scala/coreplex/CoreplexNetwork.scala

sorts the entries in the printed address map and properly formats the output.

sort entires in the printed address map

---

src/main/scala/coreplex/CoreplexNetwork.scala
src/main/scala/diplomacy/JSON.scala
src/main/scala/diplomacy/Parameters.scala
src/main/scala/diplomacy/Resources.scala
src/main/scala/groundtest/Tile.scala
src/main/scala/rocket/DCache.scala
src/main/scala/rocket/HellaCache.scala
src/main/scala/rocket/ICache.scala
src/main/scala/rocket/NBDcache.scala
src/main/scala/rocketchip/Periphery.scala
src/main/scala/rocketchip/TestHarness.scala
src/main/scala/uncore/ahb/Parameters.scala
src/main/scala/uncore/ahb/ToTL.scala
src/main/scala/uncore/apb/Parameters.scala
src/main/scala/uncore/axi4/IdIndexer.scala
src/main/scala/uncore/axi4/Parameters.scala
src/main/scala/uncore/axi4/ToTL.scala
src/main/scala/uncore/devices/debug/Debug.scala
src/main/scala/uncore/tilelink2/Broadcast.scala
src/main/scala/uncore/tilelink2/Fragmenter.scala
src/main/scala/uncore/tilelink2/Fuzzer.scala
src/main/scala/uncore/tilelink2/Legacy.scala
src/main/scala/uncore/tilelink2/Parameters.scala
src/main/scala/uncore/tilelink2/SourceShrinker.scala
src/main/scala/uncore/tilelink2/ToAHB.scala
src/main/scala/uncore/tilelink2/ToAPB.scala
src/main/scala/uncore/tilelink2/ToAXI4.scala
src/main/scala/uncore/tilelink2/Xbar.scala

This PR improves on the address map and AXI4 ID map output. It creates JSON artefacts for the results and also discovers better names for the address map.

coreplex: Improve memory map and AXI ID map output

---

src/main/scala/rocketchip/DebugTransport.scala

Add a note to wire up jtag_mfr_id

---

src/main/scala/uncore/tilelink2/ToAXI4.scala

@solomatnikov This should resolve the writes being blocked by reads from other masters.

axi4: only block writes if SAME master has outstanding reads

---

src/main/scala/util/PlusArg.scala

This does not actually output anything, that is left as an exercise for the user.

plusarg_reader : Add the ability to add a documentation string.

---

src/main/scala/uncore/ahb/SRAM.scala

Typo: is should be if ?

---

src/main/scala/tile/FPU.scala

Fix FMUL sign, again

---

src/main/scala/tile/FPU.scala

https://github.com/riscv/riscv-isa-manual/pull/75/commits/1ea65632cb08a6c03f9ffc507118e33061289595

minNum -> minimumNumber

---

src/main/scala/tile/FPU.scala

I was examining a WB-stage control signal instead of a MEM-stage control
signal.  I refactored the code to group the signals together, so that this
sort of bug is less likely going forward.

Fix FPU control bug for div/sqrt

---

.travis.yml
src/main/scala/rocketchip/Periphery.scala
src/main/scala/uncore/tilelink2/Monitor.scala
src/main/scala/uncore/tilelink2/Xbar.scala

add a debug print for xbar id mappings

---

src/main/scala/coreplex/CoreplexNetwork.scala
src/main/scala/diplomacy/Parameters.scala
src/main/scala/uncore/tilelink2/Buffer.scala

This is more generally handy when you have a lot of BufferParams.

diplomacy: BufferParams can now directly create a Queue

---

src/main/scala/coreplex/CoreplexNetwork.scala
src/main/scala/coreplex/ISPPort.scala
src/main/scala/coreplex/RocketTiles.scala
src/main/scala/diplomacy/Nodes.scala
src/main/scala/groundtest/Coreplex.scala
src/main/scala/uncore/tilelink2/NodeNumberer.scala
src/main/scala/uncore/tilelink2/Nodes.scala
src/main/scala/uncore/tilelink2/Splitter.scala
src/main/scala/uncore/tilelink2/Xbar.scala

This PR adds the capability of interconnecting multiple chips into a coherent cluster.

Inter-System-Port

---

src/main/scala/diplomacy/Parameters.scala

This should make an optimal circuit for a wider class of ranges.

diplomacy: optimize IdRange.contains

---

.travis.yml

First stage builds riscv-tools, next stage builds verilator

travis: attempt to make 2 build stages for cache

---

src/main/scala/rocket/Multiplier.scala

- Signed integer multiplication latency is now deterministic (before, it would take an extra cycle if the multiplier was negative).
- High-part multiplication is now one cycle faster.
- RV64 MULW now takes half as many cycles as MUL.
- Positive remainders are now one cycle faster.

Improve integer mul/div

---

src/main/scala/coreplex/BaseCoreplex.scala
src/main/scala/coreplex/Configs.scala
src/main/scala/coreplex/CoreplexNetwork.scala
src/main/scala/coreplex/ISPPort.scala
src/main/scala/coreplex/RISCVPlatform.scala
src/main/scala/coreplex/RocketTiles.scala
src/main/scala/groundtest/Configs.scala
src/main/scala/groundtest/Coreplex.scala
src/main/scala/groundtest/TraceGen.scala
src/main/scala/groundtest/TrafficGenerator.scala
src/main/scala/rocket/DCache.scala
src/main/scala/rocket/ICache.scala
src/main/scala/rocket/ScratchpadSlavePort.scala
src/main/scala/uncore/devices/Clint.scala
src/main/scala/uncore/devices/Plic.scala
src/main/scala/uncore/tilelink2/SRAM.scala

Also, laying groundwork for coreplex/system flattening and PAddrBits deprecation

Assorted changes based on ISP use cases

---

src/main/scala/regmapper/RegMapper.scala
src/main/scala/util/ReduceOthers.scala

This PR reduces the PLIC from 780k lines of firrtl to 393k lines. Not as much as I'd hoped. I'm not sure there is much more to do in the register router itself. I guess we could certainly shrink things further if we modify the PLIC to not use single bit enable registers.

Reduce others

---

src/main/scala/uncore/axi4/Deinterleaver.scala
src/main/scala/uncore/tilelink2/ToAXI4.scala

The AXI4Deinterleaver was found to use too many Queues; one per AXI ID. This PR helps keep this more manageable. First, it doesn't put down a Q for any AXI ID that is never used. Second, it makes it possible to strip the low bits out of the tilelink source when converted to an AXI id.

Reduce AXI4 queues

---

src/main/scala/uncore/tilelink2/ToAXI4.scala

idCount <= 1 implies that no more than one transaction can be inflight,
so there is no need to interlock R+W. However, when stripBits > 0, it is
possible for a non-FIFO master to have > 1 idCount. In this case, we
also don't need to interlock R+W.

tilelink2 ToAXI4: don't interlock R+W for non-FIFO masters

---

src/main/scala/coreplex/CoreplexNetwork.scala
src/main/scala/diplomacy/JSON.scala
src/main/scala/diplomacy/Resources.scala
src/main/scala/rocket/DCache.scala
src/main/scala/rocket/Frontend.scala
src/main/scala/rocket/ICache.scala
src/main/scala/rocket/RocketTiles.scala
src/main/scala/rocket/ScratchpadSlavePort.scala
src/main/scala/rocketchip/Periphery.scala
src/main/scala/uncore/devices/Plic.scala
src/main/scala/uncore/devices/Rom.scala
src/main/scala/uncore/devices/debug/Debug.scala
src/main/scala/uncore/tilelink2/Error.scala
src/main/scala/uncore/tilelink2/Parameters.scala
src/main/scala/uncore/tilelink2/RegisterRouter.scala
src/main/scala/uncore/tilelink2/SRAM.scala
src/main/scala/uncore/tilelink2/TestRAM.scala
src/main/scala/uncore/tilelink2/Zero.scala

This adds compatible and reg-names to most everything.

Dts improvements

---

src/main/scala/rocket/CSR.scala
src/main/scala/uncore/devices/debug/Debug.scala

Fixes some interactions between WFI instruction and Debug Mode

Debug + WFI Interactions

---

src/main/scala/uncore/devices/Plic.scala
src/main/scala/uncore/tilelink2/ToAXI4.scala

This reduces the lines of code in the PLIC by 30%. Not yet tested.

plic: Recode to use OH knowledge

---

src/main/scala/rocket/DCache.scala

This is the patch that Yunsup asked me to make to fix the issue I was seeing where access exceptions weren't being properly propagated.

Make sure that DCache s2_xcpt data scratchpad case is assigned to after initial assignment.

---

src/main/scala/rocket/CSR.scala

This makes single-step exceptions higher-priority than debug interrupts.

Mask debug interrupts similarly to other interrupts

---

src/main/scala/rocket/DCache.scala
src/main/scala/rocket/Frontend.scala
src/main/scala/rocket/ICache.scala
src/main/scala/rocket/NBDcache.scala
src/main/scala/rocket/PTW.scala
src/main/scala/rocket/Rocket.scala
src/main/scala/rocket/TLB.scala
src/main/scala/tile/Core.scala

- Handle TL errors in I$
- Fix D$ probe bug
- Add option for shared L2 TLB (disabled by default)

L1 memory system improvements

---

src/main/scala/regmapper/RegField.scala

so I don't have to RTFC and figure out what width actually was

regfield: More explanatory requires 

---

src/main/scala/tilelink/FIFOFixer.scala

In particular, it is ok if no slaves actually need FIFO fixing.
It is also ok if none of those fixed are FIFO.

tilelink: FIFOFixer must support null cases

---

src/main/scala/tilelink/Monitor.scala

tilelink: it is now legal to have errors on {Release,Hint}Ack

---

src/main/scala/diplomacy/Monitor.scala
src/main/scala/tilelink/Monitor.scala

@jchang0 You removed this. Do you remember why?

tilelink: Monitor should report line numbers of connection that failed

---

src/main/scala/chip/Periphery.scala
src/main/scala/devices/tilelink/Zero.scala

zero: fix attachment in multichannel case

---

src/main/scala/diplomacy/Parameters.scala
src/main/scala/util/ShiftQueue.scala

If enq_valid is always false, deq_valid should be too!

ShiftQueue: support constant propagation

---

src/main/scala/coreplex/RTC.scala

the counter is now connected directly to the CLINT.

fix HasRTCModuleImp

---

src/main/scala/tilelink/Fragmenter.scala

Consider the following waveform for two 4-beat bursts:
```
---A----A------------
-------D-----DDD-DDDD
Under TL rules, the second A can use the same source as the first A,
because the source is released for reuse on the first response beat.
However, if we fragment the requests, it looks like this:
---3210-3210---------
-------3-----210-3210
... now we've broken the rules because 210 are twice inflight.
```
To solve this, we alternate an a.source bit every time D completes a txn.

tilelink: fix Fragmenter source re-use bug

---

src/main/scala/rocket/BTB.scala
src/main/scala/rocket/Frontend.scala
src/main/scala/rocket/PTW.scala

Also, improve L2 TLB coding style, and fix a frontend performance bug.

Fix L2 TLB

---

src/main/scala/tilelink/WidthWidget.scala

This PR should improve WidthWidget QoR, but more importantly, removes the need for addr_lo.

Width widget enhancements

---

src/main/scala/tilelink/AtomicAutomata.scala
src/main/scala/tilelink/Fuzzer.scala
src/main/scala/tilelink/RAMModel.scala
src/main/scala/tilelink/SourceShrinker.scala

We have a few (not many, but a few) masters that will reuse a source after receiving the first beat of a D response. This *is* legal in TileLink. However, the Fuzzer was not exercising this case.

Fuzzer rage

---

src/main/scala/diplomacy/Nodes.scala

Another battle in the war against string-less requires()

diplomacy: More verbose require

---

src/main/scala/rocket/DCache.scala

... by making pstore_drain_on_miss more conservative

dcache: break potential combinatorial loop

---

src/main/scala/rocket/Frontend.scala

This seemingly irrelevant change shaves several gate delays off the I$ tl.a.valid path.

Mitigate I$->D$->I$ critical path

---

src/main/scala/tile/RocketTile.scala
src/main/scala/util/RationalCrossing.scala

also adds tweaks to the rational crossing

add optional tile boundary buffers

---

src/main/scala/rocket/PMP.scala

Use UIntToOH1

---

emulator/Makefrag-verilator

Since we aren't using chisel2, the output is the same either way.

Don't build verilog twice for emulator and emulator-debug

---

src/main/scala/diplomacy/LazyModule.scala

so that we can instantiate LazyModules within LazyRawModules.

diplomacy: provide default clock/reset for LazyRawModuleImp

---

src/main/scala/rocket/IBuf.scala
src/main/scala/rocket/RocketCore.scala

I haven't even compiled this on the latest master.

Print out the compressed instruction when executing one

---

src/main/scala/devices/tilelink/BusBlocker.scala
src/main/scala/devices/tilelink/BusBypass.scala

Sometimes you just need to put IP in a cage.

tilelink: PMP controlled BusBlocker prevents bus accesses

---

src/main/scala/rocket/DCache.scala

The following sequence would drop the first store when eccBytes=4:
sb x0, 0(t0)
nop
sb x0, 4(t0)
nop
sb x0, 1(t0)
Because the first and second store are to different ECC granules, the
hazard check correctly allowed the second one to proceed, but the third
was merged with the second, even though it conflicted with the first.
So, don't allow the third to be merged with the second, since the second
stored to a different ECC granule.

Don't merge stores that manifest WAW hazards

---

src/main/scala/devices/tilelink/BusBlocker.scala

Bus blocker lock

---

src/main/scala/tile/FPU.scala

If the first one is killed for some unrelated reason (e.g. write port
hazard), the second one will still issue to the div-sqrt unit.  While
it will itself later be killed, the fact that the later instruction
acquires a resource needed by the former instruction leads to deadlock.

Fix priority inversion for two back-to-back divides

---

src/main/scala/tilelink/PatternPusher.scala

This PR makes it possible to specify an expected read result.

PatternPusher: can now expect a certain output

---

src/main/scala/devices/debug/Periphery.scala

This allows TestHarnesses to override the JTAG VPI Clock speed and time between commands

jtag_vpi: Use Parameterized Black Box 

---

src/main/scala/rocket/CSR.scala

https://github.com/riscv/riscv-isa-manual/commit/a62e76cb16eb508199f74632eb8bf263739f25a3

Respect ISA requirements on interrupt priority order

---

src/main/scala/coreplex/FrontBus.scala
src/main/scala/coreplex/MemoryBus.scala
src/main/scala/coreplex/PeripheryBus.scala
src/main/scala/coreplex/RocketCoreplex.scala
src/main/scala/coreplex/SystemBus.scala
src/main/scala/tile/RocketTile.scala
src/main/scala/tilelink/Buffer.scala
src/main/scala/tilelink/Bus.scala

"Front" means in front of the system port.
Also added a bunch of `suggestNames` for modules generated as attachment points to the SystemBus. We should probably revisit how this is handled, and do it more programmatically.

Add a FrontBus to which low-bandwidth bus masters attach

---

src/main/scala/rocket/DCache.scala

This fixes both a deadlock and a memory corruption bug.  The following sequence manifests the deadlock case, assuming t0 is 32-byte aligned:
sw t0, 0(t0)
sw t0, 16(t0)
lw t1, 4(t0)
lw t2, 4(t0)

Only merge stores that aren't yet pending

---

src/main/scala/tilelink/ToAXI4.scala
src/main/scala/util/Property.scala

Also make variable to TLToAXI4 public

Add cover property API that can be refined through Config PropertyLibrary

---

vsrc/plusarg_reader.v

Altera Synplify and Synopsis Design Compiler complained.

Fix omitted parameter

---

project/build.properties
project/build.scala
project/plugins.sbt
src/main/scala/jtag/JtagShifter.scala

Don't merge this yet, but this PR should be used ultimately to bump chisel and firrtl

Bump chisel3 and firrtl, update plugin versions

---

src/main/scala/tile/FPU.scala

To assist retiming, manually move a max of 2 register stages of the FPU FMA pipeline into the FMA module

FPU FMA FPGA retiming assist

---

src/main/scala/diplomacy/LazyModule.scala

This should fix dedup of Tiles.

diplomacy: auto connect bundles in a stable order

---

emulator/Makefrag-verilator
src/main/scala/groundtest/Generator.scala
src/main/scala/system/ExampleRocketSystem.scala
src/main/scala/system/Generator.scala
src/main/scala/system/TestHarness.scala
src/main/scala/unittest/Generator.scala
src/main/scala/util/GeneratorUtils.scala
src/main/scala/util/Misc.scala
vsim/Makefrag-verilog

Don't remove top level ports from rocket. Closes #1040.

Use chisel3.experimental.dontTouch (take 2)

---

src/main/scala/system/Configs.scala

It was missing cores. Fixes #736.

system: fix DefaultFPGAConfig

---

src/main/scala/coreplex/BaseCoreplex.scala
src/main/scala/diplomacy/JSON.scala
src/main/scala/diplomacy/Resources.scala
src/main/scala/tilelink/Parameters.scala

cc @mikeyangsiv
This updates the DTS JSON file to include an `A` property if it supports all types of atomics.

Add atomics support to DTS JSON file.

---

src/main/scala/coreplex/BaseCoreplex.scala

Make sure the address map includes the device name.

Fix address format

---

src/main/scala/coreplex/InterruptBus.scala

coreplex: attach example external interrupts

---

src/main/scala/amba/ahb/SRAM.scala
src/main/scala/amba/ahb/Test.scala
src/main/scala/amba/ahb/ToTL.scala
src/main/scala/amba/apb/SRAM.scala
src/main/scala/amba/apb/Test.scala
src/main/scala/amba/axi4/Test.scala
src/main/scala/tilelink/Delayer.scala
src/main/scala/tilelink/ErrorEvaluator.scala
src/main/scala/tilelink/Fragmenter.scala
src/main/scala/tilelink/Monitor.scala
src/main/scala/tilelink/RAMModel.scala
src/main/scala/tilelink/ToAHB.scala
src/main/scala/tilelink/ToAXI4.scala
src/main/scala/tilelink/WidthWidget.scala

Implement the full TileLink specification for error handling.

Error support

---

src/main/scala/devices/debug/DebugTransport.scala
src/main/scala/jtag/JtagTap.scala

Otherwise the generated FIRRTL/Verilog is non deterministic

JTAG: Use sorted map for stability

---

src/main/scala/tilelink/Fragmenter.scala

Unfortunately, dLast is not actually correct for AccessAckData.
dFragnum is 0 for all the subbeats in the multibeat=>multibeat case.

tilelink: fix error fragmentation from multibeat to multibeat

---

src/main/scala/tilelink/AsyncCrossing.scala
src/main/scala/util/Property.scala

@mikeyangsiv Here are your requested covers.

Async covers

---

src/main/scala/coreplex/Configs.scala
src/main/scala/tilelink/ToAXI4.scala

At some point we stopped caching main memory for WithStatelessBridge.

Fix stateless caching

---

src/main/scala/rocket/ICache.scala
src/main/scala/tilelink/AtomicAutomata.scala
src/main/scala/tilelink/ErrorEvaluator.scala

Errors should be detected also on the swallowed read!

tilelink: AtomicAutomata should OR the Get error with the Put error

---

src/main/scala/coreplex/Configs.scala

coreplex: fix typo

---

src/main/scala/coreplex/Ports.scala

coreplex: allow MMIO to be misaligned

---

src/main/scala/tilelink/ToAXI4.scala

Fix AXI4 FIFO ordering for masters with early source reuse

---

src/main/scala/tilelink/ToAXI4.scala

This is a follow-up to PR #1108.
Rather than increasing the number of transactions we allow to be inflight,
instead just block TL when early source re-use happens. This is a better
fix since it means we don't pay mostly wasted downstream hardware to handle
an additional transaction inflight that almost never happens.

TLToAXI4: block TL early source re-use before it goes to AXI4

---

src/main/scala/amba/axi4/Deinterleaver.scala
src/main/scala/amba/axi4/Delayer.scala
src/main/scala/amba/axi4/Filter.scala
src/main/scala/amba/axi4/Nodes.scala
src/main/scala/amba/axi4/SRAM.scala
src/main/scala/amba/axi4/Xbar.scala
src/main/scala/rocket/DCache.scala
src/main/scala/tilelink/Filter.scala
src/main/scala/tilelink/RAMModel.scala
src/main/scala/unittest/Configs.scala

To actually test the AXI4 Xbar, we had to add a few more AXI components, too.

axi4: add an Xbar

---

src/main/scala/rocket/ScratchpadSlavePort.scala

Not proud of having to break into coreplex Parameters this way...

tile: bus blocker needs to know width

---

src/main/scala/coreplex/RocketCoreplex.scala
src/main/scala/devices/tilelink/BusBlocker.scala
src/main/scala/devices/tilelink/BusBypass.scala

You get TileLink assertions if mismatching bus widths are cross connected.
So don't do that.

Verify blocker width

---

src/main/scala/coreplex/BaseCoreplex.scala
src/main/scala/diplomacy/Resources.scala
src/main/scala/tile/RocketTile.scala

This expands the DTS visibility to the whole design, not just the innermost Scope.

DTS global

---

src/main/scala/rocket/DCache.scala

Firrtl can't DCE it because it would require analyzing the state machine.

Don't emit writeback state machine logic for scratchpad

---

src/main/scala/devices/debug/Debug.scala

See https://github.com/freechipsproject/chisel3/issues/527

debug: Remove workaround for Chisel 3 #527

---

src/main/scala/rocket/CSR.scala
src/main/scala/rocket/RocketCore.scala

I've added cover properties for the exceptions in RocketCore.scala. I created a `coverExceptions()` method which should basically get called everywhere that the existing `checkExceptions()` method is called. I manually read through each of the pipeline stages and added cover properties for all the exceptions that should be possible to receive at that stage (sans interrupts).
~~A have a couple of questions, probably mostly aimed at @aswaterman:~~
1. ~~I only conditionally emit the page fault exception cover properties if `rocketParams.useVM` is true. Is this the right param to be checking?~~ Also, is it necessary for me to explicitly exclude them in Scala, or is there some way to get Chisel or Firrtl to constant propagate them away later?
@jackkoenig says no to the constant prop question, …

Add cover properties for exceptions in the core.

---

src/main/scala/amba/axi4/Fragmenter.scala
src/main/scala/amba/axi4/Test.scala
src/main/scala/coreplex/Configs.scala
src/main/scala/devices/tilelink/BusBypass.scala
src/main/scala/devices/tilelink/Error.scala
src/main/scala/diplomacy/CloneModule.scala
src/main/scala/diplomacy/LazyModule.scala

Make it possible to keep the Error device transfer sizes reasonable.

Error atomics

---

src/main/scala/diplomacy/LazyModule.scala

future-proofing the LazyModule API

diplomacy: LazyModule factory uses ValName

---

src/main/scala/jtag/JtagStateMachine.scala
src/main/scala/jtag/JtagTap.scala
src/main/scala/jtag/Utils.scala

the override clock way is deprecated

JTAG: Use new withClock way of overriding clocks

---

src/main/scala/tilelink/Bundles.scala
src/main/scala/tilelink/SourceShrinker.scala

Keep as much FIFOiness as we can.

SourceShrinker improvements

---

src/main/scala/util/Property.scala

This change is made in anticipation of a proper coverage library
It's a bit ugly, but it enables people to write covers where they don't have a `Parameters` object and the global variable should be removed once the proper Chisel cover library is released.

Replace Parameters in cover with globally setable implementation

---

src/main/scala/tilelink/FIFOFixer.scala

Functional covers for TL Fifofixer.

Added functional covers

---

src/main/scala/regmapper/RegField.scala
src/main/scala/tilelink/RegisterRouter.scala

This also adds a "description" as well as "name" part to the enumeration.

RegFieldDesc: Emit enumerations into JSON if they exist

---

emulator/Makefrag-verilator
src/main/scala/devices/debug/Debug.scala
src/main/scala/util/GeneratorUtils.scala
src/main/scala/util/Misc.scala
vsim/Makefrag-verilog

Also brings in an autoclonetype enhancement and some bug fixes
Also some minor updates, got rid of some DontTouch code duplication.

Bump Chisel and FIRRTL for annotations refactor

---

build.sbt
src/main/scala/devices/debug/DebugTransport.scala
src/main/scala/devices/tilelink/BusBypass.scala
src/main/scala/util/Misc.scala

Keep things compatible with firrtl

sbt: bump json4s-jackson to 3.5.3

---

src/main/scala/diplomacy/AddressRange.scala
src/main/scala/diplomacy/Parameters.scala
src/main/scala/diplomacy/Resources.scala
src/main/scala/rocket/DCache.scala
src/main/scala/rocket/HellaCache.scala
src/main/scala/rocket/ICache.scala
src/main/scala/rocket/NBDcache.scala
src/main/scala/rocket/RocketCore.scala
src/main/scala/subsystem/BaseSubsystem.scala
src/main/scala/tilelink/ToAXI4.scala
src/main/scala/util/ECC.scala

This lays the groundwork for forthcoming PRs that will serialize metadata about the elaborated design as FIRRTL annotations.

Store metadata in serializable case classes

---

src/main/scala/util/ECC.scala

This makes it possible to update an ECC-protected word while
retaining the fact that the value has an ECC error.

ECC: support poison during encode

---

src/main/scala/rocket/IDecode.scala
src/main/scala/rocket/Multiplier.scala
src/main/scala/rocket/RocketCore.scala

Add pipelined multiplier option

---

src/main/resources/vsrc/AsyncResetReg.v

Race fixes that I thought were only needed for Verilator seems like they are also needed for VCS, depending on synthesis order.

Async Reset Reg tweaks

---

src/main/resources/vsrc/AsyncResetReg.v

Changing blackbox packaging strategy revealed bad behavior on certain simulators.

vsrc: AsyncResetReg adjustments

---

src/main/scala/devices/debug/dm_registers.scala

Based on feedback from implementing SBA there were some edits/clarifications to the spec. Incorporate them here. 
Also the OpenOCD with `prefer_sba` command is now on master of riscv-tools, so this bumps riscv-tools to that version, which would be OK to merge.

Updates to riscv-tools/Debug SBA error dfns

---

src/main/scala/devices/debug/Debug.scala
src/main/scala/devices/tilelink/CLINT.scala
src/main/scala/devices/tilelink/Plic.scala
src/main/scala/diplomacy/AddressRange.scala
src/main/scala/rocket/BTB.scala
src/main/scala/subsystem/BaseSubsystem.scala
src/main/scala/tile/RocketTile.scala
src/main/scala/tilelink/ToAXI4.scala
src/main/scala/util/Annotations.scala

These annotations capture interesting information about the design, mostly for documentation purposes.

Annotations: add some informative annotations

---

.travis.yml
regression/Makefile
scripts/RocketSim.cfg
src/main/scala/devices/debug/Debug.scala
src/main/scala/devices/debug/Periphery.scala
src/main/scala/devices/debug/SBA.scala
src/main/scala/devices/debug/dm_registers.scala
src/main/scala/subsystem/Configs.scala
src/main/scala/system/Configs.scala

Initial pull request for System Bus Access debug feature

Initial commit of SBA Debug feature

---

src/main/scala/rocket/CSR.scala
src/main/scala/rocket/DCache.scala
src/main/scala/rocket/Frontend.scala
src/main/scala/rocket/HellaCache.scala
src/main/scala/rocket/HellaCacheArbiter.scala
src/main/scala/rocket/NBDcache.scala
src/main/scala/rocket/PMP.scala
src/main/scala/rocket/PTW.scala
src/main/scala/rocket/RVC.scala
src/main/scala/rocket/RocketCore.scala
src/main/scala/rocket/ScratchpadSlavePort.scala
src/main/scala/rocket/SimpleHellaCacheIF.scala
src/main/scala/rocket/TLB.scala
src/main/scala/tile/Core.scala
src/main/scala/util/Misc.scala
src/main/scala/util/package.scala

- Improve reusability of CSR unit and D$ for non-Rocket pipelines
- Several additions to Seq/UInt PML API

Misc. utility improvements and generalizations

---

src/main/scala/devices/tilelink/Plic.scala
src/main/scala/regmapper/RegMapper.scala
src/main/scala/util/MuxLiteral.scala

This PR attempts to reduce the PLIC line count and factor out common logic where possible.

PLIC optimizations

---

src/main/scala/unittest/Configs.scala
src/main/scala/util/ECC.scala

Also improve verilog output by using xorR.

SEC: switch to systematic encoding

---

src/main/scala/regmapper/Annotation.scala
src/main/scala/util/Annotations.scala

Removed an intermediate level in the case class hierachy
Removed regFiled name
Added deviceName 
This does not affect the old JSON regmap files.
There were merge problems with the old PR so I made a new PR.

modifying the regmapper annotations

---

src/main/scala/system/RocketTestSuite.scala

Add rv64mi/access test.

---

src/main/scala/devices/debug/Debug.scala
src/main/scala/devices/tilelink/CLINT.scala
src/main/scala/devices/tilelink/Plic.scala
src/main/scala/rocket/BTB.scala
src/main/scala/subsystem/BaseSubsystem.scala
src/main/scala/tile/Core.scala
src/main/scala/tile/RocketTile.scala
src/main/scala/tilelink/ToAXI4.scala
src/main/scala/util/Annotations.scala

New elaborated configs. Add annotations for:
- Reset vectors
- Interrupts
- Registers
- Some Params

Elaborated config from annos3 rocket

---

src/main/scala/util/Misc.scala

works around a deficiency of UIntToOH in chisel3

util: pad MaskGen when lgSize.width < lg(lgBytes)

---

src/main/resources/vsrc/AsyncResetReg.v

Additional information found in the following discussion:
https://github.com/freechipsproject/rocket-chip/commit/41702a950f2fdc9a247b654869bff6a9389a9bb2#commitcomment-29219295

Enclosed non synthesis code within ifndef SYNTHESIS

---

src/main/scala/rocket/DCache.scala
src/main/scala/rocket/ICache.scala
src/main/scala/subsystem/HasTiles.scala
src/main/scala/tile/BaseTile.scala

Avoid using RocketTilesKey within Rocket code

---

src/main/scala/subsystem/BaseSubsystem.scala

add dts address anno

---

src/main/scala/diplomacy/SRAM.scala
src/main/scala/rocket/DCache.scala
src/main/scala/rocket/ICache.scala
src/main/scala/rocket/NBDcache.scala
src/main/scala/rocket/PTW.scala
src/main/scala/util/Annotations.scala
src/main/scala/util/DescribedSRAM.scala

Sram annos2

---

src/main/scala/util/Annotations.scala

adding width to port anno

---

src/main/scala/util/Annotations.scala

adding addresses to port annos

adding addresses to port annos

---

src/main/scala/util/Annotations.scala

adding address

---

src/main/scala/subsystem/HasTiles.scala

- don't supply a NullSource if there is no seip
- update comments

subsystem: clean up connectInterrupts

---

src/main/scala/subsystem/Ports.scala

ports: CanHaveSlaveTLPortModuleImp bug fix

---

src/main/scala/diplomacy/DeviceTree.scala
src/main/scala/diplomacy/JSON.scala
src/main/scala/diplomacy/Resources.scala
src/main/scala/diplomacy/package.scala

References are written: key = <&label>;
Aliases are written:    key = &label;
References compile to a phandle integer value.
Aliases compile to a string path name.

diplomacy: DTS aliases are not references

---

src/main/scala/diplomacy/FixedClockResource.scala
src/main/scala/diplomacy/Resources.scala
src/main/scala/tile/BaseTile.scala
src/main/scala/tile/Interrupts.scala
src/main/scala/tile/RocketTile.scala

This extends the diplomatic DTS API to facilitate more descriptive outputs in the freedom repository.
We are interested there in being able to describe subordinate SPI devices.

Richer DTS

---

src/main/scala/rocket/DCache.scala

adding missing dcache tag array SRAMAnno

adding missing dcache tag array SRAMAnno

---

src/main/scala/diplomacy/BundleBridge.scala
src/main/scala/subsystem/CrossingWrapper.scala

Sometimes more typing is better.

diplomacy: desugar BundleBridge -- it was too confusing

---

src/main/scala/diplomacy/BundleBridge.scala
src/main/scala/subsystem/FrontBus.scala
src/main/scala/subsystem/PeripheryBus.scala
src/main/scala/tile/BaseTile.scala

BundleBridge and CrossingWrapper API cleanups (pt 2)

---

src/main/scala/tilelink/ToAPB.scala

One small step for flops, but one large step for timing!

TLToAPB: cut paths from A to D

---

src/main/scala/subsystem/SystemBus.scala

Note: using this is kind of dangerous; make sure you aren't going to starve anyone!

subsystem: make sbus arbitration configurable

---

src/main/scala/tilelink/Bundles.scala

We are adding methods to decode the current Opcode and Param information on the tilelink bundle.
The way it is done might be messy and hoping for the reviewers for better ways.

Adding Seq for opcode and param translation in TLMessages

---

src/main/scala/amba/axi4/CrossingHelper.scala
src/main/scala/diplomacy/LazyModule.scala
src/main/scala/interrupts/CrossingHelper.scala
src/main/scala/subsystem/FrontBus.scala
src/main/scala/tilelink/CrossingHelper.scala

Manual inspection of verilog signal names led to further changes. No functional changes.

Continued tweaks to how bus coupler ports get names

---

src/main/scala/diplomacy/Resources.scala

Add a missing string-interpolation marker to an error message

---

src/main/scala/rocket/AMOALU.scala
src/main/scala/rocket/BusErrorUnit.scala
src/main/scala/rocket/CSR.scala
src/main/scala/rocket/DCache.scala
src/main/scala/rocket/Frontend.scala
src/main/scala/rocket/HellaCache.scala
src/main/scala/rocket/ICache.scala
src/main/scala/rocket/Multiplier.scala
src/main/scala/rocket/NBDcache.scala
src/main/scala/rocket/PTW.scala
src/main/scala/rocket/RocketCore.scala
src/main/scala/rocket/ScratchpadSlavePort.scala
src/main/scala/rocket/TLB.scala
src/main/scala/util/Replacement.scala
src/main/scala/util/package.scala

In trying to reuse some of these units for another generator I'm working on,  I noticed some deficiencies in QoR and also wanted a few more knobs to turn.

Several QoR and minor generator functionality improvements for Rocket-related utilities

---

.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md

This serves as an initial discussion point for #1501.
Fixes #1501

Add issue and PR template

---

src/main/scala/rocket/CSR.scala
src/main/scala/rocket/Frontend.scala
src/main/scala/rocket/PTW.scala
src/main/scala/rocket/RocketCore.scala

CSR 0x7c0 bit 0:
- when 0, behaves as normal
- when 1, branches are all predicted taken; BHT is not updated
- when written (regardless of value), fluses BTB

Add optional custom branch-prediction mode CSR

---

src/main/scala/rocket/BusErrorUnit.scala

I broke this in 1d46b6a65d34f90736c147ca06dad4ed82ed5451
I will investigate why regression testing didn't catch this.

Fix BusErrorUnit regression

---

src/main/scala/devices/debug/Custom.scala
src/main/scala/devices/debug/Debug.scala
src/main/scala/devices/debug/Periphery.scala

More diplomatic version of #1589
Users can connect custom signals to be monitored using the Debug Spec's Abstract Command interface.

Diplomatic version of Debug Custom interface

---

src/main/scala/util/package.scala

This is just to add some new rotate functions for UInts and Seqs.
**Development Phase**: Implementation

Package uint rotateleft

---

src/main/scala/rocket/DCache.scala
src/main/scala/rocket/PTW.scala
src/main/scala/rocket/TLBPermissions.scala

Does not affect Rocket, but could affect cores capable of consistently issuing an LR every cycle.

Don't hold the bus so aggressively on LR instructions

---

src/main/scala/rocket/CSR.scala

Ignore scounteren CSR if S-mode not present

---

src/main/resources/vsrc/EICG_wrapper.v
src/main/scala/groundtest/DummyPTW.scala
src/main/scala/rocket/DCache.scala
src/main/scala/rocket/HellaCache.scala
src/main/scala/rocket/HellaCacheArbiter.scala
src/main/scala/rocket/NBDcache.scala
src/main/scala/rocket/PTW.scala
src/main/scala/rocket/RocketCore.scala
src/main/scala/rocket/TLB.scala
src/main/scala/tile/L1Cache.scala
src/main/scala/tile/LazyRoCC.scala
src/main/scala/util/ClockGate.scala
src/main/scala/util/package.scala
vsim/Makefrag

- Support explicitly clock-gating the D$
- Support overriding the RAM indexing function
- Prevent superscalar LR/SC livelock
**Type of change**: bug report | other enhancement

D$ improvements

---

src/main/scala/rocket/CSR.scala
src/main/scala/rocket/DCache.scala
src/main/scala/rocket/Frontend.scala
src/main/scala/rocket/PMP.scala
src/main/scala/rocket/PTW.scala
src/main/scala/rocket/RocketCore.scala
src/main/scala/tile/Core.scala
src/main/scala/tile/CustomCSRs.scala

- Make custom CSRs more extensible
- Add chicken-bit framework
- set marchid CSR to 1, which has been assigned by RISC-V Foundation to Rocket

Custom CSR enhancements

---

src/main/scala/rocket/RocketCore.scala

Allow mvendorid CSR to be overridden

---

src/main/scala/devices/debug/Debug.scala

Correct one of the reg field descriptions for RESUMING address

debug: fix RESUMING desc

---

src/main/scala/subsystem/SystemBus.scala

Allows a wrapped error device to be added to the system bus wrapper

subsystem: can still put error on sbus

---

src/main/scala/subsystem/HasTiles.scala

**Impact**: no functional change for all previously supported configs (i.e. when PLIC exists)
Configs without PLIC should compile after this PR

Fix HasTiles for the case when PLIC does not exist

---

src/main/scala/devices/debug/Periphery.scala
src/main/scala/devices/tilelink/BusBypass.scala
src/main/scala/devices/tilelink/DevNull.scala
src/main/scala/devices/tilelink/MasterMux.scala
src/main/scala/diplomacy/Parameters.scala
src/main/scala/tilelink/AddressAdjuster.scala
src/main/scala/tilelink/BusWrapper.scala
src/main/scala/tilelink/Edges.scala
src/main/scala/tilelink/Parameters.scala
src/main/scala/tilelink/RegionReplication.scala
src/main/scala/unittest/Configs.scala

Added RegionReplicator, which presents the same physical devices at multiple addresses.
Added the AddressAdjuster, which can select to which physical address route local traffic is routed.

Off-chip coherence

---

src/main/scala/rocket/RocketCore.scala
src/main/scala/tile/FPU.scala

make signals in RocketCore and FPU accessible from other classes

expose signals

---

src/main/scala/subsystem/PeripheryBus.scala

Adding TLWidthWidget to toTile, since current API assumes identical widths between master/slave

Add WidthWidget adapter to toTile

---

src/main/scala/tilelink/Fragmenter.scala

Optimize away Fragmenter when minSize == maxSize

---

src/main/scala/subsystem/Configs.scala

Fix up(...).copy(...) use

---

src/main/scala/devices/debug/Periphery.scala
src/main/scala/devices/tilelink/BootROM.scala
src/main/scala/devices/tilelink/CLINT.scala
src/main/scala/devices/tilelink/MaskROM.scala
src/main/scala/devices/tilelink/Plic.scala
src/main/scala/subsystem/BaseSubsystem.scala
src/main/scala/subsystem/Configs.scala
src/main/scala/tilelink/Fragmenter.scala
src/main/scala/tilelink/WidthWidget.scala

Actually merge these changes into master

Handle subsystem bus interconnectivity in child classes of BaseSubsystem pt 2

---

src/main/scala/subsystem/HasTiles.scala

Allow subsytem w/ multiple cores and w/o PLIC (or external PLIC)

---

src/main/scala/rocket/DCache.scala
src/main/scala/rocket/Frontend.scala
src/main/scala/tile/FPU.scala
src/main/scala/util/Misc.scala
src/main/scala/util/Replacement.scala

Make clock_en_reg disappear when clockGate = false

---

README.md

This saves time and links to the blog for newcomers who keep banging
their head against the wall when they can't compile custom example
programs.

Note for compiling custom programs

---

src/main/scala/rocket/RocketCore.scala

Add another condition to rocket clock enable

---

src/main/scala/diplomacy/Resources.scala
src/main/scala/subsystem/BaseSubsystem.scala

Rename OM components

---

src/main/scala/diplomacy/BundleBridge.scala
src/main/scala/diplomacy/Parameters.scala
src/main/scala/subsystem/Configs.scala
src/main/scala/subsystem/MemoryBus.scala
src/main/scala/subsystem/PeripheryBus.scala
src/main/scala/tilelink/AddressAdjuster.scala
src/main/scala/tilelink/RegionReplication.scala

Add a few features that make the AddressAdjuster + RegionReplicator suitable for building multi-chip capable SoCs.
**Impact**: API addition

Multi chip coherence

---

src/main/scala/util/GeneratorUtils.scala

Generator: support using _root_ for the project

Generator: support using _root_ for the project

---

src/main/scala/devices/debug/Debug.scala

Clock-gate the debug module using the dmactive signal

---

src/main/scala/tilelink/Parameters.scala

groupBy considered harmful
**Impact**: no functional change / large impact on generated code order
Fix non-determinism in TLMonitor generation

Fix non-determinism in TLMonitor generation

---

src/main/scala/rocket/Events.scala

**Related issue**:  https://github.com/freechipsproject/rocket-chip/pull/1308
Fix the covers so that FIRRTL eliminates ones that will not be hit. eg: ```("event_name", () => false.B)```
**Impact**: Only changes the cover properties that are generated

Fix event covers to eliminate dead covers

---

src/main/scala/amba/axi4/ToTL.scala
src/main/scala/tile/BaseTile.scala
src/main/scala/tilelink/AddressAdjuster.scala

Fix several bugs in the AddressAdjuster

Fix a few issues with multi-chip designs

---

src/main/scala/amba/ahb/SRAM.scala
src/main/scala/amba/apb/SRAM.scala
src/main/scala/amba/axi4/SRAM.scala
src/main/scala/diplomacy/SRAM.scala
src/main/scala/tilelink/SRAM.scala

feature request
API addition (no impact on existing code)
implementation

new om for rams

---

src/main/scala/devices/debug/Debug.scala

Implemented hart array feature as detailed in the RISC-V Debug Spec, v 0.13

Added hart array feature

---

src/main/scala/diplomaticobjectmodel/model/ISASpecifications.scala

other enhancement
Set the ISA u spec name
API modification
implementation

added isa u spec

---

src/main/scala/rocket/DCache.scala

In 29954c6ffe3f12e498a94703b212b6fd0a43ad07, I inadvertently introduced a new critical path, because I didn't realize `s1_waw_hazard` depends on the ECC check.  Fix by killing the latter dependence.

Remove a D$ ECC critical path

---

src/main/scala/rocket/ScratchpadSlavePort.scala
src/main/scala/tile/RocketTile.scala

Fixes a problem in multicores wrt dcaches
bug report

fixes a dcache problem

---

src/main/scala/rocket/Breakpoint.scala
src/main/scala/rocket/CSR.scala

See https://github.com/riscv/riscv-debug-spec/pull/282/files for relevant specification.
- Don't allow chain to be set if this trigger doesn't belong to D-mode but the next trigger does.
- Don't allow dmode to be set if the previous trigger doesn't belong to D-mode and has chain set.
- Don't allow chains longer than 2.

Implement debug trigger-sharing and chain-limiting proposals

---

src/main/scala/rocket/RocketCore.scala
src/main/scala/util/BundleMonitorKey.scala

This reverts commit c69607cfd5eef076c8fdf26bbbd6343de9b3b1ce.
Reverting commit https://github.com/freechipsproject/rocket-chip/commit/c69607cfd5eef076c8fdf26bbbd6343de9b3b1ce
Related PR:https://github.com/freechipsproject/rocket-chip/pull/1746
The PR being reverted caused issues in the reset of the code base and I need to temperately revert it.

Revert "Core monitor bundle (#1746)"

---

build.sbt
project/build.properties

If dependent projects use json4s, they will need to bump it. It is also probably necessary to bump sbt.
This also includes minor API changes in FIRRTL like .foreach* methods on IR nodes.
Bump firrtl, json4s, and sbt

Bump firrtl, json4s, and sbt

---

src/main/scala/diplomaticobjectmodel/model/OMRocketCore.scala
src/main/scala/tile/RocketTile.scala

Adding dcache om in the case when the dtim_adapter is None

adding dcache om

---

src/main/scala/rocket/CSR.scala

This was a post-v1.10 amendment to the privileged spec.
**Related issue**: https://github.com/riscv/riscv-isa-manual/commit/059f64c941856f249d8a0647e23e150dbdb1f62c

Reserve the PMP R=0 W=1 combination

---

src/main/scala/rocket/DCache.scala
src/main/scala/rocket/PTW.scala

- D$: s2_xcpt doesn't need to drive so many things.

Minor QoR improvements

---

src/main/scala/devices/debug/Debug.scala
src/main/scala/devices/tilelink/CLINT.scala
src/main/scala/devices/tilelink/Plic.scala
src/main/scala/diplomaticobjectmodel/DiplomaticObjectModelUtils.scala
src/main/scala/diplomaticobjectmodel/model/OMAddressing.scala
src/main/scala/diplomaticobjectmodel/model/OMMemory.scala
src/main/scala/tilelink/RegisterRouter.scala

adding registers to the OM
adding register maps to the OMCLINT, OMPLIC, and OMDebug

adding om registers

---

src/main/scala/amba/ahb/SRAM.scala

other enhancement
**Impact**: API modification: plusarg is renamed to be more specific

rename ahb_fuzzing plusarg

---

src/main/scala/rocket/CSR.scala
src/main/scala/rocket/DCache.scala

Respect SEIP during WFI clock gate

---

src/main/scala/diplomaticobjectmodel/model/OMAddressing.scala

added the type field to OMBitRange

adding missing type

---

src/main/scala/util/ECC.scala

I would like to create `TLRAM`s with bytes greater than one using `IdentityCode` for testing.

remove require from ECCParams

---

src/main/scala/devices/debug/Debug.scala
src/main/scala/devices/debug/Periphery.scala
src/main/scala/diplomaticobjectmodel/model/OMDebug.scala

Debug interface

---

src/main/scala/rocket/CSR.scala

This facilitates moving emulation code out of the M-mode trusted codebase.

Support delegation of misaligned ld/st and illegal instruction traps

---

src/main/scala/tile/RocketTile.scala

add missing docname for rocket cores

add docname

---

src/main/scala/rocket/CSR.scala
src/main/scala/rocket/PMP.scala

This lets downstream users of the PMP replicate the state with DRYness.

Encapsulate PMP reset

---

src/main/scala/devices/debug/Debug.scala
src/main/scala/devices/tilelink/CLINT.scala
src/main/scala/devices/tilelink/Plic.scala

converted unicode dashes to ascii

unicode fix

---

src/main/scala/rocket/CSR.scala

Removing the CSR.R as a measure of accessing the csr

---

src/main/scala/rocket/PMP.scala

Adding cover points for PMP access types, permissions and access hits

Adding cover points for pmp permission, and access

---

src/main/scala/diplomaticobjectmodel/model/OMRocketCore.scala

Changed cache name from ICache to ITIM if there is a memory region

Add ITIM name

---

src/main/scala/rocket/PTW.scala

Get L2 TLB parity check off the critical path

---

src/main/scala/system/Generator.scala

generator: support the no rocket tiles case

---

src/main/scala/subsystem/Ports.scala

Signed-off-by: Gabriel Somlo <gsomlo@gmail.com>
**Related issue**: #1811 

Ports.scala: add comment re. capping test-harness MMIO to 4KB

---

src/main/scala/diplomaticobjectmodel/model/OMISA.scala

The OMISA was missing the user string in the case the useVM was set

OMISA user fix

---

src/main/scala/devices/tilelink/BusBlocker.scala

Add RegFieldDesc to BusBlocker devices

BusBlocker: add RegFieldDescs to the control port

---

src/main/scala/diplomaticobjectmodel/DiplomaticObjectModel.scala

OMComponents

---

src/main/scala/rocket/Frontend.scala

The fetch queue needs to fill up, which currently is only possible with certain code sequences.  This PR makes the fetch queue flow control exact rather than conservative, removing the software constraint.

Increase the number of situations in which frontend can be clock gated

---

src/main/scala/diplomaticobjectmodel/DiplomaticObjectModel.scala

Get last OMComponent

---

src/main/scala/regmapper/RegField.scala

add a new apply method in RegField

Add new RegField apply function

---

src/main/scala/diplomaticobjectmodel/model/OMCaches.scala

Object model: Make OMECC an OMEnum type

---

src/main/scala/rocket/DCache.scala

Permit execution past corrupt uncached D-responses

---

src/main/scala/rocket/DCache.scala

Further fix per-line cache flushing

---

src/main/scala/rocket/RocketCore.scala
src/main/scala/scie/SCIE.scala

**Type of change**: feature
Added 2-stage pipeline variant of the Simple Custom Instruction Extension

Add 2-stage pipeline variant of Simple Custom Instruction Extension

---

src/main/scala/diplomaticobjectmodel/model/OMPerformanceMonitor.scala
src/main/scala/tile/RocketTile.scala

perfmon name fix

---

src/main/scala/diplomaticobjectmodel/model/ISASpecifications.scala
src/main/scala/diplomaticobjectmodel/model/OMISA.scala
src/main/scala/diplomaticobjectmodel/model/OMSpecification.scala

Add the customExtension to OMISA. The purpose of this PR is to capture the list of customer instruction extensions which are being added to RISC-V.

Add customExtension to OMISA

---

src/main/scala/rocket/CSR.scala

See https://github.com/freechipsproject/rocket-chip/issues/1868

Set misa.X bit, since CEASE instruction is nonstandard

---

src/main/scala/rocket/CSR.scala

**Type of change**: bug report: Was creating cause cover points for mcause > 32
**Impact**: does not create coverpoints for cause greater than 32, if not expected

Fix Coverpoint generation in CSR file

---

src/main/scala/rocket/CSR.scala

Changing the csr cover points generated with different conditions for read only and read write csrs

Generate different cover points for RO and RW CSR registers

---

src/main/scala/diplomaticobjectmodel/model/OMSpecification.scala

**Type of change**:  feature request
Changed the OMSpecification case class hierarchy

updated the specification hierarchy

---

project/plugins.sbt

Quick fix for https://github.com/freechipsproject/chisel3/pull/1040 which adds scalastyle settings.
Support for `sbt scalastyle`.

Add scalastyle-sbt-plugin.

---

src/main/scala/subsystem/Ports.scala

**Related issue**: https://groups.google.com/a/groups.riscv.org/d/msgid/hw-dev/20190404185412.GE3175%40hedwig.ini.cmu.edu

Support misaligned addresses in WithDefaultMemPort

---

src/main/scala/diplomaticobjectmodel/HasLogicalTreeNode.scala
src/main/scala/subsystem/BaseSubsystem.scala

Adding a trait which will add the logical tree node from the parent to the child...

haslogicaltreenode

---

build.sbt

This puts macros + hardfloat in a single jar instead of being published as separate jars.
Is anyone relying on `rocket-macros` or `hardfloat` existing independently of rocket?
@ucbjrl, can you verify that this produces artifacts that look correct?

Make rocket publish a single jar.

---

src/main/scala/diplomaticobjectmodel/logicaltree/RocketLogicalTreeNode.scala
src/main/scala/diplomaticobjectmodel/model/OMRocketCore.scala

adding has scie to:
-OMRocketCore

adding has scie

---

src/main/scala/diplomaticobjectmodel/model/OMCaches.scala
src/main/scala/diplomaticobjectmodel/model/OMRocketCore.scala

- Added a function to convert a Chisel Code object to a string
- Code clean up

add a new getCode function

---

src/main/scala/diplomaticobjectmodel/model/CustomISAExtensions.scala
src/main/scala/diplomaticobjectmodel/model/ISASpecifications.scala
src/main/scala/diplomaticobjectmodel/model/OMISA.scala
src/main/scala/diplomaticobjectmodel/model/OMSpecification.scala

The custom extensions are now stored as a map of functions so that the version of the spec can be passed.

Isa extensions

---

src/main/scala/tilelink/Bundles.scala
src/main/scala/tilelink/Parameters.scala

@hcook Let me know if this works to resolve your markDUT issue with TL-UH

tilelink: remove BCE channels completely if unnecessary

---

src/main/scala/tile/BaseTile.scala

Add PMP to DeviceTree

---

src/main/scala/amba/apb/ToTL.scala
src/main/scala/devices/debug/APB.scala
src/main/scala/devices/debug/Debug.scala
src/main/scala/devices/debug/Periphery.scala
src/main/scala/diplomaticobjectmodel/logicaltree/LogicalTrees.scala
src/main/scala/diplomaticobjectmodel/model/OMDebug.scala
src/main/scala/subsystem/Configs.scala
src/main/scala/system/Configs.scala

**Impact**:API addition (no impact on existing code)
This adds a new possible interface to the Debug Module: APB. An APB-to-TL converter is instantiated, DMI is not present (builds on #1903). A place is available for additional APB registers.

Add APB Debug Interface Option

---

src/main/scala/amba/apb/ToTL.scala

There were already AHB2TL and AXI2TL adapters. Add one for APB.
Reviewers, please help with my "TODO" items, I am not sure I am following the pattern as intended.
**Impact**: API addition (no impact on existing code) |

APBToTL Adapter

---

src/main/scala/diplomaticobjectmodel/model/OMDebug.scala
src/main/scala/diplomaticobjectmodel/model/OMPorts.scala

Fix debug and add omports

---

src/main/scala/devices/debug/SBA.scala

**Related issue**: https://github.com/freechipsproject/rocket-chip/pull/1953
Need an additional check for address legality before mastering front bus

SBA: Additional check for address Get/Put legality

---

src/main/scala/diplomaticobjectmodel/model/OMISA.scala

conditionally add cflush

---

src/main/scala/diplomaticobjectmodel/logicaltree/LogicalTreeNode.scala

This PR adds a check for when the tree size == 0 and the bind call should not be invoked.

handle condition when the Logical Tree equals size 0

---

src/main/scala/diplomaticobjectmodel/logicaltree/RocketLogicalTreeNode.scala
src/main/scala/diplomaticobjectmodel/model/OMRocketCore.scala

**Type of change**:  feature request 
Added support for clock gate info in om rocket core

adding object model rocket clock gate

---

src/main/scala/diplomaticobjectmodel/DiplomaticObjectModelUtils.scala
src/main/scala/diplomaticobjectmodel/logicaltree/LogicalTrees.scala
src/main/scala/diplomaticobjectmodel/model/BusError.scala
src/main/scala/subsystem/RocketSubsystem.scala
src/main/scala/tile/BusErrorUnit.scala
src/main/scala/tile/RocketTile.scala

**Impact**: API addition (no impact on existing code
Adding the BusErrorUnit LogicalTreenNode and the Object Model

adding BusError LTN and OM

---

scripts/vlsi_rom_gen

**Related issue**: #1961 
Vivado parsing failed on:
* declaration in an unnamed block --> added name
* multi-dimensional array --> flattened

fix Vivado parsing errors

---

src/main/scala/devices/debug/SBA.scala

check sbbusyerror when generating address,data,wr/rdEn in SBA module

---

src/main/scala/devices/tilelink/Plic.scala
src/main/scala/diplomaticobjectmodel/logicaltree/LogicalTrees.scala
src/main/scala/diplomaticobjectmodel/model/OMCoreComplex.scala
src/main/scala/diplomaticobjectmodel/model/OMPLIC.scala
src/main/scala/groundtest/GroundTestSubsystem.scala
src/main/scala/subsystem/BaseSubsystem.scala
src/main/scala/subsystem/RocketSubsystem.scala

Remove the  externalGlobalInterrupts from the SubSystemLogicalTreeNode

Refactoring

---

src/main/scala/util/package.scala

Fix andNot when y is constant and narrower than x

---

src/main/scala/diplomaticobjectmodel/logicaltree/LogicalTrees.scala
src/main/scala/diplomaticobjectmodel/model/OMAddressing.scala

Add RegDesc enumerations to the object model.
Add a new OMRegDescEnumerations object model component.

Add RegDesc enumerations to the object model

---

src/main/scala/diplomaticobjectmodel/logicaltree/LogicalTrees.scala
src/main/scala/diplomaticobjectmodel/model/OMAddressing.scala
src/main/scala/diplomaticobjectmodel/model/OMBusError.scala
src/main/scala/subsystem/RocketSubsystem.scala
src/main/scala/tile/BusErrorUnit.scala
src/main/scala/tile/RocketTile.scala

Add the bus error object model

om bus error

---

src/main/scala/subsystem/MemoryBus.scala

MemoryBus WidthWidget to connect to narrower memory ports

---

src/main/scala/amba/ahb/Parameters.scala
src/main/scala/amba/ahb/SRAM.scala
src/main/scala/amba/apb/Parameters.scala
src/main/scala/amba/apb/SRAM.scala
src/main/scala/amba/axi4/Parameters.scala
src/main/scala/amba/axi4/SRAM.scala
src/main/scala/diplomacy/SRAM.scala
src/main/scala/diplomaticobjectmodel/DiplomaticObjectModelUtils.scala
src/main/scala/diplomaticobjectmodel/logicaltree/LogicalTreeNode.scala
src/main/scala/diplomaticobjectmodel/logicaltree/LogicalTrees.scala
src/main/scala/diplomaticobjectmodel/model/OMBusMemory.scala
src/main/scala/diplomaticobjectmodel/model/OMSRAM.scala
src/main/scala/diplomaticobjectmodel/model/OMTestHarness.scala
src/main/scala/rocket/DCache.scala
src/main/scala/rocket/ICache.scala
src/main/scala/rocket/NBDcache.scala
src/main/scala/rocket/PTW.scala
src/main/scala/subsystem/BaseSubsystem.scala
src/main/scala/tilelink/SRAM.scala
src/main/scala/util/DescribedSRAM.scala

Adds OMBusMemory's and OMSRAM's

Add OMBusMemory

---

src/main/scala/diplomaticobjectmodel/DiplomaticObjectModelUtils.scala
src/main/scala/diplomaticobjectmodel/logicaltree/LogicalTreeNode.scala
src/main/scala/diplomaticobjectmodel/logicaltree/RocketLogicalTreeNode.scala
src/main/scala/diplomaticobjectmodel/model/OMRocketCore.scala
src/main/scala/rocket/ScratchpadSlavePort.scala

Adding requires and refactoring

added debugging and refactored the bind function

---

src/main/scala/scie/SCIE.scala

In SCIEPipelined, manually suppress Xs

---

src/main/scala/tile/L1Cache.scala

**Type of change**: other enhancement (code clarification)
**Release Notes**: for simplicity of reuse, create "cacheDataBytes" from "cacheDataBits/8"

trait HasL1CacheParameters def cacheDataBytes

---

src/main/resources/vsrc/TestDriver.v

- TestDriver supports longer paths to destination waveforms.

Support longer destination paths to waveform output files in TestDriver

---

src/main/scala/tilelink/AddressAdjuster.scala

Sometimes you need a device to stay local to the core complex.

AddressAdjuster: support an excluded set of addresses

---

build.wake
ivydependencies.json
wit-manifest.json

add support for wake and wit

---

src/main/scala/devices/debug/Debug.scala

The Debug Module had a few registers that were being reset by the default reset input (i.e. TileLink reset) rather than dmactive.  The async crossing modules from dmouter to dminner were among these and prevented DMI from accessing any registers in dminner while reset was asserted.

Changed lingering bits of dminner to use dmactive reset

---

src/main/scala/devices/debug/Debug.scala

Changed debug module external triggers from Vec[Bool] to UInt, which has the effect of changing individual wires to vectors in the Verilog in configurations with more than one external trigger.

Changed DM external triggers from Vec[Bool] to UInt

---

src/main/scala/rocket/CSR.scala

**Related issue**: Issue #2022 
The dret instruction should throw an illegal instruction exception when executed outside debug mode.

dret should be illegal outside debug mode

---

src/main/scala/devices/debug/Debug.scala
src/main/scala/devices/debug/SBA.scala

The register map for the DMI interface did not describe register fields with sufficient detail to help automate verification testing.  This PR expands the regmaps to include this detail.

Expand regfields on DMI interface for improved DV coverage

---

build.wake
src/main/scala/groundtest/Generator.scala
src/main/scala/system/Generator.scala
src/main/scala/unittest/Generator.scala
src/main/scala/util/GeneratorUtils.scala

add an optional parameter to specify the output filename. This is helpful when there are a lot of configs passed on the command-line and the filename becomes too long.

Add filename option

---

src/main/scala/tilelink/Broadcast.scala

Improve performance of systems with a front port or more than 1 core, but no L2.

Broadcast: in the case of an Acquire.NtoB, respond Grant.toT if we can

---

.travis.yml
build.wake
ci-tests/check_submodules
ci-tests/wake_scala_compilation
regression/check_submodules.sh
wit-manifest.json

add a CI script to check that git submodules match wit dependencies

add wit dependency/git submodule check to travis

---

src/main/scala/tilelink/ToAHB.scala

**Related issue**: hgrant loss triggers loss of messages
Fix AHB race condition on loss of hgrant.

TLToAHB: fix handling of hgrant on full AHB with EBT

---

src/main/scala/tilelink/ToAHB.scala

Add support for AHB SPLIT and RETRY.

TLToAHB: optionally support SPLIT/RETRY responses

---

src/main/scala/rocket/IDecode.scala
src/main/scala/rocket/RocketCore.scala

Add support for RVE (15 x-register variant).

Add support for RVE 

---

src/main/scala/tilelink/BusWrapper.scala

Document why this requirement exists.

Improve the blockBytes vs. beatBytes requirement.

---

src/main/scala/amba/ahb/Protocol.scala
src/main/scala/amba/ahb/SRAM.scala
src/main/scala/diplomaticobjectmodel/model/OMPorts.scala

Further testing revealed a problem in the AHBSRAM error handling.
Fix error response during idle in AHBSRAM.

Fix AHBSRAM errors

---

src/main/scala/rocket/ICache.scala

Don't assume d.corrupt stays high

---

src/main/scala/rocket/DCache.scala
src/main/scala/rocket/ICache.scala

Provide better error messages when associativity is too low

---

src/main/scala/tilelink/SRAM.scala

only report corrupt for requested ECC blocks

TLSRAM: only report corrupt for requested ECC blocks

---

src/main/scala/tilelink/Bundles.scala

tilelink: fix typo in arithmetic code pretty printing

---

src/main/scala/tilelink/SRAM.scala

Adding ECC Cover points for TL SRAMs

Add ecc cover points

---

src/main/scala/amba/ahb/ToTL.scala
src/main/scala/devices/debug/DMI.scala
src/main/scala/diplomacy/Parameters.scala
src/main/scala/tilelink/Fragmenter.scala

Added diplomacy comments about emits parameters and smallestintervalcover

---

src/main/scala/diplomacy/LazyModule.scala
src/main/scala/diplomacy/Nodes.scala
src/main/scala/interrupts/Nodes.scala
src/main/scala/tilelink/Nodes.scala
src/main/scala/tilelink/Parameters.scala
src/main/scala/tilelink/RegisterRouter.scala

Adds additional information that are in the graphml

---

src/main/resources/csrc/emulator.cc
src/main/resources/vsrc/TestDriver.v
src/main/scala/system/TestHarness.scala
vsim/Makefrag

Some fixes to eventually support async reset

---

src/main/scala/rocket/Events.scala

add a requirement that the number of events within a set must fit within the mask width

Events require hits within mask width

---

src/main/scala/diplomacy/CloneModule.scala
src/main/scala/diplomacy/LazyModule.scala
src/main/scala/diplomaticobjectmodel/model/OMAddressing.scala
src/main/scala/regmapper/Annotation.scala
src/main/scala/rocket/DCache.scala
src/main/scala/rocket/HellaCache.scala
src/main/scala/rocket/ICache.scala
src/main/scala/subsystem/HasTiles.scala
src/main/scala/tilelink/RegisterRouter.scala
src/main/scala/tilelink/RegisterRouterTest.scala
src/main/scala/unittest/UnitTest.scala
src/main/scala/util/Annotations.scala
src/main/scala/util/AsyncResetReg.scala
src/main/scala/util/GeneratorUtils.scala
wit-manifest.json

This is a big one, buckle up folks
* Add Stage/Phase APIs
* Add "Aspect Oriented"-inspired API support
* Add native `AsyncReset` and abstract `Reset` support
* Add utility functions `unsignedBitLength` and `signedBitLength`
* Move `dontTouch`, `RawModule`, and `MultiIOModule` out of `chisel3.experiemental` to `chisel3`
* Add `reduceTree` to `Vec`
* Strip outer objects and classes from naming of Modules
* Support `withClock` in `RawModules` with no implicit reset
* Support bulk connecting `DontCare` to Bundles with `Analog` fields
* Make LFSR support async reset
* Fix stack trimming
* Better errors for Queues with bad sizes
* Fix directions in dynamic indexing of complex Vecs
* Dependency API
* Support for specifying FIRRTL transforms via their dependencies on other transforms
* Not yet …

Bump chisel3 and firrtl - Async reset support

---

src/main/scala/devices/debug/Debug.scala

Fixes #2170
Problem was limited range of Scala Int.

Support >= 32 cores in debug unit

---

src/main/scala/devices/debug/Debug.scala

It is useful for the debug tools to know what type of connection there is to the Debug Module.  This PR adds this information to the DTS file.

Show debug attachment in device tree

---

src/main/scala/devices/debug/Periphery.scala

**Impact**: no functional change | API modification
Making the `PSDIO` argument to `tieoffDebug` an `Option[PSDIO]` defaulting to `None`

Debug: Option[PSDIO] in tieoffDebug

---

build.sbt
wit-manifest.json

Bump for 1.2.x 20191106-SNAPSHOT

---

src/main/scala/subsystem/BaseSubsystem.scala

Moving baseBusAttachmentFunction member of BaseSubsystem into separate trait so it can be mixed-into and leveraged by other layers of design hierarchy if needed
This is a duplicate of https://github.com/chipsalliance/rocket-chip/pull/2195, which is causing a double `free` in `verilator` that I haven't been able to reproduce on my local machine

BaseSubsystem: Move attachment function into trait

---

build.sbt
project/build.properties

Bump Scala to 2.12.10 and SBT to 1.3.4

---

src/main/scala/diplomaticobjectmodel/model/ISASpecifications.scala
src/main/scala/diplomaticobjectmodel/model/OMISA.scala

RV32E and RV64E feature is added to object json.

Addition of RV32E and RV64E to rocket core object json

---

src/main/scala/formal/FormalUtils.scala
src/main/scala/tilelink/Monitor.scala
src/main/scala/util/Property.scala

This adds utilities that can be used for formal.

Monitorformaladditions

---

project/plugins.sbt
wit-manifest.json

Bumping chisel and firrtl to the latests commits on their *.2.x branches. Includes the following summary of bugfixes/updates.
Chisel3:
- Add ChiselEnum to BundleLiterals
- Fix asTypeOf for Clock
- Fix bidirectional Wire with Analog
- Improve error message when assigning from Seq to Vec
- Improve naming of anonymous/class-in-function Modules
- Support literals cast to aggregates as async reset reg init values
- Add MiMa and CI checks for binary compatibility
- Make ChiselStage targets not private
- Internal BoringUtils.bore Bug Fix
FIRRTL:
- Logger tweaks
- Ignore extmodule instances in Flatten
- getSimpleName considered harmful
- Move CheckResets after …

Bump chisel 3.2.x and firrtl 1.2.x

---

src/main/scala/amba/axis/Buffer.scala
src/main/scala/amba/axis/Bundles.scala
src/main/scala/amba/axis/Xbar.scala
src/main/scala/diplomacy/Parameters.scala
src/main/scala/util/BundleMap.scala
src/main/scala/util/package.scala

AXIS is irrevocable and some fields appear/disappear based on adapters.

AXIS fixes

---

src/main/scala/rocket/DCache.scala
src/main/scala/tilelink/Parameters.scala

**Related issue**: https://github.com/chipsalliance/rocket-chip/pull/2241#issuecomment-572800953

TLFIFOFixer.Policy requireFifo

---

src/main/scala/rocket/CSR.scala

Use ungated clock in TracedInstruction bundle

---

wit-manifest.json

**Type of change**: updates
Includes the following updates.
Chisel3:
- Band aid until litOption is implemented for Aggregates
- Bump versions for next release
- Bugfix: Select.instances now works with blackboxes

Bump chisel 3.2.x

---

wit-manifest.json

bumping chisel

---

src/main/scala/rocket/PTW.scala
src/main/scala/rocket/TLB.scala
src/main/scala/util/Replacement.scala

**Type of change**: API expansion
promote the L1TLB Entry in TLB.scala and the L2TLB Entry in PTW.scala to be public classes reusable in other packages

TLBs: make Entry classes available from other packages

---

src/main/scala/prci/IOHelper.scala

Add IOHelper

---

src/main/scala/amba/axi4/ToTL.scala

AXI4ToTL: Fix maxFlight=1 case

---

src/main/scala/formal/FormalUtils.scala

Support for custom messages in Property class.

Custommessage

---

wit-manifest.json

Highlight: massive performance improvement to chisel3 runtime on many designs
Summary of changes:
* Fix := of DontCare to AsyncReset and Reset
* Boost performance of Vec cloning
* Add support for \t in printf
* Add ScalaDoc to RegNext
Bump chisel3 along stable 3.2.x branch

Bump chisel3 along 3.2.x branch

---

src/main/scala/devices/debug/Debug.scala

**Related issue**: https://github.com/sifive/api-generator-sifive/pull/43
Fixes a couple of minor typos in the Debug Module register descriptions, pointed out by @felixonmars in https://github.com/sifive/api-generator-sifive/pull/43.

Fix typos in Debug Module register descriptions.

---

build.sbt

Restore SNAPSHOT version.

---

src/main/scala/rocket/Frontend.scala
src/main/scala/rocket/ICache.scala

 assertion for speculative fetch chicken bit

---

src/main/scala/devices/debug/Periphery.scala
src/main/scala/devices/tilelink/CLINT.scala
src/main/scala/devices/tilelink/Plic.scala
src/main/scala/subsystem/BaseSubsystem.scala
src/main/scala/util/Location.scala

BaseSubsystem: Rename attach method and traits

---

src/main/scala/amba/axi4/Parameters.scala
src/main/scala/amba/axi4/ToTL.scala
src/main/scala/tilelink/Fragmenter.scala
src/main/scala/tilelink/HintHandler.scala
src/main/scala/tilelink/Parameters.scala
src/main/scala/tilelink/ToAHB.scala
src/main/scala/tilelink/ToAPB.scala
src/main/scala/tilelink/ToAXI4.scala
src/main/scala/util/BundleMap.scala

No major revision is perfect. Fortunately, none of these fixes break API compatibility.

Fix various bugs related to the new user bits in TileLink

---

src/main/scala/rocket/Events.scala

add SuperscalarEventSets into Events.scala

---

src/main/scala/rocket/DCache.scala
src/main/scala/util/AsyncQueue.scala

Yes, apparently people care about this case still.

Fix D$ elaboration with < 4 MiB of physical address space

---

src/main/scala/util/AsyncQueue.scala

AsyncValidSync is a Raw Module
This reverts commit 4cc86868b88674f9d91c18e2f53baf1c76973174.
This re-does PR #2352 which was reverted in #2367  with no changes

Revert "Revert "Merge pull request #2352"

---

src/main/resources/vsrc/EICG_wrapper.v
src/main/scala/util/ClockGate.scala

This is intended to help with DFT insertion for explicit clock gates.

Add test_en pin to ClockGate

---

src/main/scala/regmapper/RegMapper.scala

generate register covers based on access type

---

src/main/scala/rocket/RocketCore.scala
src/main/scala/util/CoreMonitor.scala

Adding signals to the core monitor so that we can perform the correct check for cease instruction.
other enhancement
API addition (no impact on existing code
implementation

Add Exception and Priviledge mode to core monitor

---

src/main/scala/amba/ahb/ToTL.scala
src/main/scala/devices/tilelink/BusBypass.scala
src/main/scala/tilelink/WidthWidget.scala

**Related issue**: fixing a few more warnings that showed up after https://github.com/chipsalliance/rocket-chip/pull/2353

fix Chisel compile warnings: TileLink Parameters v1

---

build.wake

use stages api to build rocket-chip in wake flow

---

wit-manifest.json

Bring in some bug fixes
* Make `chisel3.util.Counter` emit valid FIRRTL
* Fix `updateBundleStack` in highly multi-threaded testers
* Fix dynamic indexing of zero-length vectors
* Don't duplicate modules with only one instance in EliminateTargetPaths
* Move AsyncReset registers initialization into `RANDOMIZE` ifdef in emitted Verilog
* Ensure mverilog compiler runs `PadWidths`
* Allow casts in AsyncReset reg literal init values (aka support non-UInt async reset regs from Chisel)
* Prevent infinite recursion in CheckResets

Bump Chisel and FIRRTL along 3.2.x and 1.2.x

---

src/main/scala/tile/Interrupts.scala

The I$ clock enable can toggle a couple times before it finally goes
to sleep.  Conservatively wait until it (and everything else) has
quiesced for several cycles before raising the cease signal.
Fix bug where cease signal was not monotonic

Deglitch the cease signal

---

src/main/scala/diplomaticobjectmodel/logicaltree/RocketLogicalTreeNode.scala
src/main/scala/diplomaticobjectmodel/model/OMISA.scala
src/main/scala/rocket/PTW.scala
src/main/scala/tile/RocketTile.scala

enable Sv48 setting PgLevels=4

Object Model: add Sv48 to RocketISA addressTranslationModes

---

src/main/scala/diplomacy/BundleBridge.scala

Sometimes BundleBroadcast sends wires far across the chip.
Add a registered option to the BundleBroadcast.

BundleBroadcast: add optional register pipelining

---

src/main/scala/devices/tilelink/Plic.scala

Support elaborating the PLIC when there are no interrupts for it to control.

Support PLIC elaboration when nDevices == 0

---

src/main/scala/prci/package.scala

prci: add Clock[Inward,Outward]Node types

---

src/main/scala/amba/axis/Parameters.scala

Sometimes you want to describe the master.

AXIS: allow masters to carry resources as well

---

src/main/scala/diplomaticobjectmodel/model/OMPorts.scala

Reverts chipsalliance/rocket-chip#2427

Revert "Object model updates for AHB and AXI"

---

README_TRAVIS.md

Recently have gone through this process (and will likely need to again with @jackkoenig 's https://github.com/chipsalliance/rocket-chip/pull/2454) so updating the instructions
**Related issue**: N/A
Update README_TRAVIS.md to enhance travis cache maintenance instructions

README_TRAVIS.md: Update cache maintenance instructions

---

wit-manifest.json

Bumping to include macros in firrtl — there are some commits from other people included as well.
* Guard `_RAND_*` declarations in Verilog with `ifdef RANDOMIZE_*` (https://github.com/freechipsproject/firrtl/pull/1548)
* Provide `FIRRTL_BEFORE_INITIAL` and `FIRRTL_AFTER_INITIAL` macros around initial blocks (https://github.com/freechipsproject/firrtl/pull/1550)
* Speed up `CheckHighForm` and `CheckChirrtl` (https://github.com/freechipsproject/firrtl/pull/1582)
**Related issue**: https://github.com/freechipsproject/firrtl/pull/1578
* optional macros have been added

bumping firrtl 1.3.x

---

src/main/scala/tilelink/Monitor.scala

additional TileLink assertions

---

CONTRIBUTING.md

Update the CONTRIBUTING.md to have a bit more information about submitting PRs and getting them approved.

Add more PR instructions/conditions to CONTRIBUTING.md

---

src/main/scala/util/GeneratorUtils.scala

Update GeneratorUtils error message to suggest checking the package path as well as spelling when it can't find a config

Update GeneratorUtils.scala "did you misspell it" error message

---

src/main/scala/tilelink/Nodes.scala

: 
implementation
Addition of TLAdapterNode_ACancel, in continuation of the work done here: https://github.com/chipsalliance/rocket-chip/pull/2480

TLAdapter_ACancel node addition

---

src/main/scala/tile/BaseTile.scala

N/A
I ran into this require statement and had some trouble understanding, so I added a small message for debug

add message to paddr bits require

---

src/main/scala/amba/ahb/SRAM.scala
src/main/scala/amba/apb/SRAM.scala
src/main/scala/amba/axi4/SRAM.scala
src/main/scala/tilelink/SRAM.scala

Changes to accomodate for address ranges, which require more than 32bits

---

src/main/scala/diplomaticobjectmodel/logicaltree/RocketLogicalTreeNode.scala
src/main/scala/diplomaticobjectmodel/model/OMRocketCore.scala

**Related issue**: follow-on to https://github.com/chipsalliance/rocket-chip/pull/2422
**Type of change**: feature enhancement

Object Model: separate concept of supervisor mode from presence of MMU

---

src/main/scala/rocket/RocketCore.scala

The xrfWriteBundle.wrenx needs additional qualification to separate it from coreMonitorBundle

Update the xrfWriteBundle.wrenx to set only when it is different from coreMonitorBundle

---

src/main/scala/subsystem/BankedL2Params.scala
src/main/scala/tilelink/Broadcast.scala

Make it possible to use a filter with a banked broadcast hub.

Banked Broadcast

---

src/main/scala/amba/ahb/ToTL.scala
src/main/scala/amba/axis/Parameters.scala
src/main/scala/diplomacy/Parameters.scala
src/main/scala/tilelink/Fragmenter.scala
src/main/scala/tilelink/Parameters.scala

Changed the function called cover to mincover.
Tightened the bound for the fragmenter by adding shrinktransfer.
Added comment.
Changed setName to name in the v2 constructor.
This is part of adding emits parameters to RC.

Changed the function called cover to mincover. Tightened the bound for the fragmenter by adding shrinktransfer. Added comment.

---

src/main/scala/diplomaticobjectmodel/logicaltree/RocketLogicalTreeNode.scala
src/main/scala/diplomaticobjectmodel/model/OMFPU.scala

Teach OM about Zfh extension

---

build.wake
ci-tests/wake_scala_compilation
wit-manifest.json

These cause warnings on 0.19.0

Fix unused args

---

src/main/scala/diplomaticobjectmodel/logicaltree/RocketLogicalTreeNode.scala
src/main/scala/diplomaticobjectmodel/model/OMRocketCore.scala
src/main/scala/diplomaticobjectmodel/model/OMUTLB.scala
src/main/scala/rocket/PTW.scala
src/main/scala/tile/RocketTile.scala

Object Model: add L2 UTLB entries and memory

Object Model: add L2 UTLB entries and memory

---

src/main/scala/prci/ClockDivider.scala

bug fix for ClockDivider

---

src/main/scala/devices/debug/Periphery.scala

Making instantiation of these reset synchronizers optional, since some configs may wish to instantiate them elsewhere in another hierarchy

Debug: Make reset synchronizer instanatiation optional

---

src/main/scala/tilelink/Xbar.scala

Correct a typo in Xbar.scala

---

README.md

Add pointer to the docs directory in the README

Add nod to docs in the README

---

src/main/scala/subsystem/HasTiles.scala

Add seipNode similar to meipNode

---

src/main/scala/rocket/PTW.scala

add PTW Performance Monitor Events for L2TLB Hit and PTE Cache Miss/Hit, but do not hook them up

PTWPerfEvents pte_miss/hit, l2hit

---

src/main/scala/subsystem/Configs.scala

fix type mismatch when using WithExtMemSize

---

src/main/scala/util/IDPool.scala

**Related issue**: after https://github.com/chipsalliance/rocket-chip/pull/2677, I can dial back https://github.com/chipsalliance/rocket-chip/pull/2673/commits/f165c98d83589e6e85dcfc52b185dd1a55d32e86

IDPool: infer widths

---

src/main/scala/rocket/CSR.scala

See https://github.com/riscv/riscv-isa-manual/issues/427
This is a backwards-incompatible change between priv-1.11 and priv-1.12, so we won't merge until closer to ratification.

implement updated MPRV proposal

---

.gitignore
build.sc
common.sc
wit-manifest.json

This PR adds mill build system.
`common.sc` is used for using rocketchip as in-project build-from-source dependency.
for example(`mychisel3`, `myhardfloat`, `myconfig` are other in-project dependencies.)
```
import $`file.rocket-chip.common`
object myrocketchip extends rocketchip.common.CommonRocketChip {
override def millSourcePath = os.pwd / "rocket-chip"
def chisel3Module: Option[PublishModule] = Some(mychisel3)
def hardfloatModule: PublishModule = myhardfloat
def configModule: PublishModule = myconfig
}
```
can create a `myrocketchip` module, while other project can directly depend on it
`build.sc` is used for running rocket-chip as top …

Add mill build system

---

src/main/scala/rocket/PTW.scala

**Related issue**: follow-up to https://github.com/chipsalliance/rocket-chip/pull/2668
PTE Cache Hit/Miss Performance Monitor Events are lower priority than L2TLB Hit event

PTW do not count pte_hit/miss event on L2TLB hits

---

src/main/scala/devices/tilelink/PhysicalFilter.scala

Add RegFieldDesc and scaladoc to PhysicalFilter Tile Link Device

PhysicalFilter: add RegFieldDesc and scaladoc

---

README.md

Fix out-of-date readme.

---

README.md

Fix for documentation. Debug section described adding some lines to the configuration, that didn't work out of the box.

Fix minor issue in readme about adding code for Debug

---

build.sbt
wit-manifest.json

Bump Chisel and FIRRTL just beyond x.4.1

Bump Chisel and firrtl along 3.4.1.x

---

src/main/scala/diplomaticobjectmodel/model/OMISA.scala

remove extra space in OM info for C extension version

---

src/main/scala/rocket/CSR.scala

trim coverage to only reachable counters

Don't attempt to cover non-existent U-mode counters

---

src/main/scala/tile/FPU.scala

Since the state transitions in the divider depend on the data values, the in.ready signal becomes X if the input data is X.  This fact becomes problematic for speculative instructions, since the state might not yet have been initialized.

prevent X prop from speculative fdiv/fsqrt instructions

---

src/main/scala/rocket/ScratchpadSlavePort.scala

Convert PutPartials to PutFulls when the mask is full to avoid RMW.

Fix a DTIM X-prop issue

---

CONTRIBUTING.md

Update CONTRIBUTING.md to add instructions for signing the Chips Alliance CLA

---

.gitmodules
build.sbt
build.sc
common.sc
regression/Makefile

**Related issue**: suppress #2844
Use ivy chisel3.

switch chisel3 dependency to ivy and bump to chisel 3.4.3

---

build.sc
common.sc

fix build errors with mill

---

src/main/scala/rocket/PTW.scala
src/main/scala/rocket/TLB.scala

**Related issue**: this code has been in Rocket-chip for a long time, since chipsalliance/rocket-chip@069858a
The RISC-V ISA spec says:
1. Access fault when accessing a PTE.
2. Page faults.
3. Access fault with physical address for an explicit memory access.
separate `ae` into two cases (AE when accessing PTE vs. AE for bad PPN) and handle them with different priorities in the TLB

MMU: final pte.permission page fault > final pte.ppn access exception

---

build.sbt

**Related issue**: #2932 
Bumped to Chisel 3.5.1

Bump to Chisel 3.5.1

---

build.sbt
project/plugins.sbt
src/main/scala/rocket/ScratchpadSlavePort.scala

Bump Chisel to 3.5.2 and Scala to 2.12.15

Bump Chisel to 3.5.2 and Scala to 2.12.15

---

src/main/scala/rocket/PTW.scala

Support building PTW with no PTECache

---

src/main/scala/util/CRC.scala

#2963 just so users can follow the CRC object's API a bit better. 
Perhaps #2960 should include a scala doc
#2963

[CRC.scala][NFC] Note CRC's object explicit+1 notation

---

src/main/scala/subsystem/Configs.scala

Update IncoherentBusTopology to support multiclock and custom cloking

---

src/main/scala/subsystem/RocketSubsystem.scala

Allow forcing RocketTiles into independent PRCI group

---

src/main/scala/subsystem/Configs.scala

**Impact**: no functional change | API addition (no impact on existing code)
Add WithHypervisor config for ease of using H-extension.

configs: add WithHypervisor config

---

src/main/scala/util/SynchronizerReg.scala

To upgrade to Chisel 3.6, this PR needs to be merged. But this is safe to merge now.
**Related issue**: chipsalliance/chisel3#2496

Fix for chipsalliance/chisel3#2496

---

src/main/scala/rocket/CSR.scala

Partially reverts #2836, but in such a way that it works with the new QMC.
FYI @sequencer

Fix decoding of CSR addresses when usingHypervisor

---

src/main/scala/rocket/RocketCore.scala

from https://github.com/chipsalliance/rocket-chip/issues/2995
cc to @aswaterman

add assert to haveFSDirty

---

src/main/scala/rocket/AMOALU.scala

Refactor AMOALU.scala to chisel3 style.

refactor AMOALU to chisel3.

---

src/main/scala/rocket/Decode.scala

Refactor Decode.scala to chisel3 style.

refactor Decode to chisel3.

---

src/main/scala/formal/FormalUtils.scala

Bump the formal subdirectory to chisel3

feat: bump formal to chisel3

---

src/main/scala/rocket/Events.scala

Refactor Events.scala to chisel3 style.

refactor Events to chisel3.

---

src/main/scala/rocket/HellaCacheArbiter.scala

Refactor HellaCacheArbiter.scala to chisel3 style.

refactor HellaCacheArbiter to chisel3.

---

src/main/scala/rocket/DCache.scala
src/main/scala/rocket/HellaCache.scala

Refactor HellaCache.scala to chisel3 style.

refactor HellaCache to chisel3.

---

src/main/scala/regmapper/DescribedReg.scala
src/main/scala/regmapper/RegField.scala
src/main/scala/regmapper/RegMapper.scala
src/main/scala/regmapper/RegisterCrossing.scala
src/main/scala/regmapper/RegisterRouter.scala
src/main/scala/regmapper/Test.scala

Converts the regmapper directory to chisel3

feat: convert regmapper to chisel3

---

src/main/scala/unittest/Configs.scala
src/main/scala/unittest/TestGenerator.scala
src/main/scala/unittest/TestHarness.scala
src/main/scala/unittest/UnitTest.scala
src/main/scala/unittest/package.scala

Convert unittest subdir to use chisel3

feat: convert unittest to chisel3

---

src/main/scala/prci/IOHelper.scala

convert prci directory to use chisel3

feat: convert prci to chisel3

---

src/main/scala/rocket/Multiplier.scala

Refactor Multiplier.scala to chisel3 style.

refactor Multiplier to chisel3.

---

src/main/scala/rocket/IBuf.scala

Refactor IBuf.scala to chisel3 style.

refactor IBuf to chisel3.

---

src/main/scala/rocket/BTB.scala

Refactor BTB.scala to chisel3 style.

refactor BTB to chisel3.

---

src/main/scala/util/package.scala

Refactor util/package.scala to chisel3 style.

refactor util/package to chisel3.

---

src/main/scala/rocket/TLBPermissions.scala

Refactor TLBPermissions.scala to chisel3 style.

refactor TLBPermissions to chisel3.

---

src/main/scala/rocket/ICache.scala

Refactor ICache.scala to chisel3 style.

refactor ICache to chisel3.

---

src/main/scala/rocket/CSR.scala

Refactor CSR.scala to chisel3 style.

refactor CSR to chisel3.

---

src/main/scala/rocket/DCache.scala

Refactor DCache.scala to chisel3 style.

refactor DCache to chisel3.

---

src/main/scala/devices/tilelink/BootROM.scala

Port BootROM.scala to Chisel 3

---

src/main/scala/util/ReduceOthers.scala

Refactor ReduceOthers.scala to chisel3 style.

refactor ReduceOthers to chisel3.

---

src/main/scala/devices/tilelink/BusBypass.scala

Port BusBypass.scala to Chisel 3

---

build.sbt
common.sc

bump chisel3 to 3.5.4

---

src/main/scala/rocket/DCache.scala
src/main/scala/rocket/Frontend.scala
src/main/scala/rocket/PTW.scala
src/main/scala/rocket/RocketCore.scala
src/main/scala/tile/FPU.scala

remove chiselName, fix for chipsalliance/chisel3#2694

---

src/main/scala/interrupts/Bundles.scala
src/main/scala/interrupts/Crossing.scala
src/main/scala/interrupts/Nodes.scala
src/main/scala/interrupts/NullIntSource.scala
src/main/scala/interrupts/Xbar.scala
src/main/scala/util/SynchronizerReg.scala

Some renaming in interrupts/* and util/SynchronizerReg for Chisel3

---

src/main/scala/subsystem/BaseSubsystem.scala
src/main/scala/subsystem/Configs.scala
src/main/scala/subsystem/HasTiles.scala
src/main/scala/subsystem/InterruptBus.scala
src/main/scala/subsystem/RTC.scala

Port subsystem/* to chisel3

---

src/main/scala/util/AsyncResetReg.scala

Refactor util/AsyncResetReg to chisel3

---

src/main/scala/subsystem/Configs.scala

Fix regression introduced by #3126

Re-add missing import in subsystem/Config

---

src/main/scala/util/Crossing.scala

Related issue:
Release Notes
Refactor Crossing.scala to chisel3 style.

Refactor crossing

---

src/main/scala/util/ROMGenerator.scala

Refactor ROMGenerator.scala to chisel3 style.

refactor ROMGenerator to chisel3. 

---

src/main/scala/util/ResetCatchAndSync.scala

Refactor ResetCatchAndSync.scala to chisel3 style.

refactor ResetCatchAndSync to chisel3.

---

src/main/scala/util/MuxLiteral.scala

Refactor MuxLiteral.scala to chisel3 style.

refactor MuxLiteral to chisel3.

---

src/main/scala/util/Counters.scala

Refactor util/Counters to chisel3

---

src/main/scala/devices/tilelink/CLINT.scala

Port CLINT.scala to Chisel 3

---

src/main/scala/rocket/IDecode.scala

Port rocket/IDecode to chisel3

---

src/main/scala/rocket/Frontend.scala

Port rocket/Frontend to chisel3

---

src/main/scala/util/ECC.scala

Port util/ECC.scala to Chisel 3

---

src/main/scala/util/CRC.scala

Refactor util/CRC to chisel3

---

src/main/scala/tile/FPU.scala

Port tile/fpu to chisel3

---

src/main/scala/util/Broadcaster.scala

Refactor util/Broadcaster to chisel3

---

src/main/scala/rocket/PTW.scala

**Related issue**:  
When Sv57 is configured, the bit width of PPN is narrower than VPN, which cause MSB bit lost when access PTE Cache.
This fix add `aux_ppn_hi` bit to hold that those missing MSBs, so that it can be properly used to construct `pte_cache_addr` by doing 
```
val ext_aux_pte_ppn = aux_ppn_hi match {
case None     => aux_pte.ppn
case Some(hi) => Cat(hi, aux_pte.ppn)
}
(ext_aux_pte_ppn >> (pgLevels - i - 1) * pgLevelBits)(pgLevelBits - 1, 0)
```
bug fix
RTL functional change
implementation

[fix] fix ppn bit mismatch when Sv57

---

CHANGELOG.md

https://github.com/chipsalliance/rocket-chip/issues/2960
This is part of the release notes! This changelog is aimed to help with migration and informing users between releases of RC.

Changelog v2

---

src/main/scala/rocket/RocketCore.scala

Port rocket/RocketCore to chisel3

---

src/main/scala/rocket/NBDcache.scala

Port rocket/NBDCache to chisel3

---

src/main/scala/rocket/HellaCache.scala

Fix hellacache RegInit width

---

src/main/scala/rocket/ScratchpadSlavePort.scala

Port rocket/ScratchpadSlavePort to chisel3

---

src/main/scala/rocket/TLB.scala

Port rocket/TLB to Chisel3

---

.github/workflows/continuous-integration.yml
.scalafix.conf

Temporarily remove this so tests pass again. In bumping to 2.13, this becomes overly aggressive.

Disable the RemoveUnused scalafix rule

---

build.sc
common.sc

This follows 60f564b
This depends on https://github.com/ucb-bar/berkeley-hardfloat/pull/69 so do not merge now

mill: Bump to scala 2.13.10/chisel3.5.5

---

build.sc

**Related issue**: follow up of #3182
Generate emulator from mill

mill: add support of emulator generation

---

build.sc

**Related issue**: follow up of #3182, and this PR depends on #3189 
Run riscv-tests from mill.

mill: add support of running riscv-tests

---

build.sbt
common.sc

Bumps the Maven release number according to actual release

chore: bump maven release for sbt and mill

---

emulator/Makefile
vsim/Makefrag

Use c++17 for emulator compile

---

src/main/scala/devices/tilelink/CLINT.scala
src/main/scala/rocket/Frontend.scala
src/main/scala/rocket/IDecode.scala
src/main/scala/rocket/NBDcache.scala
src/main/scala/rocket/RocketCore.scala
src/main/scala/rocket/ScratchpadSlavePort.scala
src/main/scala/rocket/TLB.scala
src/main/scala/tile/FPU.scala
src/main/scala/util/Arbiters.scala
src/main/scala/util/Broadcaster.scala
src/main/scala/util/CRC.scala
src/main/scala/util/Counters.scala
src/main/scala/util/ECC.scala
src/main/scala/util/HellaQueue.scala
src/main/scala/util/MuxLiteral.scala
src/main/scala/util/ROMGenerator.scala
src/main/scala/util/ReorderQueue.scala
src/main/scala/util/ResetCatchAndSync.scala

Rebasing lost commits in chisel3_port

---

.github/workflows/mill-ci.yml
build.sc
flake.lock
flake.nix
overlay.nix

**Related issue**: follow up of #3182

Add new CI on riscv-tests based on mill

---

build.sc
scripts/arch-test/emulator/env/link.ld
scripts/arch-test/emulator/env/model_test.h
scripts/arch-test/emulator/riscof_emulator.py
scripts/arch-test/spike/env/link.ld
scripts/arch-test/spike/env/model_test.h
scripts/arch-test/spike/riscof_spike.py

**Related issue**: follow up of #3182, and this PR depends on #3189
Supports [riscv-arch-test](https://github.com/riscv-non-isa/riscv-arch-test)

mill: add support of running riscv-arch-test

---

src/main/scala/rocket/CSR.scala
src/main/scala/rocket/RocketCore.scala
src/main/scala/stage/phases/AddDefaultTests.scala
src/main/scala/subsystem/Configs.scala
src/main/scala/system/Configs.scala
src/main/scala/system/RocketTestSuite.scala

**Development Phase**: mplementation

Add other riscv-tests tests

---

build.sc

mill: enable zicntr test for TinyConfig

---

.github/workflows/mill-ci.yml
build.sc

mill: enable rv64uzfh riscv-tests

---

src/main/scala/diplomacy/Clone.scala
src/main/scala/diplomacy/CloneModule.scala

**Related issue**: chipsalliance/chisel3#1945
Replace .getPorts with DataMirror.modulePorts

Replace .getPorts with DataMirror.modulePorts

---

src/main/scala/rocket/CSR.scala

**Related issue**: #3207
Implemented time[h] CSR; Support Zicntr extension.

Implement time[h] CSR using cycle[h] CSR

---

src/main/scala/rocket/CSR.scala

This is a follow-up to https://github.com/chipsalliance/rocket-chip/commit/3ff921de046367dbd114150bfca471b5eb0c1550
Add Zihpm support

Always provide hpmcounterN[h] CSRs

---

src/main/scala/rocket/CSR.scala

This reverts commit 69d260fa63faf96e52f61e59139d6142a84a5d3b.
**Related issue**: #3208 #3207
Remove time CSR as it is not compliant; Drop support of Zicntr

Revert "Implement time[h] CSR using cycle[h] CSR"

---

.github/workflows/mill-ci.yml
build.sc

Enable privileged arch-test in CI

---

README.md

Add meeting calendar and notes url

---

src/main/scala/groundtest/TraceGen.scala
src/main/scala/rocket/HellaCache.scala
src/main/scala/rocket/NBDcache.scala
src/main/scala/rocket/PTW.scala
src/main/scala/subsystem/Configs.scala
src/main/scala/system/RocketTestSuite.scala
src/main/scala/tilelink/Edges.scala
src/main/scala/tilelink/ToAPB.scala
src/main/scala/unittest/UnitTest.scala
src/main/scala/util/HellaQueue.scala
src/main/scala/util/ResetCatchAndSync.scala

Some leftover issues that the regressions didn't catch.

Assorted fixes for scala 2.13/chisel 3.5.5

---

src/main/scala/util/HellaQueue.scala
src/main/scala/util/ResetCatchAndSync.scala

util: fix errors during FIRRTL pass

---

src/main/scala/subsystem/Configs.scala

Fix MaxHartIdBits calculations for no-tile configs

---

build.sbt
common.sc

**Related issue**: blocked by #3196

Bump to Chisel 3.5.6

---

.github/workflows/mill-ci.yml
build.sc
src/main/scala/system/Configs.scala

Making hypervisor extension a config makes it more accessible for users, and the extension should be covered in CI. 
Add HypervisorConfig

Add HypervisorConfig and cover it in CI

---

.github/workflows/continuous-integration.yml

[Invalid workflow file: .github/workflows/continuous-integration.yml#L82](https://github.com/chipsalliance/rocket-chip/actions/runs/4192342513/workflow)
The workflow is not valid. .github/workflows/continuous-integration.yml (Line: 82, Col: 9): Unexpected value 'submodules'

Fix legacy CI workflow

---

.github/workflows/continuous-integration.yml

Fix CI mill version

---

.github/workflows/continuous-integration.yml
src/main/resources/META-INF/services/firrtl.options.RegisteredLibrary

**Related issue**:  Legacy CI for https://github.com/chipsalliance/rocket-chip/commit/8204bfad52aa7d8e8b831e829f233385c059d437 failed

Fix legacy CI

---

src/main/scala/amba/ahb/AHBLite.scala
src/main/scala/amba/ahb/Xbar.scala
src/main/scala/amba/apb/Xbar.scala
src/main/scala/amba/axi4/Credited.scala
src/main/scala/amba/axi4/Deinterleaver.scala
src/main/scala/amba/axi4/Filter.scala
src/main/scala/amba/axi4/Fragmenter.scala
src/main/scala/amba/axi4/IdIndexer.scala
src/main/scala/amba/axi4/ToTL.scala
src/main/scala/amba/axi4/UserYanker.scala
src/main/scala/amba/axi4/Xbar.scala
src/main/scala/amba/axis/Xbar.scala
src/main/scala/regmapper/RegisterRouter.scala
src/main/scala/tilelink/AddressAdjuster.scala
src/main/scala/tilelink/Arbiter.scala
src/main/scala/tilelink/Bundle_ACancel.scala
src/main/scala/tilelink/Credited.scala
src/main/scala/tilelink/HintHandler.scala
src/main/scala/tilelink/ToAHB.scala
src/main/scala/tilelink/ToAPB.scala
src/main/scala/tilelink/ToAXI4.scala
src/main/scala/tilelink/Xbar.scala
src/main/scala/util/BarrelShifter.scala
src/main/scala/util/RecordMap.scala

Select backportable commits from `dev` branch to `master`.
(we need mergify)

Backport from #3243

---

build.sc
flake.lock
flake.nix
scripts/arch-test/emulator/riscof_emulator.py
scripts/arch-test/spike/riscof_spike.py

mill: Use MFC

---

src/main/scala/tile/LazyRoCC.scala

Fix CharCount RoCC example bug

---

src/main/scala/amba/ahb/Nodes.scala
src/main/scala/amba/ahb/Parameters.scala
src/main/scala/amba/apb/Nodes.scala
src/main/scala/amba/apb/Parameters.scala
src/main/scala/amba/axi4/Nodes.scala
src/main/scala/amba/axi4/Parameters.scala
src/main/scala/amba/axis/Nodes.scala
src/main/scala/amba/axis/Parameters.scala
src/main/scala/devices/debug/Custom.scala
src/main/scala/devices/tilelink/Plic.scala
src/main/scala/diplomacy/BundleBridge.scala
src/main/scala/diplomacy/Nodes.scala
src/main/scala/interrupts/Nodes.scala
src/main/scala/interrupts/Parameters.scala
src/main/scala/prci/ClockNodes.scala
src/main/scala/prci/ClockParameters.scala
src/main/scala/regmapper/RegMapper.scala
src/main/scala/rocket/DCache.scala
src/main/scala/rocket/Frontend.scala
src/main/scala/rocket/ICache.scala
src/main/scala/rocket/PTW.scala
src/main/scala/rocket/TLB.scala
src/main/scala/tile/FPU.scala
src/main/scala/tilelink/Edges.scala
src/main/scala/tilelink/Nodes.scala
src/main/scala/tilelink/Parameters.scala
src/main/scala/util/Property.scala

+ Use `chisel3.experimental.SourceInfo`;

Fix Werror: replace SourceInfo with experimental.SourceInfo

---

src/main/scala/rocket/IDecode.scala
src/main/scala/rocket/RocketCore.scala
src/main/scala/subsystem/Configs.scala

Support generating rocket w/o CEASE

---

src/main/scala/tilelink/SourceShrinker.scala

This was broken in chisel2->chisel3 bump

Fix TLSourceShrinker

---

src/main/scala/rocket/CSR.scala
src/main/scala/rocket/RocketCore.scala
src/main/scala/tile/Core.scala
src/main/scala/tile/LazyRoCC.scala
src/main/scala/tile/RocketTile.scala

**Impact**:  API addition (no impact on existing code) 

Support RoCC accels which define CSRs

---

src/main/scala/amba/ahb/Bundles.scala
src/main/scala/amba/ahb/SRAM.scala
src/main/scala/amba/ahb/Test.scala
src/main/scala/amba/ahb/ToTL.scala
src/main/scala/amba/ahb/Xbar.scala
src/main/scala/amba/apb/Test.scala
src/main/scala/amba/axi4/AsyncCrossing.scala
src/main/scala/amba/axi4/Delayer.scala
src/main/scala/amba/axi4/RegisterRouter.scala
src/main/scala/amba/axi4/Test.scala
src/main/scala/amba/axi4/Xbar.scala
src/main/scala/devices/tilelink/MasterMux.scala
src/main/scala/devices/tilelink/TestRAM.scala
src/main/scala/regmapper/RegisterCrossing.scala
src/main/scala/regmapper/Test.scala
src/main/scala/tilelink/AsyncCrossing.scala
src/main/scala/tilelink/AtomicAutomata.scala
src/main/scala/tilelink/RegisterRouterTest.scala
src/main/scala/tilelink/ToAHB.scala

Fixes more things that were broken by dropping Chisel2

Fixes for unit-tests

---

src/main/scala/tilelink/Delayer.scala
src/main/scala/tilelink/Fragmenter.scala
src/main/scala/tilelink/Fuzzer.scala
src/main/scala/tilelink/RationalCrossing.scala

Fix TL unittests

---

src/main/scala/util/Blockable.scala
src/main/scala/util/CreditedIO.scala

- BlockDuringReset can now be attached to CreditedIO
- CreditedIO can have dynamically configurable `depth` number of credits, where `depth < maxDepth.U`, and maxDepth is a design parameter.

Make CreditedIO more usable

---

src/main/scala/rocket/CSR.scala

I believe wiring them to 0 is ok.

Add [m/s/h]envcfg CSRs to satisfy spec requirements

---

common.sc
src/main/scala/devices/debug/Debug.scala
src/main/scala/devices/debug/DebugTransport.scala
src/main/scala/diplomacy/BundleBridge.scala
src/main/scala/diplomacy/Nodes.scala
src/main/scala/prci/ClockGroupDriver.scala
src/main/scala/prci/IOHelper.scala
src/main/scala/rocket/DCache.scala
src/main/scala/rocket/HellaCache.scala
src/main/scala/rocket/ICache.scala
src/main/scala/rocket/Multiplier.scala
src/main/scala/rocket/SimpleHellaCacheIF.scala
src/main/scala/tile/LazyRoCC.scala
src/main/scala/tilelink/AddressAdjuster.scala
src/main/scala/tilelink/Arbiter.scala
src/main/scala/tilelink/AtomicAutomata.scala
src/main/scala/tilelink/Broadcast.scala
src/main/scala/tilelink/Monitor.scala
src/main/scala/tilelink/SRAM.scala
src/main/scala/tilelink/ToAPB.scala
src/main/scala/tilelink/WidthWidget.scala
src/main/scala/unittest/UnitTest.scala
src/main/scala/util/AsyncQueue.scala
src/main/scala/util/CreditedIO.scala
src/main/scala/util/LanePositionedQueue.scala
src/main/scala/util/MultiPortQueue.scala
src/main/scala/util/RationalCrossing.scala
src/main/scala/util/ReadyValidCancel.scala
src/main/scala/util/Repeater.scala
src/main/scala/util/ShiftQueue.scala

- remove experimental.IO chipsalliance/chisel#2863
- remove additional bracket
- remove Chisel compatibility mode

fix compile for chisel3.6

---

src/main/scala/diplomacy/LazyModule.scala

+ add `case _` to make match be exhaustive

Fix Werror: match may not be exhaustive

---

src/main/scala/util/GeneratorUtils.scala

No rocketchip stage utils

---

.github/workflows/mill-ci.yml

It runs too long, I prefer adding some new schemes for test them.

Disable Arch Test for now

---

src/main/scala/diplomacy/BundleBridge.scala
src/main/scala/diplomacy/Nodes.scala

remove import Chisel from Nodes

---

src/main/scala/rocket/RocketCore.scala
src/main/scala/subsystem/Configs.scala

Add WithNoSimulationTimeout to remove plusargs in generated RTL.

add WithNoSimulationTimeout

---

src/main/scala/devices/tilelink/Plic.scala

fix PLIC 0-bit connection

---

src/main/scala/subsystem/Configs.scala

add WithScratchpadsBaseAddress to alter rocket core dtim address

---

src/main/scala/tilelink/SourceShrinker.scala

Suppress SourceShrinker require if no shrinking is to be done

---

Makefrag

Fix Makefrag for mill cross-compile

---

src/main/scala/rocket/SimpleHellaCacheIF.scala

Connect all s1_data fields in SimpleHellaIF

---

src/main/scala/tilelink/Delayer.scala
src/main/scala/tilelink/Edges.scala

**Related issue**:  PR #3287 (not fully fixed before)

Fix the missing DontCare in TLEdgeOut

---

build.sc
flake.lock
flake.nix

Bump flake dependencies

---

src/main/scala/tile/RocketTile.scala

Fix CSRIO bidir connection

---

src/main/scala/rocket/PTW.scala

**Related issue**: `r_pte` should be updated when s2 pte cache hit
**Impact**: 
When Hypervisor is enabled and MODE is not Bare, if the `hgatp` is not in the same 512GB range as `vsatp`, the `r_pte` will be updated with unexpected value.

Fix `r_pte` update condition when S2 PTE cache hit

---

src/main/scala/rocket/PTW.scala

Fix r_pte update condition when S2 PTE cache hit (#3525)

---

build.sc

add sonatype snapshots repo for test chisel releases

---

build.sc

Bump to Chisel 5.1

---

docs/src/diplomacy/adder_tutorial.md

refactor(doc): update diplomacy adder code sample to pass compiling

---

src/main/scala/rocket/HellaCache.scala

Remove the unused outer argument in HellaCacheBundle

Remove the unused outer argument in HellaCacheBundle

---

README.md

Fix outdated technical report link.

---

src/main/scala/rocket/RocketCore.scala

Fence for RoCC on rocc-csr writes

---

src/main/scala/tilelink/FIFOFixer.scala

FIFOFixer should be identity when no clients may request Fifo

---

build.sc
common.sc

bump diplomacy and switch to diplomacy/master

---

src/main/scala/rocket/PTW.scala
src/main/scala/rocket/TLB.scala
src/main/scala/util/package.scala

Sync master into dev

---

src/main/scala/subsystem/HasHierarchicalElements.scala

Bug was introduced with hierarchical elements

Fix connection order of meip/seip to plic

---

src/main/scala/devices/tilelink/Plic.scala

Suggest name for plic domain

---

src/main/scala/devices/tilelink/BootROM.scala
src/main/scala/devices/tilelink/CLINT.scala
src/main/scala/devices/tilelink/Plic.scala
src/main/scala/prci/ClockDomain.scala
src/main/scala/tilelink/BusWrapper.scala

Name the ClockDomains

---

src/main/scala/rocket/RocketCore.scala
src/main/scala/rocket/VectorUnit.scala
src/main/scala/tile/BaseTile.scala
src/main/scala/tile/Core.scala

Support vector extensions

---

src/main/scala/rocket/RocketCore.scala

Prevent bypasses from vector instructions | fix vsets

---

src/main/scala/rocket/SimpleHellaCacheIF.scala

increase depth of SimpleHellaCacheIFReplayQ #3653

---

src/main/scala/rocket/RocketCore.scala
src/main/scala/rocket/VectorUnit.scala
src/main/scala/tile/FPU.scala

VectorDecoder in FPU may need to check v_sew'

---

src/main/scala/devices/debug/Debug.scala

Fix DMCONTROLNxt naming

---

src/main/scala/amba/axi4/Buffer.scala

Add AXI4 buffer-chain methods.

AXI4 buffer chain

---

src/main/scala/trace/TraceEncoderController.scala

Tacit bp pr

---

src/main/scala/rocket/CSR.scala

Fix for chisel7 compatibility
