chipsalliance/rocket-chip

- src/main/scala/tilelink/Fuzzer.scala
Per the tilelink specification ver. 1.7.1 section 3.2.2, valid signals should be driven low while reset is asserted. In this case, TLFuzzer is the master and should drive a.valid low during a reset.
> keep valid signal low while reset is high

- src/main/scala/devices/debug/Debug.scala
- src/main/scala/devices/debug/Periphery.scala
- src/main/scala/diplomaticobjectmodel/model/OMDebug.scala
- src/main/scala/subsystem/BaseSubsystem.scala
- src/main/scala/subsystem/Configs.scala
API changes to more consistently describe how the debug unit interfaces with external ports and buses:
- `DebugExportProtocol` exhaustively enumerates port types (`DMI|JTAG|CJTAG|APB`) rather than being a collection of one-hot boolean fields
- `BaseSubsystemBusAttachment` exhaustively enumerates tilelink bus attachment locations (`SBUS|FBUS|CBUS|MBUS|PBUS`); this will be used by other attachment methods eventually
- Debug unit can be attached to different buses based on `ExportDebug` `Field` values
(might  rebase this one #2030 goes in)
> Debug: interface and attachment parameterization

- src/main/scala/tilelink/Fragmenter.scala
Bug fix.
Fragmenter helper inserts an ephemeral node in cases where no fragmentation is required. I got the logic wrong before in that it would still try to build a fragmenter even in the negative case, which would fail.
> tilelink: correct fragmenter helper

- src/main/scala/rocket/Breakpoint.scala
- src/main/scala/rocket/RocketCore.scala
- src/main/scala/tile/BaseTile.scala
- src/main/scala/tile/Core.scala
This PR parameterizes the width of the valid field of BPWatch to accommodate systems with retireWidth>1.  
There is also a bugfix for load and store watchpoints - these were being accepted into the watchpoint pipeline two stages too early.
> parameterize watchpoint retirewidth

- src/main/scala/groundtest/Configs.scala
- src/main/scala/groundtest/GroundTestSubsystem.scala
- src/main/scala/groundtest/Tile.scala
- src/main/scala/rocket/NBDcache.scala
The TraceGenConfig in groundtest is pretty outdated and currently doesn't work. These changes get it working again and also allow it to check the NonBlockingDCache. 
Fix TraceGen groundtest and allow it to use the NonBlockingDCache
> Fix TraceGen issues and allow it to use NonBlockingDCache

- src/main/scala/groundtest/GroundTestSubsystem.scala
Restores some functionality erroneously removed by #2040
> GroundTest: restore lines needed for L2 Tracegen tests

- src/main/scala/rocket/ICache.scala
- src/main/scala/tile/RocketTile.scala
This helps introspective code know how much RAM actually lives in the ITIM.
> Separate ITIM DeviceTree into memory and control parts

- src/main/scala/devices/tilelink/DevNull.scala
`DevNull` devices (and by extension the ErrorDevice) had some baked in assumptions about supported transfer types. Mandating support for atomics and hints turned out to be disadvantageous when attempting to replicate address regions that don't have to support those transfers.
> devices: allow error devs that only support tl-ul

- src/main/scala/devices/debug/Debug.scala
Add async reset register on dmouter output hartResetReq to eliminate CDC warning.
> Debug: register hartResetReq output

- src/main/scala/tilelink/ToAHB.scala
This knob is currently necessary to tweak in some situations, but was not exposed via the `TLToAHB` helper object's apply method
> ahb: allow supportsRETRY to be overridden in helper

- src/main/scala/rocket/DCache.scala
A per-line CFLUSH followed by a regular load that gets nacked in the s1 stage could kill the load without reporting to the pipeline that it had been killed.
> Fix per-line CFLUSH

- src/main/scala/util/DescribedSRAM.scala
Being unfamiliar with the specific differences between Chisel 2 and Chisel 3, it took me a little while reading the code to realize that `SyncReadMem` and `SeqMem` are [aliases of each other](https://github.com/freechipsproject/chisel3/blob/b2a1bd7a10977d3331fee3022ec490a1aa1e0e17/src/main/scala/chisel3/compatibility.scala#L286). It doesn't seem to trigger a deprecation warning, and none of the existing chisel3 documentation appears to mention that `SyncReadMem` is the chisel3 version of `SeqMem`, despite there being independent documentation on `SyncReadMem` and `SeqMem`.
I've upgraded the `DescribedSRAM` module to chisel3 so that future readers of the code hopefully don't need to …
> Upgrade DescribedSRAM to chisel3.

- src/main/scala/devices/debug/Debug.scala
- src/main/scala/rocket/TLB.scala
Per discussion with @terpstra, doing this in a direct, non-diplomatic fashion is the best near-term solution.
> Deny access to debug region for M-mode and below

- src/main/scala/diplomaticobjectmodel/logicaltree/RocketLogicalTreeNode.scala
- src/main/scala/diplomaticobjectmodel/model/OMCaches.scala
- src/main/scala/diplomaticobjectmodel/model/OMRocketCore.scala
- src/main/scala/rocket/Frontend.scala
- src/main/scala/rocket/ScratchpadSlavePort.scala
- src/main/scala/tile/RocketTile.scala
The various Rocket memories were not being correctly serialized into the Object Model JSON file, since the case class describing the `OMCache` set the type of the `memories` attribute to `() => Seq[OMSRAM]`, and it appears that the default JSON serializer serializes function types to the empty JSON object (map) type.
The main fix I made was to change the type from `() => Seq[OMSRAM]` to just `Seq[OMSRAM]`, but I also made a few other changes to how data is being passed around, partly to obviate the need to pass around thunk in the first place but also to (IMO) simplify the control flow a little bit:
- I replaced the thunk arguments of `() => Seq[OMSRAM]` …
> Fix OMSRAM serialization in RocketTile memories.

- src/main/scala/amba/ahb/AHBLite.scala
- src/main/scala/amba/ahb/Bundles.scala
- src/main/scala/amba/ahb/Nodes.scala
- src/main/scala/amba/ahb/Parameters.scala
- src/main/scala/amba/ahb/RegisterRouter.scala
- src/main/scala/amba/ahb/SRAM.scala
- src/main/scala/amba/ahb/ToTL.scala
- src/main/scala/amba/ahb/Xbar.scala
- src/main/scala/tilelink/ToAHB.scala
Make it possible to support AHB-Full/Lite based on a diplomatic parameter.
Note that AHB still requires two kinds of nodes: those before and after an Arbiter.
> AHB: add a knob to control full/lite

- src/main/scala/rocket/ScratchpadSlavePort.scala
- src/main/scala/tile/Core.scala
- src/main/scala/tile/RocketTile.scala
A refactoring in 3133c321b7b771150168b687834fac5edd4a292a made the assumption that coreDataBits = xLen, which is not true for RV32D. Since the assumption wasn't paired with an assertion, attempting to generate such configs resulted in successful elaboration of a broken design.
> Fix configs with both RV32D and scratchpads

- src/main/scala/diplomacy/SRAM.scala
- src/main/scala/tilelink/SRAM.scala
**Type of change**:other enhancement
This is a somewhat dirty way of allowing the compat string of an sram to be set, but to default to "sifive,sram0". Another option here would be to make all the parameters a case class, but I know this code is used a lot, so I would prefer not to break compatibility. If you prefer that method though, let me know and I can implement it.
> pipe out compatname

- src/main/scala/devices/tilelink/Plic.scala
By setting maxHarts to e.g. 512 instead of the maximum of 15872, the address
space consumption falls to 4 MiB from 64 MiB.
Compacting the PLIC address space in this manner does not affect software
compatibility, because none of the offsets change.
> Add option to make PLIC take up less address space

- src/main/scala/util/AsyncQueue.scala
Before this change, the AsyncQueue puts down real hardware that in theory can be constant-propped away but is not because of the black-boxed AsyncResetReg. Since we don't use the output of any of this logic in the commented-out assertion, comment all of it out.
> AsyncQueue: Remove logic that is only needed for a commented out assertion

- src/main/scala/rocket/RocketCore.scala
remove separate coreMonitorBundle print trace "[wren]" and instead print wrdst=0 when wren=0
> coreMonitorBundle print trace wrdst=0 when wren=0

- ci-tests/check_submodules
updates the regex in the `check_submodules` script. the hashes output by `git submodule status` may be prefixed with `-`, `+`, or `U` and there may be stuff from `git describe` appended to the end of each line.
> check_submodules: update regex

- src/main/scala/amba/ahb/Monitor.scala
- src/main/scala/amba/ahb/Nodes.scala
- src/main/scala/tilelink/Bundles.scala
Sorry, was supposed to do this in https://github.com/chipsalliance/rocket-chip/pull/2124 but never got around to it before it got merged.
- add `AHBSlaveMonitor` and `AHBMasterMonitor`
- remove `TLBundleSnoop` and `DecoupledSnoop`
> add AHB Monitors, remove Snoop bundles

- src/main/scala/devices/tilelink/CLINT.scala
- src/main/scala/devices/tilelink/Plic.scala
- src/main/scala/subsystem/BaseSubsystem.scala
**Impact**:  API addition (no impact on existing code) 
- Allow some common TileLink-based peripherals (CLINT and PLIC) to have more flexible attachment points to the subsytem bus hierarchy
- Defines `type BusAttachmentFunction`
- Allow subclasses of `BaseSubsystem` to override `def attach` while providing new matches of type `BusAttachmentFunction`  
- user facing API backwards compatible
> Continue to improve flexibility of subsystem bus attachment

- src/main/scala/tilelink/Filter.scala
Adds a new built-in `ManagerFilter` to the `TLFilter` helper object called `mSubtract`. Factors out some common code between it and `mSelectIntersect`.
> tilelink: add TLFilter.mSubtract

- src/main/scala/rocket/RocketCore.scala
- src/main/scala/subsystem/HasTiles.scala
- src/main/scala/subsystem/RocketSubsystem.scala
- src/main/scala/util/CoreMonitor.scala
**Impact**: API addition
Added a new case class `CoreSignalMonitor` to directly access signals in the core which are not available as IOs.
> Core signal monitor

- src/main/scala/scie/SCIE.scala
**Type of change**: Minor fix
The SCIEPipelined module was using a define without defining it. This leads to non deterministic failures when compiling with this verilog file. Fix is to define it before using.
> Add missing define for SCIEPipelined

- README.md
- regression/Makefile
- src/main/scala/subsystem/MemoryBus.scala
- src/main/scala/subsystem/Ports.scala
- src/main/scala/system/Configs.scala
**Related issue**: Closes #1779 Closes #1788 Closes #1785 
@codelec thanks for your contribution, I expanded upon it somewhat:
- I used the `:*=` flexible cardinality operator to allow the left-hand-side of the adapter chain to set the number of ports from the blind terminal node all the way through to the memory bus crossbar.
- There were a few more cases where `BaseConfig` was being used instead of `DefaultConfig`
- I removed the vestigial `DefaultFPGASmallConfig`; use `DefaultFPGAConfig` instead, or just write your own :)
@seldridge I did not adjust the testing plan at this time 🙇 forgive me. Can you open a new issue along the lines of "Actually test all the configs in `system/configs.scala`"
**Impact**: API modification; removed defunct …
> fix configs in system/configs.scala (pt. 2)

- src/main/scala/devices/debug/DebugTransport.scala
- src/main/scala/devices/debug/Periphery.scala
When the JTAG TAP is included by a customer in a larger system, they may want to identify it using the JTAG IDCODE scan register.  This PR adds the part_number and version fields of IDCODE to the mfr_id port exposed at the top level so that all three can be set by the customer.
> Expose part_number and version of IDCODE

- src/main/scala/diplomacy/Parameters.scala
- src/main/scala/tilelink/AddressAdjuster.scala
- src/main/scala/tilelink/BankBinder.scala
- src/main/scala/tilelink/Nodes.scala
- src/main/scala/tilelink/RegionReplication.scala
This PR makes the AddressAdjuster adapter more flexible in several ways:
- It now allows the user to specify only a particular address range to be adjusted via the `adjustableRegion` optional parameter. Devices outside of this range can be attached on either the local or the remote side of the downstream ports, and traffic will be routed to them as usual. Only local devices within the `adjustableRegion` have their PMAs edited by the adapter and traffic dynamically toggled between them and the remote side device.
- It now supports flexible cardinality over its edges by defining a new CustomNode type. Specifically, it can now pass through `:=*` flexibility, allowing masters to specify the cardinality.
Also added a missing requirement and limited the scope of some existing requirements to …
> AddressAdjuster Improvements

- src/main/scala/rocket/TLB.scala
- src/main/scala/util/BlockDuringReset.scala
- src/main/scala/util/RationalCrossing.scala
...by preventing any enqueues that might spuriously happen during reset.
> Allow a RationalCrossingSource to remain in reset longer than sink

- src/main/scala/system/Generator.scala
This fixes a bug where the `regression-tests` target in `freechips.rocketchip.system.$CONFIG.d` would include tests which the core couldn't support and which were not being added via `TestGeneration.addSuites`. E.g., if you build a `WithoutFPU` configuration and try to `make run-regression-tests-fast` make will error out being unable to find the `output/rv64ud-v-fcvt` test. This fixes this by filtering the possible regression tests based on what the core actually supports.
Note: this solution includes a lot of overlap with both [`isaDTS`](https://github.com/chipsalliance/rocket-chip/blob/77b4e6b84c91aa0617c7e54c7c57c8783bcd30b3/src/main/scala/tile/BaseTile.scala#L74) and [`isaString`](https://github.com/chipsalliance/rocket-chip/blob/77b4e6b84c91aa0617c7e54c7c57c8783bcd30b3/src/main/scala/ …
> Filter RegressionTestSuite based on coreParams

- src/main/scala/subsystem/MemoryBus.scala
Signed-off-by: shuyun <shuyunjia@outlook.com>
The blockBytes of the L2 broadcast hub should be the same as the L1 blockBytes, which is the sbus.blockBytes. Although for now, the `sbus.blockBytes === mbus.blockBytes === L1 CacheBlockBytes`, it is better to declare it right, for possible future L3 implementation.
> change the blockBytes of l2 broadcast hub to sbus's blockBytes

- src/main/scala/interrupts/Parameters.scala
Previously `IntSourcePortSimple(num = 1, ports = 1, sources = 2)` would trip over the requirement about overlapping ranges on line 43. This makes the ranges unique for all simple sources within a simple port.
I think this is a more correct fix for the issue reported in #1738.
> interrupts: correct ranges for IntSourcePortSimple

- src/main/scala/tilelink/Metadata.scala
This aligns how `shrinkWrapper` handles responses for `toB` when in a `Nothing` state to be the same as responses to `toT` and `toN` when in the same state.
> Respond NtoN for all Nothing states

- src/main/scala/amba/ahb/RegisterRouter.scala
- src/main/scala/amba/apb/RegisterRouter.scala
Adds the missing mix-ins for making RegisterRouted devices that speak other AMBA protocols.
> AMBA: HasAHBControlRegMap and HasAPBControlRegMap 

- src/main/scala/diplomaticobjectmodel/logicaltree/RocketLogicalTreeNode.scala
- src/main/scala/diplomaticobjectmodel/model/OMRocketCore.scala
- src/main/scala/tile/RocketTile.scala
The OMBusError component is now being placed inside of the OMRocketCore component.
Previously, the OMBusError was a sibling to the OMRocketCore, but that meant that in a multicore design, we could not explicitly link an OMBusError to the OMRocketCore that it is associated with. Placing the OMBusError inside of the OMRocketCore solves this issue.
> Place OMBusError inside OMRocketCore

- src/main/scala/jtag/JtagTap.scala
- src/main/scala/jtag/Utils.scala
**Related issue**: https://github.com/chipsalliance/rocket-chip/issues/2165
Changed TDO and TDO.driven drivers to asynchronous reset based on jtag_reset input.
> Change TDO and TDO.driven to async reset

- src/main/scala/diplomaticobjectmodel/logicaltree/LogicalTreeNode.scala
[One weakness in Scala's type system](https://docs.scala-lang.org/tutorials/FAQ/initialization-order.html) can allow `null`s to sneak in if you access an uninitialized field. This PR adds some guards to the `LogicalModuleTree` to detect and abort if a `null` is passed in.
> Disallow null values in LogicalTree.

- src/main/scala/tilelink/Fuzzer.scala
Specifying `nOperations = 0` means that the fuzzer should run forever.
This means some other entity must be responsible for terminating the simulation.
Closes #2117
> fuzzer: update parameter description

- src/main/scala/rocket/ICache.scala
Way sizes greater than 4 KiB are now supported even when using paging. Multiple synonyms may reside in the I$ simultaneously, provided their virtual addresses aren't congruent modulo the way size.
Note the restriction is still in effect if ITIM is enabled.
Tested with https://github.com/riscv/riscv-tests/commit/2fc2416094314a4253fe096fead078b75d361bbf
> Lift I$ VIPT restriction

- src/main/scala/diplomacy/BundleBridge.scala
- src/main/scala/diplomacy/Nodes.scala
- src/main/scala/tilelink/Edges.scala
- src/main/scala/tilelink/Monitor.scala
- src/main/scala/tilelink/Parameters.scala
This encapsulates the popular pattern of making IOs out of the bundles associated with SourceNodes or SinkNodes via cloning them into `HeterogeneousBags`. It is a generalization of the behavior of `makeIO()` on BundleBridge sources and sinks, and as such I named it `makeIOs()` and reimplemented the bridge methods using it. Should be totally backward compatible.
I also threw in some TL-specific utilities for printing out port metadata or monitoring port behavior.
Follow-on PR will convert the ports to use this capability.
**Related Issues**: Someone asked for this but I'm having trouble finding the issue. 
**Impact**:API addition (no impact on existing code)
Diplomacy: Source and Sink Nodes have …
> Diplomatic IO Creation from Nodes

- src/main/scala/devices/debug/SBA.scala
This PR fixes the error handling case where programming the Debug Module's sbaccess register to a value > 4.U would not result in the correct error handling and setting of the sberror register. Also removes a spurious assertion related to the queue size on the SBA unit's TileLink response interface
> SBA: Fix invalid sbaccess value error case, remove spurious assert

- src/main/scala/groundtest/GroundTestSubsystem.scala
- src/main/scala/groundtest/TestHarness.scala
- src/main/scala/subsystem/Ports.scala
- src/main/scala/system/ExampleRocketSystem.scala
- src/main/scala/system/SimAXIMem.scala
- src/main/scala/system/TestHarness.scala
This builds on #2176 by using the new `makeIOs` methods to create ports in the subsystem. This 
new methods allows the two traits used previously to be collapsed into one, which then results in some API tweaks  to how collateral is attached in the testharness.
The following traits are removed:
- `CanHaveMasterAXI4MemPortModuleImp`
- `CanHaveMasterAXI4MMIOPortModuleImp`
- `CanHaveSlaveAXI4PortModuleImp`
- `CanHaveMasterTLMMIOPortModuleImp`
- `CanHaveSlaveTLPortModuleImp`
The following APIs are changed:
- `class SimAXIMem` is moved to the `system` package
- `object SimAXIMem` has methods `connectMMIO` and `connectMem` which are used in the test harnesses by passing them the dut instead of calling them as methods of the dut.
The following soon-to-be-deprecated APIs are avoided:
- …
> Modernize Port Creation

- src/main/scala/rocket/CSR.scala
- src/main/scala/rocket/RocketCore.scala
- src/main/scala/tile/BaseTile.scala
- src/main/scala/tile/Core.scala
- src/main/scala/tile/RocketTile.scala
The consumer of the TracedInstruction bundle from BaseTile.traceNode may not be able to keep up with the rate at which traced instructions appear on the interface.  This PR adds a traceStall signal in a return bundle that stalls the core when asserted, allowing the external trace unit to catch up.  If no trace consumers connect to traceNode, then traceStall is driven with false.B.
> Add optional trace stall function

- src/main/scala/diplomacy/Nodes.scala
Turns out `ValName.toString` prefixed the name with the string "ValName". `ValName.name` is what I wanted and even what I used in the SinkNode already.
**Related issue**: Closes #2200
**Impact**: bug fix
> diplomacy: SourceNode.makeIOs uses ValName.name

- src/main/scala/devices/debug/APB.scala
- src/main/scala/devices/debug/Custom.scala
- src/main/scala/devices/debug/DMI.scala
- src/main/scala/devices/debug/Debug.scala
- src/main/scala/devices/debug/DebugTransport.scala
- src/main/scala/devices/debug/Periphery.scala
- src/main/scala/devices/debug/SBA.scala
- src/main/scala/devices/debug/abstract_commands.scala
- src/main/scala/devices/debug/dm_registers.scala
- src/main/scala/jtag/JtagShifter.scala
- src/main/scala/jtag/JtagStateMachine.scala
- src/main/scala/jtag/JtagTap.scala
- src/main/scala/jtag/JtagUtils.scala
- src/main/scala/jtag/Utils.scala
This PR converts the Debug Module and JTAG unit to chisel3. This is to enable them to use the new Chisel3 reset functionality.
> Convert DM and JTAG to chisel3

- src/main/scala/amba/axi4/Bundles.scala
- src/main/scala/amba/axi4/Parameters.scala
- src/main/scala/amba/axi4/Test.scala
- src/main/scala/amba/axi4/ToTL.scala
- src/main/scala/amba/axi4/UserYanker.scala
- src/main/scala/tilelink/ToAXI4.scala
- src/main/scala/unittest/Configs.scala
This commit adds the support to propagate the TL user bits to the AXI4
channels if present. Some AXI4 adapter implementations currently use the AXI4 user
bits to encode routing control bits. The commit pads the TL user bits as
opaque-bits at msb position of the AXI user-field as shown below:
opaqueBits+userBits-1    userBits userBits-1   0
+--------------------------------+---------------+
|           opaque               |      user     |
+--------------------------------+---------------+
Changes:
- axi4/Parameters.scala: add opaqueBits parameter to the AXI4MasterPortParameters
- axi4/Bundles.scala: userBits and opaqueBits to combine user-bits field
- axi4/UserYanker.scala: support to propagate opaqueBits if present
- axi4/Test.scala: added a new test that injects TL userbits
- …
> [axi4/tilelink] add support to propagate TL to AXI4 user bits

- src/main/scala/devices/debug/APB.scala
- src/main/scala/devices/debug/Debug.scala
Debug: Fill in undefined addresses in APB interface with TLError device.
Note: making this a follow-on to #2205 would allow this to have less hardware impact
Resolve issue in which accesses to the APB Debug interface which targeted undefined addresses would alias to valid addresses. Instead, these accesses will now return an error.
> Debug APB: Prevent aliasing on undefined addresses

- src/main/scala/diplomacy/Nodes.scala
- src/main/scala/tilelink/AddressAdjuster.scala
- src/main/scala/tilelink/Jbar.scala
- src/main/scala/tilelink/Nodes.scala
- src/main/scala/tilelink/Xbar.scala
- src/main/scala/unittest/Configs.scala
Junction nodes are a bit esoteric. You need them when you need, for example, a 2:1 arbiter, but several times. Suppose you had N banks of L2 and wanted to connect those to two different driver crossbars. In that case you can do this:
```
l2banks.node :*= jbar.node
jbar.node :*= xbar1.node
jbar.node :*= xbar2.node
```
If the L2 has 4 banks, now there are 4 egress ports on both xbar1 and xbar2 and they are arbitrated by the jbar.
> Junction nodes

- src/main/scala/amba/axis/Bundles.scala
- src/main/scala/amba/axis/Nodes.scala
- src/main/scala/amba/axis/Parameters.scala
- src/main/scala/amba/axis/Xbar.scala
- src/main/scala/amba/axis/package.scala
- src/main/scala/diplomacy/Parameters.scala
- src/main/scala/util/BundleMap.scala
This adds support for AXI-Stream connections diplomatically. It also prototypes several innovations we should port back to the other diplomatic busses:
1. BundleMap allows us to systematically add 'user' fields to busses with associated meta-data and categorization which helps adapters operate on fields they don't know anything about
2. beatBytes as an Option. This lets the bus width be controlled by common attachment points instead of slaves.
3. all Parameters are classes with private destructor, without unapply, and with versioned copy and constructors -> this allows us to upgrade the parameter API in a backwards compatible manner
4. all …
> AXIS: add diplomatic AXI-Stream support

- src/main/scala/rocket/RocketCore.scala
Previously, it was not possible to count both exceptions and
retirement events; the latter were ignored.
> Fix perf event counting when counting exceptions

- src/main/scala/rocket/RocketCore.scala
We were failing to ignore rs1/rs2 for configs that require a D$
flush on FENCE.I.  Configs with coherence hubs/L2$ are unaffected.
Software workaround is to keep rs1=rs2=x0 (which software really
should be doing anyway).
> Ignore rs1/rs2 in FENCE.I

- src/main/scala/diplomacy/Resources.scala
- src/main/scala/subsystem/BaseSubsystem.scala
Continued refinement of the new `HasBusAttachmentFunction` trait that allows devices to Config-urably select to which TL bus they would like to be attached.
> refactor HasBusAttachmentFunction to be purely abstract

- Makefrag
api-configs-chipsalliance does not use the Maven/SBT standard
src/main/scala, instead it puts main sources in src/
> Fix Makefile rules for api-configs-chipsalliance

- src/main/scala/rocket/Frontend.scala
- src/main/scala/rocket/RocketCore.scala
- src/main/scala/tile/CustomCSRs.scala
This is mostly intended as a post-silicon debug feature to eliminate a common source of spurious events.
> Add chicken bit to disable speculative I$ refill

- src/main/scala/amba/ahb/ToTL.scala
This is only possible on a 128-bit-wide AHB interface.
***Type of change**: bug report
> AHBToTL: support bursts >= 256 bytes large

- wit-manifest.json
This enables using FIRRTL's reset inference with Diplomatic LazyModule hierarchies.
Replaces https://github.com/chipsalliance/rocket-chip/pull/2230
* Reset inference now supports last connect semantics
* FirrtlOptions and CircuitOptions no longer serialized to anno JSON file
* Bumped FIRRTL on release branch `1.2.x` just beyond `1.2.2`
> Bump firrtl

- src/main/scala/rocket/Frontend.scala
- src/main/scala/rocket/RocketCore.scala
This is also just for post-silicon debug purposes.  Disabling prefetch
doesn't add much extra PSD benefit beyond disabling speculative refill,
because the latter disables prefetching on speculative accesses already,
leaving only next-line prefetches following non-speculative refills.
But it is worth something.
> Extend I$ speculative refill chicken bit to disable prefetching, too

- src/main/scala/rocket/RocketCore.scala
Without this patch, if WFI is followed by a memory access, the D$ will continue to be clocked.
> Allow clock gating to engage even if WFI/CEASE is followed by load/store

- src/main/scala/diplomaticobjectmodel/logicaltree/LogicalTrees.scala
The previous Object Model implementation did not account for the relative offset of the dmOuter register address block. This commit adds some logic to translate the offsets into absolute addresses.
There was a bug in the generated Object Model for the Debug Module, where the register field bit offsets were incorrect. This has now been corrected.
> Fix offsets of DMOuter registers in Object Model.

- src/main/scala/rocket/DCache.scala
**Related issue**: https://github.com/chipsalliance/rocket-chip/pull/2246 causes problems in downstream repositories
> Rocket Core DCache TileLink: dont require Fifo just yet

- src/main/scala/rocket/DCache.scala
**Related issue**: The ecc coverpoints for the tag array were generated even when there was no ecc enabled in the tag array
**Type of change**: cover point fix 
> Fix Dcache Tag ECC coverpoints

- src/main/scala/groundtest/Tile.scala
**Related issue**: https://github.com/chipsalliance/rocket-chip/pull/2238
TraceGen in downstream repository needs `Some(ICacheParams)` instead of `None` for
`tileParams.icache.get.prefetch.toInt` at
https://github.com/chipsalliance/rocket-chip/blob/9a1da4e01e3e767451d9ee4a4f0ee8a55a3313da/src/main/scala/rocket/RocketCore.scala#L81
> GroundTestTileParams Some(ICacheParams)

- src/main/scala/rocket/DCache.scala
- src/main/scala/tilelink/Parameters.scala
**Related issue**: #2246 was incomplete
> Rocket Core DCache TileLink: require FIFO to allVolatile regions

- src/main/scala/diplomaticobjectmodel/model/OMPorts.scala
**Impact**: no functional change (I think?)
This PR makes a minor change to the emitted Object Model to properly spell TileLink (no spaces) in the port protocol description.
---
Tagging @john-sifive and @aisha-w-sifive, who I can't assign as reviewers because they don't have commit access to rocket-chip.
> Correct spelling of TileLink in Object Model protocol description

- src/main/scala/devices/debug/Debug.scala
- src/main/scala/devices/debug/SBA.scala
Added rf_reset signals at each point where the Full Asynchronous Reset Transform should switch from one reset to another.
> Debug: Added rf_reset signals needed by RF transform

- src/main/scala/devices/debug/SBA.scala
sbState tracks the progress of a TileLink transaction initiated by the debug module SBA interface.  When a read transaction is initiated by the DM, sbState progresses from Idle to SBReadRequest to SBReadResponse and back to idle.  The states control what is driven onto the TL interface, including driving d.ready to 1 when sbState is in the SBReadResponse state.
If there is a TL transaction in progress and the debugger sets dmactive to 0, sbState is immediately returned to Idle, thereby forcing d.ready to 0.  This can potentially hang TileLink.  
This PR disconnects sbState from dmactive so that any transaction started by the DM is followed to …
> Debug SBA: Don't reset sbState if dmactive is set to 0

- src/main/scala/rocket/Breakpoint.scala
- src/main/scala/rocket/Multiplier.scala
- src/main/scala/rocket/PMP.scala
- src/main/scala/rocket/RVC.scala
- src/main/scala/tilelink/WidthWidget.scala
- src/main/scala/util/Repeater.scala
Convert some modules to chisel3 to allow properly infer resets. Same as to #2272 but targeting master
> Convert some modules to Chisel3

- src/main/scala/amba/ahb/RegisterRouter.scala
- src/main/scala/amba/apb/RegisterRouter.scala
- src/main/scala/amba/axi4/RegisterRouter.scala
- src/main/scala/interrupts/RegisterRouter.scala
- src/main/scala/regmapper/RegisterRouter.scala
- src/main/scala/tilelink/RegisterRouter.scala
**Impact**: API modification (I guess this is technically backwards incompatible)
`RegisterRouter` no longer takes a type parameter, as it was not being used.
---
I was trying to read the definition of `RegisterRouter`, and I was having difficulty understanding what its type parameter `T <: Data` was being used for. As far as I can tell, it is not being used by anything, and simply removing it and making it a non-generic type seems to work fine. If it is in fact actually being used for something, I'd love to learn more about it, since at my current level of understanding of Scala, I can't figure out how it is being used, since none of its members or methods depend on it.
> Remove unused type parameter on RegisterRouter.

- src/main/scala/tilelink/WidthWidget.scala
Need to convert one more chisel2 `<>` to explicit series of `:=`. Rocket-Chip PR regressions don't exercise this code path.
Follow up to https://github.com/chipsalliance/rocket-chip/pull/2273
> TLWidthWidget: one more fix for the port to chisel3

- src/main/scala/rocket/DCache.scala
- src/main/scala/rocket/RocketCore.scala
- src/main/scala/tile/CustomCSRs.scala
Temporarily suppressing corrupt GrantDatas facilitates using normal loads and stores to wipe down uncorrectable errors.
> Add feature-disable bit to suppress corrupt on GrantData

- src/main/scala/amba/axi4/SRAM.scala
#1969 accidentally reverted the fix implemented by @colinschmidt in #1934. This PR restores support for large ExtMem sizes.
> Fix regression in support for large ExtMem sizes

- src/main/scala/tile/RocketTile.scala
I$ accesses can be speculative, and raising the halt signal based upon speculative accesses is problematic.
These errors can still be dealt with using a BusErrorUnit.
> Don't raise halt signal on I$ errors

- wit-manifest.json
See discussion on https://github.com/freechipsproject/firrtl/pull/1355
^---- this template question makes no sense for a PR
Async registers which are only reset, never assigned, will be emitted properly in a way that prevents lint tools from complaining about a latch.
> bump FIRRTL for async reset register fixes

- wit-manifest.json
I recently bumped chisel3 and it seems someone recently bumped firrtl so this is a small bump.
Summary of changes in chisel3:
* Patch fix to https://github.com/freechipsproject/chisel3/issues/1109
Summary of changes in firrtl:
* Constant propagate binary operations with matching arguments
* Revert last connect semantics support in reset inference
* Fix reset inference for Resets that are only invalidated
The FIRRTL changes to reset inference are an API change because last connect support was unsound and didn't work right. The new API is more restrictive but actually works.
> Bump chisel3 and FIRRTL

- src/main/scala/tilelink/Edges.scala
Getting a requirement failure during diplomacy execution with no further explanation is frustrating for users.
> Tilelink: More verbose require statements

- src/main/scala/amba/apb/ToTL.scala
Properly qualify address alignment assertion in APBToTL on whether or not there is a transaction being sent.
> APBToTL: Qualify address alignment assertion

- src/main/scala/rocket/Breakpoint.scala
- src/main/scala/rocket/RocketCore.scala
The watchpoint bundle leading out of the core could erroneously indicate a match on a load or store watchpoint.  The logic in the core was not checking that the instruction type (load vs. store) matched the breakpoint programming.
> Qualify load and store watchpoints by instruction type

- src/main/scala/prci/ClockParameters.scala
- src/main/scala/subsystem/BaseSubsystem.scala
In some configurations, we want all discovered asynchronous clock group to be driven by IO wires of the subsystem. This PR makes the choice of driver strategy configurable via a function passed as an argument to `ClockGroupDriverParameters`
Default driving behavior remains as before: all clock groups driven by implicit chisel clock of subsystem.
> prci: allow configurable ClockGroupDriver drive function

- wit-manifest.json
Summary of changes (all bug fixes in FIRRTL):
* Do not duplicate modules when there is no reason to
* Clarify spec for divide-by-zero and single-line when-else
* Fix error message for negative width exception
* Revert `not` inlining to fix Verilog emission bug
**Related issue**: https://github.com/freechipsproject/firrtl/pull/1425
Updating FIRRTL to revert `InlineNots`
> bumping firrtl

- src/main/scala/rocket/Multiplier.scala
resolving deprecation warning:
```
[deprecated] class freechips.rocketchip.rocket.MultiplierIO (1 calls): Unable to automatically infer cloneType on class freechips.rocketchip.rocket.MultiplierIO: constructor has parameters (dataBits, tagBits) that are not both immutable and accessible. Either make all parameters immutable and accessible (vals) so cloneType can be inferred, or define a custom cloneType method.
[warn] There were 1 deprecated function(s) used. These may stop compiling in a future release - you are encouraged to fix these issues.
```
Resolve deprecation warnings in MultiplierIO
> Multiplier: Make MultiplierIO clone-able

- src/main/scala/amba/axis/Buffer.scala
- src/main/scala/amba/axis/Bundles.scala
- src/main/scala/amba/axis/Parameters.scala
- src/main/scala/amba/axis/Xbar.scala
- src/main/scala/amba/package.scala
- src/main/scala/util/BundleMap.scala
- src/main/scala/util/package.scala
- Field unification can be customized and defaults to equality required
- Bulk assignment of BundleMaps now uses defaults for missing fields
- You must now define both a Field and Key class
User bits API composability improved
> BundleMap: improved API for user bits

- src/main/scala/rocket/CSR.scala
For compliance with this clause in the priv spec:
"The mcause values after reset have implementation-specific interpretation,
but the value 0 should be returned on implementations that do not distinguish
different reset conditions"
> Reset mcause to 0

- src/main/scala/devices/debug/Debug.scala
- src/main/scala/devices/debug/DebugTransport.scala
- src/main/scala/devices/debug/Periphery.scala
- src/main/scala/jtag/JtagStateMachine.scala
- src/main/scala/jtag/JtagTap.scala
- src/main/scala/jtag/Utils.scala
This PR changes the DebugTransport and JTAG modules to use abstract reset.  The jtag_reset signal is driven with an AsyncReset signal in tieoffDebug.  Old-style explicit instantiations of neg-edge registers and async-reset registers have been replaced by standard registers wrapped with the appropriate withClockAndReset.
> Use inferred resets for JTAG and DebugTransport modules

- src/main/scala/diplomaticobjectmodel/model/OMAddressing.scala
The semantics of a register field with a width = 0 are rather undefined for downstream tools. Are you supposed to define software headers for them? Are you supposed to create documentation for them?
Simplify this confusion by just omitting them from the OM entirely.
OMRegisterFields are no longer emitted if they are zero-width. They are omitted entirely from the Object Model emission.
> OMAddressing: Only emit RegFields of width > 0

- CONTRIBUTING.md
- README.md
Mainly to mention that chisel3 and firrtl should only be bumped to
stable branches
**Related issue**: NA
Add `CONTRIBUTING.md` with instructions to bump submodules
> Add CONTRIBUTING.md with instructions to bump submodules

- src/main/scala/subsystem/BaseSubsystem.scala
Adding `HierarchicalLocation` which config keys may use to control hierarchy of instantiation
> Subsystem: Add HierarchicalLocation

- src/main/scala/rocket/DCache.scala
Currently, non-allocating accesses can be reordered with allocating
accesses if they are to different virtual synonyms.  Add hardware
to detect and prevent this case.
If there's no possibility of aliasing or non-allocating accesses,
there's no additional HW cost.
I'm not entirely happy with the approach (it adds a lot of fanout to
what is sometimes a critical timing path, so at minimum it's leaky).
Might revisit later.
> D$: guarantee that no-alloc accesses are ordered even if aliased

- src/main/scala/util/AsyncQueue.scala
**Related issue**:  None
The AsyncValidSync inside AsyncCrossing is now a RawModule, not a Module. It still has two IO/s (clock and reset) but these need to be explicitly assigned.
The reason for this behavior is to allow AsyncCrossing to work across a mixture of reset schemes.
> AsyncQueue: Convert AsyncValidSync to RawModule

- src/main/scala/diplomacy/Resources.scala
bug fix to comparing `Option[String]` with `String`
```
DiplomacyUtils.regName(x._1) == "control"
```
will compare between `Option[String]` and `String`, which never equal.
If comparing this equivalency, it should be
```
DiplomacyUtils.regName(x._1).contains("control")
```
> bug fix for DeviceRegName

- src/main/scala/amba/ahb/Monitor.scala
- src/main/scala/devices/debug/Periphery.scala
- src/main/scala/diplomacy/BundleBridge.scala
- src/main/scala/prci/ResetWrangler.scala
- src/main/scala/prci/TestClockSource.scala
- src/main/scala/rocket/CSR.scala
- src/main/scala/rocket/Frontend.scala
- src/main/scala/rocket/PTW.scala
- src/main/scala/rocket/RocketCore.scala
- src/main/scala/tile/FPU.scala
- src/main/scala/tilelink/Monitor.scala
- src/main/scala/util/Annotations.scala
- src/main/scala/util/DescribedSRAM.scala
- src/main/scala/util/HeterogeneousBag.scala
- src/main/scala/util/ResetCatchAndSync.scala
```
[warn] /rocket-chip/src/main/scala/util/DescribedSRAM.scala:7:34: imported `Annotated' is permanently hidden by definition of object Annotated in package util
[warn] import freechips.rocketchip.util.Annotated
[warn]                                  ^
[warn] /rocket-chip/src/main/scala/amba/ahb/Monitor.scala:17:72: type Reset in package core is deprecated (since 3.2): Use the version in chisel3._
[warn]   def legalize(bundle: AHBSlaveBundle, edge: AHBEdgeParameters, reset: Reset): Unit
[warn]                                                                        ^
[warn] …
```
> Chisel compile warning: Chisel3 packages imports

- src/main/scala/devices/debug/Periphery.scala
- src/main/scala/tile/LazyRoCC.scala
```
[warn] /rocket-chip/src/main/scala/devices/debug/Periphery.scala:177:3: method setResource in trait HasBlackBoxResource is deprecated (since 3.2): Use addResource instead
[warn]   setResource("/vsrc/SimDTM.v")
[warn]   ^
[warn] /rocket-chip/src/main/scala/devices/debug/Periphery.scala:178:3: method setResource in trait HasBlackBoxResource is deprecated (since 3.2): Use addResource instead
[warn]   setResource("/csrc/SimDTM.cc")
[warn]   ^
[warn] /rocket-chip/src/main/scala/devices/debug/Periphery.scala:213:3: method setResource in trait HasBlackBoxResource is deprecated (since 3.2): Use addResource instead
[warn] …
```
> Chisel compile warning: HasBlackBoxResource

- src/main/scala/rocket/ICache.scala
- src/main/scala/tilelink/Arbiter.scala
- src/main/scala/util/ECC.scala
- src/main/scala/util/Misc.scala
- src/main/scala/util/Replacement.scala
```
[warn] /rocket-chip/src/main/scala/rocket/ICache.scala:191:14: method apply in object LFSR16 is deprecated (since 3.2): Use chisel3.util.random.LFSR(16) for a 16-bit LFSR
[warn]     val v0 = LFSR16(refill_fire)(log2Up(nWays)-1,0)
[warn]              ^
[warn] /rocket-chip/src/main/scala/tilelink/Arbiter.scala:100:14: method apply in object LFSR16 is deprecated (since 3.2): Use chisel3.util.random.LFSR(16) for a 16-bit LFSR
[warn]   val lfsr = LFSR16(Bool(true))
[warn]              ^
[warn] /rocket-chip/src/main/scala/util/ECC.scala:186:14: method apply in object LFSR16 is deprecated (since 3.2): Use …
```
> Chisel compile warning: random LFSR16

- src/main/scala/rocket/PMP.scala
- src/main/scala/util/package.scala
```
[warn] /rocket-chip/src/main/scala/rocket/PMP.scala:139:38: method /: in trait TraversableOnce is deprecated (since 2.12.10): Use foldLeft instead of /:
[warn]     ((true.B, 0.U.asTypeOf(new PMP)) /: pmps) { case ((h, prev), pmp) =>
[warn]                                      ^
[warn] /rocket-chip/src/main/scala/rocket/PMP.scala:163:19: method /: in trait TraversableOnce is deprecated (since 2.12.10): Use foldLeft instead of /:
[warn]   val res = (pmp0 /: (io.pmp zip (pmp0 +: io.pmp)).reverse) { case (prev, (pmp, prevPMP)) =>
[warn]                   ^
[warn] /rocket-chip/src/main/scala/util/package.scala:32:17: …
```
> Chisel compile warning: Use foldLeft instead of /: 

- src/main/scala/diplomacy/LazyModule.scala
- src/main/scala/tile/FPU.scala
- src/main/scala/tilelink/Atomics.scala
- src/main/scala/tilelink/Broadcast.scala
- src/main/scala/util/CompileOptions.scala
- wit-manifest.json
This contains workarounds for https://github.com/chipsalliance/rocket-chip/issues/2361
This bumps chisel to pick up fix for https://github.com/freechipsproject/chisel3/pull/1253 done in https://github.com/freechipsproject/chisel3/pull/1388
FPU, tilelink/Atomics, TLBroadcast are converted to be able to use chisel3 `AsyncReset`. This is done generally with a specific compatibility mode change vs entirely converting them to chisel3 in a new DefaultCompileOptions.NonStrictInferReset
Some withReset(false.B) are added around combinational hardfloat modules in the FPU to avoid having to do this recursively in hardfloat files …
> Async Reset support for Atomics, FPU, and TLBroadcast

- src/main/scala/tile/RocketTile.scala
The CPU section in the generated DTS file will have link to the associated BEU. This should help downstream software flows.
**Example of the emitted DTS (updated):**
```
{
...
model = "SiFive,FU500";
....
L34: cpus {
#address-cells = <1>;
#size-cells = <0>;
L9: cpu@0 {
clock-frequency = <0>;
...
...
...
device_type = "cpu";
....
sifive,buserror = <&L8>;
....
};
};
L33: soc {
....
....
L8: bus-error-unit@1700000 {
compatible = "sifive,buserror0";
interrupt-parent = <&L3>;
interrupts = <303>;
reg = <0x1700000 0x1000>;
reg-names = "control";
};
....
....
}
```
> BEU <-> HART link added in DTS

- src/main/scala/diplomacy/LazyModule.scala
1. make `LazyModule.nodes` accessable to user for debugging and reuse Nodes.
2. refactor `childrenIterator` to `nodeIterator`, add `nodeIterator` to access all children's `BaseNode`.
> make LazyModule.nodes accessable by users.

- src/main/scala/rocket/RocketCore.scala
**Related issue**: reverts #2118
**Impact**: API modification back to what it was before #2118 
coreMonitorBundle print only retired instructions in this format: `C%d: %d [%d] pc=[%x] W[r%d=%x][%d] R[r%d=%x] R[r%d=%x] inst=[%x] DASM(%x)`
`C`_core number_
`: `_cycle timer_
`[`_committed and not exception_`]` (1=committed, 0=exception)
`pc=[`_program counter_`]`
`W[r`_destination register number_`=`_destination register write data_`][`_destination register write enable_`]`
note: _destination register write data_ should be ignored when _destination register write enable_ is 0
`R[r`_source 0 register number_`=`_source 0 register read data_`]`
`R[r`_source 1 register number_`=`_source 1 register read …
> coreMonitorBundle print trace log wrdst and wren

- emulator/Makefrag-verilator
**Related issue**: https://github.com/chipsalliance/rocket-chip/pull/2370
I have given up on trying to switch to SiFive's (my) prebuilt Verilator binaries in https://github.com/chipsalliance/rocket-chip/pull/2370, but this at least bumps the compiled-from-source Verilator from 4.008 to 4.028, which represents about a year's worth of updates.
> Bump to Verilator 4.028.

- src/main/scala/amba/ahb/ToTL.scala
- src/main/scala/amba/apb/ToTL.scala
- src/main/scala/amba/axi4/ToTL.scala
- src/main/scala/amba/package.scala
- src/main/scala/rocket/DCache.scala
- src/main/scala/rocket/Frontend.scala
- src/main/scala/rocket/ICache.scala
- src/main/scala/tilelink/ToAHB.scala
- src/main/scala/tilelink/ToAXI4.scala
I misunderstood the AMBA specifications:
HPROT[3] (cacheable)
and
ARPROT[1] (modifiable)
are supposed to be the same, despite using different names in AHB vs. AXI4.
This mismatch then led me to incorrectly map ARPROT[2]+ARPROT[3] to
the AHB cacheable bit.
Add explicit readalloc+writealloc bits to fully cover the AXI4 bits.
Also, in most places, where we say 'cacheable', we mean set all of the bits:
bufferable (writeback ok)
modifiable (write-combining / fetch whole blocks ok)
readalloc  (use outer caches for reads)
writealloc (use outer caches for writes)
... I updated rocket accordingly.
> amba: combine modifiable+cacheable and add {read,write}alloc

- src/main/scala/util/Replacement.scala
**Related issue**: introduced by me in https://github.com/chipsalliance/rocket-chip/pull/2277/commits/9057b3c1a115b4aedfe2d2d5c8dd93596b4f7d3c
```
[warn] /rocket-chip/src/main/scala/util/Replacement.scala:46:39: match may not be exhaustive.
[warn] It would fail on the following inputs: (UInt(), _), (_, Valid()), (_, _)
[warn]     state_reg := ways.fold(state_reg) { case (prev: UInt, way: ValidIO[UInt]) =>
[warn]                                       ^
[warn] /rocket-chip/src/main/scala/util/Replacement.scala:46:64: non-variable type argument Chisel.UInt in type pattern chisel3.util.Valid[Chisel.UInt] (the underlying of …
```
> fix Chisel compile warnings in PseudoLRU.access(ways: Seq)

- src/main/scala/diplomacy/AddressRange.scala
- src/main/scala/diplomacy/Unreachable.scala
fix this Chisel compile Scala warning:
```
[warn] /rocket-chip/src/main/scala/diplomacy/AddressRange.scala:51:44: match may not be exhaustive.
[warn] It would fail on the following input: (_, _)
[warn]     ranges.tail.foldLeft(Seq(ranges.head)) { case (head :: tail, x) =>
[warn]                                            ^
```
> fix Chisel compile warning: Diplomacy AddressRange match may not be exhaustive

- src/main/scala/util/AsyncResetReg.scala
While chisel3 now provides native AsyncReset support, some code bases may still be making use of the `AsyncResetReg` modules and helpers which wrap it. Although those helpers cast the resets internally as needed to generate `AsyncReset`, they are intolerant of themselves being driven by `AsyncReset` because they are currently `Chisel._` modules and expect only `Bool` resets.
Use the compatibility options that allow these to accept resets of any type.
It's probably worth deprecating some of these interfaces, but i have not done that in this PR.
Enable `AsyncResetReg`, `AsyncResetRegVec` modules and helpers to be used within …
> AsyncResetReg: use chisel3 resets

- wit-manifest.json
Bump FIRRTL along 1.2.x branch because the previous commit had a stray debug print. While not causing any functional issues, it did cause a fairly noisy output during FIRRTL emission. This removes that debug print.
> bump FIRRTL along 1.2.x to get rid of stray debug info

- project/plugins.sbt
Removes an unneeded (I think?) resolver which fixes some warnings during an sbt build.
Specifically, this gets rid of these three lines:
```
[warn] insecure HTTP request is deprecated 'http://download.eclipse.org/jgit/maven'; switch to HTTPS or opt-in as ("jgit-repo" at "http://download.eclipse.org/jgit/maven").withAllowInsecureProtocol(true)
[warn] insecure HTTP request is deprecated 'http://download.eclipse.org/jgit/maven'; switch to HTTPS or opt-in as ("jgit-repo" at "http://download.eclipse.org/jgit/maven").withAllowInsecureProtocol(true)
[warn] insecure HTTP request is deprecated 'http://download.eclipse.org/jgit/maven'; switch to HTTPS or opt-in as ("jgit-repo" at "http://download.eclipse.org/jgit/maven").withAllowInsecureProtocol(true)
```
**Related issue**: None.
**Type of …
> Remove jgit-repo resolver

- src/main/scala/rocket/CSR.scala
- src/main/scala/rocket/Instructions.scala
See https://github.com/riscv/riscv-v-spec/commit/951b64fb10f9489ec98a27d3ef1a09e78c1037bf
> Add vcsr; move vxrm/vxsat there instead of fcsr

- src/main/scala/rocket/RocketCore.scala
**Related issue**: follow-on to #2372
> This change removes the ability to see long-latency writebacks in the log. That's OK, but might be useful to add a second printout for those in the future.
https://github.com/chipsalliance/rocket-chip/pull/2392#discussion_r403793731
> RTLsim trace log dump the wrong rd register

- src/main/scala/devices/tilelink/Error.scala
- src/main/scala/devices/tilelink/Zero.scala
- src/main/scala/diplomaticobjectmodel/model/OMErrorDevice.scala
- src/main/scala/diplomaticobjectmodel/model/OMZeroDevice.scala
Piggybacking OMZeroDevice onto #2410 , though this does not change the code to actually attach the device from TLZero along with TLError.
> Attach tl error logical tree nodes [mwachs5 patches]

- src/main/scala/devices/debug/Debug.scala
When a debugger writes to resumereq, the request passes through an AsyncQueue to dmInner. If a fast debugger writes to resumereq and then reads from dmstatus all in the same dmInner clock cycle, the resumereq has not yet been reflected in the dmstatus read value. This PR advances resumeack by one cycle to ensure the proper value is read even in this case.
dmInner stores the resume status in a flag called resumeReqRegs. This is set from dmOuter when a resume is requested. The Debug Spec says that the dmstatus any/allresumeack bits are cleared immediately after resumereq. To ensure this, the read value of resumereq is advanced by one cycle by including …
> Advance dmstatus.resumeack by one cycle

- wit-manifest.json
https://github.com/ucb-bar/berkeley-hardfloat/issues/44
> Bump hardfloat (revert DivSqrtRecF64 to use Module instead RawModule)

- src/main/scala/rocket/RocketCore.scala
**Related issue**: fuller implementation of https://github.com/chipsalliance/rocket-chip/pull/2392
**Release Notes**: “don't print bogus register reads or writes that confuse users and muddy diff-ing logs.”
> coreMonitorBundle print trace log regs only if read or written

- src/main/scala/devices/tilelink/CanHaveBuiltInDevices.scala
- src/main/scala/devices/tilelink/DevNull.scala
- src/main/scala/devices/tilelink/Error.scala
- src/main/scala/devices/tilelink/Zero.scala
- src/main/scala/diplomaticobjectmodel/model/OMErrorDevice.scala
- src/main/scala/diplomaticobjectmodel/model/OMZeroDevice.scala
- src/main/scala/subsystem/BaseSubsystem.scala
- src/main/scala/subsystem/FrontBus.scala
- src/main/scala/subsystem/MemoryBus.scala
- src/main/scala/subsystem/PeripheryBus.scala
- src/main/scala/subsystem/SystemBus.scala
This is my attempt at adding `OMErrorDevice` to the object model. It seems to work based on visual inspection of the resulting objectModel.json. Looking for feedback on whether this is the best way of plumbing and attaching the logicalTreeNodes.
includes https://github.com/chipsalliance/rocket-chip/pull/2343
- factor out `CanHaveBuiltInDevices.attachBuiltInDevices` into `attach` helper method in `BuiltInDevices` companion object
- `CanHaveBuiltInDevices` has abstract field `def builtInDevices: BuiltInDevices`
- `TLError` extends `HasLogicalTreeNode`
- `TLZero` extends `HasLogicalTreeNode`
- argument `device` of  `DevNullDevice` is a `protected val` …
> Attach TLError LogicalTreeNodes to subsystem LogicalTreeNode

- src/main/scala/diplomaticobjectmodel/logicaltree/RocketLogicalTreeNode.scala
- src/main/scala/diplomaticobjectmodel/model/OMISA.scala
- src/main/scala/diplomaticobjectmodel/model/OMPLIC.scala
- src/main/scala/rocket/CSR.scala
- src/main/scala/rocket/IDecode.scala
- src/main/scala/rocket/RocketCore.scala
- src/main/scala/subsystem/HasTiles.scala
- src/main/scala/tile/BaseTile.scala
- src/main/scala/tile/Core.scala
- src/main/scala/tile/Interrupts.scala
This facilitates an embedded-system design point where a secure monitor runs in M-mode, and a less-trusted application that needs to take interrupts runs in S-mode.
Effectively, it's a replacement for the N extension for user-mode interrupts.
Support an MMU-less S-mode, for isolation of embedded processes that take interrupts.
> Separate concept of supervisor mode from presence of MMU

- src/main/scala/stage/phases/AddDefaultTests.scala
- src/main/scala/stage/phases/TransformAnnotations.scala
While bumping Rocket Chip in Chipyard i ran into a couple of order issues with the initial Stage / Phase implementation. There many ways they can be fixed, but this is what i did: 
1) The dependency manager can schedule `TransformAnnotations` behind chisel's `AddImplicitOutputFile` phase, which leads the down stream phases to use the instance of the annotation provided by `AddImplicitOutputFile` and not `TransformAnnotations`. I added a dependency between the two phases to resolve this. 
2) The dependency manager can schedule `AddDefaultTestSuites` ahead of `GenerateFirrtlAnnos`, which leads to `RocketTestSuiteAnnotation`s being serialized when they cannot be. While there are myriad ways to fix this i've simply marked them as unserializable. 
**Impact**: no …
> A Pair of Phase-Ordering Fixes

- ci-tests/wake_scala_compilation
**Related issue**: https://github.com/sifive/wit/pull/225
**Type of change**: fixes CI test wake compilation
**Impact**: API stabilization
pin Wit version to a specific branch
> pin Wit version to branch v0.12.0

- src/main/scala/rocket/RocketCore.scala
- src/main/scala/util/CoreMonitor.scala
**Related issue**: follow-on to #2409
coreMonitorBundle remove `wren` and instead have `wrenx` for integer regfile writes and `wrenf` for floating point regfile writes.
Any users of `coreMonitorBundle.wren` will get a compile error and should change to `wrenx` for the same behavior.
> coreMonitorBundle.wren separate into wrenx/wrenf for integer/float

- src/main/scala/tilelink/Parameters.scala
#2320 introduced a bug in `TLSlaveParameters.v1copy` that was then rolled out at large via #2353. The wrong `name` val was used in the copy constructor. Outcome of the bug is that many TLSlaves have been reporting their name as `"disconnected"`. However, in practice these names seem to only appear in e.g. diplomatic `require` failures that attempt to use the name of the failing slave in their error message. I don't believe any verilog emission was actually affected by this bug.
I fixed the bug in 8ab8246, but I think this bug could have been avoided by making `setName` an `Option` so that `name` and `setName` have different types. Handling it this way cleans up the `setName` code; there is a fundamental difference between setting/not-setting the name and choosing to name something `""`. I …
> Diplomatic tilelink "v1" parameter fixes

- src/main/scala/tile/RocketTile.scala
When hartid is not a constant, driving it to the I$ D$ and CSR file directly from a Tile IO distorts placement of the core. These registers alleviate that.
However, when the hartid IS a constant, these registers are unneeded. I believe chisel will eliminate the registers via constant propagation.
Pipeline tile hartid input.
> RocketTile: do not distort placement when hartid is not constant

- src/main/scala/rocket/PTW.scala
- src/main/scala/tile/LazyRoCC.scala
Because of pipeline replays, round-robin arbitration isn't actually fair.
Using static prioritization is always OK, since RoCC instructions are
older than instructions using the D$, which are older than instructions
being fetched from the I$.
> Use static priority arbitration in PTW

- src/main/scala/devices/debug/Periphery.scala
- src/main/scala/diplomacy/Nodes.scala
- src/main/scala/subsystem/BankedL2Params.scala
- src/main/scala/subsystem/Configs.scala
- src/main/scala/subsystem/FrontBus.scala
- src/main/scala/subsystem/HasTiles.scala
- src/main/scala/subsystem/MemoryBus.scala
- src/main/scala/subsystem/PeripheryBus.scala
- src/main/scala/subsystem/RocketSubsystem.scala
- src/main/scala/subsystem/SystemBus.scala
- src/main/scala/tilelink/AddressAdjuster.scala
- src/main/scala/tilelink/BusWrapper.scala
- src/main/scala/tilelink/Jbar.scala
- src/main/scala/tilelink/Nodes.scala
- src/main/scala/tilelink/Parameters.scala
- src/main/scala/tilelink/RegionReplication.scala
JunctionNodes now support configurable up/down connection ratio.
RegionReplicator and AddressAdjuster now takes a region+local AddressSet instead of a mask (MultiChipMaskKey was removed).
AddressAdjuster can now optionally leave off the 'remote' side of the connection.
AddressAdjuster and RegionReplicator now work on prefixes (not chip id)
> Revise Multichip routing

- src/main/scala/tile/Interrupts.scala
Follow-up to https://github.com/chipsalliance/rocket-chip/pull/2419
Add an assertion that CEASE will not go low once raised until after reset
> Add assertion on CEASE line

- src/main/scala/diplomaticobjectmodel/model/OMPorts.scala
An example representation of a port with AXI protocol:
```
"signalNamePrefix" : "axi4_mem_port",
"width" : 32,
"protocol" : {
"specification" : {
"name" : "AXI Protocol",
"version" : "4",
"_types" : [ "OMSpecification" ]
},
"_types" : [ "AXI", "AMBA", "OMProtocol" ]
},
```
An example representation of a port with AHB-Lite protocol:
```
"signalNamePrefix" : "ahb_sys_port",
"width" : 32,
"protocol" : {
"specification" : {
"name" : "AHB Lite Protocol",
"version" : "3",
"_types" : [ "OMSpecification" ]
},
"_types" : [ "AHB", "AMBA", "OMProtocol" ]
},
```
> Object model updates for AHB and AXI

- src/main/scala/rocket/CSR.scala
- src/main/scala/tile/BaseTile.scala
- src/main/scala/util/TraceCoreInterface.scala
[The RISC-V Processor Trace Specification](https://github.com/riscv/riscv-trace-spec/blob/master/riscv-trace-spec.pdf) has recently been ratified.  The definition of the core-to-trace encoder interface has been changed from the legacy definition currently implemented in rocket-chip.  This PR adds a second BundleBridge trace interface that conforms to the new version of the spec that will allow processors that conform to that spec to connect their trace ports to encoders.
The TraceAux bundle is for sideband signals that are useful but not in the spec.  Previously, there has been a `stall` request signal and this PR adds a new `enable` signal to …
> Add definitions for ratified version of RISC-V Processor Trace spec

- src/main/scala/amba/apb/Monitor.scala
- src/main/scala/amba/axi4/Monitor.scala
**Related issue**: follow-up to #2357
```
[warn] /rocket-chip/src/main/scala/amba/apb/Monitor.scala:17:67: type Reset in package core is deprecated (since 3.2): Use the version in chisel3._
[warn]   def legalize(bundle: APBBundle, edge: APBEdgeParameters, reset: Reset): Unit
[warn]                                                                   ^
[warn] /rocket-chip/src/main/scala/amba/axi4/Monitor.scala:17:69: type Reset in package core is deprecated (since 3.2): Use the version in chisel3._
[warn]   def legalize(bundle: AXI4Bundle, edge: AXI4EdgeParameters, reset: Reset): Unit
[warn] …
```
> Chisel compile warning: Chisel3 package import

- src/main/scala/diplomaticobjectmodel/model/OMPorts.scala
An example representation of a port with AXI protocol:
```
"signalNamePrefix" : "axi4_mem_port",
"width" : 32,
"protocol" : {
"specification" : {
"name" : "AXI Protocol",
"version" : "4",
"_types" : [ "OMSpecification" ]
},
"_types" : [ "AXI", "AMBA", "OMProtocol" ]
},
```
An example representation of a port with AHB-Lite protocol:
```
"signalNamePrefix" : "ahb_sys_port",
"width" : 32,
"protocol" : {
"specification" : {
"name" : "AHB Lite Protocol",
"version" : "3",
"_types" : [ "OMSpecification" ]
},
"_types" : [ "AHB", "AMBA", "OMProtocol" ]
},
```
> Updates to object model to include right protocol information

- src/main/scala/devices/debug/SBA.scala
AMBA adapters include PROT bits which indicate the characteristics of the transaction.  This PR adds drivers for these bits when the debug module initiates a transaction using SBA.
Privileged=1
Fetch=0
Secure=1
Modifiable=Bufferable=ReadAlloc=WriteAlloc=0
> Drive AMBAProt bits from debug SBA

- src/main/scala/tile/Interrupts.scala
Registers driving cease and wfi did not have reset values and could possibly be high for one cycle under reset.
> Provide reset values for registers driving cease and wfi

- .travis.yml
- src/main/scala/diplomacy/package.scala
- src/main/scala/subsystem/RocketSubsystem.scala
- src/main/scala/tile/RocketTile.scala
This is useful when the hartid of a core cannot be known statically.
> subsystem: add an optional node to use for assigning hartids

- Makefrag
- src/main/scala/rocket/DCache.scala
- src/main/scala/rocket/RocketCore.scala
- src/main/scala/stage/phases/AddDefaultTests.scala
- src/main/scala/stage/phases/GenerateArtefacts.scala
- src/main/scala/stage/phases/GenerateFirrtlAnnos.scala
- src/main/scala/stage/phases/GenerateROMs.scala
- src/main/scala/stage/phases/GenerateTestSuiteMakefrags.scala
- src/main/scala/stage/phases/PreElaboration.scala
- src/main/scala/stage/phases/TransformAnnotations.scala
- src/main/scala/system/RocketChipStageGenerator.scala
- src/main/scala/tile/FPU.scala
- src/main/scala/tilelink/SRAM.scala
- wit-manifest.json
* Update some uses of @chiselName to disable new prefixing behavior
* Update Stage/Phase dependencies to new Dependency instead of Class
* Technically bumped to merge-base of each tag with their respective
release branches: 3.3.x for chisel3 and 1.3.x for firrtl
This better supports Wit dependencies
* Include all chisel3 class files on FIRRTL run classpath
We include chisel3 on the classpath for running FIRRTL because of use of utils like `chisel3.util.HasBlackBoxResource`. https://github.com/freechipsproject/chisel3/pull/1384 broke up the chisel3 build into multiple directories so I had to update the Makefiles to include the extra directories.
TODO Release Notes Highlights
**Development Phase**: …
> Bump to Chisel v3.3.0 and FIRRTL v1.3.0

- src/main/scala/tilelink/Broadcast.scala
- src/main/scala/tilelink/SourceShrinker.scala
This change makes the `TLBroadcast` and `TLSourceShrinker` transparently pass through any user bits that are received from clients attached to them.
> Make the TLBroadcast and TLSourceShinker adapters pass through user bits

- .travis.yml
Back at the end of 2017 apparently `sudo: required` gave you a bigger disk image, which we needed. But we're seeing a lot of Travis instability now so reverting this change to see if a) we still need that and b) whether it resolves some of the stability issues
For CI, don't request sudo (which gives a larger disk image) from Travis
> .travis.yml: get rid of request for sudo

- .travis.yml
As of SBT 1.3, the cache for dependencies changed. This updates it for dependencies as well as adds caching for SBT itself. Should save some time and help insulate CI against Maven Central being flakey.
> Update Travis cache for Scala dependencies and SBT

- src/main/scala/tile/Interrupts.scala
#2420 added an assertion to check for a glitchy cease, but the assertion was acting on the unstable cease signal and not the quiesced signal.
> cease glitch assertion should look at stable cease signal

- src/main/scala/rocket/DCache.scala
This bug can manifest with a store, load, store to same word as the first
one, then load, as follows. The first store succeeds, but is still in the
pending store buffer.  Some unrelated load occurs.  Then a store to the
same word as the first store occurs, this time detecting an ECC error.
Finally, some unrelated load occurs.  (The loads are mostly irrelevant,
but the pipeline needs to stay busy for the bug to manifest.)
Since the bug can only manifest with two nearby stores to the same word,
one detecting an error and one not detecting an error, this bug is not
especially likely to occur in practice.  In particular, if the error grew
before the sequence began, the bug would not manifest.
The fix is to prevent the store-merging logic from engaging by gating the
valid signal after the ECC …
> Fix a rare D$ ECC bug

- src/main/scala/tilelink/Broadcast.scala
- src/main/scala/tilelink/CacheCork.scala
Releases from caches are now properly marked when they exit AMBA ports.
> Release as amba cache op

- src/main/scala/util/PlusArg.scala
I came across a case where I needed to add a plusarg in a BlackBoxed verilog module and found that I needed to use `PlusArgArtefacts.append` for verilator to correctly parse my plusarg. This worked fine, but to get the help text to make sense I needed to add some features. This does change the API for `PlusArgInfo`, but other function calls are backwards compatible.
> Add support for emitting string-valued plusargs and plusargs with no default

- src/main/scala/rocket/Decode.scala
For cases where none of the clauses (nor the default) is X, skip the
optimization problem altogether.
It turns out this is both a common and problematic case.  For a design I'm
working on, it reduced the runtime to about 10s from [whenver I Ctrl-C'd the
thing after several minutes].
> Improve DecodeLogic runtime

- src/main/scala/tilelink/Monitor.scala
Reverts chipsalliance/rocket-chip#2450
As pointed out, the added assertions in the prior PR are redundant.
> Revert "additional TileLink assertions"

- src/main/scala/diplomacy/Parameters.scala
- src/main/scala/diplomaticobjectmodel/model/OMISA.scala
- src/main/scala/tilelink/AddressAdjuster.scala
- src/main/scala/tilelink/BusWrapper.scala
- src/main/scala/tilelink/Parameters.scala
Improved QoR in designs with large physical address maps.
> Dynamic local and remote order

- src/main/scala/tilelink/SourceShrinker.scala
- src/main/scala/tilelink/Xbar.scala
The TLSourceShrinker adapter circuitry becomes passthrough when it detects that the requested number of sources is larger than the actual number of sources used by the upstream topology. However, the adapter was still reporting the client metadata as if all clients had been combined together. Instead, we now more accurately preserve the client metadata information through the passthrough form of the adapter.
> TLSourceShrinker: Preserve metadata when no shrinkage is required

- src/main/scala/tilelink/Fragmenter.scala
The TL spec requires denied messages with data to be also corrupt.
In cases where the Fragmenter extends the denied signal, it must also
ensure that corrupt is also raised.
> Fragmenter: when extending denied, we must also extend corrupt

- src/main/scala/tilelink/AddressAdjuster.scala
- src/main/scala/tilelink/BusWrapper.scala
Porting some old enhancements to the AddressAdjuster and one bugfix:
- Allow DTS to report a default relocation amount that isn't the 0th region
- Allow the two legs to have divergent user bits with :<=
> AddressAdjuster patches

- src/main/scala/rocket/ICache.scala
- src/main/scala/tile/BusErrorUnit.scala
add Bus Error Unit cause #1: I-Cache TileLink Bus error (was Reserved)
> BEU report Corrupt+Denied on I-Fetch

- .github/workflows/continuous-integration.yml
Per https://github.com/actions/cache/issues/141#issuecomment-629342357, several of the recent commits have improved reliability:
- https://github.com/actions/cache/pull/306
- https://github.com/actions/cache/pull/300
- https://github.com/actions/cache/pull/305
This may help with the reliability of the GitHub Actions CI checks we have, since we've noticed some flakiness since they were first merged in #2465.
> Use newer GitHub actions/cache for improved reliability.

- src/main/scala/rocket/CSR.scala
The spec requires that implementations support fractional LMUL settings
for LMUL ≥ SEW/ELEN.  The old code enforced the looser constraint that
LMUL ≥ SEW/VLEN, so e.g. if VLEN were twice ELEN, we would support one
notch smaller LMUL for any given SEW.
Tightening the constraint will catch software bugs that rely on vtype
settings that aren't guaranteed to be supported across implemenetations.
The space of configurations that need to be verified is also reduced.
> RVV 0.9: Tighten fractional LMUL-SEW constraint

- src/main/scala/amba/axi4/IdIndexer.scala
- src/main/scala/amba/axi4/Parameters.scala
- src/main/scala/amba/axi4/ToTL.scala
- src/main/scala/diplomacy/Parameters.scala
- src/main/scala/tilelink/Parameters.scala
- src/main/scala/tilelink/ToAXI4.scala
Requests for information about the meaning and properties of certain ids used in diplomatic protocols to be stored in the Object Model necessitates having a common representation of id spaces across protocols. I refactored some common code related to displaying this information during elaboration such that an underlying abstract class and trait are now shared across the representations.
**Type of change**: refactoring
> Standardize IdMap and IdMapEntry

- regression/Makefile
- regression/run-test-bucket
- regression/travis_wait.bash
This fixes two issues when using the new regression scripts on Travis infrastructure:
1. `travis_setup_env.bash` may have an undefined variable `TRAVIS_ENABLE_INFRA_DETECTION`. This script needs to continue past this and have unset variable checking disabled.
2. `travis_wait.bash` is written such that it needs to continue after the first failure to do useful things like print out the log of execution.
**Related issue**: None.
None.
> Fix Travis CI Shell Options

- src/main/scala/stage/phases/AddDefaultTests.scala
- src/main/scala/stage/phases/GenerateArtefacts.scala
- src/main/scala/stage/phases/GenerateFirrtlAnnos.scala
- src/main/scala/stage/phases/GenerateTestSuiteMakefrags.scala
- src/main/scala/system/RocketChipStageGenerator.scala
Add a separate `RocketChiselStage` that adds appropriate modifications to `ChiselStage` that rocket chip needs (only modification is the addition of . Remove `ChiselStage` from `RocketChipStage`'s type hierarchy.
I only spot checked that this passes `DefaultConfig` and that the stack trace trimming didn't appear to break.
I think that this is a better approach than to rely on access to `ChiselStage.run` which is a method that should probably be made `protected`.
**Related issue**: Fixes #2467
- Remove emitVerilog, emitFirrtl, and emitChirrtl methods from RocketChipStage
> RocketChipStage shouldn't extend ChiselStage

- build.wake
Add a resource string (via `setPlanResources`) for java invocations.
A wake runner can use this to resolve a shell `PATH` and `JAVA_HOME` to allow setting different installation locations for java.
If no wake runner is available, wake will fallback to the current default `PATH=/usr/bin:/bin`
> Add 'openjdk/java/1.8.0' resource string to java invocations

- src/main/scala/amba/axi4/Deinterleaver.scala
Support Asynchronous Reset for AXI4 Deinterleaver
> AXI4 Deinterleaver: update to chisel3 to get inferred reset

- regression/Makefile
- src/main/scala/rocket/BTB.scala
- src/main/scala/rocket/PTW.scala
- src/main/scala/rocket/TLB.scala
- src/main/scala/unittest/Configs.scala
- src/main/scala/util/CoreMonitor.scala
- src/main/scala/util/Replacement.scala
**Type of change**: performance enhancement
- Formerly, the PseudoLRU algorithm would not replace all entries in a non-power-of-2 ways cache (or TLB).  For example, PLRU with 6 ways results in way 5 (the sixth way) never being replaced unless it is otherwise invalidated.  However, the way index is always "in bounds", so this is purely a performance bug, not a functional bug.
- The new PseudoLRU algorithm is more verbose Chisel code, with extra if-statements to recursively descend an un-balanced binary tree.
- I wrote tests to exercise the old and the new PLRU behavior.  @hcook do I need to do anything else to include these in CI regressions?
- While I was at …
> PseudoLRU non-power-of-2

- src/main/scala/diplomaticobjectmodel/DiplomaticObjectModelUtils.scala
OM Memory Map: prohibit passing a register map if there is not exactly 1 matching memory region
Add requirement to ensure that `getOMMemoryRegions` is called correctly
> OMMemoryMap: register map can only go to 1 memory region

- src/main/scala/diplomaticobjectmodel/model/OMPorts.scala
> added source ID into Object Model, i.e. OMPorts

- src/main/scala/diplomacy/BundleBridge.scala
- src/main/scala/diplomacy/package.scala
- src/main/scala/subsystem/RocketSubsystem.scala
- src/main/scala/tile/BaseTile.scala
This PR adds two new capabilities to the diplomatic BundleBridge API.
`BundleBroadcast` is generalized into a `BundleBridgeNexus` that now can accept multiple inputs and a user-defined function for reducing the inputs into a single wire value that is to be broadcast, as well as a user-defined function for broadcasting that value.
- the confusingly named `BundleBridgeNexus` case class is renamed to `BundleBridgeNexusNode`
- `BundleBridgeNexus` is now the base class of the implementation of the reduction and broadcast wiring. It defaults to or-reducing its inputs and broadcasting identical copies of the reduction.
- `BundleBridgeNexus` can also be supplied a default wire value in cases where there are no input edges. This value is treated as an input by `inputFn`.
- aiding backwards …
> BundleBridge enhancements

- src/main/scala/diplomacy/Parameters.scala
If AddressSet.unify is ever passed a Seq with a duplicated AddressSet, it
will incorrectly widen that AddressSet.  This can happen even if you called
.distinct before calling AddressSet.unify, because unification can merge two
AddressSets into a new AddressSet which collides with a pre-existing
overlap/duplicate.
Fixed a very bad bug introduced in 63becef3ec369b569254378c5fc5b6be910b7874 on May 11.
> AddressSet.unify: fix reduction bug

- regression/run-test-bucket
- src/main/scala/rocket/DCache.scala
- src/main/scala/rocket/TLB.scala
Previously, the TLB would report that M_PWR (PutPartial) was permissible
anywhere that M_XWR (PutFull) was.  This is fine for cache transactions,
since the caches can handle PutPartial internally.  It's not fine for
uncached transactions, since PutFull support does not imply PutPartial
support.
So, check for PutPartial support separately, similar to AMOs.  If the
access is cached, assume the access can proceed, since it'll be handled
in cache.  If the access is uncached, check the PMA.
Rocket never issues M_PWR, so there's no functional change on that front.
> TLB: Check for PutPartial support separately from PutFull

- src/main/scala/util/package.scala
Otherwise the module can end up being called package_Anon.v
Previously, designs could end up with a module called `package_Anon*.v` which has now been renamed `OptimizationBarrier*.v` Note, there may be other things that end up called package_Anon.v that are not solved by this change.
> OptimizationBarrier: give the module an actual name. 

- src/main/scala/tilelink/Broadcast.scala
- src/main/scala/tilelink/Edges.scala
This adds the ability to add Probe filters to the Broadcast coherence manager.
> Broadcast filters

- .github/workflows/continuous-integration.yml
- .travis.yml
- regression/Makefile
- regression/run-test-bucket
This adds the few Scalatest tests to the regression suite of both Travis and GitHub Actions.
This is largely cargo cult-ed from existing tests, but I expect @richardxia can straighten me out.
None.
> Add `sbt test` to regressions

- src/main/scala/rocket/Events.scala
**Related issue**: add the `require` from https://github.com/chipsalliance/rocket-chip/pull/2125 onto https://github.com/chipsalliance/rocket-chip/pull/2337
require that `SuperscalarEventSets` events fit within mask, same as regular `EventSets`
> SuperscalarEventSets check width

- regression/Makefile
sbt test depends on `FIRRTL_JAR` which puts the `firrtl-test.jar` files in the `test_lib` dir
> make scalatest rule depend on FIRRTL_JAR

- src/main/scala/tilelink/Broadcast.scala
Fix a situation where the generator fails when a useless TLBroadcast is instantiated with no inner caches.
> Broadcast: don't drive a 0-width wire

- src/main/scala/tilelink/Broadcast.scala
The idea here is to have standard interface for describing that you want a
control inteface for the coherence manager.  If you want one, then the filter
gets the opportunity to use it.
> TLBroadcast: make it possible to hook up a control interface

- src/main/scala/amba/ahb/Test.scala
- src/main/scala/amba/ahb/ToTL.scala
It has been deemed desirable to output the data value of a read response
which fails, hopefully reducing confusion for people looking at waveforms.
The AHB spec does not require this and vendor VIP does not test for this.
Therefore, two changes were made to confirm this additional requirement is met:
- The AHBToTL block has an assertion that hrdata is steady during an error response
- The scoreboard fuzzer now checks that corrupt read data matches what was written
I have confirmed that both assertions fire when the hrdata register is removed.
> AHBToTL: add a register to retain hrdata during an error response

- src/main/scala/diplomacy/BundleBridge.scala
RegNext erases the width of a UInt.
This leads to:
java.lang.IllegalArgumentException: requirement failed: hartPrefixNode.node (A nexus node with parent 'hartPrefixNode/topMod/topDesign/gen' at  (BundleBridge.scala:144:31)) requires all outputs have equivalent Chisel Data types, but got
UInt<10>(Wire in BundleBridgeNexus)
vs
UInt(Reg in BundleBridgeNexus)
Using safeRegNext, we can keep the useful requirement check and still have
BundleBridgeNexus work when registered=true with a UInt.
@jackkoenig FYI
> BundleBridge: preserve width; don't use RegNext

- src/main/scala/amba/ahb/ToTL.scala
On the first cycle, this assertion can spuriously fire.
> AHBToTL: fix an assertion failure on power-0

- src/main/scala/rocket/Events.scala
Let member `gate` of `EventSet` could be accessed so EventSet could be cloned by EventSet monitor
> public EventSet.gate so EventSet could be clone with tapped signals

- src/main/scala/tilelink/BusWrapper.scala
Auto-generated signal names for diplomatically punched wires can contain the name of the node to which they are connected. While this behavior is informative in some cases, in other cases it represents a "leak" in terms of the contents of a child module becoming visible to a parent scope. One common case of this undesirable aspect of the behavior is the point at which `TLBusWrapper` "coupler scopes" are connected to the crossbar module within the BusWrapper. The child scope is usually productively named after the device it is connected to, and there is no added value in the specific adapters that happen to be used inside a particular coupler configuration being made apparent via the wire names internal to the wrapper, it's just another source of possible verilog diff mismatches across …
> TLBusWrapper: for internal wire name stability, genericize inner coupler port name

- build.wake
This adds a self-location def `rocketChipRoot` so that other wake rules can find this repository regardless of where it is located in the collection of repositories that makes up your workspace.
Some repository layouts expect a flat list of repositories while others expect a hierarchy, this helps make a repository location-independent if consumers of the repository use the `<reponame>Root` definition as a base prefix when referencing components
> Use self-location in wake rules

- src/main/scala/diplomaticobjectmodel/logicaltree/LogicalTreeNode.scala
- src/main/scala/groundtest/Configs.scala
- src/main/scala/groundtest/GroundTestSubsystem.scala
- src/main/scala/groundtest/Status.scala
- src/main/scala/groundtest/Tile.scala
- src/main/scala/groundtest/TraceGen.scala
- src/main/scala/subsystem/Configs.scala
- src/main/scala/subsystem/HasTiles.scala
- src/main/scala/subsystem/RocketSubsystem.scala
- src/main/scala/system/Configs.scala
- src/main/scala/tile/BaseTile.scala
- src/main/scala/tile/RocketTile.scala
- src/main/scala/util/package.scala
`HasTiles` is refactored to eagerly instantiate tiles of all types by pulling instances of `CanAttachTile` out of a new `Field` named `TilesLocated`.
This change has the following benefits:
- Any class `<: BaseTile` can be `Config`-urably instantiated inside a design without needing to mix in additional traits to the subsystem class hierarchy.
- Various subsystem user code that would like to operate over the `tiles` list (e.g. `nTiles`) does not have to jump through hoops to ensure that it doesn't get called before all tile-adding traits are mixed in, because those traits no longer exist.
In order to make a tile instantiate-able via the new field, you must supply a class like this one:
```
case class RocketTileAttachParams(
tileParams: RocketTileParams,
crossingParams: …
```
> Standardize Tile Instantiation and Attachment

- src/main/scala/rocket/CSR.scala
The ISA specifies the XS field to be read-only. This PR modifies Rocket's CSR file to hardware XS to 3 (dirty) when RoCC is present, and 0 otherwise.
**Development Phase**: mplementation
> Disallow writes to MSTATUS.XS

- src/main/scala/tilelink/CacheCork.scala
There are situations where devices have larger write capability than read
capability.  However, we should not transfer that mismatch into the
supported cache block sizes.
> CacheCork: cache block size for writing cannot exceed reading!

- .github/workflows/continuous-integration.yml
maybe using the official release v2 will somehow magically improve the hit rate?
> github ci: attempt to use cache@v2

- .github/workflows/apt-packages.txt
- .github/workflows/continuous-integration.yml
GitHub seems to have a very high failure rate when restoring artifacts from the cache. When this happens, the build will attempt to compile some of the cached artifacts, such as riscv-tools, from scratch. Because we were not installing all of the packages required for building the artifacts in the later jobs, if the cache restoration step fails, then the build will fail.
Installing the same packages across all jobs will ensure that even if the cache fails to restore, then our jobs will still succeed, albeit more slowly.
> GitHub Actions: Install the same packages in all jobs.

- src/main/scala/rocket/TLB.scala
If an SFENCE.VMA with rs1 != x0 or rs2 != x0 happens on the same cycle as an I-TLB refill, the refill still occurs, even if the SFENCE.VMA should've flushed the entry being refilled.
SFENCE.VMA with rs1=x0 and rs2=x0 is unaffected.
It's exceedingly difficult to manifest this bug.  We found it by inspection (thanks @khannaudit), not by observing it in the wild.
> Fix rare TLB refill/invalidate race condition

- build.wake
I can't actually add @mmjconolly as a reviewer, since he does not have write access to this repo, so @jackkoenig will have to be one to actually approve this PR.
In https://github.com/chipsalliance/rocket-chip/pull/2526, one of the strings that we changed was a single-quoted string, which does not do string interpolation, which resulted in a string that literally had a value of `{rocketChipRoot}/bootrom/bootrom.img`. This fixes it to be a double-quoted string, which _is_ interpolated.
BTW, if either of you knows how to set up a Vim syntax highlighting file to specially highlight interpolated expressions within a string, it'd be nice to get this into …
> build.wake: Fix string interpolation of bootrom path.

- src/main/scala/rocket/RocketCore.scala
- src/main/scala/tile/FPU.scala
The current coreMonitorBundle does not detect the late latency load writes and fp writes. This is adding the CoreMonitorBundle definitions to detect such cases.
> Add CoreMonitorBundles to for late latency writes

- src/main/scala/regmapper/RegFieldDesc.scala
RegFieldDesc.name and RegFieldDesc.group must match specific regular expression `^[_:A-Za-z][-._:A-Za-z0-9]*$` or the design will not elaborate.
> Require RegFieldDesc names match a certain RegEx

- build.wake
- ci-tests/wake_scala_compilation
- wit-manifest.json
Publish the directory location of the ivydependencies.json for the api-scala wake rules to consume
Note: 
* adds direct wit dependency on api-scala-sifive, as we now use the `ivyDepLocations` topic
* api-scala-sifive requires use of wake 0.17.2, so update the rocket-chip CI to reflect this
> wake: publish location of the ivydependencies.json

- .gitmodules
- src/main/scala/prci/ClockBundles.scala
- src/main/scala/prci/ClockGroup.scala
- src/main/scala/prci/ClockParameters.scala
- src/main/scala/system/ExampleRocketSystem.scala
- src/main/scala/tilelink/BusWrapper.scala
- wit-manifest.json
Redo of #2487 which seems to have rebase issues
Bumps FIRRTL along 1.3.x 
~This builds on top of #2486 and will be rebased on top of it as that API changes.~
This demonstrates the use of the new RecordMap. API to get better names for clock group signals
In the comments I'll include a diff before and after this change.
**Type of change**:feature request
(Generated RTL will have different output)
Also bumps firrtl along 1.3.x branch which notably changes the Dedup behavior (this was a bug before)
I/O and internal signals in the clock related modules (ClockSource, ClockGroup, etc) will have more meaningful I/O names vs simply indexed names. This also results in less deduplication of …
> PRCI: use RecordMap API to get easier to follow names on clock group signals

- wit-manifest.json
Bumps to 3.3.x merge-base with v3.3.2
* Add Grouping API (https://github.com/freechipsproject/chisel3/pull/1073)
* Provide `Decoupled.empty` (https://github.com/freechipsproject/chisel3/pull/785)
* Report errors as exceptions when hit outside of Chisel contexts (https://github.com/freechipsproject/chisel3/pull/1425)
* Fix Double Elaboration (https://github.com/freechipsproject/chisel3/pull/1426)
* Memoize hashcode of ChiselCircuitAnnotation (https://github.com/freechipsproject/chisel3/pull/1485)
* Fixes a performance bug affecting Stage/Phase users
Bump Chisel to near v3.3.2
> Bump chisel3 to v3.3.2-ish

- src/main/scala/tile/Core.scala
**Related issue**: Follow up to #2531 which introduced this bug (https://github.com/chipsalliance/rocket-chip/blame/master/src/main/scala/tile/Core.scala#L134)
Fix a bug in the computation of HartID and ResetVector width going into the Tile due to improper use of Chisel compatibility mode functions.
> HartId/ResetVector: Correct the input width calculation

- src/main/scala/tile/FPU.scala
> Fix the wdata in frfWriteBundle for fp loads

- src/main/scala/rocket/CSR.scala
Some derivatives of rocket-chip need more than 8 bits to properly reflect the interrupt cause in the TracedInstruction trace output.  This PR expands TracedInstruction.cause to xLen, the same width as the mcause/scause register.  Many bits will be driven with constant 0 and can be ignored.
> Expand TracedInstruction.cause to xLen

- src/main/scala/diplomacy/BundleBridge.scala
- src/main/scala/diplomacy/Nodes.scala
- src/main/scala/groundtest/Tile.scala
- src/main/scala/rocket/DCache.scala
- src/main/scala/rocket/Frontend.scala
- src/main/scala/rocket/HellaCache.scala
- src/main/scala/rocket/ICache.scala
- src/main/scala/subsystem/HasTiles.scala
- src/main/scala/subsystem/MemoryBus.scala
- src/main/scala/subsystem/PeripheryBus.scala
- src/main/scala/subsystem/RocketSubsystem.scala
- src/main/scala/subsystem/SystemBus.scala
- src/main/scala/tile/BaseTile.scala
- src/main/scala/tile/RocketTile.scala
- src/main/scala/tilelink/BusWrapper.scala
In some configurations we want to be able to relocate the apparent base address of MMIO devices inside the tile. This is problematic for the fast path that the RocketCore has to the ITIM and DTIM, which has to know what the overridden base address should be. To address this limitation this PR adds another (optional) tile input "constant" that is or'd with the base address used in the ITIM and DTIM hit calculations.
This PR also cleans up a few loose ends left over from #2521 and #2497 
- `BaseTile.mmioAddressPrefixNode` propagates a prefix or supplies a default `0.U`
- `TileCrossingParamsLike.controlBaseAddressPrefixWhere` to lookup prefix information location for …
> Bundle Bridge Tile MMIO Address Prefix

- src/main/scala/tilelink/Monitor.scala
> Added channel C-D properties

- src/main/scala/devices/debug/SBA.scala
The address being sent from the trace encoder to the sb2tl module takes on the wrong value in the cycle when sbdata0 is read when sbreadondata is set (sbreadondata causes the SBA to initiate a read transaction on the bus when sbdata0 is read).  Although the actual data transaction has the correct address, the address legality check does not process the correct address and may not flag illegal addresses.
> Debug: Fix address sent from DM to SB2TL

- src/main/resources/vsrc/plusarg_reader.v
fix VCS Lint warning message:
```
Lint-[WMIA-L] Width mismatch in assignment
plusarg_reader.v, 18
Width mismatch between LHS and RHS is found in assignment:
The following 32-bit wide expression is assigned to a 6-bit LHS target:
Source info: myplus = DEFAULT;
Expression: myplus
```
> plusarg default bit width

- src/main/scala/amba/ahb/ToTL.scala
- src/main/scala/devices/debug/DMI.scala
- src/main/scala/diplomacy/Parameters.scala
- src/main/scala/tilelink/Fragmenter.scala
- src/main/scala/tilelink/Monitor.scala
- src/main/scala/tilelink/Parameters.scala
> Adding V2 Constructors in Paramaters and Emits Parameters

- src/main/resources/vsrc/plusarg_reader.v
Fixes chipsalliance/rocket-chip#2558 to use Verilog syntax `parameter`, not SystemVerilog `bit`.
> fix "plusarg default bit width"

- src/main/scala/scie/SCIE.scala
fix VCS `Lint-[WMIA-L] Width mismatch in assignment`
> VCS Lint: width mismatch in assignment

- src/main/scala/tile/BaseTile.scala
@hcook A recent change to the trace-related BundleBridges in BaseTile.scala caused an issue when more than 1 sink node was connected to traceCoreNode: multiple connections to traceCoreSourceNode.  This change will make multiple connections correctly.
> Fix duplication problem in traceCoreNode logic

- src/main/scala/groundtest/GroundTestSubsystem.scala
- src/main/scala/groundtest/Tile.scala
- src/main/scala/prci/ClockBundles.scala
- src/main/scala/prci/ClockDomain.scala
- src/main/scala/prci/ClockGroupDriver.scala
- src/main/scala/prci/ClockNodes.scala
- src/main/scala/prci/ClockParameters.scala
- src/main/scala/subsystem/BaseSubsystem.scala
- src/main/scala/subsystem/HasTiles.scala
- src/main/scala/subsystem/RocketSubsystem.scala
- src/main/scala/tile/BaseTile.scala
- src/main/scala/tile/RocketTile.scala
- src/main/scala/tile/TilePRCIDomain.scala
Tiles are now instantiated inside of a wrapper whose purpose is to contain logic related to their Power, Clock, Reset and/or Interrupt domain. In particular:
- The layer has a diplomatically-derived clock and reset, which are used to drive the tile clock and reset.
- The portion of TileLink clock crossings that are supposed to be in the tile clock domain are instantiated in this layer.
- Interrupt synchronizers are instantiated in this layer.
- Boundary buffers and isolation cells related to hierarchical P&R are to be instantiated in this layer.
- In the future core-local interrupt handlers could be instantiated in this layer.
- All tiles are now …
> Tile PRCI Domain Wrappers

- src/main/scala/util/IDPool.scala
Using SubsystemResetSchemesKey = ResetAsynchronousFull requires that the reset value of all registers be a constant.  FIRRTL was unable to determine that in this instance, necessitating this change.  No functional difference.
> Enable ResetAsynchronousFull in IDPool

- src/main/scala/prci/ResetStretcher.scala
- src/main/scala/subsystem/RocketSubsystem.scala
The Rocket Tile is not currently written to support an asynchronous reset.  When the rest of a system has an asynchronous reset configured by SubsystemResetSchemeKey, a module is inserted into the reset path in the PRCI domain that synchronizes and stretches the core_reset to be a minimum of 16 cycles as required by the core design.  The Tile and everything it contains is generated with synchronous reset.
> Add Reset Stretcher in PRCI Domain for async reset systems

- src/main/scala/diplomacy/DeviceTree.scala
interrupt-controller@xyz can get pretty long on Sv48 systems.
> devicetree: allow node names longer than 32 bytes

- src/main/scala/tilelink/BankBinder.scala
- src/main/scala/tilelink/Broadcast.scala
- src/main/scala/tilelink/CacheCork.scala
- src/main/scala/tilelink/Filter.scala
- src/main/scala/tilelink/Parameters.scala
- src/main/scala/tilelink/ToAXI4.scala
**Related issue**: deprecated in https://github.com/chipsalliance/rocket-chip/pull/2505
fix these Chisel compile deprecation warnings:
```
[warn] /rocket-chip/src/main/scala/tilelink/BankBinder.scala:27:30: method supportsProbe in class TLMasterParameters is deprecated: Use supports.probe instead of supportsProbe
[warn]       supportsProbe      = c.supportsProbe      intersect maxXfer,
[warn]                              ^
[warn] /rocket-chip/src/main/scala/tilelink/BankBinder.scala:28:30: method supportsArithmetic in class TLMasterParameters is deprecated: Use supports.arithmetic instead of supportsArithmetic
[warn]       supportsArithmetic = c.supportsArithmetic …
```
> TileLink Diplomacy parameters supportsProbe -> supports.probe

- src/main/scala/tilelink/Monitor.scala
change monitor to not put diplomacy in error messages during normal run, but as an optional feature used for debugging
> change monitor to not put diplomacy in error messages

- src/main/scala/diplomaticobjectmodel/model/OMISA.scala
This describes whether non-memory instructions support nonzero vstart values.
> Add OMVectorExtension.vstartALU field

- src/main/scala/rocket/CSR.scala
This is a backwards-incompatible change to the layout of the RVV vtype CSR.
https://github.com/riscv/riscv-v-spec/commit/b8cd98bc9467617b6653583116b2dfe9eefb2f51
> RVV 1.0: reorder fields in vtype

- src/main/scala/amba/axi4/Bundles.scala
- src/main/scala/amba/axi4/Credited.scala
- src/main/scala/amba/axi4/CrossingHelper.scala
- src/main/scala/amba/axi4/Nodes.scala
- src/main/scala/amba/axi4/Parameters.scala
- src/main/scala/diplomacy/Parameters.scala
- src/main/scala/interrupts/CrossingHelper.scala
- src/main/scala/tilelink/Bundles.scala
- src/main/scala/tilelink/Credited.scala
- src/main/scala/tilelink/CrossingHelper.scala
- src/main/scala/tilelink/Nodes.scala
- src/main/scala/tilelink/Parameters.scala
- src/main/scala/unittest/Configs.scala
- src/main/scala/util/CreditedIO.scala
This PR adds a new kind of flow control, CreditedIO, which fills the same role for credit/debit systems that DecoupledIO fills for ready/valid systems. Included in this PR are conversion methods to and from Decoupled as well as adapters for TileLink and AXI4.
The advantage of a credit/debit system is that you can add an arbitrary number of fanout=1 fanin=1 pipeline stages in both the data delivery and credit return paths. By comparison, adding ready/valid pipeline stages invariably includes at least a fan of degree 2.
See the following design diagram: https://app.lucidchart.com/invitations/accept/8271ee7b-98ba-44a4-ab3e-e8ae5af9fb43
**Type of change**:  feature request
> Add CreditedIO to support register-register interfacing for AXI4 and TL

- src/main/scala/tile/LazyRoCC.scala
Convert LazyRoCC examples to use chisel3 syntax instead of legacy Chisel compatibility.
> Port LazyRoCC examples to chisel3

- ci-tests/wake_scala_compilation
Stop regressing on wake 0.18 support; compile using 0.18.1 instead of 0.17.2.
> CI: compile using wake 0.18.1

- src/main/scala/diplomaticobjectmodel/logicaltree/RocketLogicalTreeNode.scala
- src/main/scala/diplomaticobjectmodel/model/OMRocketCore.scala
- src/main/scala/rocket/Breakpoint.scala
- src/main/scala/rocket/CSR.scala
- src/main/scala/rocket/Instructions.scala
- src/main/scala/rocket/RocketCore.scala
- src/main/scala/tile/Core.scala
The Debug Spec defines `mcontext` and `scontext` as CSRs that M-mode and S-mode OSs can write to when switching tasks.  The OS writes a process ID or similar identifier to uniquely identify the incoming task or process.  A debugger may choose to qualify breakpoints by requiring that either `mcontext` or `scontext` (or both) match values programmed into the `textra` register of each breakpoint.  This allows triggering on a virtual address that might be used by more than one process.
`mcontext` and `scontext` have a secondary use as additional comparison registers that an M-mode or S-mode application can write to enable and …
> Debug: Add mcontext/scontext registers for breakpoint qualification

- src/main/scala/rocket/RocketCore.scala
- src/main/scala/tile/FPU.scala
- src/main/scala/util/CoreMonitor.scala
The wdata was collecting incomplete value for fp cases when xlen was different from flen for example xlen = 32 and flen = 64 because the data width was based on xlen.
> Change wrdata width to support xLen != fLen case

- src/main/scala/devices/debug/DMI.scala
- src/main/scala/devices/debug/Debug.scala
A request was made to simplify the DMIToTL module so that it uses only PutFull TL transactions and not PutPartial.  PutPartial had been used to handle DMI_NOP requests from the Debug Transport Module.  These generated a TL PutPartial to the DMCONTROL register with mask=0, so had no effect on the state of DMCONTROL.  This PR changes handling of DMI_NOP to do a PutFull to HARTINFO, which is a read-only register so still will have no effect on register state.
HARTINFO was moved from DMInner to DMOuter to facilitate this.  HARTINFO has only read-only fields that are populated by implementation parameters so can be in either domain.
> Remove PutPartial from DMIToTL

- src/main/scala/rocket/PTW.scala
**Impact**: performance improvement, no functional change
This only affects designs with MMU and clock gating.
The bug is that an L2TLB write will almost always block the next L2TLB search, even many cycles later, because the `l2_refill` register doesn't clear until the next search enables the clock.  The fix is to add the `l2_refill` register to `ptw_clock_en`.
`customCSRs.disableDCacheClockGate` is a work-around to utilize the L2TLB at the cost of extra power.
> PTW clock_en l2_refill

- src/main/scala/tilelink/SRAM.scala
- src/main/scala/unittest/Configs.scala
Here is a picture of the change to the pipeline:
https://app.lucidchart.com/invitations/accept/da44b89c-a93c-45e9-ba5e-cb6f9140d84e
Compared to the old pipeline, occupancy is increased from 2 cycles to 3 for:
- atomics
- sub-ECC-granularity writes
- repaired ECC values
In exchange for this occupancy increase, a new register (REG) was added:
sram data output => *REG* => ecc-correction => ALU => sram write setup
This path was sufficiently long that it limited fMAX on many designs.
In designs without ECC and without atomics, this pipeline is optimized away.
Compared to the old pipeline, response latency is unchanged (by default) for:
- reads   (1)
- atomics (1)
- writes  (1)
- ECC-repaired reads   (2)
- ECC-repaired atomics (2)
Added a knob (sramReg) to set latency for all operations to 2. …
> SRAM: repipeline the TLRAM into a 3 cycle RMW state machine

- src/main/scala/diplomacy/Nodes.scala
**Release Notes**:
`BundleBridgeNexusNode` is using `MixedNexusNode`, debug without nearby nodes is hard.
This PR gives better debug infomation by printing nearby nodes `require` is false.
> Add some debug info to diplomacy.

- src/main/scala/rocket/CSR.scala
- src/main/scala/subsystem/HasTiles.scala
- src/main/scala/tile/BaseTile.scala
- src/main/scala/tile/Interrupts.scala
- src/main/scala/tile/RocketTile.scala
- src/main/scala/util/BlockDuringReset.scala
- src/main/scala/util/RationalCrossing.scala
Tile notification output ports should be reset to 0 asynchronously when using `SubsystemResetKey = ResetAsynchronous`.  Since the module reset for the Tile is a stretched `Bool()` reset, bring a second reset into the Tile sourced from the original external IO.  When the notifications are placed in a `withReset` block, this resets the registers driving the outputs asynchronously.
@hcook, there's probably a cleaner way to connect the core_reset IO into the Tile...
Also changed the `RationalCrossing` so that the sink (which may be in an async reset domain) does not act on any output from the source (which may be synchronously reset some time later) until …
> Change tile outputs to initialize with async reset

- src/main/scala/rocket/DCache.scala
- src/main/scala/rocket/Frontend.scala
- src/main/scala/rocket/HellaCache.scala
- src/main/scala/rocket/ICache.scala
The design also supports parametrization of both the sectoring and the number of superpages in the L1 TLBs. The code has always supported the different values, but the parameters to control it were not exposed up the hierarchy.
> Add params for nTLBBasePageSectors and nTLBSuperpages for both I and D TLBs

- src/main/scala/rocket/CSR.scala
- src/main/scala/tile/RocketTile.scala
Per a review comment in another repository, change the method to ensure trace.valid signals are deasserted during and just after reset.  Now uses an async-reset delay to gate trace.valid in RocketTile rather than gating with core.reset.
> Revise trace.valid gating method to relieve timing on reset

- src/main/scala/rocket/PTW.scala
**Related issue**: follow-on improvement to https://github.com/chipsalliance/rocket-chip/pull/2601
**Type of change**: performance enhancement
Wait for L2TLB search to improve performance on back-to-back page table walks from L1DTLB then L1ITLB or vice versa.
> PTW: wait for L2TLB refill before searching

- README.md
Clarify the location where example Config alterations should be added while working through one example in the Readme.
**Related issue**: https://github.com/chipsalliance/rocket-chip/issues/2600
**Impact**: no functional change (readme text only)
> readme: clarify example config location

- src/main/scala/rocket/PMP.scala
**Related issue**: PMP NA4 coverpoints generated in configs with pmpGranularity > 4
Configs with pmpGranularity > 4 will not be able to create a PMP region Naturally Aligned to 4 (NA4). However NA4 coverpoints are generated in PMP and D$ TLB regardless. This means ~(2*nPMP*3) redundant coverpoints generated in configs with pmpGranularity > 4, where nPMP is the number of PMP regions in config.
> Remove NA4 cover point for pmpGRanularity > 4

- src/main/scala/amba/axi4/Parameters.scala
- src/main/scala/amba/axi4/ToTL.scala
- src/main/scala/diplomacy/Parameters.scala
- src/main/scala/diplomaticobjectmodel/model/OMPorts.scala
- src/main/scala/tilelink/Parameters.scala
- src/main/scala/tilelink/ToAXI4.scala
This PR adds a `maxTransactionsInFlight` field to `IDMapEntry` and `OMIdMapEntry`. This field offers an upper-bound on the number of transactions possibly in flight from a given master associated with a range of ids. The calculation is protocol specific; while it is exactly the number of source ids for TileLink, for AXI4 incomplete information forces us to make a conservative overestimate: assume that every single ID could possibly generate the maximum number of transactions (which may or may not be true), and that each source could generate simultaneous read and write transactions using the same ID (which may or may not be true).
Related issue:
Type of change: feature request
Impact: API addition (no impact on existing code)
Release Notes
> Add maxTransactionsInFlight to IDMapEntry and OMIdMapEntry

- src/main/scala/devices/tilelink/BusBlocker.scala
- src/main/scala/devices/tilelink/ClockBlocker.scala
- convert to chisel3
- upstream factory helper from `sifive-blocks` (users might have to change import from `sifive.blocks.util` to `freechips.rocketchip.devices.tilelink`)
- improve detail of scaladoc comments
**Type of change**:feature request
**Impact**:  API addition (no impact on existing code) 
> Update BasicBusBlocker (chisel3, scala-doc, factory)

- src/main/scala/rocket/DCache.scala
- src/main/scala/tilelink/Bundles.scala
- src/main/scala/tilelink/CacheCork.scala
C channel now has the same user bits A channel does.
This moves the responsibility for filling in AMBAProt on C-channel from the CacheCork to the caches.
However, it frees those caches to supply additional fields in their requests, which was previously impossible.
Time will tell if we need additional configuration flexibility between A- and C-channel fields.
> User fields on C channel

- build.wake
- wit-manifest.json
This adds some indirection so that the hardfloat repository doesn't have to be at a fixed location
cc @jackkoenig @terpstra 
> wake: avoid hardcoded directory path for 'hardfloat' repository

- src/main/resources/vsrc/SimDTM.v
- src/main/resources/vsrc/SimJTAG.v
Verilator ignores these delays (after warning the user), so they can
result in race conditions.
This fixes an issue visible on https://github.com/chipsalliance/rocket-chip/pull/2617 where some assertions fire erroneously due to some optimizations Verilator makes that are incorrect due to the race conditions.
Thank you to @ernie-sifive for doing this work 
Remove Verilog delay statements from SimJTAG.v and SimDTM.v
> Remove Verilog delay from DPI outputs and use falling edge instead

- src/main/scala/tilelink/Xbar.scala
fix a type mismatch error.
```scala
def inputs: Seq[(OutwardNode[DI, UI, BI], RenderedEdge)]
def outputs: Seq[(InwardNode[DO, UO, BO], RenderedEdge)]
```
> bug fix for inlined xbar

- src/main/scala/subsystem/Configs.scala
- src/main/scala/subsystem/RocketSubsystem.scala
This change is meant to allow for using more generic or even specialized implementations of the master parameter of RocketCrossingKey.
@hcook I'm a little bit more concerned about my change to subsystem/Configs.scala. Right now just TileMasterPortParams is used. If another subclass gets used then WithIncoherentTiles might not do the right thing.  I wasn't sure if this was the best approach.
> Relax master parameter of RocketCrossingParams

- src/main/scala/amba/axi4/Deinterleaver.scala
Otherwise, cycle timing of the design can be impacted by the optimization
which removes this IP. The new default changes the behaviour to leave the
timing unaffected by the optimization, which, while a change, is safer.
@hcook I've opted not to try to modify the circuit to make the non-optimized case pass-through. I'd rather spend that mental energy on a better non-store-and-forward deinterleaver.
> AXI4Deinterleaver: add a buffer when optimized away

- src/main/scala/system/SimAXIMem.scala
`SimAXIMem` currently assumes physical memory always starts at zero; this is not the case as it is possible to modify `p(ExtMem).get.master.base` for scenarios where the memory does not actually start there (e.g. when instantiating on Zynq FPGA and using the upper half of DRAM).  This change adds support for this situation by reading the base of `ExtMem` and `ExtBus` from the parameters for instantiation.
> Make SimAXIMem start at expected memory base instead of zero

- src/main/scala/rocket/DCache.scala
- src/main/scala/rocket/HellaCache.scala
This is particularly useful for reducing energy per scalar access when attaching a coprocessor that requires a very wide D$ port.
Enabled with optional parameter DCacheParams.subWordBits.
> Support subbanking the D$ to save power for narrow accesses

- .scalafix.conf
- src/main/scala/amba/axi4/package.scala
- src/main/scala/diplomacy/package.scala
- src/main/scala/interrupts/package.scala
- src/main/scala/tilelink/package.scala
- src/main/scala/util/package.scala
---
Followup to https://github.com/chipsalliance/rocket-chip/pull/2648.
This PR enables the [`LeakingImplicitClassVal `](https://scalacenter.github.io/scalafix/docs/rules/LeakingImplicitClassVal.html) lint rule in Scalafix. In Scala, `val` constructor parameters are part of the public interface of a class. However, in most cases, `implicit` classes do not intend to publicly expose the `val` parameter, as the parameter is generally only there to assign an internal name to the object being implicitly converted to another type. This lint rule will require that all `val` parameters to `implicit class`es be explicitly marked as `private`.
To the …
> Enable LeakingImplicitClassVal lint rule

- .github/workflows/continuous-integration.yml
- .gitignore
- .sbtopts
- CONTRIBUTING.md
- Makefrag
- README.md
- build.sbt
- build.wake
- emulator/Makefrag-verilator
- project/build.properties
- project/plugins.sbt
- regression/Makefile
- regression/run-test-bucket
- scripts/swap-sbt-build
- src/main/scala/stage/phases/GenerateFirrtlAnnos.scala
- src/test/scala/generatorTests/StageGeneratorSpec.scala
- src/test/scala/linting/rule/LintConflictingModuleNamesSpec.scala
- src/test/scala/transforms/naming/RenameDesiredNamesSpec.scala
- vsim/Makefrag-verilog
- wit-manifest.json
This PR kills the FIRRTL fat jar, instead using https://github.com/freechipsproject/chisel3/pull/1563 to include FIRRTL as a managed dependency in SBT. It also supports toggling between source and published dependencies, if you delete `.sbtopts` it will use the published dependencies.
TODO
**Impact**: API modification (to build API and Makefiles)
Change build flow to build FIRRTL as SBT-managed dependency and use rocket-chip fat jar in Makefiles
> Update to Chisel 3.4.0 and FIRRTL 1.4.0

- src/main/scala/amba/ahb/SRAM.scala
- src/main/scala/amba/apb/SRAM.scala
- src/main/scala/amba/axi4/SRAM.scala
- src/main/scala/diplomacy/SRAM.scala
- src/main/scala/tilelink/SRAM.scala
- src/main/scala/util/ECC.scala
Add public accessors for addresses and chisel memories of `AXI4/ABP/AHB/TLRAM` so they may be used to record metadata in downstream passes.
> Public accessors for SRAM modules

- src/main/scala/rocket/DCache.scala
- src/main/scala/rocket/HellaCache.scala
- src/main/scala/util/Replacement.scala
Also extended the ReplacementPolicy API to indicate whether the policy is typically used on a per-set basis (as with pLRU etc.) or a global basis (as with random).
> Make D$ replacement policy configurable

- src/main/scala/tile/BaseTile.scala
Add `riscv,pmpgranularity` parameter to device tree string; property name inspired by `riscv/riscv-isa-sim` DTB parser.
https://github.com/riscv/riscv-isa-sim/blob/ecc039ef5726315b7e37e8a9c7b682bbe09c9cf5/riscv/dts.cc#L270
Observed the following output in a custom configuration:
```
riscv,isa = "rv32imac";
riscv,pmpgranularity = <4>;
riscv,pmpregions = <4>;
```
**Impact**: no functional change | API addition (no impact on existing code)
> Add PMP granularity to DTS

- src/main/scala/rocket/BTB.scala
- src/main/scala/rocket/DCache.scala
- src/main/scala/rocket/Frontend.scala
- src/main/scala/rocket/IBuf.scala
- src/main/scala/util/IDPool.scala
- src/main/scala/util/Replacement.scala
- src/main/scala/util/package.scala
- wit-manifest.json
> Misc. fixes to make Rocket tolerant to X-propagation

- src/main/scala/util/package.scala
Fixes a zero-width-wire situation.
> Make rotates work when size<=1

- src/main/scala/devices/debug/Debug.scala
I had to make this modification so this bundle and bundles which include it can be `cloneType`'d
> Debug: val members in extTrigger bundles for compatibility with cloneType

- src/main/scala/prci/ResetSynchronizer.scala
* [prci] Add a pair of diplomatic reset synchronizers
Some other thoughts: 
- Here I don't bother exposing any of the underlying parameters of ResetCatchAndSync; if that's desired i can add requested ones. 
- ResetWrangler could be made more diplomatic in spirit by removing its direct instantiation of ResetCatchAndSync.
> [prci] Add a pair of diplomatic reset synchronizers

- src/main/scala/util/IDPool.scala
add IDPool arguments `lateValid` and `revocableSelect` to shift the deep logic cones from before the `valid/select` registers to after the `bitmap` register
> IDPool: synthesis timing enhancement argument options

- src/main/scala/tilelink/Monitor.scala
change the allowed TileLink coherence permission `param` for `ProbeAckData/ReleaseData` from `TtoB/TtoN/BtoN` to `TtoT/TtoB/TtoN`
> TileLink Monitor: C-Channel ProbeAckData/ReleaseData from Trunk permission param to any Trunk/Branch/None

- src/main/scala/amba/axi4/IdIndexer.scala
Any string that could potentially show up as metadata in the graphml cannot have text bracketed by `<...>` without that text being interpreted as a XML tag. Such a string was getting inserted in some cases for designs with AXIIdIndexers, a situation which was introduced by by me in https://github.com/chipsalliance/rocket-chip/pull/2483/ (though I don't think the data in question was being ingested into the graphml at that point?)
> axi4: remove <>s from metadata

- src/main/scala/util/IDPool.scala
**Related issue**: introduced by https://github.com/chipsalliance/rocket-chip/pull/2673
work around Firrtl Async reset check failure
```
======== Starting Transform firrtl.checks.CheckResets ========
Exception in thread "main" firrtl.checks.CheckResets$NonLiteralAsyncResetValueException:  @[IDPool.scala 18:23]: [module IDPool] AsyncReset Reg 'bitmap' reset to non-literal 'bits(_bitmap_T, 7, 0)'
```
introduced by
```
val bitmap = RegInit(-1.S(numIds.W).asUInt()(numIds-1, 0))
```
from https://github.com/chipsalliance/rocket-chip/pull/2673/commits/f165c98d83589e6e85dcfc52b185dd1a55d32e86
> IDPool: RegInit reset literal value

- src/main/scala/diplomacy/LazyModule.scala
- src/main/scala/diplomacy/Nodes.scala
**Related issue**:  https://github.com/chipsalliance/rocket-chip/pull/2674
This PR replaces the `bundlesSafeNow` guard with a looser `instantiated` guard that is set to true when `instantiate` is called and is never reset to false afterwards. This allows the `in`/`out` bundles to be accessed by things like Aspects after the `LazyModuleImp` has been instantiated.
protected function `finishInstantiate` is removed from `BaseNode` and `LazyModule` as it is no longer necessary.
> loosen Node bundle accessor requirements

- src/main/scala/amba/axi4/Deinterleaver.scala
- src/main/scala/amba/axi4/IdIndexer.scala
- src/main/scala/amba/axi4/UserYanker.scala
- src/main/scala/tilelink/ToAXI4.scala
- src/main/scala/util/Annotations.scala
Miscellaneous improvements to several AXI4 AMBA adapters:
- Scala doc
- Clarify some variable names
- More comments
- Unify TLToAXI4 metadata code paths into a single path through `TLtoAXI4IdMap`
- Make any value of `TLToAXI4.stripBits` other than 0 illegal and stop using it internally.
- Remove usage of un-consumed `Annotated.idMapping` and delete associated application and annotation class.
**Type of change**:other enhancement
**Impact**: no API changes
> Improvements To AMBA AXI4 Adapters

- src/main/scala/devices/tilelink/CanHaveBuiltInDevices.scala
- src/main/scala/subsystem/Configs.scala
- src/main/scala/subsystem/FrontBus.scala
- src/main/scala/subsystem/MemoryBus.scala
- src/main/scala/subsystem/PeripheryBus.scala
- src/main/scala/subsystem/SystemBus.scala
- src/main/scala/tilelink/CacheCork.scala
Makes optional the instantiation of previously mandatory adapters for these devices, and also adds a CacheCork option for the Zero device
> BuiltInDevices: Optional instantiation of TL adapters

- docs/src/diplomacy/select_tutorial.md
- src/main/scala/aop/Select.scala
- src/main/scala/diplomacy/LazyModule.scala
- src/main/scala/diplomacy/Nodes.scala
- src/main/scala/diplomacy/package.scala
This is a sketch of a [Select](https://github.com/freechipsproject/chisel3/blob/master/src/main/scala/chisel3/aop/Select.scala) library for diplomatic nodes and `LazyModules`. The motivation behind this is to enable fine-grained selection of node bundles for things like monitoring, without having to override the `NodeImp.monitor` method or change a `LazyModule`'s `Parameters` or modify any design code.
> add Select combinators

- src/main/scala/rocket/PTW.scala
**Related issue**: follow-up to https://github.com/chipsalliance/rocket-chip/pull/2688
do not count PTE Cache Miss performance monitor event on the leaf (last) level of the page table walk, because the PTE Cache is not used there
> PTW do not count pte_miss on leaf walk level

- src/main/scala/rocket/DCache.scala
- src/main/scala/rocket/HellaCache.scala
- src/main/scala/rocket/PTW.scala
- src/main/scala/rocket/RocketCore.scala
Since the same physical address can legally live in multiple places for
caches that support aliasing, we can expose this additional degree of
freedom. It is useful for decoupled accelerators whose memory addresses
have been converted up front.  If they use the physical address directly,
then they'll often access the wrong set, causing an aliasing miss.  If
they happen to know which alias is most likely, they can use this new
mechanism to choose it.
No change for the non-aliasing case.
> D$: support specifying the cache index when aliasing possible

- src/main/scala/rocket/CSR.scala
- src/main/scala/rocket/Instructions.scala
- src/main/scala/util/Counters.scala
add CSR `mcountinhibit` as was defined in RISC-V Privileged ISA version 1.11
> CSR mcountinhibit

- src/main/scala/rocket/DCache.scala
- src/main/scala/rocket/HellaCache.scala
This reduces the latency of some inclusion and coherence misses, in exchange for additional C-channel traffic.  It is disabled when using the broadcast hub, because there it doesn't improve latency.
> Support noisy drops from L1 D$

- src/main/scala/rocket/CSR.scala
- src/main/scala/rocket/RocketCore.scala
Since we use the cycle counter to determine when to unpause, we shouldn't
pause when the cycle counter doesn't count.
> Ignore PAUSE instructions when mcountinhibit.CY=1

- build.sbt
- wit-manifest.json
* Add Force Name API (https://github.com/freechipsproject/chisel3/pull/1634)
* Use `lo` and `hi` instead of `left` and `right` in SeqUtils prefixing
* Provide user source locators in errors (https://github.com/freechipsproject/chisel3/pull/1618)
* Fix quadratic growth of names in recursive functions (https://github.com/freechipsproject/chisel3/pull/1614)
* Support Cat with zero-length Vecs (https://github.com/freechipsproject/chisel3/pull/1623)
* Make `-e` option work in object ChiselStage methods (https://github.com/freechipsproject/chisel3/pull/1630)
* Fix module name collisions in injecting aspect (https://github.com/freechipsproject/chisel3/pull/1635)
* Use `List[String]` for prefix stack to enable structural sharing (https://github.com/freechipsproject/chisel3/pull/1617)
* Cheaper …
> Bump Chisel along 3.4.x release branch

- src/main/scala/util/SynchronizerReg.scala
It was intended that the SynchronizerPrimitiveShiftReg be identical, as they have suggestName applied that was intended to capture all variance in terms of functionality.
However, because they had inferred reset type (the reset is cast appropriately *inside* the Primitive module), the FIRRTL would not be identical at the point of Dedup and you could end up with 2 versions. The final verilog (since verilog dosen't distinguish between reset types) would be identical.
Since the Primitives are intended to be easy to replace with library-specific macro sells for synchronization, this is undesirable.
This change pushes the reset type up into the SynchronizerShiftReg (which still may end up with multiple copies) to make sure you only get one SynchronizerPrimitiveShiftReg of each type.
**Related …
> SynchronizerPrimitiveShiftReg: fix Dedup Issue

- src/main/scala/prci/ResetSynchronizer.scala
Identity nodes perform an initial `out <> in` assignment, which causes the outwards resets to receive assignments to both `AsyncReset` and `Bool` types.
> [prci] Fix ResetSynchronizers to use AdapterNodes instead of IdentityNodes

- src/main/scala/rocket/DCache.scala
I introduced some deadlock a couple days ago.
> Fix regression introduced by 79dd73a38c4b6ba8f2261b1f24bd6fa7094b1316

- src/main/scala/subsystem/BusTopology.scala
- src/main/scala/subsystem/Configs.scala
This upstreams some of stuff we're using in Chipyard, that was discussed in ucb-bar/chipyard#690. It splats out the existing SubsystemCrossingParams into multiple `Key`s per Henry's suggestion. We could consider deprecating that class now. 
I've also added the ability to disable the default DriveClockFromMaster behavior in the provided topologies. We're driving them ourselves in Chipyard, mostly because we want to make clock naming independent of xtype selection. 
One idea I had for making it easier to define custom topologies downstream, might be to push this into the `Parameter`s instance with two Maps:
1) Map[Location, TLBusWrapperInstantiationLike] to represent instantiations
2) Map[(Location, Location), TLBusWrapperConnection] to represent connections. 
This might help avoid needing …
> Add An Optional L2:MBus crossing; Misc Xtype + Bus Frequency Config Mixins

- src/main/scala/stage/phases/PreElaboration.scala
`TargetDirKey` is a `Field[String]` that gets populated with the `TargetDirectoryAnnotation`
during `PreElaboration`.
Enables other `Config` `Field`s to refer to the Stage's TargetDir.  Specifically, the current [chipyard.config.WithBootROM](https://github.com/ucb-bar/chipyard/blob/0685812c342c31d735472ad13573ce8f21ed3687/generators/chipyard/src/main/scala/ConfigFragments.scala#L36-L38) depends on finding a file relative to the current-working directory of the `Stage`.  Adding `TargetDirKey` will allow `chipyard.config.WithBootROM` to look for contents relative to the TargetDir.  This will be helpful as we develop distributed elaboraton flows for Firesim in firesim#651 …
> Create TargetDirKey to expose Stage's --target-dir to Config

- src/main/scala/util/ElaborationArtefactAnnotation.scala
Stopgap solution to issue of `ElaborationArtefacts` outputting stale instance paths. This adds `ElaborationArtefactAnnotation` which contains the filename and list of `Token`s that contain the contents of the file. `Token` subclasses are `StringToken`, `ModulePathToken`, and `ReferencePathToken`. `ModulePathToken` and `ReferencePathToken` contain `Target`s that are updated by firrtl. `ElaborationArtefactsTransform` serializes the `ElaborationArtefactAnnotation`s
`ElaborationArtefactAnnotation`s can be annotated with the `ElaborationArtefactAnnotation.annotate` and `Token.apply` methods e.g.
```
ElaborationArtefactAnnotation.annotate("foo.json",
Seq(Token(s"""{ foo: $foo, bar: $bar, mod: """"), Token(module), Token("""", ref: """"), Token(module.reset), Token("""" }"""))
```
there is a …
> add ElaborationArtefactAnnotation

- src/main/scala/rocket/DCache.scala
Partial writes to the same word were not hazard-checked properly for
VIPT caches with page size < way size.
> Fix regression introduced by 407496940 for M_PWR commands

- src/main/scala/diplomaticobjectmodel/logicaltree/RocketLogicalTreeNode.scala
- src/main/scala/diplomaticobjectmodel/model/OMRocketCore.scala
- src/main/scala/rocket/CSR.scala
- src/main/scala/rocket/IDecode.scala
- src/main/scala/rocket/Instructions.scala
- src/main/scala/rocket/RocketCore.scala
- src/main/scala/subsystem/HasTiles.scala
- src/main/scala/tile/BaseTile.scala
- src/main/scala/tile/Core.scala
- src/main/scala/tile/Interrupts.scala
- src/main/scala/tile/RocketTile.scala
- New NMI inputs covering both resumable and unresumable NMI
- NMI wired through and integrated into the CSR module's interrupt handling infrastructure
- New CSRs for NMI created.
- New mnret instruction created.
- Object model items now reflects presence of NMI
- Bus Error Unit local interrupt is now wired to cause RNMI and populate mncause with a unique exception code.
> NMI implementation

- src/main/scala/util/ElaborationArtefactAnnotation.scala
`ElaborationArtefactAnnotaion` will fail to rename if it contains a `MemoryPathToken` pointing at a seq mem of an aggregate type. e.g. for `mem: SyncReadMem[Vec[UInt]]`, firrtl will rename `mem` to `mem_0`, `mem_1`, `mem_2`, etc.
This updates `MemoryPathToken` to handle this case by renaming the token to multiple `MemoryPathToken`s separated by spaces. so the resulting output will look like `"mem_0 mem_1 mem_2 ...`
> allow renames to multiple targets for MemoryPathToken

- src/main/scala/devices/tilelink/Plic.scala
PLIC Priority registers are now explicitly named with a suffix. This prevents tooling which assumes that the "first" register in a group should have the 0th index ending up with Priority[2] ending up in a register called priority_1, and so on.
> PLIC Priority RegFieldDesc fix off-by-one

- src/main/scala/devices/debug/Periphery.scala
- src/main/scala/devices/tilelink/BootROM.scala
- src/main/scala/devices/tilelink/CLINT.scala
- src/main/scala/devices/tilelink/Plic.scala
- src/main/scala/prci/ClockGroup.scala
- src/main/scala/subsystem/BaseSubsystem.scala
- src/main/scala/subsystem/InterruptBus.scala
- src/main/scala/subsystem/RTC.scala
An alternate implementation to #2622. 
Two problems:
- Not sure if the extra layers of module hierarchy are desired, but we can always inline the CD wrappers.
- Something needs to supply the IBus ClockSource when there's no PLIC.
~~I think it would be really cool if we had a mixin for LazyModule, `DiplomaticImplicitClockAndReset` or something, that would add a ClockSinkNode and automatically drive the ModuleImp's implicit clock and reset using that node's resulting clock bundle.~~ This is effectively covered by extending `ClockSinkDomain`. 
**Type of change** other enhancement
> Avoid Subsystem Implicit Clock

- src/main/scala/rocket/DCache.scala
> D$: fix two noisy-drop performance bugs

- src/main/scala/rocket/PTW.scala
- src/main/scala/rocket/RocketCore.scala
- src/main/scala/tile/Core.scala
**Related issue**: contributed by @ncppd from https://github.com/chipsalliance/rocket-chip/pull/2743
Add `RocketCoreParameters.nL2TLBWays` to configure a set-associative L2TLB with invalid-first-then-PLRU replacement policy.
For now, keep the default direct-mapped (1-way) dimensions.
> PTW.scala: enabling configurable L2 TLB (sets/ways)

- src/main/scala/tilelink/Monitor.scala
- src/main/scala/tilelink/Parameters.scala
**Related issue**: follow-up to deprecation warnings introduced in https://github.com/chipsalliance/rocket-chip/pull/2505
**Impact**: API removal
the `expectsVipChecker` naming introduced in https://github.com/chipsalliance/rocket-chip/pull/2505 caused confusion, so going back to the "support*/emits*" and "Fast-or-Safe" naming schemes.
> TileLink warnings: edge.manager.supports*

- src/main/scala/rocket/ICache.scala
This modified `ccover` is guarded by `refill_done`, which will only cover the last beat corruption. This PR use `refillError` to fix this.
> fix a ccover bug in I$

- src/main/scala/util/ElaborationArtefactAnnotation.scala
**Related issue**: introduced by https://github.com/chipsalliance/rocket-chip/pull/2729
fix compile warning:
```
[warn] /rocket-chip/src/main/scala/util/ElaborationArtefactAnnotation.scala:80:27: unreachable code
[warn]       case Some(other) => throw new Exception(s"memory $target cannot be renamed to $other")
[warn]                           ^
```
> compile warning: ElaborationArtefactAnnotation remove unreachable code

- src/main/scala/rocket/DCache.scala
**Related issue**: introduced by https://github.com/chipsalliance/rocket-chip/pull/2555
fix compile warnings:
```
[warn] /rocket-chip/src/main/scala/rocket/DCache.scala:141:31: match may not be exhaustive.
[warn] It would fail on the following input: CreditedCrossing(_, _)
[warn]     val a_queue_depth = outer.crossing match {
[warn]                               ^
[warn] /rocket-chip/src/main/scala/rocket/DCache.scala:1064:32: match may not be exhaustive.
[warn] It would fail on the following input: CreditedCrossing(_, _)
[warn]     val beatsBeforeEnd = outer.crossing match {
[warn]                                ^
```
> compile warning: DCache CreditedCrossing

- src/main/scala/devices/debug/Debug.scala
- src/main/scala/devices/debug/DebugTransport.scala
- src/main/scala/tile/LazyRoCC.scala
- src/main/scala/tilelink/Monitor.scala
- src/main/scala/util/ReadyValidCancel.scala
**Related issue**: follow-up to https://github.com/chipsalliance/chisel3/pull/1448
remove `@chiselName` pragma from all `import chisel3._` files
> chisel3.experimental.chiselName is no longer necessary with chisel3._

- src/main/scala/util/ReadyValidCancel.scala
**Impact**: This should have had no impact so far, because I am unaware of anything instantiating this with `rr = true`.
fix `ReadyValidCancelRRArbiter` output value when Round-Robin parameter `rr = true`
> ReadyValidCancelRRArbiter: round-robin select wrong rotate

- src/main/scala/groundtest/TraceGen.scala
Previously, the TraceGen unit performed fences by simply waiting for all inflight loads/store to be ack'd. Since this does not perform a microarchitectural fence in the target memory system, the resulting trace can appear to fail memory consistency checks. https://github.com/riscv-boom/riscv-boom/issues/524
The solution is to observe the signal indicating when the target memory system is ready for a fence.
> TraceGen should observe dmem.ordered when attempting a fence

- src/main/scala/tilelink/Monitor.scala
**Type of change**: bug report in assertion
**Impact**: We don't actually use this opcode anywhere in practice which is why no one has noticed.
TLMonitor was not checking against the correct opcode for a (so far unused) B channel message. Now it should check the right opcode.
> TLMonitor: wrong opcode is checked in (unused) B Channel Get message

- src/main/scala/system/Configs.scala
**Related issue**:  #2599
Add WithCoherentBusTopology to BaseFPGAConfig.  Fixing issue when trying to build rocket-chip for fpga.
> add WithCoherentBusTopology to BaseFPGAConfig

- src/main/scala/util/ReadyValidCancel.scala
**Impact**: functional change | no API modification
wrap `ReadyValidCancelRRArbiter` `nextSelectEnc` value using modulo when Round-Robin parameters `rr=true && !isPow2(n)`
> ReadyValidCancelRRArbiter: non-power-of-2 round-robin select

- src/main/scala/rocket/DCache.scala
When a store is immediately followed by a load to the same address,
and the load detects an ECC error (corresponding to the old contents),
the store fails to take effect.
> Fix a scratchpad ECC bug

- src/main/scala/rocket/DCache.scala
- src/main/scala/rocket/HellaCache.scala
- src/main/scala/rocket/TLB.scala
- src/main/scala/rocket/TLBPermissions.scala
**Related issue**: revert https://github.com/chipsalliance/rocket-chip/pull/1039/commits/1867a5b226f29604f4c724d664cac18f485fb51f from https://github.com/chipsalliance/rocket-chip/pull/1039
The Rocket TLB calculates `cacheable = supportsAcquireT`, but Diplomacy calculates `cacheable = supportsAcquireB`.
This cacheability mismatch risks causing problems.
1. Set `cacheable = supportsAcquireB`.
2. Require that cacheable **writeable** memory `supportsAcquireT`.
Cacheable ROMs: treat acquire-able read-only memory as cacheable.
> Core/TLB: cacheable when supportsAcquireB

- src/main/scala/rocket/RocketCore.scala
Fixes an x-prop issue: looks like there is an assertion in the core which fires because the scie decoder outputs are x. These outputs depend on the instruction, coming in. As this is the first clock cycle the instruction is also x.
> Suppress SCIE assertion when instruction not valid

- src/main/scala/rocket/ScratchpadSlavePort.scala
Don't let D$ req.cmd field become X, or else it'll make req.ready become X, which confuses the Rocket core.
Wrong D$ command was sent on first slave-port access.
> Fix x-prop issue in ScratchpadSlavePort

- src/main/scala/rocket/ICache.scala
ITIM writes are implemented as RMW operations and so cause ITIM reads.
Thus, initializing the ITIM can cause Xs to leak out.  But full-word ITIM writes don't need to be RMW, so we can suppress the Xs from leaking out in that special case.
Conveniently, we already require that TIMs be initialized with full-word writes for ECC purposes, so preventing the Xs from leaking out only in the full-word write case suffices.
> Suppress an X-propagation in Rocket ITIM

- src/main/scala/rocket/RocketCore.scala
rs1[4] was being ignored in determining whether the access was a read or a write.  Other CSR instructions are unaffected.  RV32I/RV64I cores are unaffected.  Only Rocket with RV32E.
> Fix CSRRSI/CSRRCI in RV32E cores

- src/main/scala/tilelink/WidthWidget.scala
Widening WidthWidgets contain an uninitialized data register. The first transaction through the widget may propagate that register's contents on the bus, which is logically correct but can propagates a X, violating our constraint that we never provide X in the payload of a valid xact.
Fix by propagating in.bits.data, rather than the register, until the register has been written at least once. This is cheaper than resetting the register.
> Prevent TLWidthWidget from generating X outputs

- src/main/scala/rocket/DCache.scala
TileLink includes these message ordering rules:
> Release
> Once the Release is issued, the master should not issue a ProbeAck, ProbeAckData, Acquire, Get, Put, ArithmeticData, LogicalData, or further Release on the block until it receives a ReleaseAck from the slave acknowledging completion of the writeback.
**Related issue**: The Rocket/Bullet DCache relaxed this in https://github.com/chipsalliance/rocket-chip/pull/2696 to allow a ProbeAck or Acquire to overtake a Release, but not overtake a ReleaseData.
> DCache does not block Acquire/ProbeAck by outstanding Release

- src/main/scala/rocket/TLB.scala
**Related issue**: After https://github.com/chipsalliance/rocket-chip/commit/228498ded61a85d8888ca1748facfa5f4dd26893, the `TLBEntry.getData(vpn)` function creates a new `OptimizationBarrier` module each time it is called, three times per entry.  This results in more generated Verilog submodules with the same inputs:
```
OptimizationBarrier ppn_data_barrier(_1..15)
OptimizationBarrier entries_barrier(_1..15)
OptimizationBarrier normal_entries_barrier(_1..15)
```
Call the `TLBEntry.getData(vpn)` function once per entry per search request port, then pass that result as an argument to other functions. This deduplicates the above to these generated Verilog submodules:
```
OptimizationBarrier entries_barrier(_1..23)
``` …
> TLB: Deduplicate down to one OptimizationBarrier per TLBEntry

- src/main/scala/amba/axi4/Bundles.scala
- src/main/scala/system/TestHarness.scala
This is the work around for TestHarness io cannot be named correctly chipsalliance/chisel3#1862.
But I think this should be safe to merge.
**Related issue**: chipsalliance/chisel3#1862
> convert TestHarness to chisel3, work around compatibility mode naming issue.

- src/main/scala/util/GenericParameterizedBundle.scala
This PR removes `cloneType` implementation in `GenericParameterizedBundle`, which should be the fix for chipsalliance/chisel3#1858.
This PR should be merged in Chisel 3.4.3/3.5 bumpping PR.
chipsalliance/chisel3#1858
deprecate `GenericParameterizedBundle`
> Deprecate GenericParameterizedBundle for autoclonetype2

- src/main/scala/tilelink/ToAXI4.scala
https://github.com/chipsalliance/rocket-chip/blob/025184e1a0fdd8338eb0f66ad9ab33587b619854/src/main/scala/tilelink/ToAXI4.scala#L205-L209
The current arbitration policy in the TLToAXI4 converter always prioritizes AXI4 r-channel responses. This policy leads to starvation for clients waiting for a AccessAck, when the AXI4 r-channel is saturated. For example, a system where the L2 cache evicts a line, then saturates AXI4 with reads, may stall indefinitely waiting for a WriteAck.
This PR implements an alternate policy that stalls for b-channel acks if the b-channel ack has been blocked for 7 consecutive cycles. This is just one possible approach to avoid the indefinite stall. 
**Type of issue**: bug report 
> TLToAXI4 should not block AXI4-b writeacks indefinitely

- common.sc
Mill implemented its own `testOnly` in https://github.com/com-lihaoyi/mill/commit/838e3259921718778b01b554455bbf1942865cb5 , this PR fixed compile in mill 0.9.8.
> remove testOnly, since upstream implemented it.

- src/main/scala/rocket/PTW.scala
**Related issue**: introduced by https://github.com/chipsalliance/rocket-chip/pull/2748
hoist `l2_plru.way(r_idx)` onto a register before L2TLB refill `wmask`
> PTW timing: L2TLB PLRU select write way

- src/main/scala/rocket/PTW.scala
**Related issue**: my timing fix from #2856 was incomplete
hoist `r_valid_vec` onto a register before L2TLB refill `wmask`
> PTW: timing L2TLB valid select write way

- src/main/scala/diplomaticobjectmodel/logicaltree/RocketLogicalTreeNode.scala
- src/main/scala/rocket/CSR.scala
- src/main/scala/tile/Interrupts.scala
The NMI arch spec is being prepared for submission to RISC-V International. As part of that, the UNMI feature has been removed from it.  External IO unmi_* were removed and all internal implementation referring to unmi was removed. Most changes are in the CSR modules where NMI is processed.
The latest NMI spec has added a bit `mnie` (not `nmie`) to `mnstatus`.  This bit reflects the internal `rnmie` state. `rnmie` is set at reset, is cleared when an NMI is taken, and is set by executing `mnret` at the end of the NMI handler (unchanged by this PR). Now `rnmie` can also be read and set by software so that nested NMIs …
> NMI spec updates: removed UNMI, added new mnie bit to mnstatus

- src/main/scala/rocket/PTW.scala
**Related issue**: resolves https://github.com/chipsalliance/rocket-chip/issues/2895
Page fault on "table" entry (RWX=0) with D/A/U bit set.
Well-behaved software should have no problem.
Software that was setting these reserved bits will start getting unexpected page faults.
> PTW: Non-leaf PTEs with D/A/U==1 are reserved

- src/main/scala/rocket/TLB.scala
PTW fault prioritization: if a PTW _doesn't_ finish with a valid address, then we cannot check if the memory address has side effects to take a misaligned exception
> PTW fault should be higher priority than misaligned exception

- src/main/scala/rocket/Frontend.scala
- src/main/scala/rocket/ICache.scala
- src/main/scala/tilelink/ToAHB.scala
**Related issue**: follow-up to https://github.com/chipsalliance/rocket-chip/pull/2386
We don't believe anything inside Rocket-chip was depending on this.
If somebody was using the Cacheable bit from a Non-cacheable AXI or AHB port, then this would be an errata.
The AMBA AXI protocol specification includes a section “Mismatched memory attributes” which says:
> Multiple agents that are accessing the same area of memory, can use mismatched memory attributes. However, for functional correctness, the following rules must be obeyed:
> - All masters accessing the same area of memory must have a consistent view of the Cacheability …
> AmbaProt memory type for non-cacheable fetches should be "Normal Non-cacheable Bufferable"

- src/main/scala/groundtest/Tile.scala
Makes it easier to test alternative implementations of HellaCache
> Update GroundTest to use generic BuildHellaCache key

- src/main/scala/rocket/PTW.scala
- src/main/scala/rocket/TLB.scala
**Related issue**: resolves https://github.com/chipsalliance/rocket-chip/issues/2795
needs riscv-software-src/riscv-isa-sim#874 and riscv-software-src/riscv-isa-sim#875 to fully correctly match RTL behavior.
`PTE_RSVD` was introduced into Spike in riscv-software-src/riscv-isa-sim#750
Reserved PTE bits report page fault instead of access exception.
Add an additional bit `pf` to `PTWResp` and `TLBEntryData` to pipe this through.
> Priv 1.12: PTW page fault instead of access exception if PTE reserved bit set

- src/main/scala/rocket/TLB.scala
**Related issue**: follow-up fix to https://github.com/chipsalliance/rocket-chip/pull/2913
An Access Exception (AE) on a Page Table Walk (PTW) should not set Page Fault (PF) response from the TLB.
> TLB reporting page fault instead of PTW access fault

- src/main/scala/rocket/RocketCore.scala
**Impact**:
Avoid false RAW/WAW hazards for integer instructions that access an `x` register whose numeric specifier coincides with the `f` register destination of an earlier floating-point instruction.
Example testcase:
```asm
fmv.w.x f10, zero
addi x10, x10, 1
```
It appears this phenomenon is not uncommon in compiled code since gcc's register allocator frequently tends to use `a0-a7` (`x10-x17`) and `fa0-fa7` (`f10-f17`) as temporaries.
> Fix false-positive FP data hazards

- src/main/scala/rocket/TLB.scala
**Related issue**: after https://github.com/chipsalliance/rocket-chip/pull/2841
The `sectorHit` function in the TLB is used for PLRU updates and inserting new entries in the same sector.
The `TLBEntry.hit` function includes both `vpn` and `virtual` arguments to distinguish between HS/HU or VS/VU entries, but the `sectorHit` function does not.  This won’t cause problems when inserting new entries in the same sector, but can allow misses due to mismatching Virtual bit to still update the PLRU as if they were a hit.
1. The fix is to add a `virtual` argument to the `TLBEntry.sectorHit` function.
2. A further optimization after the fix is to move the `v` bit from …
> Hypervisor: L1TLB PLRU updated by sector hit mismatching Virtual bit

- src/main/scala/amba/axis/Bundles.scala
* AXISBundleBits extends off BundleMap which is of type Record and therefore needs cloneType
* resolves a user issue that can be seen at the repo in this post after compiling the current main's rocket-jar:
* https://stackoverflow.com/questions/72043687/implementing-a-diplomatic-axi-stream-interface-in-chisel-bundlemap-clonetype-e
* git repo: https://github.com/jurevreca12/temp_dspblock_example
* git commit: aca81ab9df437e8cea7fa8abd361b6bab7f40326
* note: replace `lib/rocketchip.jar` with a compiled `rocketchip.jar` from main
* bug fixed by using a `rocketchip.jar` generated from this PR's branch
Signed-off-by: Michael Etzkorn <michael-etzkorn@sage.micro.com>
https://stackoverflow.com/questions/72043687/implementing-a-diplomatic-axi-stream-interface-in-chisel-bundlemap- …
> [AXISBundleBits] re-add clonetype override

- src/main/scala/subsystem/Configs.scala
- src/main/scala/util/ClockGate.scala
I found the EICG_wrapper.v file was not copied to the build directory automatically, the original flow works because it uses rc_resource_dir as the include path.
> Bind Verilog path with EICG_wrapper

- src/main/scala/rocket/CSR.scala
From https://github.com/chipsalliance/rocket-chip/issues/2980#issuecomment-1123218779, make vsstatus.xs read only, and hard-wired to dirty when RoCC is enabled.
> Disallow writes to VSSTATUS.XS

- src/main/scala/rocket/CSR.scala
From https://github.com/chipsalliance/rocket-chip/issues/2980#issuecomment-1123218779, correct the  rocc_illegal signal to use vsstatus.xs field.
> fix rocc_illegal under VS mode

- src/main/scala/rocket/RocketCore.scala
From https://github.com/chipsalliance/rocket-chip/issues/2987, disallow to select both hyper and rve
> only one of hypervisor and rve can be selected

- common.sc
Bump mill's Chisel from 3.5.0 to 3.5.3 (sbt has already bumped Chisel to 3.5.2) which includes a [Chisel decoder update](https://github.com/chipsalliance/chisel3/commit/28eef17430d8bbca2765b5a2b0ab0337f7484840), so the tests related to Chisel's decoder ([generatorTests.StageGeneratorSpec](https://github.com/chipsalliance/rocket-chip/blob/master/src/test/scala/generatorTests/StageGeneratorSpec.scala) and [#2991 sanitytests.VerilatorTest](https://github.com/chipsalliance/rocket-chip/pull/2991)) can be performed correctly.
Otherwise, the test would fail like below:
```
StageGeneratorSpec:
Test
- should pass *** FAILED *** …
```
> Bump mill's Chisel to 3.5.3

- src/main/scala/rocket/Frontend.scala
- src/main/scala/rocket/RocketCore.scala
> This is a bug in the hypervisor implementation populating `htval2` starting from https://github.com/chipsalliance/rocket-chip/pull/2841/commits/ebe27d681043f6df9393d9ff816db54cd406330a.
> 
> The core isn’t making forward progress because the ITLB is thrashing (it only has one copy of the GPA register, hence can’t support multiple speculative accesses that each need their own GPAs).  The resulting ITLB misses result in D$ conflict misses, which prevent an older load instruction from making progress.
> 
> The bug can only manifest when executing within a guest.  When not using the hypervisor extension, it can’t occur.
> 
> The RTL fix is to disable speculative ITLB refill unless recent forward progress has been made (perf impact should be imperceptible).
> 
> Andrew was …
> Hypervisor forward progress: prevent ITLB miss fault PTW thrashing DCache

- src/main/scala/rocket/CSR.scala
- src/main/scala/rocket/PTW.scala
**Related issue**: Fix the bit-width out of range when both Sv57 and hypervisor are enabled, causing vpnBits/vaddrBits can be larger than the actual width of signal. A simple fix is maxing out the width when LSBs is being extracted. 
**Type of change**: bug report/fix
**Impact**: bug fix
> [ptw/fix] fix bit width mismatch when Sv57 is enabled

- src/main/scala/rocket/ICache.scala
**Related issue**: Documentation
Add documentation for Rocket-Chip Instruction Cache, based on [a612389](https://github.com/chipsalliance/rocket-chip/pull/3001/commits/a612389f87fdb72431d8646715e62a158ba51916).
My work are listed as followed:
1. Fix typo
2. Reorganization to improve readablity
3. Delete some inline comments and 'todo' to avoid presenting too much details
> Add documentation for ICache

- scripts/toaxe.py
As part of Chipyard's https://github.com/ucb-bar/chipyard/pull/1163 it was noticed that the `toaxe.py` script is Python2 specific. This PR runs `2to3` on the file and removes an unneeded import for `sets` so that this is now Python3 compatible.
> Convert toaxe.py to Python3

- src/main/scala/devices/debug/Periphery.scala
**Related issue**: chipsalliance/chisel3#2567
calcify the name of TileLink Debug Module to fix bug since chipsalliance/chisel3#2567 get merged.
For detail bug report, see: https://github.com/chipsalliance/playground/runs/7890002567
> change debug module name to tlDM.

- src/main/resources/vsrc/RoccBlackBox.v
Fix 1: incorrect signal assigned to `rocc_resp_bits_rd` in `RoCCBlackBox`; 
Fix 2: incorrect `RoccBlackBox` behavior after logic synthesis (tested for Xilinx FPGA with Vivado).
`src/main/resources/vsrc/RoccBlackBox.v` is modified to fix incorrect signal assignment and behavior in synthesis result
> RoccBlackBox fix 

- src/main/scala/rocket/ALU.scala
> refactor ALU.scala to chisel3 style

- src/main/scala/rocket/Breakpoint.scala
Refactor Breakpoint.scala to chisel3 style
> refactor Breakpoint to chisel3.

- src/main/scala/rocket/PMP.scala
Refactor PMP.scala to chisel3 style.
> refactor PMP to chisel3.

- src/main/scala/rocket/Consts.scala
Refactor Consts.scala to chisel3 style.
> refactor Consts to chisel3.

- src/main/scala/rocket/PTW.scala
**Related issue**: further follow-up to https://github.com/chipsalliance/rocket-chip/pull/3006
**Type of change**: feature
**Impact**: functional addition (no impact on existing code)
Fix the bit-width out of range when Sv57 is enabled, causing vpnBits/vaddrBits can be larger than the actual width of signal. A simple fix is maxing out the width when LSBs is being extracted.
> PTW: pte_cache_addr vpn_idxs shift/pad/extract for Sv57

- src/main/scala/rocket/SimpleHellaCacheIF.scala
Refactor SimpleHellaCacheIF.scala to chisel3 style.
> refactor SimpleHellaCacheIF to chisel3.

- .github/workflows/continuous-integration.yml
**Related issue**:  #3025
This PR open the check for chisel3_port branch, the upcoming chisel3 port PR will be opened against which. After LEC is done, it will be pushed to master.
> add CI check for chisel3_port branch

- src/main/scala/devices/debug/Debug.scala
- src/main/scala/devices/debug/Periphery.scala
- src/main/scala/devices/debug/dm_registers.scala
Documentation
other enhancement
no functional change
implementation
Add more micro-architecture details in documentation for debug module.
Fix format and typo issues in documentation.
> Improved Debug Module documentation 

- src/main/scala/groundtest/DummyPTW.scala
- src/main/scala/groundtest/GroundTestSubsystem.scala
- src/main/scala/groundtest/Status.scala
- src/main/scala/groundtest/TestHarness.scala
- src/main/scala/groundtest/Tile.scala
- src/main/scala/groundtest/TraceGen.scala
Convert groundtest subdirectory to chisel3
> feat: convert groundtest to chisel3

- src/main/scala/util/Timer.scala
Refactor Timer.scala to chisel3 style.
> refactor Timer to chisel3.

- src/main/scala/util/Arbiters.scala
> Refactor util/Arbiters to chisel3

- src/main/scala/util/ReorderQueue.scala
Refactor ReorderQueue.scala to chisel3 style.
> refactor ReorderQueue to chisel3.

- src/main/scala/util/HellaQueue.scala
> Port util/HellaQueue.scala to Chisel3

- src/main/scala/stage/phases/AddDefaultTests.scala
- src/main/scala/subsystem/Configs.scala
- src/main/scala/subsystem/HasTiles.scala
- src/main/scala/subsystem/RocketSubsystem.scala
`RocketTilesKey` and `RocketCrossingKey` are legacy `Fields`, the new `TilesLocated` and `InstantiableTileParams` API is more generalized for multi-tile systems.
This PR removes those keys.
> Remove RocketTilesKey, RocketCrossingKey

- src/main/scala/util/HellaQueue.scala
A regression was introduced in #3108 but was missed by CI. This PR tries to fix it.
We may want to add test cases for all modules by simply instantiating them.
> Fix HellaQueue in Chisel3

- scripts/RocketSim.cfg
`-rtos riscv` is deprecated. It works with the openocd in rocket-tools but the latest openocd and riscv-openocd both do not recognize this option.
The openocd in rocket-tools points to a version after this commit
https://github.com/riscv/riscv-openocd/commit/50d0c2f67c1c32cb58d0a28f88e49e15623dcdc7
but it is before the removal of rtos riscv
https://github.com/riscv/riscv-openocd/commit/d52e4668a60212524b3d29b92b47cc21c5317b66
When I was migrating the CI (see https://github.com/chipsalliance/playground/pull/46) to the latest openocd, it will not recognize this option. The openocd from `riscv-openocd` also does not work with this option.
This commit still works with the current CI as rocket-tools support this option.
**Impact**: API …
> Replace deprecated rtos riscv in openocd cfg

- src/main/scala/rocket/PTW.scala
**Impact**: Using same explicit bit-width for page cache reference/assignment to avoid incorrect MSB /reference assignment
Bug fix: Missing MSB assignment of page cache tag result in hfence.gvma has no ability to invalidate corresponding page cache entry which tag with v bit set. Padding the pte_cache_addr to `tag width - 1` fixs this problem
> [fix] missing PTE Cache tag MSB caused by width mismatch

- src/main/scala/rocket/DCache.scala
On systems without atomics a dummy bundle is created. After switching to chisel3 the explicit tieoff is required to prevent an unconnected wire error during verilog generation.
> Tieoff atomics bundle in DCache.

- src/main/scala/tile/FPU.scala
floatTypes should be a def, otherwise minFLen/fLen may be 0 when the expression is evaluated
> Fix floatTypes in HasFPUParameters

- src/main/scala/rocket/RVC.scala
This commit changes how compressed move instructions are decoded. It adds an useAddiForMv argument to RVCDecoder to allow the user to specify how C.MV is decoded.
From RISC-V spec, C.MV expands to a different instruction than the canonical MV pseudoinstruction, which instead uses ADDI. Implementations that handle MV specially, e.g. using register-renaming hardware, may find it more convenient to expand C.MV to MV instead of ADD, at slight additional hardware cost.
We add a configuration option for decoding C.MV to ADDI.
> rvc: allow decode C.MV to ADDI with useAddiForMv

- src/main/scala/rocket/CSR.scala
- src/main/scala/rocket/RocketCore.scala
- src/main/scala/tile/BaseTile.scala
- src/main/scala/tile/Core.scala
Previously misa always reported `rv64gcx`. Now misa will have the 'X' field set only if customIsaExt is defined, and the DTS string will contain custom extensions. Rocket is now `rv64gc_Xrocket` in the DTS. Could this cause any issues in  DTS-parsing code?
> Add interface for setting custom ISA strings in DTS

- src/main/scala/tilelink/Monitor.scala
Bug fix. Per the spec: 
> Because Channel C responses to Channel B requests are routed to a single slave and uniquely
identified to an ongoing operation based on c address, we can further relax the uniqueness
restriction on Channel B requests, requiring only that the combination of b source and b address
be uniquely inflight. This relaxation is necessary in order to simultaneously probe multiple masters
on the same address, while also probing the same master on multiple addresses. Channel C 
responses may use any c source associated with the sender; this signal is ignored for those
message types.
> Don't check probeacks in TLMonitor.legalizeCDSource

- regression/Makefile
- src/main/scala/diplomacy/Clone.scala
- src/main/scala/diplomacy/LazyModule.scala
- src/main/scala/diplomacy/Nodes.scala
- src/main/scala/subsystem/Configs.scala
- src/main/scala/subsystem/HasTiles.scala
- src/main/scala/system/Configs.scala
This PR implements support for cloning arbitrary LazyModules. The cloned module still performs diplomatic elaboration, but its `LazyModuleImp` is not evaluated. The empty `Dangle`s from diplomatic elaboration are matched with the IOs of the `AutoBundle` from the cloned record of the prototype module.
**Impact**:  API addition (no impact on existing code) 
> Support LazyModule cloning

- src/main/scala/devices/debug/Debug.scala
- src/main/scala/diplomacy/Parameters.scala
- src/main/scala/jtag/JtagShifter.scala
- src/main/scala/jtag/JtagTap.scala
- src/main/scala/regmapper/RegMapper.scala
- src/main/scala/rocket/CSR.scala
- src/main/scala/rocket/NBDcache.scala
- src/main/scala/tilelink/Atomics.scala
- src/main/scala/tilelink/Broadcast.scala
- src/main/scala/tilelink/Fuzzer.scala
- src/main/scala/tilelink/SourceShrinker.scala
- src/main/scala/tilelink/ToAHB.scala
- src/main/scala/util/AsyncQueue.scala
- src/main/scala/util/LanePositionedQueue.scala
- src/main/scala/util/package.scala
**Related issue**: chipsalliance/chisel3#2758
fix https://github.com/chipsalliance/chisel3/pull/2758
+ Remove parenthesized forms of asUInt(), asSInt(), orR(), andR(), zext();
> Remove chisel3 deprecated code

- .github/workflows/mill-ci.yml
- build.sc
**Related issue**: #3191, #3192, #3193
Cherry-picked commits from them to test CI. Especially, #3193 is for passing ebreak test. These commits will be removed once they have been merged. The successful running of CI introduced by this PR may indicate that these PR could be merged.
This CI may finish running in a reasonable time. In my machine, running arch-test without floating point finished in one hour.
Add new CI on riscv-arch-test based on mill
> Add CI on riscv-arch-test based on mill

- src/main/scala/rocket/DCache.scala
**Related issue**: #3165
Fix PMA for DCache when there are requests from both cpu and tlb_port
> Fix DCache pma_checker req connection

- src/main/scala/diplomacy/LazyModule.scala
The original design directly calls toString method, which generates strange wire/module name.
For example:
```scala
new SimpleLazyModule {
val scop = LazyScope {
LazyModule(new SimpleLazyModule())
}
}
```
```verilog
module SimpleLazyModule_2(
input   clock,
input   reset
);
wire  ValNamescop_clock; // @[LazyModule.scala 436:27]
wire  ValNamescop_reset; // @[LazyModule.scala 436:27]
SimpleLazyModule_1 ValNamescop ( // @[LazyModule.scala 436:27]
.clock(ValNamescop_clock),
.reset(ValNamescop_reset)
);
assign ValNamescop_clock = clock;
assign ValNamescop_reset = reset;
endmodule
```
This patch will generate the real name of the lazyscope:
```verilog
module SimpleLazyModule_2(
input   clock, …
```
> Generate correct lazyscope name

- src/main/scala/rocket/CSR.scala
Ref to https://github.com/riscv/riscv-isa-manual/commit/51522f98b5cae989c7d161e00b20a08483a2301e
However this change does not only affect `ebreak` so I need to check further.
**Related issue**: https://github.com/chipsalliance/rocket-chip/pull/3191#issuecomment-1367788856
Populate tval with pc when ebreak
> Populate tval with pc when ebreak

- src/main/scala/tilelink/RegisterRouter.scala
> RegDescsJson should use actual name of devices instead of "device"

- .gitignore
- src/main/scala/rocket/CSR.scala
- src/main/scala/rocket/RocketCore.scala
- src/main/scala/tile/Core.scala
Rocket can't pass through wdata due to OOO write back, but other cores may support this.
> Support passing wdata through TracedInstruction

- src/main/scala/tile/BaseTile.scala
For new version of the unprivileged spec, zicsr/zifencei have been separated out of I (base extension). Rocket always supports them. So should other cores that have the support of the old base extension.
Zihpm (also zicntr), however, is an internal uarch for rocket so I wonder if this isaDTS will affect other cores or not.
**Related issue**: https://github.com/chipsalliance/rocket-chip/pull/3202#discussion_r1064312736
**Impact**: API addition
Add H/Zicsr/Zifencei/Zihpm/Zfh to dts
> Add more extensions to dts

- src/main/scala/rocket/CSR.scala
The RISC-V Privileged ISA spec says:
> When V=0, a write to vsatp with an unsupported MODE value is ... the fields of vsatp are treated as WARL in the normal way. However, when V=1, a write to satp with an unsupported MODE value is ignored and no write to vsatp is effected.
We were not handling the V=1 case.
> CSR: writes to vsatp.ASID should be mode-checked

- src/main/scala/rocket/TLB.scala
**Impact**: functional fix for the failing scenario: `vstage1_en=0`, `bad_va=0` and `bad_gpa=1`
L1TLB: concatenate the `bad_gpa` bit on top of the bad VA=GPA address instead of `bad_va`
> L1TLBs: fault response GPA bad_gpa/va

- vsim/Makefrag
- vsim/Makefrag-verilog
VPD/DVE is deprecated
VSIM simulators will now generate FSDB waveforms
> Swtich to FSDB in vsim

- src/main/scala/rocket/PTW.scala
The result of the `makeFragmentedSuperpagePPN` function was being used by a leaf-level 4KB page translation result, resulting in an incorrect VA-to-PA translation result.
The fix is to only use `makeFragmentedSuperpagePPN` if `count < (pgLevels-1)`.
> PTW: only makeFragmentedSuperpagePPN from superpage count level

- .github/workflows/mill-ci.yml
Because we moved from the persistent self-hosted runner setup to the ephemeral one, the old workaround for installing nix is no longer needed and is causing problems. This PR reverts the workaround.
> Fix GitHub Action unable to install nix

- .mergify.yml
This implements backporting using Mergify. It will be triggered when a PR meets the following conditions:
1. merged
2. base branch is `dev`
3. has the `backport` tag
When triggered, it will cherry-pick the commits of the current PR to create a new PR whose base branch is `master`, and the new PR will have the label `backporting`. If there are conflicts, it will also have a `conflicts` label.
**Related issue**: #3251 
> Backporting with Mergify

- src/main/scala/rocket/CryptoNIST.scala
- src/main/scala/rocket/IDecode.scala
- src/main/scala/rocket/RocketCore.scala
It is not rs2, it is imm
**Related issue**: #3255
**Impact**: Functionality will not change, as the original rs2 from regfile is not used. Performance may inprove as #3255 indicates.
Fix aes64ks1i decoding
> IDecode: Fix aes64ks1i imm decode

- src/main/scala/rocket/TLB.scala
This was introduced by "(185cac83) Add hypervisor extension (#2841)"
This is a dead code, as no circuit is producing and consuming this bit.
This was discovered when migrating Core.scala to chisel3, where strict checking was applied for IO and firrtl found this is not connected.
In the context of hypervisor extension, V bit, or _virtualization mode_, indicates whether the hart is currently executing in a guest.
For TLBReq, the V bit is needed as it affects the PTW thus TLB behavior on whether to do _Two-Stage Address Translation_.
However, the bit is not needed for TLBException. The exceptions (pf, gf, ae, ma) have no V=1/V=0 variants. Also, there is no point to add V bit for gf (guest page fault).
The io.resp.gf added below in the original patch also does not connect io.resp.gf.v. If …
> Remove redundant TLBExceptions V bit

- src/main/scala/util/IDPool.scala
+ Wrap `given` in backticks to use it as an identifier, which will become a keyword in Scala 3.
> Fix Werror: key word error `given`

- src/main/scala/tilelink/Xbar.scala
Running TileLink unit test `TLXbarUnitTestConfig` would result in FIRRTL error about `io.start` port of DUT being uninitialized:
`Xbar.scala:458:19: error: sink "dut.io_start" not fully initialized in module "TLRAMXbarTest"`
This fixes the issue by connecting them with the top module `UnitTestSuite`.
> Fix unconnected io.start for TLRAMXbarTest and TLMulticlientXbarTest

- src/main/scala/devices/debug/Periphery.scala
- src/main/scala/groundtest/GroundTestSubsystem.scala
- src/main/scala/interrupts/NullIntSource.scala
- src/main/scala/interrupts/package.scala
- src/main/scala/subsystem/HasTiles.scala
- src/main/scala/subsystem/RocketSubsystem.scala
- src/main/scala/system/TestHarness.scala
**Related issue**: Alternative implementation of #3276
> Relax dependencies on HasPeripheryDebug

- src/main/scala/rocket/BTB.scala
- src/main/scala/rocket/NBDcache.scala
- src/main/scala/rocket/PTW.scala
- src/main/scala/rocket/ScratchpadSlavePort.scala
- src/main/scala/rocket/TLB.scala
> Porting Chisel 2 to Chisel 3: rocket/

- .github/workflows/mill-ci.yml
Nix 2.14 was released with incompatibilities with cachix/install-nix-action.
This PR pins nix to 2.13.3 to avoid CI fails
See: https://github.com/cachix/install-nix-action/issues/161
> Pinning nix to 2.13.3 in github workflows

- src/main/scala/devices/tilelink/ClockBlocker.scala
- src/main/scala/devices/tilelink/Deadlock.scala
- src/main/scala/devices/tilelink/Error.scala
- src/main/scala/devices/tilelink/MaskROM.scala
- src/main/scala/devices/tilelink/MasterMux.scala
- src/main/scala/devices/tilelink/PhysicalFilter.scala
- src/main/scala/devices/tilelink/Plic.scala
- src/main/scala/devices/tilelink/TestRAM.scala
- src/main/scala/devices/tilelink/Zero.scala
> Porting Chisel 2 to Chisel 3: devices/

- src/main/scala/amba/axi4/UserYanker.scala
> Porting Chisel 2 to Chisel 3: amba/axi4/UserYanker.scala

- src/main/scala/rocket/TLB.scala
VS-mode (Stage-1) tera/giga/peta-page entries can be fragmented by Stage-2 superpage entries, and need the same TLB Invalidate (SFENCE.VMA / HFENCE.VVMA) matching based on VS-mode (Stage-1) page size.  Fix in the L1TLBs (ITLB and DTLB): superpage entries conservatively match when `fragmented_superpage`, just as we already do in the leaf page sectored entries.
> L1TLB: VS-mode SFENCE misses tera/giga-page entries fragmented superpages

- src/main/scala/tile/LazyRoCC.scala
> Change CharCountRoCC Example to use dcacheParams

- build.sc
`riscv-tests.suite[]` wont compile
Before
```
$ mill resolve riscv-tests.suite._
[1/1] resolve 
riscv-tests.suite[]
riscv-tests.suite[mt]
riscv-tests.suite[rv32mi-p-lh]
riscv-tests.suite[rv32mi-p-lw]
riscv-tests.suite[rv32mi-p-sh]
...
```
After
```
$ mill resolve riscv-tests.suite._
[1/1] resolve 
riscv-tests.suite[mt]
riscv-tests.suite[rv32mi-p-lh]
riscv-tests.suite[rv32mi-p-lw]
riscv-tests.suite[rv32mi-p-sh]
...
```
> mill: fix empty cross arg for riscv-tests.Suite

- src/main/scala/rocket/RocketCore.scala
- src/main/scala/tile/BaseTile.scala
The `encodeVirtualAddress` function in the cache pipeline relies on setting the sign-extended-mask extra bit to the opposite value, but the `badGPA` (i.e. `badVA(false)`) function in the ITLB/DTLB ignores the sign-extended-mask check for GPA when stage-1-**disabled** and stage-2-enabled.
So, when a VA (a.k.a. GPA in this mode Sv39x4) has bits[63:41]!=0 and bit[40]==1, the `encodeVirtualAddress` function sets bit [41]==0, which passes the `badGPA` (i.e. `badVA(false)`) function check.
> Hypervisor: encodeVirtualAddress extra MSB to canonicalize VS-disabled

- README.md
**Type of change**: documentation improvement
Update 'IDEs Support' section in README
> Update 'IDEs Support' section in README

- common.sc
Relying on chisel snapshot is causing a lot of pain for rocket chip and its dependencies like hardfloat/inclusive-cache/blocks, especially chisel master now removes Chisel and moves Cat into chisel3._. It even breaks the CI for PRs of last week.
In the dev meeting it is decided that we should rely on 3.6 instead of snapshot.
> Use chisel 3.6 rc2 instead of SNAPSHOT

- src/main/scala/rocket/DCache.scala
- src/main/scala/util/AsyncResetReg.scala
- src/main/scala/util/CreditedIO.scala
- src/main/scala/util/Frequency.scala
- src/main/scala/util/GenericParameterizedBundle.scala
- src/main/scala/util/HeterogeneousBag.scala
- src/main/scala/util/IdentityModule.scala
- src/main/scala/util/LCG.scala
- src/main/scala/util/LatencyPipe.scala
- src/main/scala/util/Misc.scala
- src/main/scala/util/MultiWidthFifo.scala
- src/main/scala/util/PSDTestMode.scala
- src/main/scala/util/Property.scala
- src/main/scala/util/RationalCrossing.scala
- src/main/scala/util/ShiftReg.scala
> Porting Chisel 2 to Chisel 3: util/

- src/main/scala/tilelink/Atomics.scala
- src/main/scala/tilelink/Broadcast.scala
- src/main/scala/tilelink/Buffer.scala
- src/main/scala/tilelink/BusWrapper.scala
- src/main/scala/tilelink/CacheCork.scala
- src/main/scala/tilelink/Delayer.scala
- src/main/scala/tilelink/Edges.scala
- src/main/scala/tilelink/ErrorEvaluator.scala
- src/main/scala/tilelink/FIFOFixer.scala
- src/main/scala/tilelink/Filter.scala
- src/main/scala/tilelink/Fragmenter.scala
- src/main/scala/tilelink/Fuzzer.scala
- src/main/scala/tilelink/Isolation.scala
- src/main/scala/tilelink/Jbar.scala
- src/main/scala/tilelink/Map.scala
- src/main/scala/tilelink/Metadata.scala
- src/main/scala/tilelink/Parameters.scala
- src/main/scala/tilelink/PatternPusher.scala
- src/main/scala/tilelink/RAMModel.scala
- src/main/scala/tilelink/RationalCrossing.scala
- src/main/scala/tilelink/RegisterRouter.scala
- src/main/scala/tilelink/RegisterRouterTest.scala
- src/main/scala/tilelink/SourceShrinker.scala
- src/main/scala/tilelink/ToAHB.scala
- src/main/scala/tilelink/ToAXI4.scala
> Porting Chisel 2 to Chisel 3: tilelink/

- src/main/scala/rocket/RocketCore.scala
- src/main/scala/tile/BaseTile.scala
The same change as #3332, but rebase to dev branch.
The Linux Kernel requires letters in the riscv,isa string in the device tree must be all lowercase to simplify parsing. [see here](https://github.com/torvalds/linux/blob/v6.3/Documentation/devicetree/bindings/riscv/cpus.yaml#L82)
However, rocket-chip will produce an ISA string with uppercase letters will cause the kernel to misbehave. Especially when using defconfig Linux with rocket-chip without FPU, the ISA string parser will confuse the current kernel that the CPU has "f" from "Zifencei", and the kernel will panic at `__fstate_restore` due to illegal instruction exceptions.
I tried to patch the Linux Kernel, but a maintainer thinks it will make the device tree have no backward compatibility. In my opinion, the rocket-chip should be …
> all isaDTS strings to lowercase

- src/main/scala/rocket/NBDcache.scala
+ replace `m _` with `() => m` in the method without a parameter list and by-name params;
> Fix Werror: replace `m _` with `() => m` in param less method

- src/main/scala/amba/axi4/RegisterRouter.scala
In legacy code it is ok to clone a Wire using Wire()
now the requirement is more strict and WireDefault is needed
The Output is added for code style consistency
**Related issue**: #3059, #3324
> Fix AXI4 RegisterRouter on Wire Clone

- src/main/scala/tile/RocketTile.scala
- src/main/scala/tile/TilePRCIDomain.scala
This allow forcing insertion of boundaryBuffers even when no clock crossings are generated.
boundaryBuffers are also moved to within the Tiles, to simplify physical design.
> Improve boundaryBuffers API | move boundaryBuffers to within-Tile

- src/main/scala/tilelink/Filter.scala
Enables filtering out multiple ranges at once.
> Support TLFilter.mSubtract with multiple AddressSets

- scripts/debug_rom/debug_rom.S
- scripts/debug_rom/debug_rom_nonzero.S
Modern `encoding.h` has `CSR_DSCRATCH0` instead of `CSR_DSCRATCH`
> Update debug_rom source to use CSR_DSCRATCH0

- src/main/scala/rocket/RocketCore.scala
- src/main/scala/tile/BaseTile.scala
- src/main/scala/tile/Core.scala
- src/main/scala/tile/TilePRCIDomain.scala
- src/main/scala/util/Blockable.scala
An alternative approach to #3355, core implementations can set a custom `traceCustom` field to pull out extra information out of the `TraceBundle`.
@bgottschall does this look OK for you?
> Support custom bundles in Trace

- build.sc
- emulator/Makefile
- src/main/resources/csrc/debug_rob.cc
- src/main/resources/vsrc/debug_rob.v
- src/main/scala/rocket/CSR.scala
- src/main/scala/rocket/DebugROB.scala
- src/main/scala/rocket/RocketCore.scala
- src/main/scala/subsystem/Configs.scala
- src/main/scala/tile/FPU.scala
- vsim/Makefrag
The ROB is implemented in C++, and interfaced through DPI.
It is unsynthesizable, of course, but it lets us generate a wdata-enabled commit log, if desired.
This is useful for debugging.
> Add support for an unsynthesizable ROB to produce a TracedInstruction stream with wdata

- src/main/scala/util/AsyncQueue.scala
- src/main/scala/util/Crossing.scala
This makes AsyncQueue easier to use in other RawModules.
> Make AsyncQueue use Rawmodule

- src/main/scala/devices/debug/SBA.scala
Replace `.U(i)` with `.U.extract(i)`
> Fix Werror: bit extraction

- src/main/scala/interrupts/Nodes.scala
- src/main/scala/jtag/JtagStateMachine.scala
- src/main/scala/jtag/JtagTap.scala
- src/main/scala/subsystem/BaseSubsystem.scala
- src/main/scala/tilelink/Arbiter.scala
- src/main/scala/tilelink/AtomicAutomata.scala
- src/main/scala/tilelink/Buffer.scala
- src/main/scala/unittest/UnitTest.scala
- src/main/scala/util/ReadyValidCancel.scala
- src/main/scala/util/package.scala
+ add `()` to those empty argument list function call; 
> Fix Werror: empty argument list

- src/main/scala/rocket/TLB.scala
TLB: swap back so that `must_alloc` is decided by for the `amo_logical` term based on `!supportsLogical`, and similarly for `amo_arithmetic` based on `!supportsArithmetic`.
In practice, we don’t think this bug in the generator ever manifested in practice, because these supportsLogical and supportsArithmetic have always been the same in Diplomacy as far as we can recall.
> TLB: must_alloc swapped AMO Logical/Arithmetic

- src/main/scala/rocket/TLB.scala
**Related issue**: The L1TLB (ITLB or DTLB) erroneously applies the `vsstatus.SUM` check to the PTW returned PTE `U` bit, even when the PTW returned `ae_final && stage2 && !stage2_final`: an access exception on Stage-2 PTW for Stage-1 PTE, i.e. before the final Stage-1 PTW (and its included `U` bit) was completed.
L1TLB (ITLB and DTLB): add a new flop bit `ae_stage2` to OR into `stage1_bypass` when the PTW responds `ae_final && stage2 && !stage2_final`.
> TLB: vsstatus.SUM check should not apply to Stage-2 fault before Stage-1 response

- src/main/scala/rocket/CSR.scala
The rocket-chip `medeleg` CSR is intentionally designed to hold only legal values. Given that `usingHypervisor` is used to distinguish whether the hardware supports hypervisor extensions (as seen from the source code everywhere), we should use it for the delegable exceptions as well.
> CSR: optionally set delegable hypervisor exceptions

- src/main/scala/rocket/PTW.scala
For PTEs whose physical address is out-of-range, we need to set `ae_ptw` instead of `ae_final` to raise access-fault.
Because non-leaf PTEs will not have R or X bits set, `ae_final` will be overrided by page-fault exceptions.
See https://github.com/chipsalliance/rocket-chip/issues/3402#issuecomment-1614229185 for more information.
> PTW: set ae_ptw for out-of-range non-leaf PTEs

- src/main/scala/amba/axi4/Bundles.scala
- src/main/scala/devices/tilelink/PhysicalFilter.scala
- src/main/scala/interrupts/Bundles.scala
- src/main/scala/tilelink/AtomicAutomata.scala
- src/main/scala/tilelink/Bundles.scala
- src/main/scala/tilelink/RAMModel.scala
- src/main/scala/tilelink/ToAHB.scala
- src/main/scala/util/GenericParameterizedBundle.scala
Chisel compiler plugin provides autoclonetype.
> Remove GenericParameterizedBundle since we already have autoclonetype in chisel

- src/main/scala/rocket/CSR.scala
RISC-V ISA requires that `mconfigptr` must be implemented.
> CSR: add mconfigptr and default to zero

- src/main/scala/amba/axis/Bundles.scala
- src/main/scala/amba/package.scala
- src/main/scala/tilelink/RegisterRouter.scala
- src/main/scala/tilelink/ToAXI4.scala
- src/main/scala/util/BundleMap.scala
Implement `BundleMap` with new Connectable API.
Depends on #3451 
> New BundleMap

- build.sc
- common.sc
- overlay.nix
In this commit, I bumped mill to 0.11. And make chisel be able to cross aginst two versions: 3.6.0 and 5.0.0, which ease the downstream users(chipyard) to be able to stay and old version, but also pave the road of future Chisel 5 and Chisel 6 support in rocketchip.
depends on ucb-bar/berkeley-hardfloat#78
> Bump mill and Cross Compile Chisel

- src/main/resources/META-INF/services/firrtl.options.RegisteredLibrary
remove linting package from RegisteredLibrary since we have already removed the entire SFC in #3379 .
> remove linting package from RegisteredLibrary

- src/main/scala/rocket/Frontend.scala
- src/main/scala/rocket/HellaCache.scala
- src/main/scala/subsystem/Configs.scala
- src/main/scala/tile/L1Cache.scala
This is useful for designs with wide system interconnect, but narrow caches.
> Support rocket cache rowBits != sbusWidth

- src/main/scala/amba/ahb/Xbar.scala
- src/main/scala/amba/apb/Xbar.scala
- src/main/scala/amba/axi4/RegisterRouter.scala
- src/main/scala/amba/axi4/Xbar.scala
- src/main/scala/groundtest/DummyPTW.scala
- src/main/scala/groundtest/Tile.scala
- src/main/scala/rocket/HellaCache.scala
- src/main/scala/rocket/ICache.scala
- src/main/scala/rocket/NBDcache.scala
- src/main/scala/tilelink/Broadcast.scala
- src/main/scala/tilelink/Fragmenter.scala
- src/main/scala/util/BundleMap.scala
- src/main/scala/util/LatencyPipe.scala
Fixes before we can merge dev->master.
> Fixes for latest chisel

- src/main/scala/rocket/AMOALU.scala
This makes it a bit easier to use the StoreGen circuit. StoreGen shouldn't error if the `typ` argument is narrower than `maxSize` would normally permit.
> Make StoreGen support narrow typ field

- src/main/scala/tilelink/ToAXI4.scala
`flow` must be explicitly passed to `Queue.irrevocable` to avoid mismatching the arguments.
**Related issue**: #3287
> Fix the missing flow argument in TileLink/ToAXI4

- build.sc
Dev is removing it, for downstreams(SFC users) they can still work on the master branch.
> Remove Chisel 3.6 support

- src/main/scala/util/DelayQueue.scala
**Related issue**: https://github.com/chipsalliance/rocket-chip/pull/3512
Adds two variations of queues that delay elements by a certain cycle count (either static at compile time or configurable during runtime). Re-uses some of the infrastructure used #3512. Replaces some of the work done in https://github.com/ucb-bar/chipyard/pull/1645
> Add DelayQueue

- .gitmodules
- build.sc
This PR support RocketChip build chisel from source, this flow is not for users, only for devs to test new version of Chisel and check some backport feature is working when they are not released to maven.
> Support RocketChip build Chisel from source

- src/main/scala/tile/BaseTile.scala
- src/main/scala/tile/Core.scala
Without upstreaming these patches, T1 cannot elaborate... We need decouple in the future. Since there is no current valid useVector implementations, I think this is safe to merge.
> Support vector-units w/o L1D$ access

- src/main/scala/rocket/CSR.scala
* Fix the mapping when we access scontext or hcontext to ensure we don't switch targets.
* hcontext is assigned an address in the middle of the VS register address range and should be excluded from the S->VS mapping.
* Add comment to clarify why we are mapping the S to VS and VS to S.
The previous code would have remapped `SContext` on to `HContext` when in VSMode. This is an error, unfortunately HContext was assigned the address that may have been given to `VSContext` if added in the future. The adjusted code will no longer map this incorrectly.
> SContext is remaps to HContext when in VSMode

- src/main/scala/tilelink/SRAM.scala
Enhance ECC SRAM write throughput when eccBytes > 1 by 2 cycles per write when utilizing the full bus.
> Update ECC SRAM to improve throughput on full write

- docs/src/diplomacy/adder_tutorial.md
- src/main/scala/diplomacy/BundleBridge.scala
- src/main/scala/diplomacy/LazyModule.scala
- src/main/scala/groundtest/TraceGen.scala
- src/main/scala/jtag/JtagShifter.scala
- src/main/scala/rocket/BTB.scala
- src/main/scala/rocket/DCache.scala
- src/main/scala/rocket/NBDcache.scala
- src/main/scala/rocket/RocketCore.scala
- src/main/scala/rocket/ScratchpadSlavePort.scala
- src/main/scala/tilelink/AtomicAutomata.scala
- src/main/scala/tilelink/Edges.scala
- src/main/scala/tilelink/Fragmenter.scala
- src/main/scala/tilelink/Fuzzer.scala
- src/main/scala/tilelink/Metadata.scala
- src/main/scala/util/RecordMap.scala
- src/main/scala/util/TraceCoreInterface.scala
Upstream Chisel deleted many old deprecated APIs in chipsalliance/chisel#3733, this PR fixes them to compile with the mainline Chisel.
> Fix Chisel deprecated APIs

- build.sc
Option "-disable-infer-rw" was removed before firtool 1.37.0 used by Chisel 3.6.0 was release.
This patch fixes the build.
> Fix build.

- README.md
- src/main/scala/rocket/CSR.scala
- src/main/scala/tilelink/SRAM.scala
> Sync master into dev

- src/main/scala/amba/ahb/RegisterRouter.scala
- src/main/scala/amba/apb/RegisterRouter.scala
- src/main/scala/amba/axi4/RegisterRouter.scala
- src/main/scala/tilelink/RegisterRouter.scala
I could not find users for these that would resist this change
> Remove deprecated RegisterRouter APIs

- src/main/scala/rocket/DebugROB.scala
- src/main/scala/rocket/RocketCore.scala
- src/main/scala/subsystem/Configs.scala
- src/main/scala/tile/FPU.scala
> Add hardware debug ROB

- src/main/scala/rocket/PMA.scala
- src/main/scala/rocket/TLB.scala
Logically equivalent modularization. Useful for systems which want to implement PMA checks elsewhere in the pipeline.
> Modularize PMA-checking functionality

- src/main/scala/diplomacy/LazyModule.scala
> Add error message in LazyModule construction

- src/main/scala/amba/axi4/Xbar.scala
**Related issue**: https://github.com/chipsalliance/rocket-chip/issues/3548
> Fix AXI4 Xbar elaboration error due to missing fields

- src/main/scala/tilelink/Parameters.scala
This avoids cases where identical TLSlavePortParameters (but with different orderings of TLSlaveParameters) produce different, yet logically-equivalent RTL (reduction trees in findSafe, for instance)
> Use sortedSlaves in some TL helpers

- src/main/scala/subsystem/BaseSubsystem.scala
we don't like it for creating our own subsystem, I believe @jerryz123 also does. 
> remove depending on explicit SBUS

- src/main/scala/groundtest/GroundTestSubsystem.scala
- src/main/scala/subsystem/BaseSubsystem.scala
- src/main/scala/subsystem/RocketSubsystem.scala
I split the traditional Resource Binding out from BareSubsystem, I should not break any dependency on `BaseSubsytem`.
But for a modern API in the future, I prepare to land the brand new `Property` API in Chisel and `OM` API in CIRCT for metadata processing.
> Prepare to purge resource API

- src/main/scala/devices/tilelink/CLINT.scala
- src/main/scala/groundtest/GroundTestSubsystem.scala
- src/main/scala/subsystem/BaseSubsystem.scala
- src/main/scala/subsystem/Ports.scala
- purge xbus to migrate to location API
- split dts related logic out from BareSubsystem to prepare for CIRCT-OM
> [NoMerge] Pending PRs for T1 Tile

- src/main/scala/tile/LazyRoCC.scala
> Add slave node to RoCC

- src/main/scala/rocket/Multiplier.scala
Some area-minimal implementations will want to use the iterative multiplier, but need the full accumulator.
> Support pulling out full imul response

- src/main/resources/META-INF/services/firrtl.options.RegisteredLibrary
Resolves #3579, adds support for Chisel 6+.
**Related issue**: #3579
> Delete SFC RegisteredLibrary file

- src/main/scala/rocket/PTW.scala
- src/main/scala/rocket/TLB.scala
- src/main/scala/rocket/TLBPermissions.scala
Previously, the rocket permissions checker assumed that Rocket could generate Get/Put requests up to CacheBlockBytes in size. This is actually not possible, Rocket by itself will not generate requests > xLen in size.
This relaxes the check within rocket to check for a maxSize of xLen/8. 
Implementations which may perform > xLen/8 byte accesses simply set a higher lgMaxSize for the TLB.
> Support managers with < pageSize alignment

- src/main/scala/groundtest/TraceGen.scala
Spot fix for the API addition in #3588 
> Fix missing no_resp field in TraceGen hella-cache req

- src/main/scala/rocket/PTW.scala
- src/main/scala/rocket/TLB.scala
- src/main/scala/util/package.scala
1. The PTE Cache is supposed to cache the address being requested from memory.
2. The RISC-V Privileged ISA spec states that, for _every_ Stage-2 walk at _every level_ of Stage-1 walk, we need to check
> For Sv39x4, ... Address bits 63:41 must all be zeros, ...
> For Sv48x4, ... Address bits 63:50 must all be zeros, ...
> For Sv57x4, ... Address bits 63:59 must all be zeros, ...
> or else a guest-page-fault exception occurs.
> PTW Hypervisor bug fixes: check GPA bits higher than HGATP.Mode

- src/main/scala/rocket/RocketCore.scala
> Fix s1_data when coreDataBits > xLen

- src/main/scala/tilelink/Fragmenter.scala
This should be safe. TLFragmenter can't fragment caching requests. But masters which are non-probable (non-caching) will only generate non-caching requests, which are fragmentable.
> Allow TLFragmenter to fragment from non-probable masters

- src/main/scala/devices/debug/Periphery.scala
This wouldn't compile for me due to conflicting chisel3.IO and chisel3.experiemental.IO
> Fix chisel3.experimental imports in debug/Periphery

- src/main/scala/tilelink/SRAM.scala
**Commit Description:**
Change a_sublane to not count sublanes if it's a read. Reads return full data width, no matter if the A channel size is not the data width
**Comments**
Noticed that when size is not maxed out on a read to the TLRAM, it was translating it to a RMW. Would make sense if there was an ECC error but that should get handled by d_need_fix in d_wb, sublane should not be responsible.
`val d_wb = d_full && (d_sublane || d_atomic || (d_read && d_need_fix))`
> Update SRAM.scala to improve perf on non-full sized reads

- src/main/scala/rocket/Frontend.scala
- src/main/scala/rocket/RVC.scala
**Related issue**:  In OpenXiangShan repo, this [PR](https://github.com/OpenXiangShan/XiangShan/pull/2850) included some rocket-chip modifications that may contribute to upstream.
Add explicit illegal RVC instruction detection logic to RVC decoder, enabling a easy implementation for `Sstvala`
> Add illegal instruction detection to RVC decoder

- src/main/scala/rocket/PTW.scala
**Related issue**: follow-on to https://github.com/chipsalliance/rocket-chip/pull/3591
PTW: qualify `invalid_gpa` with `pte.v` and all the other terms from `pf` (page fault) in `gf` (guest page fault).
> PTW: traverse check GPA bits higher than HGATP mode only if valid

- src/main/scala/rocket/CSR.scala
- src/main/scala/rocket/Frontend.scala
- src/main/scala/rocket/RocketCore.scala
Doing this feature as required by the architecture:
> For guest-page faults, the trap instruction register is written with a special pseudoinstruction value if:
> (a) the fault is caused by an implicit memory access for VS-stage address translation, and
> (b) a nonzero value (the faulting guest physical address) is written to `mtval2` or `htval`.
> If both conditions are met, the value written to `mtinst` or `htinst` must be taken from the table below; zero is not allowed.
Paying off this tech debt from https://github.com/chipsalliance/rocket-chip/pull/2841
> The `mtinst` and `htinst` CSRs are hardwired to 0, placing additional onus on hypervisor software to use the HLVX instruction.
**Type of change**: bug report | feature request
**Impact**: functional addition …
> Hypervisor: drive mtinst/htinst

- src/main/scala/devices/debug/Debug.scala
- src/main/scala/devices/debug/SBA.scala
- src/main/scala/devices/tilelink/Error.scala
- src/main/scala/rocket/CSR.scala
- src/main/scala/rocket/ICache.scala
- src/main/scala/tilelink/Monitor.scala
- src/main/scala/tilelink/WidthWidget.scala
> Fix extraction-width warnings

- src/main/scala/tile/FPU.scala
- Support configurable fpmu/ifpu latency
- Support pipelined coprocessor requests into the FPU
This does not affect existing designs.
> Minor FPU imropvements

- src/main/scala/amba/apb/ToTL.scala
APB address is getting bitwise flipped to get TL address which then immediately fails the assertion below that checks they are the same. 
`when (out.a.fire) {
assert(in.paddr === out.a.bits.address, "Do not expect to have to perform alignment in APB2TL Conversion")
}`
Reverts line back to before commit #3059
> Update APBtoTL scala to not flip apb address when doing conversion

- src/main/scala/subsystem/Cluster.scala
- src/main/scala/subsystem/HasHierarchicalElements.scala
- src/main/scala/subsystem/HasTiles.scala
This avoids accidental no-implicit-clock errors, now that BaseSubsystem has no clocks
Resolves #3647 
> Interrupts coming outwards from the Tile should cross into a toPlicDomain

- src/main/scala/rocket/PTW.scala
**Related issue**: This is a similar bug as https://github.com/chipsalliance/rocket-chip/pull/3625: different bits for a valid-but-table entry in the same last-level FSM state.
PTW: qualify `invalid_gpa` with `pte.leaf()` instead of just `pte.v`.
> PTW: traverse check GPA bits higher than HGATP mode only if leaf

- src/main/scala/rocket/CSR.scala
- src/main/scala/rocket/RocketCore.scala
- src/main/scala/rocket/VectorUnit.scala
- src/main/scala/tile/BaseTile.scala
- src/main/scala/tile/Core.scala
> Allow non-V implementations of vector units, with Zve/Zvl extensions

- src/main/scala/subsystem/Configs.scala
As asked by Jerry in issue #3647, submitting several config-fragments that I have created while working in chipyard. Some of the fragments I've created are for enabling features and some are more QoL to give more customization to existing features. Happy to remove any of them if they are too verbose.
> Adding new config fragments to Rocket-chip subsystem Config.scala

- src/main/scala/devices/tilelink/PhysicalFilter.scala
- src/main/scala/tilelink/Xbar.scala
Please refer to the issue page below.
https://github.com/ucb-bar/chipyard/issues/1888
**Related issue**: https://github.com/ucb-bar/chipyard/issues/1888
**Impact**: Affect custom user field of TL Channels
> Add IO Connections for Custom User Field in TL Channels within Xbar

- src/main/scala/rocket/RocketCore.scala
- src/main/scala/rocket/VectorUnit.scala
- src/main/scala/tile/BaseTile.scala
- src/main/scala/tile/Core.scala
- src/main/scala/tile/FPU.scala
> Fix support for vector units with Zvfh

- src/main/scala/rocket/CSR.scala
- src/main/scala/rocket/PTW.scala
- src/main/scala/rocket/TLB.scala
- src/main/scala/tile/BaseTile.scala
**Related issue**: follows https://github.com/chipsalliance/rocket-chip/pull/3006
Fix bit-width out-of-range compile error with large address widths when VM disabled.
> VM disabled: support larger physical addresses

- src/main/scala/rocket/RocketCore.scala
- src/main/scala/tile/FPU.scala
This avoids deadlock conditions due to coprocessor requests typically being from older instructions.
> Prioritize coprocessor FPU reqs over core FPU reqs

- src/main/scala/rocket/CSR.scala
Non-V will not have misa.V set, but should still execute V
> Support non-V, but with-vector implementations

- src/main/scala/tilelink/Xbar.scala
If a TLXbar is very large, it will print a warning using `$name`. However, `$name` can only be accessed after `desiredName` is set otherwise it will throw an error like `chisel3.package$ChiselException: Error: desiredName of freechips.rocketchip.tilelink.TLXbar$Impl is null. Did you evaluate 'name' before all values needed by desiredName were available?`. This re-orders the `desiredName` override to the top of the `LazyModuleImp`.
> Move `desiredName` override to top of `LazyModuleImp`

- src/main/scala/rocket/RocketCore.scala
> vsets should trap when mstatus.VS is off

- src/main/scala/rocket/Configs.scala
> Support either rational direction for rocket rational CDCs

- src/main/scala/rocket/RocketCore.scala
**Related issue**:  This PR contains a fix for the core clock gating bug described in the following issue: https://github.com/chipsalliance/rocket-chip/issues/3695.
The core clock will no longer be gated when there is a RoCC instruction active or busy.
> Rocket Core Clock Gate Bug Fix

- src/main/scala/devices/debug/Debug.scala
This pr is for debug multiCore. Hart0 should not be reset when reset hartX(X>0) by writing dmcontrol(hasel=0, hartsello=X, hartreset=1, dmactive=1).
> fix `hartReset` in DM

- src/main/scala/rocket/RVC.scala
**Related issue**: not applicable
According to unprivileged specification section 26.5.2:
>  C.ADDI4SPN is a CIW-format instruction that adds a zero-extended non-zero immediate, scaled by
> 4, to the stack pointer, x2, and writes the result to rd′. This instruction is used to generate pointers to
> stack-allocated variables, and expands to addi rd′, x2, nzuimm[9:2]. C.ADDI4SPN is only valid
> when nzuimm≠0; the code points with nzuimm=0 are reserved.
`C.ADDI4SPN` with `imm=0` (i.e. `x(12,5) === 0.U`) should be reserved (illegal for now), whether or not `rd'=0` (i.e. `x(4,2) === 0.U`)
> Fix: c.addi4spn with imm=0 and rd'!=0 should be reserved

- src/main/scala/subsystem/Cluster.scala
Fixes tile filtering logic for seipNodes by using `hasSupervisorMode` instead of `useSupervisor`.
**Related issue**: https://github.com/ucb-bar/chipyard/pull/2190
> Fix filtering tiles with supervisor for seipNodes

- build.sc
- src/main/scala/rocket/DCache.scala
Resolves #3722.
**Related issue**: #3722
Update to Chisel 6.7.0
> Update to Chisel 6.7, use new annotation API

- src/main/scala/amba/ahb/Xbar.scala
- src/main/scala/amba/apb/Xbar.scala
- src/main/scala/amba/axi4/Xbar.scala
- src/main/scala/interrupts/Xbar.scala
**Related issue**: https://github.com/chipsalliance/rocket-chip/pull/2639
Fix type mismatch that makes it always false.
``` scala
def inputs: Seq[(OutwardNode[DI, UI, BI], RenderedEdge)] = (iPorts zip edgesIn) map { case ((_, n, p, _), e) =>
val re = inner.render(e)
(n, re.copy(flipped = re.flipped != p(RenderFlipped)))
}
/** Metadata for printing the node graph */
def outputs: Seq[(InwardNode[DO, UO, BO], RenderedEdge)] = oPorts map { case (i, n, _, _) => (n, n.inputs(i)._2) }
```
> Fix circuitIdentity in Xbars

- src/main/scala/subsystem/Ports.scala
If a user enables AXI4 Monitors (using `AXI4MonitorBuilder`), they'll get a no-implicit-clock error at this point, which isn't easy to track down. Chipyard worked around a similar problem with TileLink Monitors here: https://github.com/ucb-bar/chipyard/pull/1868
Resolve build error when using AXI4 monitors.
> Resolve no-implicit-clock error with AXI4 monitors

- src/main/scala/devices/tilelink/BootROM.scala
- src/main/scala/subsystem/Configs.scala
- src/main/scala/util/package.scala
> Support multiple ROMs

- src/main/scala/amba/axi4/SRAM.scala
**File Changed**: SRAM.scala
The code involved is as follows:
```
val r_sel0 = address.contains(in.ar.bits.addr)
val w_sel0 = address.contains(in.aw.bits.addr)
val r_sel1 = RegNext(r_sel0)
val w_sel1 = RegNext(w_sel0)
when (in.aw.fire) {
w_id := in.aw.bits.id
w_sel1 := w_sel0
w_echo :<= in.aw.bits.echo
}
when (in.ar.fire) {
r_id := in.ar.bits.id
r_sel1 := r_sel0
r_echo :<= in.ar.bits.echo
}
```
**Change Description**: In the original code within the SRAM.scala file, the signals r_sel_1 and w_sel_1 were being assigned values based on the rising edge of the clock using in.ax.bits.addr. Consequently, the rresp and wresp wire signals, which are directly …
> fix(SRAM.scala): change x_sel_1 RegNext to Reg(Bool())

- src/main/scala/rocket/RocketCore.scala
This is because whole-register load/stores do not trap on vill
> Require EarlyVectorDecode to check vill internally

- .github/workflows/mill-ci.yml
PR #3740 is hitting CI issues due to `coursier/cache-action@v5` using a deprecated caching service.
Background:
- https://github.blog/changelog/2025-03-20-notification-of-upcoming-breaking-changes-in-github-actions/#decommissioned-cache-service-brownouts
- https://github.blog/changelog/2025-01-15-github-actions-ubuntu-20-runner-image-brownout-dates-and-other-breaking-changes/#actions-cache-v1-v2-and-actions-toolkit-cache-package-closing-down
> Update GitHub actions

- src/main/scala/amba/ahb/Nodes.scala
- src/main/scala/amba/apb/Nodes.scala
- src/main/scala/amba/axi4/Nodes.scala
- src/main/scala/tilelink/Nodes.scala
This operator coerces every right-hand-size element to drive a left-hand-size element, which is exactly the use-case for a monitor.
See here for more information:
- https://www.chisel-lang.org/docs/explanations/connectable#coercing-mono-direction-connection-operator-
- https://www.chisel-lang.org/api/latest/chisel3/connectable/Connectable.html
> Use Connectable coercion operator to drive diplomatic monitors

- src/main/scala/rocket/TLB.scala
The RISC-V Privileged ISA specification says for the `HLVX` instructions:
> For the supervisor physical address that results from address translation, the supervisor physical memory attributes must grant both execute and read permissions.
> TLB should consider PMP.X checking HLVX load access fault
