- fsim/fpga_mem_gen
- vsim/vlsi_mem_gen
Running fpga_mem_gen in a Python 3 environment dies due to one use of `range` and a `print` statement that doesn't use parentheses. This trivially fixes both of these without breaking Python 2 compatibility.
Commit message:
Two quick fixes that enable fpga_mem_gen to work with either Python 2 or
Python 3:
* Change an `xrange` instance to `range`
* Wrap the arguments of a bare `print` in parentheses
> Fix FPGA/VLSI Mem Gen for Python 2 and 3 Environments

- csrc/mm.h
> Force C++ emulator to always use 1GB for MEM_SIZE

- regression.sh
I want to be able to test the master of riscv-gnu-toolchain against the current
RTL as part of the buildbot.  This flag takes a list of repositories (by their
submodule path) and updates those to the current master, which facilitates that
check.
> Add a "--master" flag to the regression script

- Makefrag
Builds fail with:
java.util.concurrent.ExecutionException: java.lang.OutOfMemoryError: PermGen space
at java.util.concurrent.FutureTask.report(FutureTask.java:122)
at java.util.concurrent.FutureTask.get(FutureTask.java:188)
at sbt.ConcurrentRestrictions$$anon$4.take(ConcurrentRestrictions.scala:188)
at sbt.Execute.next$1(Execute.scala:83)
at sbt.Execute.processAll(Execute.scala:86)
deep in sbt/scala.
> Double Java MaxPermSize.

- project/build.scala
This prevents the build from barfing if you use more than one rocketchip addon.
> build.scala uses space-delimited ROCKETCHIP_ADDONS

- src/main/scala/Configs.scala
- src/main/scala/RocketChip.scala
- src/main/scala/TestConfigs.scala
This implements a DMA engine in Rocket Chip, which allows fast copying and prefetching of data into the L2 cache. The system is split into two parts, a frontend sitting in each CPU as a RoCC accelerator, which handles segmentation and address translation, and a backend in uncore, which takes contiguous transfer or prefetch requests from the frontend and translates them into the proper TileLink messages for the L2.
This unit will probably later be extended to allow DMA from IO or network devices. 
Uncore PR: https://github.com/ucb-bar/uncore/pull/6
Rocket PR: https://github.com/ucb-bar/rocket/pull/21
GroundTest PR: https://github.com/ucb-bar/groundtest/pull/1
> Implement DMA unit

- Makefrag
make changed its priorties for resolving implicit rules, which causes different
behavior when running "make run-bmark-tests".  This patch changes the hex file
rules to ensure they match between the two versions of make.
I've tried this with both make-3.81 and make-4.1, and they both work for me.
> Support make-3.82 and newer

- csrc/htif_emulator.h
We used to just be writing the SCR anyway, but now that the SCR maps are
automatically defined VCS will detect the missing SCR and bail out when
compiling test harness code.  This patch just doesn't write the HTIF SCR when
there isn't one.
> The FPGA doesn't have an HTIF clock divider

- src/main/scala/Configs.scala
- src/main/scala/RocketChip.scala
- vsim/Makefrag
- vsrc/backup_mem.v
- vsrc/rocketTestHarness.v
We still use the backup memory port when building chips, but it's gotten no testing upstream so it's completely broken.  This resurrects the backup memory port Verilog test harness, adds a configuration option that will enable that test harness, and fixes the backup memory port on multi-channel configurations.
> Fix the backup memory port

- src/main/scala/Configs.scala
- src/main/scala/Testing.scala
These won't actually work until further commits.  Rocket RV32 support
is complete, but on the priv-1.9 branch.
> Add RV32 test/configuration options

- src/main/scala/Configs.scala
- src/main/scala/TestConfigs.scala
When we instantiated a 16-tile RocketChip, it failed to run programs because the upper bit of transactions created by AXI masters (in this case, RTC) was being cut off, as the masters don't know that the NASTI arbiters require some bits for use as their own transaction ID.  This PR defines a new value, `MTIFMasterTagBits`, which indicates how many bits of the total AXI transaction ID can be used by masters for their own purposes, and changes `MIFTagBits` ensure the bus is wide enough.
Note that this depends on ucb-bar/junctions#12, which defines the `MTIFMasterTagBits` case object.
> Fix MIF bug that cuts off upper xact id bits

- .gitmodules
This was previously removed from the master branch of ucb-bar/rocket-chip, but not from the hwacha branch.  Removing it now should prevent `git submodule update` from failing due to the unavailability of jackhammer.
> Removed jackhammer submodule

- .travis.yml
- src/main/scala/Configs.scala
- src/main/scala/RocketChip.scala
- src/main/scala/TestConfigs.scala
Similar to the last PR. This changes the routing for the memory channels from AXI to TileLink. Related PR for uncore.
> Switch memory to Tilelink interconnect

- Makefrag
Now developers can define the SBT environment variable to use their local sbt throughout the entire project (rocket-chip, firrtl, and torture).  Note, I didn't change the original behavior to minimize disruption of existing users.
> streamline sbt

- src/main/scala/Configs.scala
- src/main/scala/RocketChip.scala
@aswaterman This adds the change you requested. Instead of routing using a fixed MMIOBase, we add "mem" back to the address map as the first element and use that for routing in the l1tol2 network. We also add cacheability bits to the address map and use those to decide whether to use the MSHR or IOMSHR in Rocket's L1 data cache.
> Put memory into the address map and no longer use MMIOBase

- src/main/scala/Configs.scala
- src/main/scala/TestConfigs.scala
this avoids filling in the stack trace every time
a config doesn't contain the parameter
This speeds up a Hwacha config's compile time by 1 minute (from 2 to 1) in Chisel 2 and 4 minutes (6->2) in chisel3.
See https://github.com/ucb-bar/context-dependent-environments/pull/2
and some discussion https://github.com/ucb-bar/chisel3/issues/143
> add default cases to configs that use CDEMatchError

- src/main/scala/Configs.scala
The DRAM controller for the Hurricane2 chip has an AHB port for configuration. Thus, we need a way to talk AHB from rocket. This adds an AXI -> AHB (NASTI -> HASTI) converter, some tests in groundtest, and a AHB RAM in uncore.
> Add AXI to AHB converter and more conformant HASTI RAM

- csrc/vcs_main.rocketTestHarness.cc
- src/main/scala/Configs.scala
For the hurricane2 tape out and other future work, the width of the AXI id fields will be fixed. Thus, the TL -> AXI converter will have to account from this and map TileLink ids to AXI ids.
> Don't make MIFTagBits a computed parameter

- src/main/scala/Testing.scala
This ensures that assertion failures, which currently print a message to
the console but return a successful exit code, now will cause non-zero
exit code. This is meant to help automated tools like travis and
buildbot do a better job at catching assertions.
This impacts the various run-* targets in the simulation
directories.
> return non-zero exit codes when an assertion fires

- csrc/emulator.cc
- csrc/emulator_type.h
- emulator/Makefile
- emulator/Makefrag-emulator
- emulator/Makefrag-verilator
- src/main/scala/TestBench.scala
This works good in general, but mkpipe for vpd doesn't work, so make run-test-*-debug dumps nothing even though verilator correctly dumps waveform to the file. It's not clear what's happening to the dump file in VerilatedVcdC.
> replace emulator with verilator for chisel3

- .travis.yml
- Makefrag
- emulator/.gitignore
- emulator/Makefrag-verilator
- regression/Makefile
Thanks to Donggyu (for making Verilator work) and Colin (for making Rocket Chip run under Chisel 3 in all configurations), we can now switch over to Chisel 3.  This PR cleans up a few rough edges:
* The newest Verilator is installed and used, since nobody has it and we need it.
* Travis runs Chisel 2 and Chisel 3 on all configurations
* CHISEL_VERSION=3 is now the default
I don't think we're quite ready to deprecate Chisel 2 yet, so I'm leaving all the Chisel 2 stuff in place.  This means Travis will take twice as long to test everything.
> Default to Chisel 3

- .travis.yml
- Makefrag
- emulator/Makefrag-verilator
- src/main/scala/Configs.scala
- src/main/scala/RocketChip.scala
- src/main/scala/TestConfigs.scala
- vsim/Makefrag-verilog
- vsrc/rocketTestHarness.v
Until now, the number of L1 client channels was set statically in the
configuration. This static configuration also assumed the same number of
cached and uncached channels per tile. As we plan to move towards
heterogenous multicore systems, this restriction should be removed.
This commit changes the generator so that number of channels per tile
can be independently set (using cde.Parameters.alterPartial).
The OuterMemorySystem will dynamically compute the number of cached and
uncached channels by summing the number of each kind of channel per core.
There are changes to all of the submodules to make them compatible with the new way of doing things, please check those as well.
> Dynamically compute number of L1 client channels

- .travis.yml
- fsim/Makefrag
- src/main/scala/Configs.scala
- src/main/scala/TestBench.scala
- src/main/scala/Testing.scala
- vsrc/rocketTestHarness.v
Sorry for mixing a bunch of stuff together into one PR. I'll detail everything I did here.
We got rid of backup memory, but there was still some code hanging around that we didn't clean up. This gets rid of the dead backup memory code generated by Testing.scala and in rocketTestHarness.v.
The DualCoreConfig causes a lot of issues in Travis because the asm tests often time out. Since we already have a dual-core Memtest config, we're not really testing anything extra, so I removed it from the Travis tests.
We've been lumping the A and M extensions under rv64ui and the F and D extensions together under rv64uf. The commit here splits them up properly.
> Fix tests and clean up leftover code from BackupMemory

- .travis.yml
- regression/Makefile
Exactly what it says on the tin. This builds and runs several different configs in the same Travis job so that we don't have to wait for GCC to compile a dozen times.
Right now, I have the configurations separated in two, with one for the Rocket assembly tests and the other for the ground tests, but we could break this up further if necessary.
> Merge different configs into regression suites to reduce travis build times

- src/main/scala/RocketChip.scala
- src/main/scala/TestConfigs.scala
Making a PR for tracking. This solves the issue Wesley posted for uncore.
https://github.com/ucb-bar/uncore/issues/52
Basically, the RTL would fail to synthesize if the number of caching clients was set to 0. This allows the number of caching clients or even the number of total clients to be set to 0.
There's some special-casing code in uncore and rocket chip to allow this to happen. Basically, if there are no caching clients, the coherence agents will skip the probe stage. If there are no clients at all, (such as with the UnitTest) a dummy OuterMemorySystem is generated which just ties off the memory and mmio ports.
> Allow number of caching and non-caching clients to go to 0

- src/main/scala/Configs.scala
- src/main/scala/TestConfigs.scala
This allows us to instantiate both Memtest and NastiConverterTest together in the same design and have them operate simultaneously on the same blocks. This mocks the kind of traffic that will be generated in an SoC with PCIe bus mastering.
> Refactor groundtest configuration

- src/main/scala/DirectGroundTest.scala
- src/main/scala/TestConfigs.scala
This refactors the unit tests in groundtest a bit for better code separation and reusability. Unit tests for TileLink components can now use different sets of drivers, which are self-contained tests of TileLink functionality.
> Refactor groundtest unittests into separate package

- src/main/scala/TestConfigs.scala
The deadlock condition occurs when the acquire tracker attempts to
request a writeback while the writeback unit is still busy and a
voluntary release for the block to be written back is coming in.
The voluntary release cannot be accepted because it conflicts with the
acquire tracker. The acquire tracker can't merge the voluntary release
because it is waiting to send the writeback. The writeback can't
progress because the release it is waiting on is behind the voluntary
release.
The solution to this is to break the atomicity guarantee between the
acquire tracker and the writeback unit. This allows the voluntary
release tracker to take the voluntary release before the writeback unit
accepts the conflicting request. This causes a potential race condition
for the metadata array. The solution …
> Fix L2 Writeback deadlock issue

- src/main/scala/Testing.scala
This allows composing Config classes on the command line. Underscores are translated into the ++ operator.
As a fairly extreme example,
make CONFIG=TinyConfig
is equivalent to 
make CONFIG=WithRV32_WithSmallCores_WithStatelessBridge_BaseConfig
This does not support parameterized Config constructors (e.g. WithNCores).
> Allow aggregate CONFIG on Command Line

- groundtest/src/main/scala/CacheFillTest.scala
- groundtest/src/main/scala/Comparator.scala
- groundtest/src/main/scala/Generator.scala
- groundtest/src/main/scala/NastiTest.scala
- groundtest/src/main/scala/Regression.scala
- groundtest/src/main/scala/Tile.scala
- groundtest/src/main/scala/TraceGen.scala
- groundtest/src/main/scala/Util.scala
- junctions/src/main/scala/unittests/MiscNastiTests.scala
- junctions/src/main/scala/unittests/MultiWidthFifoTest.scala
- junctions/src/main/scala/unittests/NastiDemuxTest.scala
- junctions/src/main/scala/unittests/UnitTest.scala
- junctions/src/main/scala/util.scala
- src/main/scala/DirectGroundTest.scala
- src/main/scala/RocketChip.scala
- src/main/scala/TestConfigs.scala
- src/main/scala/Testing.scala
- src/main/scala/UnitTest.scala
- uncore/src/main/scala/unittests/Drivers.scala
- uncore/src/main/scala/unittests/Tests.scala
Move the unit tests out of groundtest.unittests to junctions.unittests and uncore.unittests. This puts them in the same packages in which the hardware being tested is defined.
There is now a separate kind of tile for building and running the unit tests.
> Refactor unit tests, distributing across packages

- .travis.yml
- regression/Makefile
- src/main/scala/Configs.scala
- src/main/scala/TestConfigs.scala
- src/main/scala/Testing.scala
This changes the Travis build to only run the tests that Scott's test grader identified as actually contributing to hardware coverage. We will set up a build server to do nightly builds which will run the full asm-tests and bmark-tests.
We are also dropping the RoccExampleConfig from the CI build and moving that to the nightly build.
> Only run the important (high coverage) tests in regression suite

- Makefrag
Without this when I update firrtl the new version doesn't get built, so
my build is constantly failing.
> Add firrtl build dependencies

- project/build.scala
- project/plugins.sbt
The sbt pack plugin allows us to dump out jar files for all of the rocketchip libraries (chisel, cde, uncore, junctions, rocket, groundtest, and rocketchip), making it easier for us to use them in external projects.
> Add sbt pack plugin

- .travis.yml
- Makefrag
- coreplex/build.sbt
- coreplex/src/main/scala/Configs.scala
- coreplex/src/main/scala/Coreplex.scala
- coreplex/src/main/scala/DirectGroundTest.scala
- coreplex/src/main/scala/TestConfigs.scala
- coreplex/src/main/scala/Testing.scala
- coreplex/src/main/scala/UnitTest.scala
- junctions/src/main/scala/addrmap.scala
- junctions/src/main/scala/unittests/UnitTest.scala
- project/build.scala
- regression/Makefile
- rocket/src/main/scala/tlb.scala
- src/main/scala/Configs.scala
- src/main/scala/Coreplex.scala
- src/main/scala/Devices.scala
- src/main/scala/DirectGroundTest.scala
- src/main/scala/Generator.scala
- src/main/scala/RocketChip.scala
- src/main/scala/TestBench.scala
- src/main/scala/TestConfigs.scala
- src/main/scala/UnitTest.scala
- uncore/src/main/scala/converters/Nasti.scala
- uncore/src/main/scala/tilelink/Definitions.scala
- uncore/src/main/scala/tilelink/Interconnect.scala
- uncore/src/main/scala/unittests/Drivers.scala
This commit refactors things so that the coreplex is a distinct module.
The tiles, L2 agents, and tilelink networks, and internal devices (PLIC, PRCI, BootROM, Debug) reside in the coreplex.
All converters, external-facing devices, and clock crossers now reside outside.
> Refactor top-level to separate coreplex from platform

- coreplex/src/main/scala/Configs.scala
- coreplex/src/main/scala/Coreplex.scala
- coreplex/src/main/scala/DirectGroundTest.scala
- coreplex/src/main/scala/UnitTest.scala
- src/main/scala/Configs.scala
- src/main/scala/RocketChip.scala
In the coreplex refactoring, I only had one bus port (TileLink master) exported out of the coreplex. This was fine because we only had the AXI bus ports, and those could be collected with an AXI arbiter. But I now realize that we might want to add different kinds of bus masters. Instead of having to instantiate another TileLink arbiter in the top-level, it would be better just to extend the l1tol2 network.
> Allow coreplex to take in more than 1 bus port

- groundtest/src/main/scala/BusMasterTest.scala
- src/main/scala/Configs.scala
- src/main/scala/Devices.scala
- src/main/scala/RocketChip.scala
- src/main/scala/TestConfigs.scala
Before, we assumed that extra devices in the periphery would only need MMIO ports (i.e. acting as a slave talking to extra IO). But now I realize they might also need to have client ports in order to do any kind of DMA. This gives the devices an optional client port (the MMIO port is also made optional) to give the implementation more flexibility.
> Allow ExtraDevices to have client ports as well as MMIO ports

- src/main/scala/RocketChip.scala
seems like a simple omission as it is connected to by both the test harness and the coreplex itself
> connect top level interrupts to coreplex

- groundtest/src/main/scala/BusMasterTest.scala
- groundtest/src/main/scala/CacheFillTest.scala
- groundtest/src/main/scala/Regression.scala
- rocket/src/main/scala/btb.scala
- rocket/src/main/scala/csr.scala
- rocket/src/main/scala/dcache.scala
- rocket/src/main/scala/fpu.scala
- rocket/src/main/scala/nbdcache.scala
- rocket/src/main/scala/ptw.scala
- rocket/src/main/scala/rvc.scala
- rocket/src/main/scala/tlb.scala
- rocket/src/main/scala/util.scala
- uncore/src/main/scala/agents/Agents.scala
- uncore/src/main/scala/agents/Broadcast.scala
- uncore/src/main/scala/agents/Cache.scala
- uncore/src/main/scala/agents/Ecc.scala
- uncore/src/main/scala/agents/Trackers.scala
- uncore/src/main/scala/coherence/Policies.scala
- uncore/src/main/scala/devices/Bram.scala
- uncore/src/main/scala/devices/Debug.scala
- uncore/src/main/scala/tilelink/Definitions.scala
- uncore/src/main/scala/unittests/Drivers.scala
- uncore/src/main/scala/util/Package.scala
I got a bit annoyed at how the UIntIsOneOf and AugmentedSeq implicits were duplicated in rocket and uncore. Also how there was both a uncore.Util and uncore.util package.
This merges the two packages together and gets rid of the repeated definition in rocket.
I also replaced everywhere we use (state === for) || (state === bar) ... This touches a lot of files, so the diff is a bit large.
> Clean up our use of UIntIsOneOf

- src/main/scala/rocketchip/Configs.scala
- src/main/scala/rocketchip/Devices.scala
- src/main/scala/rocketchip/RocketChip.scala
- src/main/scala/rocketchip/TestConfigs.scala
- src/main/scala/rocketchip/TestHarness.scala
Before we had a sequence of builders, one for each device.
But really we just want one builder for each of them, since we have to define all of them in the same place anyway.
This makes it possible to connect the devices to each other.
> Refactor extra devices builder

- .gitmodules
I don't believe we actually want to include openocd as a submodule. I had added commands to install it as part of the regression.
@aswaterman correct?
> Remove openocd from .gitmodules

- emulator/Makefile
- vsim/Makefile
The make infrastructure has historically been rather trigger-happy because it nearly always attempted to include the generated .d file, making just about everything effectively depend on Chisel execution.  This led to some unwanted behavior, e.g., Chisel would run even when you used `make -n`.
This fixes the problem by included the .d file only when it's actually needed to define the simulation targets.
> More accurate conditional include of generated .d make fragment

- src/main/scala/rocket/nbdcache.scala
`p` is already used for the implicit parameters, so we should really avoid using it for other things.
> Use a better iterator inside the DCache

- src/main/scala/rocketchip/Configs.scala
- src/main/scala/rocketchip/Devices.scala
- src/main/scala/rocketchip/RocketChip.scala
- src/main/scala/rocketchip/TestConfigs.scala
This addresses Issue #219  -- the NExtInterrupts parameter is now divided into NExtTopInterrupts (which actually come out of Top) and NExtPeripheryInterrupts (which actually come out of Periphery). The Periphery interrupts are at the lower bits (which may have some ramifications for priority)
> Allow some External Interrupts to come from Periphery

- vsim/Makefrag
Following FIRRTL PR [252](https://github.com/ucb-bar/firrtl/pull/252), we should turn off randomization of disconnected wires in the simulator.
For one thing, this makes it difficult to find accidentally disconnected wires in RTL simulation. For another, it is not always safe to assume that an undriven net will have a sensible value in actual hardware.
Registers and memories are still given random initialization, since they will get some initial value on power on in the actual circuit.
There's an additional commit to make sure the rocket pipeline stages are clean on reset. Currently there is a remote possibility that an erroneous dcache write will be sent out and committed to memory.
> Do not randomize disconnected outputs

- vsim/Makefrag
Basically the same as the previous PR that got dropped, except this turns on all the randomization options by default. Necessary to get up to date with the latest FIRRTL changes.
> Get in line with FIRRTL randomization flag changes

- src/main/scala/rocketchip/Configs.scala
There is a problem that external address map is not included when it is configured with ExtMMIOPorts and without ExtraDevices.
I fixed it.
> Add address map entries for exported mmio port.

- src/main/scala/groundtest/Tile.scala
- src/main/scala/rocket/nbdcache.scala
- src/main/scala/rocket/rocc.scala
- src/main/scala/rocket/tlb.scala
This cherry-picks some bugfix commits from my new dma branch. The main changes are
* Fix the DecoupledTLB so that it actually handles misses correctly
* Fix DummyPTW to set the new status and ptbr fields that the TLB depends on
* Don't override the setting of req.bits.phys in the SimpleHellaCacheIF
* Tie invalidate_lr to false by default in RoCC accelerator
> Backport some changes from DMA branch

- Makefrag
- emulator/Makefrag-verilator
- vsim/Makefrag-verilog
It may be the case that you want the configuration project to be different from the test harness project. This change allows that to happen by specifying a separate variable CFG_PROJECT, which is by default the same as PROJECT.
> Allow configuration to be in separate project from test harness

- src/main/scala/coreplex/Coreplex.scala
The Coreplex/Uncore/OuterMemorySystem module hierarchy was mostly getting in the way, the code is much cleaner this way.
> flatten Coreplex module hierarchy

- .travis.yml
It turns out the makefile will try to rebuild the installed verilator binary if the source is missing, so we should cache the entire verilator directory (both source and installation). Hopefully this will speed up future Travis runs.
> Have Travis cache the entire verilator directory

- src/main/scala/rocketchip/Configs.scala
- src/main/scala/rocketchip/RocketChip.scala
with the AddrMap ordering constraint relaxed, this parameter is no longer needed.
> remove parameter ExtIOAddrMapEntries

- src/main/scala/coreplex/Coreplex.scala
This is the only case of creating IOs with the constructor rather than the companion object.
We don't want this to happen anymore as per email discussion.
> only use companion objects for types

- vsim/Makefrag-verilog
Without this, all of the memories wind up as two-ported.
> Turn on the inferRW Firrtl pass

- src/main/scala/junctions/addrmap.scala
This is a temporary fix, which can generate more hardware than necessary, but this is OK for now, since this code will soon be replaced with tilelink2 code.
> Fix routing in non-contiguous MMIO regions

- src/main/scala/uncore/tilelink2/Legacy.scala
> tilelink2 Legacy: it's only an error if it's valid

- src/main/scala/uncore/tilelink2/Buffer.scala
- src/main/scala/uncore/tilelink2/Fragmenter.scala
- src/main/scala/uncore/tilelink2/HintHandler.scala
- src/main/scala/uncore/tilelink2/LazyModule.scala
- src/main/scala/uncore/tilelink2/Nodes.scala
- src/main/scala/uncore/tilelink2/WidthWidget.scala
- src/main/scala/uncore/tilelink2/package.scala
In order to implement a pass-through RAM Monitor model, we will want to support
a variable number of inputs and outputs with BOTH different manager and client
parameters on each bundle.
> TL2Node: make it possible for {Identity,Output,Input}Node to pass a Vec

- src/main/scala/uncore/util/BlackBoxRegs.scala
There was no good reason for had AsyncResetRegVec to take implicit Parameters, so cleaning it up to make it easier to use.
> Get rid of the unecessary Parameters for Async Reset Reg

- src/main/scala/rocketchip/Configs.scala
- src/main/scala/rocketchip/TestHarness.scala
Since the reorganization of the test harness, we've lost the ability to use dramsim. This makes it difficult to get reasonable benchmark results in simulation. This doesn't really restore that functionality, but it gets you part of the way there. Basically, you can set it up so that responses from the SimAXIMem have a fixed latency. I'm not really sure what the most sensible default for `SimMemLatency` is, however.
> Allow configuration of simulation memory latency

- src/main/scala/coreplex/Coreplex.scala
- src/main/scala/coreplex/UnitTest.scala
- src/main/scala/rocketchip/Top.scala
This is the comment I made on the Periphery refactor. To keep things consistent, we should pass nMemChannels to the Coreplex through the CoreplexConfig instead of the cde Parameters.
> Pass nMemChannels to coreplex through CoreplexConfig

- src/main/scala/uncore/tilelink2/Parameters.scala
- src/main/scala/uncore/tilelink2/RAMModel.scala
This case should result in undefined data for the Get.
It was previously requiring the Get to return the new Put data,
which is only guaranteed by a FIFO device.
> tilelink2 RAMModel: fix put, get, putAck, getAck case

- src/main/scala/junctions/asyncqueue.scala
- src/main/scala/junctions/crossing.scala
- src/main/scala/junctions/nasti.scala
- src/main/scala/junctions/unittests/UnitTest.scala
- src/main/scala/rocketchip/DebugTransport.scala
- src/main/scala/uncore/devices/Debug.scala
- src/main/scala/uncore/tilelink2/Buffer.scala
- src/main/scala/uncore/tilelink2/Crossing.scala
- src/main/scala/uncore/tilelink2/Fuzzer.scala
- src/main/scala/uncore/tilelink2/RegField.scala
- src/main/scala/uncore/tilelink2/RegisterCrossing.scala
- src/main/scala/uncore/tilelink2/RegisterRouterTest.scala
- vsrc/ClockDivider.v
This PR includes an AsyncQueue for crossing data instead of the Handshaker.
It also includes TL2 components that can cross TL2 between domains and/or cross an individual register for a register mapped device between domains. The included unit tests validate it against future breakage.
> Clock crossing redux

- src/main/scala/uncore/tilelink2/RegisterCrossing.scala
This gives the slave side of an async write crossing the knowledge that their register was written. with a valid value. This allows doing things like latching the result in a different downstream register  (which you would need if that register was asynchronously reset using our current AsyncResetRegisterVec hack).
You don't want to just blindly take the value every cycle, since the registers in the crossing aren't  reset, so you could get a junk value after nicely async-resetting your flop.
> Give AsyncCrossing slave registers more write control

- vsim/Makefrag-verilog
Helps create just the Firrtl or Verilog target files. Not sure if these are really wanted but I find them useful.
> Add firrtl and verilog Makefile targets to vsim

- csrc/emulator.cc
- emulator/Makefrag-verilator
- regression/Makefile
- src/main/scala/rocketchip/UnitTest.scala
- vsim/Makefrag
- vsrc/TestDriver.v
This uses C and Verilog pre-processor macros to set the name of the top-level module so that MODEL doesn't have to be TestHarness in order to simulate. This also moves the UnitTest stuff from rocketchip.utest back up to rocketchip and renames rocketchip.utest.TestHarness to rocketchip.UnitTestHarness.
> Allow MODEL to be something other than TestHarness

- src/main/scala/coreplex/Configs.scala
- src/main/scala/junctions/nasti.scala
- src/main/scala/junctions/stream.scala
- src/main/scala/rocketchip/Periphery.scala
- src/main/scala/rocketchip/TestHarness.scala
- src/main/scala/uncore/converters/Nasti.scala
Trying to save on Travis latency a bit. This fixes a few minor things.
1. As mentioned in issue #272, we should be consistent about using named constants for the AXI resp, cache, and prot fields. 
2. There's no reason that NTiles should be a Knob instead of a config. Knobs should only be used for things that can be tuned to get performance but don't affect the architectural view of the processor.
3. When I added the latency pipe, I didn't realize how annoying it would be to see a bunch of single-entry queues under the dut module in dve. This collects them into a module so that they don't blow up the module list in the waveform viewer.
> Fix a bunch of small annoyances

- src/main/scala/coreplex/Coreplex.scala
- src/main/scala/rocketchip/Periphery.scala
- src/main/scala/uncore/util/Enqueuer.scala
There's no reason to have objects with such long names when we could just overload the TileLinkEnqueuer object. This is the same approach taken by TileLinkIOWrapper.
> Merge ClientTileLinkEnqueuer and ClientUncachedTileLinkEnqueuer into TileLinkEnqueuer

- src/main/scala/coreplex/TestConfigs.scala
- src/main/scala/rocketchip/Configs.scala
- src/main/scala/uncore/Builder.scala
This combined with ucb-bar/context-dependent-environments#6 removes MatchErrors from the compilation of rocket-chip. Improves performance by ~30%
> Use CDEMatchError for improved performance

- src/main/scala/uncore/util/BlackBoxRegs.scala
- vsim/Makefrag
- vsrc/AsyncResetReg.v
- vsrc/AsyncSetReg.v
The way BlackBox "init" registers were coded before was
not really kosher verilog for most synthesis tools.
Also, the enable logic wasn't really pushed down into the flop.
This change is more explicit about set/reset flops.
Again this is only a temporary fix that would go away
with parametrizable blackboxes (or general async reset support).
> util: Do BlackBox Async Set/Reset Registers more properly

- src/main/scala/uncore/tilelink2/AddressDecoder.scala
- src/main/scala/uncore/tilelink2/Parameters.scala
- src/main/scala/uncore/tilelink2/RegMapper.scala
- src/main/scala/uncore/tilelink2/RegisterRouter.scala
- src/main/scala/uncore/tilelink2/RegisterRouterTest.scala
Restore the default behaviour of the RegisterRouter: undefined registers return zeros and ignore writes.
> RR: undefined regs return zeros

- src/main/scala/rocketchip/Utils.scala
- src/main/scala/uncore/tilelink2/Edges.scala
- src/main/scala/uncore/tilelink2/Fragmenter.scala
- src/main/scala/uncore/tilelink2/Fuzzer.scala
- src/main/scala/uncore/tilelink2/HintHandler.scala
- src/main/scala/uncore/tilelink2/IntNodes.scala
- src/main/scala/uncore/tilelink2/Monitor.scala
- src/main/scala/uncore/tilelink2/Parameters.scala
- src/main/scala/uncore/tilelink2/RAMModel.scala
- src/main/scala/uncore/tilelink2/RegisterRouter.scala
- src/main/scala/uncore/tilelink2/Xbar.scala
This reduces the circuit complexity for all TL2 components which must inspect the address.
> Tl2 cheap address decode

- src/main/scala/groundtest/Generator.scala
- src/main/scala/groundtest/Regression.scala
- src/main/scala/uncore/devices/Rom.scala
- src/main/scala/uncore/tilelink2/Fuzzer.scala
- src/main/scala/unittest/Configs.scala
- src/main/scala/unittest/UnitTest.scala
- src/main/scala/util/Timer.scala
All tests now each have their own Timer/timeout, and the suite runs them in parallel until all finish or any timeout.
Also adds SimpleTimer, which tracks a single inflight event and is tolerant to being stopped repeatedly.
> [unittest] Parallelize UnitTestSuite

- src/main/scala/coreplex/BaseCoreplex.scala
- src/main/scala/coreplex/Coreplex.scala
- src/main/scala/groundtest/BusMasterTest.scala
- src/main/scala/groundtest/Configs.scala
- src/main/scala/groundtest/Regression.scala
- src/main/scala/rocket/dcache.scala
- src/main/scala/rocketchip/BaseTop.scala
- src/main/scala/rocketchip/ExampleTop.scala
- src/main/scala/rocketchip/Periphery.scala
- src/main/scala/rocketchip/Utils.scala
These were bothering me while I was adding multiclock support to the Coreplex, but split into a separate PR.  This commit renames the coreplex/peripheral bus to cbus and pbus, and changes the Coreplex bundle names.
> Rename Coreplex/Peripheral bus, some Coreplex bundle names

- vsrc/TestDriver.v
I think there was a merge conflict somewhere. This should be 'clock', not 'clk'
> Correct Merge Conflict -- clock, not clk

- src/main/scala/uncore/tilelink2/Fragmenter.scala
This fixes an issue where `addr_lo` was being passed through unchanged, which triggered unaligned address assertions in the Monitor.
> tilelink2 Fragmenter: Mask low bits of D channel addr_lo

- src/main/scala/rocketchip/BaseTop.scala
- src/main/scala/rocketchip/Configs.scala
- src/main/scala/rocketchip/Periphery.scala
- src/main/scala/uncore/devices/Prci.scala
This removes the hard-coded constants that had started pervading the design and leverages the new RegisterRouter's flexibility of bus width.
> Periphery: make bus width and arithmetic atomics configurable

- src/main/scala/uncore/tilelink2/Arbiter.scala
- src/main/scala/uncore/tilelink2/Xbar.scala
This moves the Xbar from using custom code to using the Arbiter.
The arbiter has better ready-valid decoupling.
> tilelink2 Xbar: decouple ready from valid

- src/main/scala/junctions/asyncqueue.scala
@terpstra @yunsup 
In general, it's a good idea to have asynchronous reset on the crossing FIFOs, since the blocks may come out of reset at different times, clocks may not have started yet, etc.
This PR achieves that and blows away the non-async-reset option.
Are there any other low-level crossing primitives that need this treatment?
> Async rst async queue

- src/main/scala/junctions/addrmap.scala
- src/main/scala/rocketchip/Utils.scala
If you connect two devices with the same name in TL2 (totally ok there),
when they get put into the TL1 addrmap, one gets silently overwritten.
This renames the second occurance as _1, third as _2, and so on.
> rocketchip: rename identically names devices with _%d

- src/main/scala/rocketchip/BaseTop.scala
- src/main/scala/rocketchip/Generator.scala
- src/main/scala/uncore/tilelink2/LazyModule.scala
- src/main/scala/uncore/tilelink2/Nodes.scala
- src/main/scala/util/GeneratorUtils.scala
This entertaining little PR adds support for generating fancy TL2 bus diagrams.
Attached is the ExampleTop of rocket chip as it stands right now, as rendered by yEd using hierarchical layout. More sophisticated bus topologies look even cooler.
> Tl2 graphml

- src/main/scala/uncore/tilelink2/Parameters.scala
This helps devices with misaligned ranges still connect to TL2.
> tilelink2 AddressSet: add .misaligned(low, size) helper method

- src/main/scala/uncore/tilelink2/Edges.scala
- src/main/scala/uncore/tilelink2/WidthWidget.scala
Refactor use of the address into accessor methods addr_{lo,hi}.
This should solve the problem @a0u had with beatBytes==1 on SPI.
This should also make it easier when we bite the bullet and have address (lo+hi) on ABC.
> Tl2 addr width0

- emulator/Makefile
- scripts/tracegen+check.sh
- src/main/scala/coreplex/BaseCoreplex.scala
- src/main/scala/coreplex/Coreplex.scala
- src/main/scala/groundtest/Configs.scala
- src/main/scala/groundtest/TraceGen.scala
- src/main/scala/rocketchip/Periphery.scala
- src/main/scala/uncore/agents/Agents.scala
- src/main/scala/uncore/converters/Tilelink.scala
- src/main/scala/uncore/util/Enqueuer.scala
There have been some changes to AXE which break our current implementation of TraceGen. These fixes help us get back on track. Basically, we have to make sure we store some known value to all of the addresses we are using before we do any other operation.
> Fixup Tracegen

- src/main/scala/coreplex/BaseCoreplex.scala
- src/main/scala/rocketchip/BaseTop.scala
- src/main/scala/rocketchip/ExampleTop.scala
This would allow, for instance, putting the coreplex on a separate clock
domain and crossing the IOs over through asynchronous queues.
The ExampleMultiClockTop* classes are removed since they no longer fit
into the class hierarchy.
> Factor coreplex IO connection into separate trait

- src/main/scala/coreplex/BaseCoreplex.scala
- src/main/scala/coreplex/Configs.scala
- src/main/scala/groundtest/NastiTest.scala
- src/main/scala/rocketchip/Configs.scala
- src/main/scala/rocketchip/Periphery.scala
The "Outermost" and "MMIO_Outermost" keys are renamed to "MCtoEdge"
and "MMIOtoEdge". They are only used after width conversion to adapt to
external interfaces in the periphery.
That means there is no longer any width adapting done in the Coreplex,
the width adapter is moved to the Periphery just before conversion
to AXI/AHB or sending off chip.
We also add an additional TLKey "EdgetoSlave" for the bus_axi interface.
This means there is also a width adapter from the AXI -> TL converter
to the coreplex slave port.
This also fixes a bug introduced previously in which the wrong
parameters object is given to the width adapter for external MMIO.
> Give TileLink keys more sensible names

- src/main/scala/uncore/tilelink2/WidthWidget.scala
The mask of a Get should also be converted.
This manifested as a bug when going from 32=>64 bits. A large Get
could end up with mask that was not full.
> tilelink2 WidthWidget: Gets must have their mask adjusted

- src/main/scala/uncore/tilelink2/Bundles.scala
- src/main/scala/uncore/tilelink2/Fuzzer.scala
- src/main/scala/uncore/tilelink2/RAMModel.scala
- src/main/scala/uncore/tilelink2/RegMapper.scala
@aswaterman This removes all uses of chisel3._ as requested
> tilelink2: don't use chisel3 namespace

- src/main/scala/uncore/tilelink2/RegisterCrossing.scala
It is no longer needed when the underlying crossings are asynchronously reset. Update the order of operations.
@terpstra  can you take a look at this?
> crossing: Remove reset from the logic in Register Crossing 

- regression/Makefile
- src/main/scala/uncore/tilelink2/AtomicAutomata.scala
- src/main/scala/uncore/tilelink2/Crossing.scala
- src/main/scala/uncore/tilelink2/Fragmenter.scala
- src/main/scala/uncore/tilelink2/Fuzzer.scala
- src/main/scala/uncore/tilelink2/HintHandler.scala
- src/main/scala/uncore/tilelink2/RAMModel.scala
- src/main/scala/uncore/tilelink2/RegisterRouterTest.scala
- src/main/scala/uncore/tilelink2/SRAM.scala
- src/main/scala/uncore/tilelink2/TLNodes.scala
- src/main/scala/uncore/tilelink2/WidthWidget.scala
- src/main/scala/uncore/tilelink2/Xbar.scala
- src/main/scala/unittest/Configs.scala
These tests mostly use the Fuzzer and RAMModel to check that adapters correctly handle-randomly generated legal traffic, without deadlocking or corrupting data.
These tests are added to the UnittestSuite target in regression/Makefile. They should fit within the existing timeframe of the other suites but might have to be adjusted if they start taking too long to elaborate.
> Add TL2 synthesizeable UnitTests for many adapters

- src/main/scala/uncore/tilelink2/RegisterCrossing.scala
- src/main/scala/util/BlackBoxRegs.scala
I find that I end up with a bunch of "AsyncResetRegVec_N" and other commonly used structures in my hierarchy. I'd prefer to give them names like "myReg", "yourReg", "myReg_rcrossing", etc.
I'm not sure this is the right way to go about this, happy for feedback and suggestions.
This is an example of where https://github.com/ucb-bar/chisel3/issues/303 would make a difference.
This PR also resolves the difference in behavior between instantiating a single AsyncResetReg (with a Bool) and a AsyncResetReg (UInt).
> Suggest sane names for common objects

- src/main/scala/rocketchip/Utils.scala
- src/main/scala/uncore/devices/Prci.scala
CLInt (local interrupt control)  moves to 0x0200_0000.
PLIC (external interrupt control) moves to 0x0C00_0000.
@aswaterman
> clint & plic: Move the default addresses

- src/main/scala/uncore/tilelink2/RegField.scala
- src/main/scala/uncore/tilelink2/RegMapper.scala
- src/main/scala/uncore/tilelink2/RegisterCrossing.scala
- src/main/scala/uncore/tilelink2/RegisterRouter.scala
- src/main/scala/uncore/tilelink2/RegisterRouterTest.scala
The RegisterRouter fundamentally uses a Decoupled interface for arbitration amongst RegFields. Furthermore, a device might update a RegField while it is being read. This is Decoupled behaviour. This PR accepts the Decoupled nature of the RegisterRouter and uses a bypassable Queue to make the behaviour Irrevocable as required by TL2. The test case and API of RegField have been relaxed accordingly.
> Tl2 rr irrevocable fix

- vsrc/TestDriver.v
I've gone back and forth on this, and regardless of whether we use $urandom or $random, this code seems necessary anyways, so we should merge this in.
> correctly initialize $random with seed

- src/main/scala/uncore/tilelink2/Legacy.scala
Without this fix, all loads from the core are full size.
> tilelink2: Legacy should preserve the access size

- src/main/scala/util/Timer.scala
- vsrc/TestDriver.v
for better interoperability between different Verilog simulators.  Turns out $get_initial_random_seed is VCS only.  h/t @scottj97
> use $urandom as seed for $random

- src/main/scala/util/AsyncQueue.scala
This fixes a bug that would cause the Async Queue sync depth to be one less than expected.
> asyncqueue: Fix typo in the Async Queue 

- project/plugins.sbt
We'd like to use the sbt-unidoc plugin in Chisel3. Unfortunately, sbt's treatment of subproject plugins requires we add this to the parent project's plugins.
> Add sbt-unidoc plugin; bump sbt-buildinfo version.

- src/main/scala/regmapper/RegisterCrossing.scala
- src/main/scala/util/AsyncQueue.scala
This is to aid debugging but even more so for backend constraint writers, who generally
need predictable names for registers to set false paths, etc.
I also picked up @terpstra 's change which renamed 'reg' to 'control' to avoid use of Verilog keyword. 
I see @terpstra already did some stuff in #387 to help with predictable names, I can work on merging this with his later today.
> async_queue: Give names to all the registers which show up in the queue

- src/main/scala/regmapper/RegisterCrossing.scala
This requires master clock and master reset to be explicitly specified in the AsyncRWSlaveRegField (which has symmetry withslave clock and reset). This removes the need for AsyncScope inside this module.
> register_crossing: Remove the need for AsyncScope 

- src/main/scala/rocketchip/DebugTransport.scala
By using AsyncDebugCrossing instead of AsyncDebugTo/From, AsyncScope empty modules aren't introduced to the design. I'd prefer to get rid of the empty modules wherever possible.
Also cleans up the now unused AsyncMailbox blackbox.
> debug: Remove Async Scope from Crossing

- src/main/scala/diplomacy/Nodes.scala
- src/main/scala/regmapper/RegisterCrossing.scala
- src/main/scala/uncore/axi4/package.scala
- src/main/scala/uncore/tilelink2/Bundles.scala
- src/main/scala/uncore/tilelink2/Crossing.scala
- src/main/scala/uncore/tilelink2/Edges.scala
- src/main/scala/uncore/tilelink2/Fuzzer.scala
- src/main/scala/uncore/tilelink2/HintHandler.scala
- src/main/scala/uncore/tilelink2/Isolation.scala
- src/main/scala/uncore/tilelink2/Monitor.scala
- src/main/scala/uncore/tilelink2/RAMModel.scala
- src/main/scala/uncore/tilelink2/RegisterRouterTest.scala
- src/main/scala/uncore/tilelink2/package.scala
- src/main/scala/util/AsyncQueue.scala
- src/main/scala/util/Crossing.scala
This change makes AsyncQueue and TLAsync{Source,Sink} automatically clear the FIFO counters and safely block ready/valid when one half of the crossing is reset.
@jchang0 Here is the branch to test
> Safer crossings

- src/main/scala/diplomacy/Parameters.scala
- src/main/scala/uncore/axi4/Buffer.scala
- src/main/scala/uncore/axi4/Fragmenter.scala
- src/main/scala/uncore/axi4/Nodes.scala
- src/main/scala/uncore/axi4/Parameters.scala
- src/main/scala/uncore/axi4/RegisterRouter.scala
- src/main/scala/uncore/axi4/Test.scala
- src/main/scala/uncore/tilelink2/AtomicAutomata.scala
- src/main/scala/uncore/tilelink2/Fragmenter.scala
- src/main/scala/uncore/tilelink2/Fuzzer.scala
- src/main/scala/uncore/tilelink2/Parameters.scala
- src/main/scala/uncore/tilelink2/RAMModel.scala
- src/main/scala/uncore/tilelink2/RegisterRouter.scala
- src/main/scala/uncore/tilelink2/ToAXI4.scala
- src/main/scala/uncore/tilelink2/package.scala
- src/main/scala/unittest/Configs.scala
This AXI4 fragmenter slices all AXI accesses into simple power-of-two sized and aligned transfers of the largest size supported by the slave.  This makes it suitable as a first stage transformation to apply before an AXI4=>TL bridge. It also makes it suitable for placing after TL=>AXI4 bridge driving an AXI-lite slave.
> AXI4 fragmenter

- src/main/scala/regmapper/RegisterCrossing.scala
- src/main/scala/uncore/tilelink2/Bundles.scala
- src/main/scala/uncore/tilelink2/Crossing.scala
- src/main/scala/uncore/tilelink2/Isolation.scala
- src/main/scala/util/AsyncQueue.scala
The source must wait for the sink's clock after the source was reset, and vice versa.
Also, be more precise about what exactly is an critical crossing failure.
> Better crossing reset handling

- src/main/scala/uncore/axi4/Bundles.scala
- src/main/scala/uncore/axi4/Fragmenter.scala
- src/main/scala/uncore/axi4/Test.scala
- src/main/scala/uncore/axi4/ToTL.scala
- src/main/scala/uncore/tilelink2/package.scala
- src/main/scala/unittest/Configs.scala
This bridge when combined with an AXI4Fragmenter should support all of AXI4.
It will report DECERR if the address is invalid and SLVERR if the TL2 slave reports error.
It enforces FIFO by only allowing one of each AXI ID inflight at a time, which should be enough throughput when combined with an L2 cache since it transfers a cache line per round trip.
> AXI4=>TL2 converter

- vsrc/TestDriver.v
Fixes the following warning:
```
$value$plusargs("max-cycles=%d", max_cycles);
|
ncvlog: *W,NOSYST (/home/scottj/work/federation/rocket-chip/vsrc/TestDriver.v,25|18): System function '$value$plusargs' invoked as a task. Return value will be ignored.
```
> Fix Verilog compile warning from Cadence Incisive

- vsim/Makefrag-verilog
We still should move to invoking Firrtl programmatically rather than via the command-line, but this commit updates Firrtl for now.
> Bump firrtl and update vsim Makefrag-verilog

- vsrc/TestDriver.v
Now that we have ifdef VCS in here lets use it for something more than compatibility
This is a little diff I keep around for debugging non-determinism, thought others might find it useful. The reason I can't just use the stdout where VCS prints the seed is sometimes the non-determinism is rare and so I want to run a bunch of tests in parallel and correlating the stdout to the output file can be difficult.
> Print out seed if we can

- vsrc/TestDriver.v
If user compiles without +define+DEBUG but then requests +vcdfile at
simulation time, that request would be silently ignored. This changes
it to a fatal error.
It's good philosophy to treat plusargs like +vcdfile as commands, not
suggestions, and die immediately if they cannot be honored, instead of
silently ignoring them. Otherwise the user sits through the entire
simulation and then is left scratching his head wondering where his
waveforms are.
> Sanity check compile-time vs simulation-time options

- src/main/scala/uncore/axi4/ToTL.scala
When selecting between error generation on R and real data on R,
correctly calculate the R backpressure.
This bug manifests when a valid request is immediately followed by
an invalid request, wedging the R channel.
> axi4 ToTL: fix decode error arbitration

- src/main/scala/uncore/converters/Tilelink.scala
- src/main/scala/unittest/Configs.scala
The TileLink widener and narrower did not support PutAtomic operations, so they were not passing through correctly. This commit fixes that issue and adds a unittest.
> Add PutAtomic support to width adapters

- csrc/jtag_vpi.c
This eliminates one of the potential race conditions w.r.t. the port number which may occur if you run multiple JTAG simulations on the same machine. This also bumps up `riscv-tools` to pull in https://github.com/riscv/riscv-tests/pull/34, which tells the `gdbserver.py` script to dynamically look for the port that the JTAG server has bound to instead of assuming that it's always 5555.
Once this is merged in, I'll make a followup PR to remove our internal forks of the JTAG and debug tools.
> Use random, unused port for JTAG VPI

- Makefrag
- README.md
- src/main/scala/uncore/axi4/SRAM.scala
- src/main/scala/uncore/tilelink2/SRAM.scala
Chisel now depends on firrtl and will look for a locally published copy.  The workaround is to publish firrtl locally.  This could cause headaches if multiple firrtl versions are in play.  A possible resolution is to have firrtl snapshots versioned by the commit hash, per @jackkoenig.
@richardxia this presumably requires some downstream changes, or perhaps I should take an alternate approach altogether.
> Bump chisel/firrtl

- src/main/scala/groundtest/Regression.scala
- src/main/scala/uncore/agents/Broadcast.scala
There is logic in the broadcast hub to skip the outer acquire if there
is an outgoing release, since the data will be written out through the
release channel. However, this will cause an issue in the case of
PutBlock requests. If the tail beats of the PutBlock show up after the
outer release has already been sent, the data will be corrupted.
The fix is to make the outer release block if there are pending
inner PutBlock beats.
I've also added a regression test to the broadcast regression test suite that catches this behavior.
> Fix issue with PutBlock and Release in BroadcastHub

- src/main/scala/coreplex/Configs.scala
This bug is ancient. I don't understand how it never mattered before.
Anyway, in processors with a custom CacheBlockBytes, this value is wrong!
The symptom is that TL1 components end up missing high address bits.
This causes, for example, a system to jump to 0 instead of RAM.
I don't understand how this very serious bug did not cause problems before.
> coreplex: CacheBlockOffsetBits was wrong!

- vsim/Makefrag-verilog
> Use % in makefrag-verilog to prevent double firrtl execution

- src/main/scala/rocket/Dcache.scala
This bug causes unsigned loads to fetch too many words.
> dcache: the high bit of s2_req.typ is the SIGN bit (not size)

- src/main/scala/rocket/tlb.scala
Speculative branches can some times go to addresses considered executable by the fast address decoding function. This showed up when running linux on FPGA.
> TLB: do not access illegal addresses

- src/main/scala/uncore/devices/Prci.scala
This is needed so that SMP-safe boot loaders can safely
read/write to the IPI register of non-existent harts.
> clint: undefined registers must be zero

- src/main/scala/config/Config.scala
- src/main/scala/coreplex/Configs.scala
- src/main/scala/groundtest/Configs.scala
- src/main/scala/rocketchip/Configs.scala
- src/main/scala/unittest/Configs.scala
The old style of specifying Configs used total functions.  The only way to
indicate that a key was not matched was to throw an exception.  Not only was
this a performance concern, but it also caused confusing error messages
whenever you had a match failure from a lookup within a lookup.  The
exception could get handled by an outer-lookup that then reported the wrong
key as missing.
> Configs: use a uniform syntax without Match exceptions

- vsim/vlsi_mem_gen
I got an error when performing `make verilog` in the vsim folder:
```
Traceback (most recent call last):
File "/home/oguz286/Projects/rocket-chip/vsim/vlsi_mem_gen", line 177, in <module>
main()
File "/home/oguz286/Projects/rocket-chip/vsim/vlsi_mem_gen", line 174, in main
print(gen_mem(*parse_line(line)))
File "/home/oguz286/Projects/rocket-chip/vsim/vlsi_mem_gen", line 151, in gen_mem
for i in range(mask_seg):
TypeError: 'float' object cannot be interpreted as an integer
```
This was due to the `parse_line` function performing a floating point division, and I changed it to an integer division.
> Perform integer division when parsing rocketchip.DefaultConfig.conf

- csrc/emulator.cc
Revision 7e79421 (issue #484) makes emulator.cc rejecting any unrecognized
+arg "legacy" arguments, however, this breaks riscv-torture emulator tests
as it needs to pass +signature to the DTM.
I think it is actually impossible to check for unknown argument here
unless we hardcode a list of all arguments recognized by fesrv. Fix this
issue by passing all arguments starting with the first unknown argument
to DTM.
Updates #484.
> Fix emulator argument processing for unknown DTM arguments

- regression/Makefile
- src/main/scala/rocketchip/ExampleTop.scala
- src/main/scala/rocketchip/TestHarness.scala
This reverts some changes to make ExampleRocketChipTop and its TestHarness actually absorb the WithJtagDTM configuration parameter. This allows us to (again) test the JTAG DTM.
Is it possible to add the test in regression to the suite? As of now I manually run it when I'm updating the JTAG DTM, but I think it would be good to automate this so it doesn't keep getting broken. Is there a limit on resources or time that we're in danger of hitting if I add this?
> jtag_dtm: Update regression to run and pass.

- src/main/scala/coreplex/CoreplexNetwork.scala
There should be a buffer on the external L2 input before the L1toL2 Xbar. All other clients of the Xbar have one, and this keeps them lined up.
Conversely, there is no need for a buffer on the mmio output since it comes directly from the buffer L1toL2 Xbar.
> coreplex: move TLBuffers for L2 and socBus

- Makefrag
This anticipates ucb-bar/chisel3#448. When rocket-chip uses that version of chisel3, the extra copy to chisel3/lib may be removed.
> Match chisel3 userootunmanageddir - use RootProject/lib as unmanagedBase.

- src/main/scala/uncore/tilelink2/AsyncCrossing.scala
- src/main/scala/uncore/tilelink2/Bundles.scala
- src/main/scala/uncore/tilelink2/Nodes.scala
- src/main/scala/uncore/tilelink2/RationalCrossing.scala
- src/main/scala/uncore/tilelink2/package.scala
- src/main/scala/unittest/Configs.scala
- src/main/scala/util/RationalCrossing.scala
If you know two clocks are related with a N:1 or 1:N relationship, you can cross the clock domains with lower latency than an AsyncQueue. This crossing adds 1 cycle in the target clock domain. For a TileLink round-trip, this means it adds one cycle latency to each domain, equivalent to a TLBuffer. Just like a TLBuffer, all outputs of TLRational are registers (bits, valid, and ready). As opposed to a TLBuffer, the construction costs 3*bits instead of 2*bits, so it is not completely free.
> Rational clock crossing

- .gitignore
In #526, we now build firrtl.jar to rocket-chip's `lib/` directory. This adds a gitignore rule for the entire `lib/` directory.
> Ignore the built firrtl.jar.

- src/main/scala/coreplex/BaseCoreplex.scala
- src/main/scala/coreplex/Configs.scala
- src/main/scala/coreplex/CoreplexNetwork.scala
- src/main/scala/diplomacy/LazyModule.scala
This makes it much easier for banked coherence managers to support
cross-bank functionality, like a common control port, for example.
> BankedL2Config: use the same LazyModule for all L2 banks

- src/main/scala/diplomacy/AddressDecoder.scala
This is useful when using the AddressDecoder back to back.
> AddressDecoder: support AddressSets with infinite bits

- src/main/scala/util/Misc.scala
As of ucb-bar/chisel3#491, `abs` now returns the same type as its argument. Add a cast to UInt.
**NOTE**: This is compatible with the version of [chisel3](https://github.com/ucb-bar/chisel3/tree/3ef63639284b2b56f415e1540c58d85d88c360db) currently used by rocket-chip
> Fix up Absolute value.

- emulator/Makefile
- src/main/scala/coreplex/RocketTiles.scala
- src/main/scala/rocket/Tile.scala
- src/main/scala/rocketchip/RocketTestSuite.scala
- src/main/scala/uncore/tilelink2/Nodes.scala
- src/main/scala/uncore/tilelink2/Parameters.scala
- src/main/scala/uncore/tilelink2/RationalCrossing.scala
- src/main/scala/uncore/tilelink2/package.scala
- src/main/scala/util/ClockDivider.scala
- src/main/scala/util/RationalCrossing.scala
- vsim/Makefrag
- vsrc/ClockDivider2.v
Make it possible to specify which side of the crossing is fast and which is slow.
Using this option can make it easier to close timing for the slow side of the crossing; it places the registers all on the slow side. However, if the wrong side is declared fast, the crossing will not be legal! The default remains a symmetric crossing which is safe in all cases and always puts the register on the sink side.
> Rational config

- src/main/scala/junctions/hasti.scala
**Problem: HastiTestSRAM can't Read/Write byte when HSIZE is 0 (indicates the size of a data transfer is byte).**
Take dataBits is 32 bits for example.
What the expected relationship between HSIZE and mask_decode is as below:
- HSIZE[2:0]        -> mask_decode[2:0]
- 000 (Byte)         -> 001
- 001 (Half word) -> 011
- 010 (Word)       -> 111
What the expected relationship between mask_decode and mask_wide is as below:
- mask_decode[2:0] -> mask_wide[3:0]
- 001 -> 0001
- 011 -> 0011
- 111 -> 1111
In other words, 
- mask_wide[0] depends on mask_decode[0],
- mask_wide[1] depends on mask_decode[1],
- mask_wide[2] depends on mask_decode[2],
- mask_wide[3] depends on mask_decode[2].
Let's look at the code: `log2Up(i+1)` (In this example, i is from 0 to 3), the result never is 0. So …
> Fix HastiTestSRAM can't R/W byte when HSIZE is 0

- src/main/scala/groundtest/Comparator.scala
- src/main/scala/junctions/hasti.scala
- src/main/scala/uncore/ahb/SRAM.scala
- src/main/scala/uncore/apb/SRAM.scala
- src/main/scala/uncore/axi4/SRAM.scala
- src/main/scala/uncore/tilelink2/SRAM.scala
- src/main/scala/uncore/tilelink2/SourceShrinker.scala
- src/main/scala/uncore/tilelink2/package.scala
- src/main/scala/util/Package.scala
- Remove redundant definitions
- Make API more idiomatic (x holdUnless y, instead of holdUnless(x, y))
- Add new SeqMem API, readAndHold, which corresponds to most common use of holdUnless
> Standardize Data.holdUnless and SeqMem.readAndHold

- src/main/scala/tile/FPU.scala
We were zero-extending it, which is a double-precision zero in the recoded format.  So, when spilled and reloaded with fsd/fld, the original value was destroyed.  Instead, set the MSBs so that it represents sNaN.  When spilled, the single-precision number will be preserved as the NaN payload.
> Fix in-register representation of fdiv.s/fsqrt.s result

- .travis.yml
- regression/Makefile
We can only run 4 at a time; 5 causes the test time to double.
In the past we had a 50minute build deadline, but that's fixed.
> travis: only run 4 jobs at once

- src/main/scala/rocket/ICache.scala
- src/main/scala/uncore/tilelink2/Monitor.scala
- src/main/scala/uncore/tilelink2/Xbar.scala
Trim uses of TL BCE channel bits. This PR leaves ready/valid for these channels to ensure compatibility when connecting a TL-C-capable device to a TLC-C-incapable device.
> Ignore TL-C

- src/main/scala/coreplex/CoreplexNetwork.scala
This Xbar connects the largest components in the design; the cores
and the L2 banks. We already have a full buffer on the core side.
However, the valid path going to the L2 comes back as a ready path.
Putting a flow Q also on the outputs of the l1tol2 cuts this path
in half at no cost to IPC.
@hanatsifivedotcom
> l1tol2: put a flow Q on the exits

- src/main/scala/coreplex/RocketTiles.scala
- src/main/scala/rocket/Tile.scala
- src/main/scala/tile/Core.scala
Fall back on global variable but check that it is compatible with memory as seen from rocket's tilelink master port.
> rocket: remove hard-coded paddrBits

- src/main/scala/groundtest/DummyPTW.scala
- src/main/scala/rocket/PMP.scala
- src/main/scala/tile/FPU.scala
Single-precision values are stored in the regfile as double-precision, so that FSD on a single-precision value stores a proper double and FLD restores it as either a double or a single.
For Travis economy, I've folded in two unrelated updates:
- Fix groundtest nondeterminism by tying off some disconnected signals
- Improve PMP QoR by using a carry chain to implement the mask generator
> Implement new FP encoding proposal

- src/main/scala/uncore/devices/Rom.scala
This allows TLROM devices to specify a name and compatibility string for the Config String other than "rom"
> TLROM: allow name and compatibility strings to be provided by subclasses

- src/main/scala/rocket/DCache.scala
There's a structural hazard on s2_req, so disallow cache refill initiation while any MMIO loads are in flight.
> Fix MMIO/cache refill concurrency bug in DCache

- src/main/scala/rocketchip/Configs.scala
Defaulting to 0 prevents Linux from booting
> Use 1 MHz as default timebase

- regression/Makefile
- src/main/scala/coreplex/RISCVPlatform.scala
- src/main/scala/rocketchip/RISCVPlatform.scala
- src/main/scala/rocketchip/TestHarness.scala
- src/main/scala/uncore/devices/debug/Debug.scala
Debug Module exports two signals, `ndreset` (Non Debug Reset) and `dmactive` (Debug Module Active). How they should be used is up to the integrator and not clear how to use them within the RocketChipExampleTop (because we want to basically override the entire reset). The TestHarness shows how `ndreset` could be used on an FPGA or SoC which is instantiating ExampleRocketChipTop.
> Debug Controls

- src/main/scala/coreplex/RISCVPlatform.scala
- src/main/scala/uncore/devices/Rom.scala
- src/main/scala/uncore/devices/debug/Debug.scala
DebugROM was pulled out of DebugModule for CDC reasons which no longer apply. Unify these modules again and update the DTS description of DebugModule.
> debug: Put DebugROM back inside the overall Debug Module

- src/main/scala/rocket/ICache.scala
- src/main/scala/rocket/PTW.scala
- src/main/scala/rocket/Rocket.scala
- Revive I$ parity option; pipeline it into the ID stage to keep it off SRAM critical path
- Get I$ s1_kill signal off the critical path
- Add a 1-entry flow queue between I$ and pipeline, cutting I$ -> decode -> stall signal -> I$ path
> I$ improvements

- src/main/scala/uncore/tilelink2/package.scala
Sometimes it is useful to generate a mask with bits that correspond
to a larger unit than bytes.
> maskgen: support wider granularity result

- src/main/scala/uncore/tilelink2/CacheCork.scala
- src/main/scala/uncore/tilelink2/Fragmenter.scala
These help prevent you from constructing a situation where TileLink is used illegally.
> Add a few diplomacy restrictions

- src/main/scala/rocketchip/RocketTestSuite.scala
Jenkins builds are failing with a:
```
...
% cd vsim
% make clean
% make CHISEL_VERSION=3
% make -j 4 run CHISEL_VERSION=3
...
mkdir -p ./output
make: *** No rule to make target `/vm/home/jenkins/workspace/rocket-chip_with_chisel3/../riscv_tools/cd8bc4798c38ba11118492474e96baf717c7af36/riscv64-unknown-elf/share/riscv-tests/isa/rv64uf-p-fsgnj', needed by `output/rv64uf-p-fsgnj'.  Stop.
```
> Remove tests obsoleted by new FP encoding proposal

- src/main/scala/rocket/Arbiter.scala
- src/main/scala/rocket/DCache.scala
- src/main/scala/rocket/HellaCache.scala
- src/main/scala/rocket/NBDcache.scala
- src/main/scala/rocket/PTW.scala
- src/main/scala/rocket/Rocket.scala
- src/main/scala/rocket/SimpleHellaCacheIF.scala
- src/main/scala/rocket/TLB.scala
- src/main/scala/rocket/TLBPermissions.scala
- src/main/scala/rocketchip/Generator.scala
- src/main/scala/rocketchip/RocketTestSuite.scala
- src/main/scala/uncore/tilelink2/Broadcast.scala
- Mitigate critical path for D$ exception reporting
- Send D$ grant acks early
- Cope with early grant acks in broadcast hub
- Cope with early release acks in D$
- Generate access exceptions for LR/SC on uncacheable memory (including scratchpad)
- Guarantee eventual probe forward progress for pessimal LR/SC sequences
> Grab bag of memory system improvements

- src/main/scala/rocketchip/DebugTransport.scala
Debug Transport Module was not passing back the busy or error responses it was getting or generating. Busy Response was just tied to 0.
> Correctly drive Debug Transport Module busy signal.

- src/main/scala/regmapper/RegMapper.scala
- src/main/scala/uncore/devices/Plic.scala
With this pipe here, devices which declare concurrency > 0
actually accept transactions on the same cycle they complete
the previous one. This is unexpected behavior.
> regmapper: remove the Pipe in the RegMapper Queue

- src/main/scala/rocketchip/DebugTransport.scala
- src/main/scala/uncore/devices/debug/Debug.scala
This simplifies SW design and CDC issues.
> debug: Make DMI NOPs really NOPs.

- src/main/scala/rocket/BTB.scala
- src/main/scala/rocket/CSR.scala
- src/main/scala/rocket/Frontend.scala
- src/main/scala/rocket/IBuf.scala
- src/main/scala/rocket/ICache.scala
- src/main/scala/rocket/Rocket.scala
- src/main/scala/rocketchip/RocketTestSuite.scala
- src/main/scala/tile/FPU.scala
- src/main/scala/util/Package.scala
- src/main/scala/util/ShiftQueue.scala
- Work in progress to improve the frontend, to simplify provisioning new frontend features in the future
- Bypass RAS push to improve CPI
- Reduce MMIO load latency by bypassing scoreboard update
- Use modified interrupt priority order (LIP > EIP > SIP > TIP)
- Use detect-tininess-after-rounding mode in hardfloat
> Various processor improvements

- src/main/scala/rocket/DCache.scala
When used with a RationalCrossing, pipelined MMIO does not come out cleanly.
The first beat works, but if the second beat gets stalled, the pipeline is
restarted. This is a quick hacky test to absorb the beats. Perhaps a better
fix can be made to achieve the same effect.
@aswaterman Amusingly, when this patch is combined with a 2:1 crossing, we
achieve the same exact waveform as with a certain other bad configuration, but
without the need for any hacks. MMIOs come out pipelined and there is only
a 5 cycle delay from load to dependent load. No fastLoadWord needed.
> dcache: put a flow Q to absorb back-pressure without restarting pipeline

- README.md
As pointed out, if we just point to 'master' branch, then people wouldn't get the correct list of dependencies.
This addresses #702
> point to riscv-tools README for dependencies

- src/main/scala/coreplex/RocketTiles.scala
- src/main/scala/rocket/Tile.scala
- src/main/scala/rocketchip/ExampleTop.scala
- src/main/scala/rocketchip/Periphery.scala
- src/main/scala/tile/Interrupts.scala
This does a more fine-grained synchronization for the different interrupt types and different synchronization types:
Within the Coreplex:
-- only debug interrupt is always fully asynchronous
-- Local Interrupts are always assumed to have been synchronized to core clock 
-- CLINT interrupt is known to be synchronous to core clock
-- PLIC interrupt is known to be synchronous to periphery clock, treat it accordingly
Additionally, there are now two subtraits of the PeripheryExtInterrupts (which becomes abstract). One which does the synchronization and one which assumes it has already been done.
There may still be some issues in the way the interrupt numbers are being assigned, still verifying this does what we want.
> Interrupts: Less Pessimistic Synchronization

- src/main/scala/rocket/ICache.scala
@solomatnikov found the bug.  It doesn't manifest in Rocket because the Frontend masks io.resp.valid with s2_valid.
> I$: Don't raise io.resp.valid if io.s1_kill was high previous cycle

- src/main/scala/rocket/Frontend.scala
Reduce pathological RVC stalls
> Increase frontend decoupling

- src/main/scala/rocket/Frontend.scala
9c1d12696552c70313c0c0ba22fef49287187d88 was an incomplete fix, so
sometimes we were requesting pipeline replays when they weren't
necessary.
> Fix RVC/uncacheable instruction memory performance bug

- src/main/scala/rocket/CSR.scala
This reverts commit ea0714bfcba3546e14cd022faafe8a4c0c27e968.
We've waffled on this matter in the priv spec: https://github.com/riscv/riscv-isa-manual/commit/326bec83de23f4d2daf24cfed6b5251748cad632
> Revert "rocket: hard-wire UXL/SXL fields to 0"

- src/main/scala/uncore/tilelink2/Fragmenter.scala
@hcook please try this out and let me know if it solves your problem.
> tilelink2: keep earlyAck Fragmenter sources distinct

- src/main/scala/diplomacy/Nodes.scala
- src/main/scala/rocketchip/Configs.scala
- src/main/scala/uncore/tilelink2/Monitor.scala
- src/main/scala/uncore/tilelink2/Nodes.scala
Forcing the bundles to exist early can mess up module ownership.
> diplomacy: provide connect access to edges without bundles

- regression/Makefile
This bumps riscv-tools and updates the Makefile flow so that the tests will pass (with VCS).
This is still not tested in the Travis regression. I have another branch that uses remote-bitbang that I will merge in a different PR.
> Debug Tests

- csrc/emulator.cc
- src/main/scala/uncore/tilelink2/Monitor.scala
- src/main/scala/util/PlusArg.scala
- vsim/Makefrag
- vsrc/plusarg_reader.v
This PR adds the ability to add a tilelink progress watchdog at runtime.
```./simv ... +tilelink_timeout=100```
will cause the Monitor to assert fail if no progress is made on a channel after 100 cycles.
This feature is currently not supported by verilator.
See: https://www.veripool.org/issues/1165
> Plusargs -- tilelink timeout detection from the command line

- src/main/scala/rocket/CSR.scala
- src/main/scala/rocket/PTW.scala
PTW now does not require atomic memory operations, so take out the requirement
Bug fix in CSR which manifest itself when compiling a config with no extension
> Fix issues when generating config ISA with no extension (I)

- csrc/jtag_vpi.c
The message is needed by other processes, and if the simulator output is not flushed, it can deadlock.
> jtag_vpi: Attempt to more aggressively flush the simulator output

- vsrc/jtag_vpi.tab
If -debug_pp is omitted, need to specify more in the PLI TAB file.
Again would like to get rid of all the VPI stuff entirely in the future.
> JTAG VPI: Make it work without debug_pp flag

- emulator/Makefrag-verilator
- vsrc/plusarg_reader.v
Once verilator 3.903 is released, util.PlusArgs will support it.
@scottj97 can you confirm the modified verilog still works on all the other tools?
> Verilator plusargs

- src/main/scala/coreplex/CoreplexNetwork.scala
- src/main/scala/rocket/TLB.scala
- src/main/scala/uncore/apb/Parameters.scala
- src/main/scala/uncore/axi4/Fragmenter.scala
- src/main/scala/uncore/axi4/Parameters.scala
- src/main/scala/uncore/tilelink2/Arbiter.scala
- src/main/scala/uncore/tilelink2/AtomicAutomata.scala
- src/main/scala/uncore/tilelink2/Parameters.scala
- src/main/scala/uncore/tilelink2/Xbar.scala
- src/main/scala/uncore/tilelink2/package.scala
This PR moves manager unification to being a pretty-print (DTS/address map) only modification. We use manager unification to recombine the L2 banks, for example. However, we don't want to apply it within the actual elaboration, because it can result in loss of information. In particular, FIFO domain information.
> Unify only at end

- .travis.yml
This should save us 24 minutes every time rocket PR queue gets busy.
> travis: front-load the longer running tests

- src/main/scala/rocket/Rocket.scala
This fixes a problem where an sbreak called in S-mode may cause an illegal instruction exception when the trap vector is a compressed instruction.
> Check for rvc before declaring illegal instruction after an ebreak.

- vsrc/plusarg_reader.v
vivado-2016.1 synthesis doesn't support SystemVerilog string type parameters
> changing SystemVerilog params to Verilog style

- src/main/scala/rocket/Frontend.scala
- src/main/scala/rocket/ICache.scala
specifically ones that would like to change the fetch width and number of
bytes in an instruction
This should keep the status quo for everyone but enable some new use-cases.
> refactor ICache to be reusable by other frontends

- src/main/scala/coreplex/Configs.scala
- src/main/scala/rocket/RocketTiles.scala
- src/main/scala/tile/LazyRoCC.scala
- src/main/scala/uncore/tilelink2/package.scala
This PR moves the RoCC interface to use Diplomacy and TileLink2.
This allows the memory channel parameters to be negotiated making RoCC configurations significantly simpler.
I've specified another TL Node type that allows the consumer to specify a single client node or use an output node to connect to multiple sub-modules. I think this strikes a nice implementation where the simple RoCC accelerators that do not use TL2 do not need any code in their accelerator relating to it.
I've also updated Hwacha to use this interface to ensure that more complicated uses behave as expected and everything is working on that front.
@hcook please review
@seldridge @zhemao are the others I know of using this interface that might have feedback.
> Move RoCC interface to Diplomacy and TL2

- emulator/Makefrag-verilator
* Originally verilator will generate a large cpp file containing a large
function, which costs about 13 min to compile. By using --output-split-cfuncs,
this large function will be splitted into several functions in servral
files. This will greatly improve the compile time with 'make -j'. By '-j32',
the compile time can be reduced to about 1 min.
> emulator,Makefile-verilator: add --output-split-cfuncs flag

- src/main/scala/rocket/DCache.scala
- src/main/scala/rocket/Frontend.scala
- src/main/scala/rocket/HellaCache.scala
- src/main/scala/rocket/IBuf.scala
- src/main/scala/rocket/NBDcache.scala
- src/main/scala/rocket/Rocket.scala
- src/main/scala/rocket/TLB.scala
- src/main/scala/uncore/util/Ecc.scala
- src/main/scala/util/Package.scala
- ECC on D$ RAMs
- Allow speculative I$ refill to cacheable regions (shaves ~5 cycles off I$ miss penalty)
- Reorganize D$ data RAMs to reduce read energy when TL width > Rocket width
- Forbid S-mode execution from user pages (priv-1.11)
- Several minor things
> Various memory system improvements

- src/main/scala/rocket/Frontend.scala
- src/main/scala/rocket/ICache.scala
- src/main/scala/rocket/RocketTiles.scala
- src/main/scala/rocket/ScratchpadSlavePort.scala
Instead of pointing from the dtim/itim to the cpu, have the cpu point to the dtim/itim.
This works better for those cases where a cpu is not visible but it's memory is.
> Flip dts itim and dtim references

- src/main/scala/uncore/devices/debug/Debug.scala
For an arbitrary DMI master on a fast clock running against a core
on a slow clock, there was a race between writing resumereq and
reading resumeack. When using JTAG DTM this does not occur in practice,
but clean it up for running simulations with FESVR and future DMI masters.
> debug: Fix race between resumereq and resumeack

- src/main/scala/uncore/tilelink2/SRAM.scala
- src/main/scala/uncore/tilelink2/TestRAM.scala
If you place an SRAM for main memory, make sure the 'reg' field is filled.
> SRAM: MemoryDevices use .reg (not .reg("mem"))

- src/main/scala/uncore/devices/Plic.scala
I tried the same trick on the 'completers' and dropped another 10% in output LoC. The if-elses are still pretty ugly for the completers so I didn't push it directly to the 'recode' PR #837 
This is also yet to be tested.
> plic: Use same recoding technique on complete as well as claim

- emulator/Makefile
I never quite understood why it used to be `run-bmarks-test` (as compared to `run-asm-tests`), but it looks like it's been changed everywhere else.
> Excise the last instance of run-bmarks-test

- src/main/scala/uncore/devices/Plic.scala
While the spec is unclear what happens when you access unused registers in the PLIC, for simplicity turn off register aliasing. If this becomes a performance/area issue we can revisit.
> PLIC: (undefZero=true) Don't allow addresses to alias

- src/main/scala/jtag/JtagTap.scala
The chisel2-style APIs are soon to disappear from the chisel3 core (they'll still be available in compatibility mode). It's time to switch to the chisel3 format.
> Use chisel3 Clock() method.

- src/main/scala/regmapper/RegField.scala
Create byte-sized read-write RegFields out of a large UInt register.
It is updated when any of the bytes are written. Because the RegFields
are all byte-sized, this is also suitable when a register is larger
than the intended bus width of the device (atomic updates are impossible).
> regmapper: add byte-sized RegField helper function

- src/main/scala/coreplex/RocketTiles.scala
- src/main/scala/diplomacy/Nodes.scala
- src/main/scala/diplomacy/Parameters.scala
- src/main/scala/rocket/HellaCache.scala
- src/main/scala/tilelink/FIFOFixer.scala
This makes it possible to decide which slaves are made mutually FIFO. For example, there is no need for rocket to serialize memory to an SRAM, just because it's not behind a coherence manager.
> Fifo fixer configable

- src/main/scala/chip/Configs.scala
- src/main/scala/chip/RISCVPlatform.scala
BootROM parameters currently control the boot rom address, size, and the
hang which essentially sets the reset vector. This commit allows specifying
different parameter values as required.
> bootrom: Adding bootrom parameters

- src/main/scala/chip/Periphery.scala
External is a better name because the interrupts are external to the system, but not necessarily to a chip.
> Rename offchip-interrupts to external-interrupts.

- src/main/scala/tilelink/Fuzzer.scala
If you don't mark "finished" specifically as output, it screws up inter-operation with code written in chisel3.
> Fix the TLFuzzer IO

- src/main/scala/regmapper/RegisterCrossing.scala
This gives a cloneType to RegisterWriteIO and RegisterReadIO so that it can be used in Wire definitions. Fixes #817.
> Add cloneType to RegisterWriteIO and RegisterReadIO

- src/main/scala/coreplex/Configs.scala
- src/main/scala/coreplex/PeripheryBus.scala
- src/main/scala/coreplex/RTC.scala
- src/main/scala/system/Configs.scala
This PR is the first step to refactor devices that need to know the PeripheryBus frequency to setup the default divisor value (e.g., UART).
> coreplex: retire RTCPeriod & introduce PeripheryBusParams.frequency

- src/main/scala/tilelink/Fragmenter.scala
No strictly necessary, because the initial value does not matter, but good hygiene since it drives a cycle of logic.
> tilelink: initialize toggle in Fragmenter

- src/main/scala/devices/tilelink/Error.scala
- src/main/scala/devices/tilelink/ROM.scala
- src/main/scala/devices/tilelink/TestRAM.scala
- src/main/scala/devices/tilelink/Zero.scala
- src/main/scala/rocket/ICache.scala
- src/main/scala/rocket/ScratchpadSlavePort.scala
- src/main/scala/tilelink/Broadcast.scala
- src/main/scala/tilelink/Bundles.scala
- src/main/scala/tilelink/CacheCork.scala
- src/main/scala/tilelink/Delayer.scala
- src/main/scala/tilelink/Edges.scala
- src/main/scala/tilelink/Fragmenter.scala
- src/main/scala/tilelink/HintHandler.scala
- src/main/scala/tilelink/Monitor.scala
- src/main/scala/tilelink/RegisterRouter.scala
- src/main/scala/tilelink/SRAM.scala
- src/main/scala/tilelink/ToAHB.scala
- src/main/scala/tilelink/ToAPB.scala
- src/main/scala/tilelink/ToAXI4.scala
When we first implemented TL, we thought this was helpful, because
it made WidthWidgets stateless in all cases. However, it put too
much burden on all other masters and slaves, none of which benefitted
from this signal. Furthermore, even with addr_lo, WidthWidgets were
information lossy because when they widen, they have no information
about what to fill in the new high bits of addr_lo.
> tilelink: remove obsolete addr_lo signal

- src/main/scala/amba/axi4/Test.scala
- src/main/scala/coreplex/SystemBus.scala
- src/main/scala/devices/tilelink/BusBypass.scala
- src/main/scala/devices/tilelink/Error.scala
- src/main/scala/diplomacy/Parameters.scala
- src/main/scala/system/ExampleRocketSystem.scala
- src/main/scala/tilelink/CacheCork.scala
- src/main/scala/tilelink/Parameters.scala
These cases exist:
GET_EFFECTS, PUT_EFFECTS, UNCACHEABLE && !supportsAcquire: MMIO
UNCACHED && !supportsAcquire: speculation ok and may be cached
UNCACHED && supportsAcquire: LLC/CacheCork applied (slave never probes)
CACHED, TRACKED && supportsAcquire: slave might probe
> tilelink: it is now legal to support Acquire for UNCACHED regions

- src/main/scala/coreplex/BaseCoreplex.scala
- src/main/scala/coreplex/RocketCoreplex.scala
- src/main/scala/tile/RocketTile.scala
The wrappers around the tiles needs to have consistent names, monitors, and boundary buffers to placate downstream toolflows.
> Stabilize tile wrappers for downstream tools

- src/main/scala/rocket/DCache.scala
- src/main/scala/rocket/RocketCore.scala
- Don't nack D$ misses when there's a pending store (reduces effective miss penalty from time to time)
- Bypass TLB refill signal to reduce effective L2 TLB hit time from 10 cycles to 5
- Merge D$ store hits when ECC is enabled, rather than flushing pipeline on D$ WAW hazards
- Improve fidelity of two perf counters
- Don't refill BTB on not-taken branches (this fixes a recent performance regression I made)
> Perf improvements

- src/main/scala/coreplex/MemoryBus.scala
- src/main/scala/tilelink/Filter.scala
- src/main/scala/tilelink/Map.scala
Now we can use TLFilter and TLMap to basically chop up and move around TileLink devices as we wish.
> Tilelink map

- src/main/scala/diplomacy/LazyModule.scala
This makes sure that all the base classes call instantiate()
> diplomacy: seal the LazyModuleImpLike trait

- regression/Makefile
- src/main/scala/tilelink/RAMModel.scala
The AMBA tests were failing because the Fuzzer now exercises the 'source reuse' option of TL. This interacted badly with the overlapped response detection of the RAMModel. The AXI4 tests exercised this case with legal response interleaving.
> Fix ram model source reuse

- src/main/scala/rocket/DCache.scala
This reverts commit 7d94074b05a91403dca88fb2f4195174d3f69f29, which
works fine with optimistic behavioral RAMs but not real ones.
> Revert "Remove one gate from D$ ECC check"

- src/main/scala/rocket/DCache.scala
- src/main/scala/rocket/Frontend.scala
- src/main/scala/rocket/NBDcache.scala
- src/main/scala/rocket/TLB.scala
Otherwise, it will attempt to perform AMOs where they're unsupported!
> Don't report to the DTIM that data is cacheable

- src/main/scala/rocket/DCache.scala
The tag RAMs tend to be fast, so take up some of the slack.
This makes s2_nack faster.
> Perform tag error detectoin/correction in same cycle as RAM

- src/main/scala/rocket/IBuf.scala
Don't examine a packet's xcpt signal if it might be invalid.  In this case,
the correct fix is to not examine xcpt at all; the deleted code was vestigial.
(Note, the other use of xcpt(j+1) in this code is indeed safe.)
> Fix IBuf bug

- src/main/scala/rocket/IBuf.scala
These appear to be equivalent, but the old one seems to fail in Vivado and
this one seems to pass.  This is not yet conclusive.
> Roll back use of UIntToOH1

- vsrc/plusarg_reader.v
Don't rely on 'initial' to run for synthesis.
> plusarg_reader: make synthesis path a no brainer

- src/main/scala/rocket/RocketCore.scala
The current TestDriver uses a +max-cycles plus arg to cleanly exit simulations after a certain number of simulation cycles. This works fine if your Core Clock is the same as your TestDriver clock, but this is not always the case. This PR adds an assertion within the core so that the max-core-cycles can be specified, which is always the same as what shows up in the processor trace.
> Add a +max-core-cycles PlusArg

- src/main/scala/util/HeterogeneousBag.scala
This lead to strange firrtl errors when you had two empty
HeterogeneousBags in the same Bundle.
> HeterogenousBag: empty bags were being combined!

- src/main/scala/tile/RocketTile.scala
Previously, the requirement for PAddrBits only checked to be equal or greater than the bundle bits. Changing it to check for these to match exactly as for cases when the PAddrBits greater than address bits we could run into scenarios which cause possible address wrap around issues.
@aswaterman @terpstra review requested
> Fixing requirements for PAddrBits

- vsrc/AsyncResetReg.v
This adds the same code emitted by FIRRTL for squashing Xs in registers, memories, etc to the AsyncResetReg black box, so that they have the same behavior. This is important for simulations which may not actually assert reset at time 0, regardless of the clocking.
> async_reset_reg: Squash X's the same as for synchronous reg

- src/main/scala/coreplex/SystemBus.scala
These functions were actually for cross connecting chips.
> SystemBus: remove misnamed functions

- src/main/scala/coreplex/SystemBus.scala
Otherwise you end up with a lot of TLBuffer_1, TLBuffer_17
> systemBus: allowing naming the TLBuffers which get inserted

- src/main/scala/diplomacy/Parameters.scala
- src/main/scala/tilelink/Buffer.scala
TLBuffer has various properties which aren't immediately clear from the current graphml output. This PR adds them to the nodedebugstring. When using yEd, this string shows up when you click on the node. For example, this is from the DefaultConfig:
> TLBuffer: Add a nodedebugstring 

- src/main/scala/coreplex/SystemBus.scala
- src/main/scala/devices/tilelink/Error.scala
For any normal (not memory) slaves on the SystemBus, use a full buffer. The only slave directly on the SystemBus in rocket is the error device, so remove it's manually placed buffer. Also, lift the burden of fixing FIFOness of periphery slaves from the system bus.
> SystemBus: add output buffering

- src/main/scala/jtag/JtagTap.scala
There may be a better way to do this, but this is sufficient to get tests to pass with current chise3.
> Jtagresettobool - add explicit toBool cast now required on reset.

- vsrc/jtag_vpi.v
Otherwise if init_done is driven from something that isn't initialized at time-zero, this may not work properly.
> jtag_vpi: add some hysteresis for waiting for init_done

- src/main/scala/rocket/DCache.scala
This assertion made sure the D$ controller was able to write the tag RAM
when a cache line was refilled.  However, it is benign if it fails to do
so: the metadata is invalid at this point, so the miss will simply happen
a second time.
This happens when resolving a tag ECC error during hit-under-miss.
> Remove overzealous assertion

- src/main/scala/rocket/DCache.scala
Since the correction updates the entire word, the WAW hazard detection
logic is not sufficient to prevent overwriting a recent store.  So,
re-read the word after all pending stores have drained.
> Don't perform in-place correction if there was a recent store

- src/main/scala/coreplex/BaseCoreplex.scala
- src/main/scala/coreplex/Configs.scala
- src/main/scala/coreplex/ResetVector.scala
- src/main/scala/coreplex/RocketCoreplex.scala
- src/main/scala/coreplex/SystemBus.scala
- src/main/scala/devices/tilelink/BootROM.scala
- src/main/scala/groundtest/Configs.scala
- src/main/scala/rocket/Frontend.scala
- src/main/scala/rocket/ScratchpadSlavePort.scala
- src/main/scala/rocket/TLB.scala
- src/main/scala/tile/BaseTile.scala
- src/main/scala/tile/Core.scala
- src/main/scala/tile/FPU.scala
- src/main/scala/tile/L1Cache.scala
- src/main/scala/tile/RocketTile.scala
> Remove global fields PAddrBits and ResetVectorBits

- src/main/scala/config/Config.scala
- src/main/scala/coreplex/Configs.scala
- src/main/scala/coreplex/FrontBus.scala
- src/main/scala/coreplex/InterruptBus.scala
- src/main/scala/coreplex/MemoryBus.scala
- src/main/scala/coreplex/PeripheryBus.scala
- src/main/scala/coreplex/Ports.scala
- src/main/scala/coreplex/RTC.scala
- src/main/scala/coreplex/RocketCoreplex.scala
- src/main/scala/coreplex/SystemBus.scala
- src/main/scala/devices/debug/DebugTransport.scala
- src/main/scala/devices/debug/Periphery.scala
- src/main/scala/devices/tilelink/Clint.scala
- src/main/scala/devices/tilelink/Plic.scala
- src/main/scala/diplomacy/DeviceTree.scala
- src/main/scala/diplomacy/package.scala
- src/main/scala/groundtest/Configs.scala
- src/main/scala/rocket/TLB.scala
- src/main/scala/system/Configs.scala
- src/main/scala/tilelink/Bus.scala
- src/main/scala/tilelink/Fragmenter.scala
- src/main/scala/tilelink/Parameters.scala
Diplomacy now provides the `x"..."` string context, which converts string literals representing hexadecimal numbers into `BigInt`s. You can insert arbitrary underscores, e.g., `x"8000_0000_0000"` instead of `BigInt(0x800000000000)`.
Config now provides optional default values for `Field` objects that are used as lookup keys. However, using the same class names for key objects as the case class name of the value they are holding results in `illegal cyclic reference`, so I'm trying to start walking back that anti-pattern.
Closes #962, closes #892
> Clean up various Configs/Fields/Params

- src/main/scala/devices/debug/Debug.scala
- src/main/scala/devices/debug/Periphery.scala
- src/main/scala/util/PSDTestMode.scala
- src/main/scala/util/ResetCatchAndSync.scala
Generally, any generated resets need a test mode override to allow controllability of the resets during post-silicon-testing. Since all resets are (or should be) generated with the ResetCatchAndSync utility, add this functionality there. This is disabled by default so should have no effect until it is turned on with the Config parameter.
> reset_catch: Allow Test Mode Overrides

- src/main/scala/rocket/DCache.scala
- src/main/scala/rocket/ICache.scala
- src/main/scala/rocket/NBDcache.scala
- src/main/scala/rocket/PTW.scala
allow the instance name to disambiguate without reference to the full hierarchical path
> try to give seqmems clearer names for use with external tools

- src/main/scala/coreplex/RocketCoreplex.scala
- src/main/scala/rocket/BusErrorUnit.scala
- src/main/scala/rocket/DCache.scala
- src/main/scala/rocket/Frontend.scala
- src/main/scala/rocket/HellaCache.scala
- src/main/scala/rocket/ICache.scala
- src/main/scala/rocket/RocketCore.scala
- src/main/scala/rocket/ScratchpadSlavePort.scala
- src/main/scala/tile/Core.scala
- src/main/scala/tile/RocketTile.scala
- src/main/scala/util/ECC.scala
- src/main/scala/util/ShiftReg.scala
This reports correctable and uncorrectable ECC errors to a unit which sends interrupts to the PLIC.
Some TODOs/requests for feedback:
- Is the integration of this unit in CanHaveScratchpad and RocketTileWrapper done right?
- Should add a crossbar inside CanHaveScratchpad so the ITIM/DTIM/BEU only have one port to the outside.  But since they all have slightly different widths/capabilities, it's not abundantly clear how to do that.
- Need to handle/report TL errors for cached & uncached memory accesses.
- Need to write a software test for the above.
> Add L1 bus-error unit

- src/main/scala/rocket/CSR.scala
It's optional, and we were doing it wrong before, so just don't do it.
> Don't write badaddr on misaligned fetch exceptions

- vsrc/AsyncResetReg.v
Due to the way verilog simulates async reset registers, if reset was already positive then you use the initialize to put in a random initial value, it won't get cleared even if rst is asserted.
> async_reset_reg: Don't randomize the register if rst is asserted anyway

- src/main/scala/rocket/DCache.scala
- src/main/scala/rocket/ICache.scala
- src/main/scala/rocket/NBDcache.scala
- src/main/scala/rocket/PTW.scala
- src/main/scala/tile/RocketTile.scala
- src/main/scala/util/ECC.scala
- src/main/scala/util/Misc.scala
Adds optional support for signaling unrecoverable errors [1] out of the tiles. For now, such a condition can only be triggered by uncorrectable ECC errors occurring in either the DCache or ICache. 
[1] https://en.wikipedia.org/wiki/Halt_and_Catch_Fire
> Halt and Catch Fire

- src/main/scala/coreplex/Configs.scala
- src/main/scala/coreplex/MemoryBus.scala
- get `Parameters` from the calling `coreplex`
- allow managers to signal unrecoverable/`halt`
- add a `TLWidthWidget` between system bus and memory bus, behind manager
Closes #991 , closes #1010
> coreplex: clean up coherence manager attachment point

- src/main/scala/coreplex/RocketCoreplex.scala
- src/main/scala/tile/RocketTile.scala
From tile wrapper (fast clock) to coreplex (slow clock)
> Move rocket output interrupt syncronizers

- src/main/scala/amba/ahb/SRAM.scala
- src/main/scala/amba/apb/SRAM.scala
- src/main/scala/amba/axi4/SRAM.scala
- src/main/scala/diplomacy/SRAM.scala
- src/main/scala/tilelink/SRAM.scala
Make it easier to give diplomatic SRAMs predictable names, DRY out some of the common internals
> diplomacy: standardize sram device resource naming

- src/main/scala/devices/tilelink/Error.scala
- src/main/scala/tilelink/CacheCork.scala
Grant messages should match the Acquire they respond to. Nevertheless, a Grant error always means you must not retain ownership of the block and retry the Acquire.
> Error grants

- src/main/scala/coreplex/RocketCoreplex.scala
- src/main/scala/rocket/HellaCache.scala
- src/main/scala/system/ExampleRocketSystem.scala
- src/main/scala/system/TestHarness.scala
- src/main/scala/util/Misc.scala
- Const prop cannot shove hartid into the tile
- Keep all dcache resp fields
- Keep all system-level top ports
Closes #964, closes #966
> Make use of the new DontTouch annotation

- src/main/scala/coreplex/RocketCoreplex.scala
- src/main/scala/coreplex/SystemBus.scala
This isn't at all prettier, but it gets rid of one potential inconsistency in the definitions of these parameters.
> Get rid of paddrBits from SystemBus

- src/main/scala/coreplex/Configs.scala
- src/main/scala/coreplex/RocketCoreplex.scala
- src/main/scala/rocket/HellaCache.scala
- src/main/scala/system/Configs.scala
- src/main/scala/system/ExampleRocketSystem.scala
- src/main/scala/system/TestHarness.scala
- src/main/scala/tile/RocketTile.scala
- src/main/scala/util/Misc.scala
- revert #1027, bugs in DontTouch wrt tile dedup and DCE
- allow non-contiguous hartids via parameter in RocketTileParams
- make WithNCores partial configs override rather than append more tiles
> Miscellaneous multicore cleanup

- src/main/scala/rocket/DCache.scala
- src/main/scala/rocket/NBDcache.scala
- src/main/scala/tilelink/Atomics.scala
- src/main/scala/tilelink/Broadcast.scala
- src/main/scala/tilelink/Bundles.scala
- src/main/scala/tilelink/CacheCork.scala
- src/main/scala/tilelink/Edges.scala
- src/main/scala/tilelink/Monitor.scala
- src/main/scala/tilelink/RAMModel.scala
We had planned for a while to add an 'Overwrite' message which obtains
permissions without requiring retrieval of data. This is useful whenever
a master knows it will completely replace the contents of a cache block.
Instead of calling it Overwrite, we decided to split the Acquire case.
If you AcquirePerm, you MUST Release and ProbeAck with Data.
> tilelink: split Acquire into Acquire{Block,Perm}

- src/main/scala/tile/BaseTile.scala
Require and/or force vaddrBits to be bigger than paddrBits so there's room to zero-extend a physical address by 1 bit, so that when the virtual address is sign-extended, the sign is zero.
> Fix paddrBits < xLen && paddrBits == vaddrBits case

- src/main/scala/tile/RocketTile.scala
Just reorder the construction to ensure the val is created soon enough.
> RocketTile: make sure 'hartid' is available for traits

- src/main/scala/devices/tilelink/Clint.scala
- src/main/scala/regmapper/RegField.scala
Update to use more powerful API. Makes for a better piece of example code.
> clint: use RegField.toBytes to save some work

- src/main/scala/coreplex/BaseCoreplex.scala
- src/main/scala/coreplex/RocketCoreplex.scala
Also names some IntXBars for easier understanding of the emitted code / graphml.
Previously, `localIntNodes` were created any time someone called myModule.localIntNodes, which I don't think was the intention. Change the `def` to a `lazy val` so that they only get created once and the same copy is used every time.
> Correctly hook up the Local Interrupts into the Coreplex. 

- src/main/scala/amba/axi4/AsyncCrossing.scala
- src/main/scala/amba/axi4/Test.scala
- src/main/scala/coreplex/Ports.scala
- src/main/scala/tilelink/ToAXI4.scala
We used to pack the addr_lo into user bits. We don't do that anymore.
There is thus no need to waste those bits, nor to pass that arg.
> axi4: conversion from TL does not need beatBytes

- src/main/scala/tilelink/Parameters.scala
... now reports whether a address space could ever possibly be cached, even if no visible adapters make it support Acquire transactions.
From the perspective of software, the necessary resource information is whether the address space is part of cacheable shared memory, or volatile memory-mapped IO. Whether a particular client can actually cache it depends on the capabilities of the interstitial adapters.
> tilelink: cacheable resource permission 

- src/main/scala/tile/RocketTile.scala
Before it was possible to have your hartid truncated and not realize it.
I am not sure this is the right place to put this, is it expected that all subclasses of `HartedTile` would have this same requirement? Or  is this specific to RocketTiles?
> Add a check that MaxHartIdBits is enough for all hartids

- src/main/scala/rocket/CSR.scala
- src/main/scala/rocket/RocketCore.scala
* CSR provides a decode port to check for an illegal instruction.
* This commit now allows for multiple instructions in decode to get this
illegal instruction information.
* This commit leverages the existing decodeWidth parameter. This will
potentially over-provision the number of decode ports needed for
RVC-enabled cores.
Closes #1068
> csr: allow for superscalar decode

- src/main/scala/rocket/ScratchpadSlavePort.scala
Fragmenters currently cost a register equal in size to a full address. Still, I bet the area trade-off is a wash since we save a FIFOFixer. I think we also remove those Fragmenter registers elegantly by adding an 'irrevocable' flag to ClientPortParameters, which I intend to do in a follow-up PR.
> tile: don't chain too many unneeded TileLink adapters

- src/main/scala/rocket/ICache.scala
Workaround: disable interrupts and then do:
.align 3
sb x0, (t0) # t0 contains ITIM-deallocate address
fence.i
> Fix ITIM bug overwriting I$ contents when deallocating ITIM

- src/main/scala/interrupts/Crossing.scala
Otherwise you can get interrupts wedged high from a domain that has
not yet been clocked/powered up.
> interrupts: Crossing should use asynchronously reset registers

- src/main/scala/devices/tilelink/BusBypass.scala
When switching ports, the bypass stalls new messages until all
outstanding messages have received their responses. However, this
stall must NOT stop the remaining beats of a partially sent request.
> BusBypass: only stall A once the last beat is accepted

- src/main/scala/coreplex/Configs.scala
- src/main/scala/system/Configs.scala
`RocketCrossingKey` now controls the corking of incoherent tile caches.
@terpstra TODO: make the default `BankedL2Key` (with BroadcastHub) do the right thing when `NTILES == 1`
> coreplex: WithStatelessBridge => WithIncoherentTiles

- src/main/scala/rocket/ScratchpadSlavePort.scala
- src/main/scala/tilelink/Fragmenter.scala
It seems quite common to have a device that is backed by ECC. When
performing a multibeat PutPartial, these devices can exhibit their
first error on the last beat (if it had an incomplete write mask
for that beat, which required read-write-modifying corrupted data).
Generally, these devices have ECC granularity <= the bus width. In
those cases, if you send a PutFull, the first beat carries the
error value for the whole burst. Consider:
If the PutFull was below the granularity, it was a single beat.
If the PutFull was multi-beat, it exceeds the granularity.
Therefore, an important variation on the earlyAck optimization is
the case where only PutFulls receive an earlyAck.
> Fragmenter: add an option for earlyAck only on PutFulls

- src/main/scala/rocket/ICache.scala
needs to use RocketTileParams.hartid instead of zipWithIndex
> rocket: fix itim GetPropertyByHartId

- src/main/scala/tilelink/AtomicAutomata.scala
- src/main/scala/tilelink/Parameters.scala
- src/main/scala/tilelink/ToAHB.scala
- src/main/scala/tilelink/ToAPB.scala
- src/main/scala/tilelink/Xbar.scala
This tree test method will also be useful in a forth-coming PR.
> tilelink: don't pollute TLParamters with AtomicAutomata's implementation

- src/main/scala/coreplex/RocketCoreplex.scala
- src/main/scala/devices/tilelink/BusBlocker.scala
- src/main/scala/groundtest/TraceGen.scala
- src/main/scala/rocket/ScratchpadSlavePort.scala
- src/main/scala/tile/BaseTile.scala
- src/main/scala/tile/RocketTile.scala
...instead of on the master side of the system bus.
Child `Tile` classes inheriting from `HasTileMasterPort` but not `HasScratchpadSlavePort` might need to add `masterNode := tileBus.node` by hand, sorry (cc/ @ccelio)
> tile: put a BasicBusBlocker inside RocketTile

- src/main/scala/rocket/ICache.scala
Deallocation can change repl_way, which violates the assumption that it remains constant throughout refill.
The workaround described in commit 3db066303b16f6ac6688cdc2f48d7ff066e4b52b still suffices, provided only the hart that owns the ITIM changes the ITIM allocation.
This subsumes commit 3db066303b16f6ac6688cdc2f48d7ff066e4b52b.
> Fix ITIM deallocation during I$ refill causing data corruption

- src/main/scala/rocket/DCache.scala
This esoteric bug manifests if a tag-read error occurs when a FENCE.I is executed, even if the error was correctable.  Subsequently, an attempt to flush a dirty line may flush the wrong line's data.
> Avoid data corruption under correctable tag error during flush

- regression/Makefile
Factor out gdbserver common invocation into GDBSERVER (fixing
--print-failtures).
Add --print-log-names to that command so the logfiles can be inspected
while the simulation is still running.
`RISCV=... cmd` is more idiomatic than `export RISCV=... && cmd`
> Cleanups, and print out log names ASAP.

- src/main/scala/devices/debug/Debug.scala
- src/main/scala/regmapper/RegField.scala
The debug module and all slaves using RegField.bytes were out-of-spec.
This degrades QoR and could potentially create a combinational loop at some design points.
> TileLink compliance: d_bits may not depend on d_ready

- src/main/scala/coreplex/CrossingWrapper.scala
- src/main/scala/coreplex/FrontBus.scala
- src/main/scala/coreplex/PeripheryBus.scala
- src/main/scala/coreplex/RocketCoreplex.scala
- src/main/scala/coreplex/SystemBus.scala
- src/main/scala/diplomacy/Nodes.scala
- src/main/scala/diplomacy/package.scala
- src/main/scala/tilelink/Bus.scala
The reason for the `:=?` operator was for when you have an adapter chain
whose direction of cardinality you could not know. We used explicit
directives to tell these compositions which way to go.
Unfortunately, that makes the API leaky. You think the chain of adapters
is just one adapter, but you have to use strange Cardinality scopes to
use it. That's just bad.
The new `:*=*` just automagically figures it out from the graph.
> diplomacy: remove the :=? operator in favour of magic :*=*

- src/main/scala/rocket/Frontend.scala
After detecting a corrupted BTB, don't speculatively update it until the next non-speculative fetch.  This prevents the frontend from replaying forever.
> Prevent frontend deadlock fetching from uncacheable memory

- src/main/scala/coreplex/BaseCoreplex.scala
- src/main/scala/coreplex/Configs.scala
- src/main/scala/coreplex/HasTiles.scala
- src/main/scala/coreplex/RocketCoreplex.scala
- src/main/scala/diplomacy/SRAM.scala
- src/main/scala/diplomacy/package.scala
- src/main/scala/groundtest/Coreplex.scala
- src/main/scala/groundtest/Tile.scala
- src/main/scala/groundtest/TraceGen.scala
- src/main/scala/rocket/Frontend.scala
- src/main/scala/rocket/HellaCache.scala
- src/main/scala/rocket/ICache.scala
- src/main/scala/rocket/PTW.scala
- src/main/scala/rocket/ScratchpadSlavePort.scala
- src/main/scala/tile/BaseTile.scala
- src/main/scala/tile/Core.scala
- src/main/scala/tile/FPU.scala
- src/main/scala/tile/Interrupts.scala
- src/main/scala/tile/L1Cache.scala
- src/main/scala/tile/LazyRoCC.scala
- src/main/scala/tile/RocketTile.scala
- src/main/scala/tilelink/SRAM.scala
HasTiles now deals with only extremely general tile IOs.
Some RocketTiles specific behavior moved into RocketCoreplex.
BaseTile now has optional LocalInterruptNode.
> coreplex: make HasTiles more generic

- src/main/scala/rocket/RocketCore.scala
- src/main/scala/rocket/TLB.scala
When xLen > paddrBits, enforce that physical addresses are zero-extended.  This works by checking that the _virtual_ address is _sign_-extended, then checking that its sign is positive.
The regression test is here: https://github.com/riscv/riscv-tests/commit/03447f08863f1f25243c52a2139d0c968157a9f8
> Enforce physical-address canonicalization

- src/main/scala/devices/tilelink/Error.scala
- src/main/scala/rocket/DCache.scala
- src/main/scala/tilelink/Parameters.scala
The DCache needs all executable regions be tracked, or else it has to be flushed on FENCE.I at significant performance cost.
(https://github.com/freechipsproject/rocketchip/blob/master/src/main/scala/rocket/DCache.scala#L725)
However, we marked the ErrorDevice executable in 6a0150aad72f4e3a34f1f9d674a6c185f7e30fcc to facilitate I$ testing.  We either need to revert that change, or we need to mark the ErrorDevice as TRACKED, or we need to special-case the DCache check to ignore the ErrorDevice.
This option seems least undesirable.
> Claim that ErrorDevice is TRACKED

- src/main/scala/coreplex/Ports.scala
Fixes #1175
@hcook Maybe we should consider an alternative design pattern for these diplomacy-IO connections. This is like the fourth time I've seen this bug. Even a zipEq that requires the two lists to be equal length would be an improvement. Or maybe better still we can have some sort of API that packages more of the plumbing.
> Fix TL MMIO port

- src/main/scala/rocket/HellaCache.scala
In accordance with https://github.com/freechipsproject/chisel3/issues/752
> Dual-port RAM replaced with single-port RAM for tag_array in HellaCache

- .travis.yml
- csrc/SimDTM.cc
- csrc/SimJTAG.cc
- csrc/emulator.cc
- csrc/remote_bitbang.cc
- csrc/remote_bitbang.h
- emulator/Makefile
- regression/Makefile
- scripts/RocketSim.cfg
- scripts/RocketSim.py
- scripts/RocketSim32.py
- scripts/RocketSim64.py
- src/main/scala/devices/debug/Periphery.scala
- src/main/scala/system/Configs.scala
- vsim/Makefrag
- vsrc/AsyncResetReg.v
- vsrc/SimJTAG.v
Refactored version of #1088 . Includes #597.
This does a few things:
* Adds some simple tests of the JTAG debug interface to the regression
* bumps rocket-chip including @seldridge's PR #597
* requires `sudo` image from Travis, because that is what is needed now to build riscv-tools.
> Add Debug tests to Regressions

- csrc/verilator.h
I ran into a compilation issue.
This link explains the problem well: https://stackoverflow.com/a/5499222/3736700
For example, in a header file, it is generally not considered a good idea to put the line using namespace std; (or to use any namespace, for that matter) because it can cause names in files that include that header to become ambiguous. In this setup, you would just #include <string> in the header, then use std::string to refer to the string type.
> remove string type ambiguity in header

- src/main/scala/diplomacy/LazyModule.scala
This PR makes it possible to access a node's bundles from within instantiate()
> diplomacy: run user instantiate() method after nodes are initialized

- csrc/remote_bitbang.cc
For whatever reason, my system (OS X) threw errors related to interpreting this call to `bind` as `std::bind` instead of `::bind`.
Has anyone else seen this?
> Use bind from global namespace

- build.sbt
- src/main/scala/devices/tilelink/Clint.scala
- src/main/scala/devices/tilelink/Plic.scala
- src/main/scala/regmapper/RegField.scala
- src/main/scala/tilelink/RegisterRouter.scala
This is a first stab at functionality we need to enable, but don't think this is really the right place to do it.
We should be able to take in register maps as JSON inputs and output them as JSON for a register map created by a Chisel coder. 
As a strawman this PR changes it so that all `TLRegMapper` devices output an XSVD format description (https://xpack.github.io/xsvd/) which is basically a simplified , JSON-based subset of IP-XACT.
Some obvious problems with this right now:
- A lot of info has to be manually specified by the user (as noted by @terpstra  on #1183)
- XSVD, IP-XACT, etc often deal with "Registers" or "RegisterArrays", which contain "Fields". Right now the `RegField.Map` offers no way to enter any sort of name/description or other properties at that level. Only `RegField` …
> TLRegMapper: emit a JSON file describing the register fields

- build.sbt
- src/main/scala/devices/debug/Debug.scala
- src/main/scala/devices/tilelink/Clint.scala
- src/main/scala/devices/tilelink/Plic.scala
- src/main/scala/regmapper/RegField.scala
- src/main/scala/regmapper/RegMapper.scala
- src/main/scala/tilelink/Example.scala
- src/main/scala/tilelink/RegisterRouter.scala
Previously, RegField took a `name` and `description` string. This isn't really sufficient for flows that may want to use the designer's knowledge, especially whether the register was reset or not, whether it is R/W, or what (R/W behavior may be abled to get extracted automatically sometimes, but not always).
This replaces the two strings with a more descriptive case class that can be populated by the RegField author and used by other flows.
> more detailed RegField descriptions

- src/main/scala/devices/tilelink/Error.scala
- src/main/scala/rocket/HellaCache.scala
- src/main/scala/tilelink/CacheCork.scala
- src/main/scala/tilelink/Parameters.scala
Prior to this PR, the error device was allowed to be cached by
multiple actors despite never probing any of them. This is a
pretty unusual set of properties that has caused us trouble
several times now in the past.
Let's instead put the Error device into one of two very well
established categories: a straight-up MMIO device or a tracked
memory region.
> Error: don't be an exception wrt. caching

- csrc/emulator.cc
- csrc/remote_bitbang.cc
The error code for the remote bitbang JTAG wasn't being initialized. This sets it to zero by default (note: this doesn't seem to be set anywhere, currently). @mwachs5: can you take a look and see if this is right for a quick fix? Currently VCD runs seem to be returning an exit code (unnecessarily), though the exit code is due to reading an uninitialized variable.
Additionally this adds user-visible differentiation to why an emulator got an error code.
- Fixes #1240.
- Fixes #1236
> Clarify errors, init jtag error code to zero

- src/main/scala/tilelink/RegisterRouter.scala
If registers aren't described, we at least output that such a field exists. But previously they had bad names, where the intention was to give them some sort of unique name.
> RegFieldDesc: fix the output produced for undescribed registers

- src/main/scala/tile/RocketTile.scala
The TL port can easily starve the processor, even at only 20% utilization,
because of a bad interaction with the pipeline.  Giving the processor
static priority is OK in practice, since <50% of instructions are loads
and stores in typical workloads.  Even if it executes 100% loads and stores,
it must eventually encounter an I$ miss, taken branch, or exception, so
even malicious code can't permanently starve the TL port.
> Give Rocket priority over DTIM TL port

- src/main/scala/coreplex/Configs.scala
- src/main/scala/devices/debug/Debug.scala
- src/main/scala/devices/debug/Periphery.scala
- src/main/scala/devices/tilelink/Clint.scala
- src/main/scala/devices/tilelink/Plic.scala
- src/main/scala/rocket/CSR.scala
- src/main/scala/rocket/DCache.scala
- src/main/scala/rocket/HellaCache.scala
- src/main/scala/rocket/RocketCore.scala
- src/main/scala/system/Generator.scala
- src/main/scala/system/RocketTestSuite.scala
- src/main/scala/tile/Core.scala
- src/main/scala/tile/FPU.scala
Most of this PR is cleaning up abuse of the XLen parameter; Rocket and the FPU were almost ready to support RV32D.
> Support fLen > xLen

- src/main/scala/rocket/CSR.scala
- src/main/scala/rocket/RocketCore.scala
This removes undefined behavior when clearing the misa.C bit when the PC is not currently aligned.  The manner in which it is fixed is still up for debate, but better to remove the undefined behavior in the mean time.  See https://github.com/riscv/riscv-isa-manual/pull/139
> Implement misa.C proposal

- vsim/Makefrag
I wasn't able to build a VCS version without this. @mwachs5: seem reasonable to include jtag_vpi.c here?
This should fix https://github.com/freechipsproject/rocket-chip/issues/1061. This is mentioned in https://github.com/ucb-bar/riscv-boom/issues/38.
> Add jtag_vpi.c to sources for vsim

- src/main/scala/rocket/RocketCore.scala
AMO.aq should be implemented as AMO;FENCE, whereas AMO.rl should be implemented as FENCE;AMO.  These had been swapped.  This error does not affect cacheable accesses using the blocking D$, nor does it affect accesses to the data scratchpad, nor does it affect accesses to strongly ordered I/O regions (which is the default).
Cacheable accesses using the nonblocking D$ and accesses to weakly ordered I/O regions may manifest memory-ordering violations.  For these accesses, the workaround is to use AMO.aqrl whenever AMO.aq or AMO.rl had been used.
> Fix mapping of acquire/release AMOs to fence operations

- src/main/scala/tile/LazyRoCC.scala
This aligns the RoCC interface with the new cloneType. Simple fix, just make `outer` a `val` like was done in #1232. I'm testing this now.
I lament the state of RoCC regression tests... :sob:
> Align RoCCIO with new cloneType

- vsim/Makefrag
- vsim/Makefrag-verilog
When running with VCS all arguments are exposed directly to HTIF. This differs with Verilator/emulator.cc where only the arguments that HTIF is supposed to see are provided (specifically, host and target arguments).
This uses new `+permissive` and `+permissive-off` options for HTIF that will enable permissive argument parsing by HTIF temporarily. This means that HTIF will, instead of treating the first argument that it doesn't understand as the target binary, ignore any option it doesn't understand. This enables using whatever VCS option a user wants to use.
Without this, VCS isn't usable, e.g., HTIF will think that `+verbose` is the binary and error on that.
Currently, @colinschmidt and @ccelio are affected.
Requires:
> Fix VCS argument parsing

- src/main/scala/regmapper/Annotation.scala
- src/main/scala/regmapper/RegField.scala
- src/main/scala/tilelink/RegisterRouter.scala
Preserves existing output file names and content format.
@mwachs5 If you are going to make further changes to the RegFieldDesc format, can you pull this in and make your changes on top of it? Otherwise feel free to ignore until I finish the broader annotation PR.
> regmapper: refactor how json is emitted

- src/main/scala/tilelink/RAMModel.scala
I noticed the 0x was missing the x in the RAMModel printouts.
> Fix typo in RAMModel Get printf

- csrc/emulator.cc
With -DVM_TRACE=1 on gcc 7.2.0.
Very small change.  May only affect me.  Is it possible -DVM_TRACE=1 is not regressed?
~~~~
http://en.cppreference.com/w/cpp/memory/unique_ptr
[..]/emulator.cc: In function ‘int main(int, char**)’:
[..]/emulator.cc:254:8: error: ‘unique_ptr’ is not a member of ‘std’
std::unique_ptr<VerilatedVcdFILE> vcdfd(new VerilatedVcdFILE(vcdfile));
~~~~
More info : http://en.cppreference.com/w/cpp/memory/unique_ptr
Output of gcc -v:
~~~~
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/7/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 7.2.0-8ubuntu3.2' --with-bugurl=file:///usr/share/doc/gcc-7/README.Bugs …
> Header required for -DVM_TRACE=1

- src/main/scala/devices/debug/Debug.scala
- src/main/scala/devices/debug/abstract_commands.scala
- src/main/scala/devices/debug/dm_registers.scala
RISC-V Debug spec was recently updated to support more than 1024 harts. This change was made backwards compatible for systems with up to 32 harts, but some registers names changed and some fields were added/renamed.
Although the RISC-V debug spec now supports 2^20 harts, rocket-chip still only allows up to 1024 harts.
This PR also brings in the changes to the System Bus Access registers  version 1, and should probably be merged before #1286
> Update Debug Module registers

- src/main/scala/rocket/CSR.scala
- src/main/scala/rocket/RocketCore.scala
See https://github.com/riscv/riscv-isa-manual/commit/0472bcdd166f45712492829a250e228bb45fa5e7
- Reads of xEPC[1] are masked when RVC is disabled
- Writes to MISA are suppressed if they would cause a misaligned fetch
- Misaligned PCs no longer need to be checked in decode
> Implement Hauser misa.C misalignment proposal

- src/main/scala/groundtest/GroundTestSubsystem.scala
- src/main/scala/subsystem/FrontBus.scala
- src/main/scala/subsystem/MemoryBus.scala
- src/main/scala/subsystem/PeripheryBus.scala
- src/main/scala/subsystem/Ports.scala
- src/main/scala/subsystem/SystemBus.scala
- src/main/scala/tilelink/BusWrapper.scala
Just take a single BufferParams for all couplers.
Add TLBuffer.chain in the thunk if you need it.
Preserves default bufferings.
> buswrapper: remove buffer chains from api

- src/main/scala/diplomacy/SRAM.scala
- src/main/scala/tilelink/SRAM.scala
- src/main/scala/unittest/Configs.scala
As described in the code, this SRAM uses either RMW with back-to-back SRAM read-write or a direct W if the operation is larger than the ECC granularity.
> TLRAM: add support for ECC

- src/main/scala/rocket/RocketCore.scala
- src/main/scala/tilelink/Buffer.scala
- src/main/scala/util/PlusArg.scala
PlusArg.timeout provides a wrapper module that has no outputs, which is nice for recognizing that the PlusArg blackbox is being used in simulation only.
> PlusArg.timeout

- src/main/scala/rocket/Events.scala
For EventSets defined by the designer, provide a mechanism to also add functional coverage for those events.
The intent here is to have the functional cover on the input of the event logic cone (before Event selection) since functional covers are not synthesized and do not consume downstream HW resources (i.e. counters).
Note: it looks like FIRRTL is not able to determine that some of these events are unhittable (i.e. `("event_name", () => false.B)`)
> Events with functional covers

- build.sbt
My use case is:  I want to update my local repo to HEAD, compile, publish JARs in "less" steps.
Here are the commands I use:
1. Build FIRRTL and run `sbt publishLocal` (no change)
2. Build and publish other JARs in a single step:
~~~~
cd /path/to/rocketchip
git pull origin master
git submodule update --init --recursive
rm -rf ~/.ivy2/local/berkeley
rm -rf ~/.ivy2/local/edu.berkeley.cs
sbt clean compile publishLocal
~~~~
more info : https://www.scala-sbt.org/0.13/docs/Multi-Project.html#Aggregation
Low urgency on this PR.  Taking the time to give back.
> aggregate rocketchip subtasks

- src/main/scala/rocket/Multiplier.scala
- src/main/scala/tile/FPU.scala
- src/main/scala/util/Annotations.scala
- src/main/scala/util/Misc.scala
The trait `ShouldBeRetimed` can be used to apply `RetimeModuleAnnotations` to Modules that should be the target of [register retiming](https://en.wikipedia.org/wiki/Retiming) in downstream tools.
> Annotations: ShouldBeRetimed applies RetimeModuleAnnotation

- scripts/vlsi_mem_gen
I wanted an option to write out blackbox versions of memories.
Please review this PR.  Recommend changes or alternate solution, if available.
A few test cases follow.
No arguments added. Position argument works as before.
~~~~
$ ./vlsi_mem_gen ../ExampleRocketSystem.conf
< no change in output >
~~~~
Positional argument for .conf file.
~~~~
$ ./vlsi_mem_gen 
usage: vlsi_mem_gen [-h] [--blackbox] .conf file
vlsi_mem_gen: error: too few arguments
~~~~
No arguments added.  Result: no change.
~~~~
$ ./vlsi_mem_gen ../ExampleRocketSystem.conf
< no change in output >
~~~~
Positional argument for .conf file and with -b option.  Result: empty module body.
~~~~
$ ./vlsi_mem_gen -b ../ExampleRocketSystem.conf
module data_arrays_0_ext(
input RW0_clk,
input [11:0] RW0_addr,
input RW0_en,
input …
> vlsi_mem_gen: Add -b/--blackbox option, retain existing API

- src/main/scala/rocket/PMP.scala
Lock the next-highest address register for TOR but not NA4/NAPOT/OFF.
> Fix PMP-locking logic

- src/main/resources/csrc/emulator.cc
This is added to allow defining a port for the JTAG Remote Bit Bang, instead of affecting one randomly.
remote_bitbang_t(port); instead of remote_bitbang_t(0);
If no port is selected default value is 0, then the port is chosen randomly.
Tested with OpenOCD + GDB
https://github.com/freechipsproject/rocket-chip/issues/1339
> Adding --rbb-port=PORT parameter to the Emulator

- src/main/resources/vsrc/AsyncResetReg.v
Without this change, if `rst` is not actually asserted at time 0, at time #0.002 even if `rst` is asserted the register gets a random value. That doesn't make sense for an AsyncResetReg.
With this change maybe I can get rid of the `q` vs `q_reg` hackery as well, not sure.
> AsyncResetReg: more reset race fixes

- src/main/scala/tilelink/WidthWidget.scala
If you have gaps in the source ID space, there is no need
to populate those registers. Drive them to 0 for DC.
> WidthWidget: save some flops in the uncommon case

- src/main/scala/amba/ahb/Bundles.scala
- src/main/scala/amba/apb/Bundles.scala
- src/main/scala/amba/axi4/Bundles.scala
- src/main/scala/groundtest/Configs.scala
- src/main/scala/groundtest/GroundTestSubsystem.scala
- src/main/scala/subsystem/Configs.scala
- src/main/scala/subsystem/Ports.scala
- src/main/scala/system/Configs.scala
- src/main/scala/system/ExampleRocketSystem.scala
- src/main/scala/system/TestHarness.scala
- src/main/scala/tilelink/Bundles.scala
This PR adds support for specifying that individual ports are optional via parameters stored in the `Config` classes. This should allow their removal without modification of any `trait` extensions. I also:
- updated the SimAXIMem API to be a better example of using Edges
- cleaned up the various `Port` traits
- added helper methods for tying off various diplomatic bundles
(/cc @ppoocde  @mayoru)
> Subsystem: support optional ports via configs

- src/main/scala/devices/debug/Debug.scala
- src/main/scala/devices/debug/SBA.scala
The functional parameters in `DebugModuleParams` render it unserializable as a Firrtl annotation. As a workaround I split them out into their own case class and key. I'm not sure if this is the right long term solution but it at least unblocks @rmac-sifive.
> Debug: work around param case class serialization limitation

- src/main/scala/regmapper/GetMeMyModule.scala
This is a really ugly hack that is used to get the current module during elaboration. The specific reason that this hack is required is because Chisel3 has a private[chisel3] Module which contains the current module pointer. 
This is an issue that a number of people at SiFive have run into and will continue to run into when needing to access the current module from within nested helper functions during elaboration.
> Adding an ugly hack to get the current module during elaboration.

- src/main/scala/subsystem/Configs.scala
- src/main/scala/subsystem/RocketSubsystem.scala
- src/main/scala/tile/BaseTile.scala
- src/main/scala/tile/LazyRoCC.scala
- src/main/scala/tile/RocketTile.scala
I'm eliminating the somewhat convoluted RoccParams in favor of just directly supplying `BuildRoCC` generator functions and cleaning up the flow of parameters. This has the following consequences:
- `nPTWPorts` and `usesFPUs` are now parameters supplied by individual accelerators to the base `LazyRoCC` class
- each accelerator takes an `OpcodeSet` as a constructor argument, because it is now a mandatory argument to `LazyRoCC` (backwards incompatible, sorry!)
- `AccumulatorExample` actually takes `n` as an argument
- `BuildRoCC` is now completely independent from `RocketTileParams`
- `RocketTileParams` is serializable (fixes #1398)
- tiles are homogeneous w.r.t. RoCCs by default
> Update and simplify RoCC parameterization

- src/main/scala/regmapper/RegisterCrossing.scala
`RegField`s created using `AsyncRWSlaveRegField` helper had no way to get descriptions applied. Add the ability to pass those in.
> RegField: Allow description to be passed in to AsyncRWSlaveRegField

- src/main/resources/csrc/remote_bitbang.cc
Run the JTAG simulation tests a bit faster by turning off some debugging output and using newer version of OpenOCD.
> OpenOCD Sim Speedup & RISC-V Tests Bump

- README.md
This documents the process of debugging RISC-V programs running on the Emulator using the GNU debugger and OpenOCD in a similar manner as https://github.com/riscv/riscv-isa-sim#debugging-with-gdb .
https://github.com/freechipsproject/rocket-chip/issues/1339
> Documenting emulator debugging process with GDB

- .travis.yml
- src/main/scala/devices/debug/Debug.scala
Harts should only be writing to the EXCEPTION location if doing work under the direction of the debugger. Otherwise this indicates some other sort of debug mode exception, which is unexpected since Debug ROM code is super benign.
> debug: assert on unexpected exceptions

- src/main/scala/rocket/DCache.scala
- For corrupt grant data, poison the ECC bits while refilling
- For corrupt MMIO data, engage the bus-error unit
> Handle TL errors better in D$

- src/main/scala/devices/debug/Debug.scala
- src/main/scala/util/ResetCatchAndSync.scala
Previously we were bypassing only the output of any ResetCatchAndSync. But, we should also bypass any logically generated resets that go *into* a ResetCatchAndSync so that those flops themselves are not a DFT hole.
> PSDTestMode: in Debug Module, bypass dmactive reset during PSDTestMode

- src/main/scala/amba/axi4/Bundles.scala
- src/main/scala/amba/axi4/Parameters.scala
- src/main/scala/amba/axi4/ToTL.scala
- src/main/scala/tilelink/ToAXI4.scala
- src/main/scala/util/IDPool.scala
This PR adds a signal which can be used to indicate ECC corrupted data beats.
> AXI4: add an optional non-standard 'corrupt' signal

- src/main/scala/devices/tilelink/PhysicalFilter.scala
- src/main/scala/tilelink/CacheCork.scala
The PhysicalFilter previously allowed multiple denied Grants to be inflight at once. This violates the TL spec. Also, unify the addressing between all the ports controlled by a single PhysicalFilter.
> PhysicalFilter: fix re-use of Grant sink IDs

- src/main/resources/csrc/remote_bitbang.cc
- src/main/scala/rocket/CSR.scala
- src/main/scala/rocket/DCache.scala
- src/main/scala/rocket/Decode.scala
- src/main/scala/rocket/Frontend.scala
- src/main/scala/rocket/NBDcache.scala
- src/main/scala/rocket/RocketCore.scala
- src/main/scala/rocket/TLB.scala
- src/main/scala/tile/Core.scala
- src/main/scala/tile/FPU.scala
See https://github.com/riscv/riscv-isa-manual/commit/32b74b7a02e492c48a910ba0d20bcc52155b0616
This change specifically prevents writing H (2) to mstatus.MPP for
systems with S-mode.  There is no change for systems without S-mode.
And of course dcsr.PRV should be treated the same way.
> In priv-1.11, mstatus.MPP is WARL, not WLRL

- src/main/scala/amba/axi4/Test.scala
- src/main/scala/tilelink/Fragmenter.scala
- src/main/scala/tilelink/ToAXI4.scala
Although it is not possible to 100% faithfully convert AXI DECERR => denied and AXI SLVERR => corrupt, this PR gets us as close as we can. Previously, all AXI errors were interpreted as corrupt, which means that accesses to memory that did not exist could increase the counters monitoring ECC failures.
Now that TLToAXI4 can generate denied AccessAckData, we also need a special override to allow it to be used with the TLFragmenter, which is typically how one implements AXI4Lite. The new 'holdFirstDeny' option makes the TLFragmenter behave the same way that TLToAXI4 behaves; report denied iff the first data beat indicates denied/DECERR. This is obviously problematic if an AXI4 slave only reports DECERR part-way through a burst. However, since TL bursts typically never cross a cache block …
> TLToAXI4: treat DECERR as denied when possible

- src/main/scala/rocket/NBDcache.scala
NBDcache now creates a RAM named data_array_nbdcache__ext instead of _T_39_ext
> Normal RAM names for NBDcache

- src/main/scala/diplomacy/LazyModule.scala
This PR makes LazyRawModuleImp far more useful, as you can feed in a clock from one child to drive all the others. This is important when stitching together top-level modules with PLL children, for example.
> LazyRawModuleImp: support a default clock for all children

- src/main/scala/subsystem/Configs.scala
- src/main/scala/system/Configs.scala
@hcook I'm not sure if this is an issue, so would like to get your feedback.  Was talking with @terpstra  and he mentioned that if the core doesn't have a D$, it shouldn't have a CacheCork.  So I tracked it down to the TinyConfig core and it seems like removing the following lines seems to have remove the CacheCork.  But I don't know enough about the rest of the system to know if I'm removing something that shouldn't be removed.
> Tiny Config have scratch pad instead of D$, so shouldn't have cache cork

- src/main/scala/groundtest/TraceGen.scala
- src/main/scala/subsystem/HasTiles.scala
- src/main/scala/subsystem/RocketSubsystem.scala
- src/main/scala/tile/BaseTile.scala
- src/main/scala/tile/Interrupts.scala
- src/main/scala/tile/LazyRoCC.scala
- src/main/scala/tile/RocketTile.scala
HasRocketTile's clock-domain crossing code for TileLink and interrupts is pretty generic.  This PR moves it into helper methods on HasTile, so other tiles can leverage them without duplicating code.
> Factor out some generic code in HasRocketTiles

- src/main/scala/diplomacy/LazyModule.scala
- src/main/scala/util/GeneratorUtils.scala
This will be necessary to be able to decouple the top 'shell' from the
internal 'design'.  The way this is going to work is that the 'shell'
creates Nodes for it's top-level IO which are then connected to arbitrarily
deep points in the design.
> GeneratorUtils: support LazyModules as the top Module

- src/main/scala/diplomacy/BundleBridge.scala
This can be quite useful for plumbing IO from deep inside the hierarchy to
the top of the design.
Example:
```
// Wrap up SomeDevice's module.io Bundle into an ioNode
val (ioNode, device) = BundleBridge(new SomeDevice)
// Somewhere else in the design in LazyModule scope:
val sink = ioNode.sink // creates a sink node of matching type
// In LazyModuleImp scope:
val io = sink.io // io is a Wire () connected to device.module.io
```
> diplomacy: add BundleBridge for cross-module bundles

- src/main/scala/system/Generator.scala
This bug has flown under the radar because most times we use the same
project for the config and the top.  However, in the case of shells, you use
the top=shell and config=design, which are usually in different projects.
> Generator: use the config's project for the path

- src/main/scala/rocket/HellaCache.scala
- src/main/scala/rocket/RocketCore.scala
- src/main/scala/tile/Core.scala
Since an LR/SC sequence can have taken branches/jumps within the loop, Rockets with no branch prediction can fail to meet the forward-progress guarantee.  Increase the timeout to handle the case that all instructions hit in the I$ but up to 14 of them are mispredicted branches. (14 is 16 minus the LR and the SC instructions themselves.)
This is extremely conservative, but in practice it won't result in locking lines for too long, because the line is unlocked either by the SC or (in Rocket, specifically) by the next load or store.
> Make lrscCycles core-specific; increase it

- src/main/scala/diplomacy/LazyModule.scala
- src/main/scala/diplomacy/package.scala
- src/main/scala/subsystem/CrossingWrapper.scala
This replaces the old instantiate() API.
This new API is strictly more powerful as you can use it from
helper functions. The instatiate() API required you to put your
extra glue code in one place and it had to be in the LazyModule.
Example:
```
def helper() {
val child = LazyModule(new Device)
InModuleBody { child.module.io.bypass := false.B }
}
```
> Add InModuleBody API

- src/main/scala/devices/debug/DebugTransport.scala
Acknowledge response for write transactions on DMI bus immediately instead of waiting for the next transition through DR Capture state.
> Dmi write delay fix

- src/main/scala/diplomacy/BundleBridge.scala
Having a lot of children all called 'bridge' was not ideal.
> BundleBridge: improve module and instance naming

- src/main/resources/vsrc/AsyncResetReg.v
- src/main/scala/util/AsyncResetReg.scala
While the inversion trick works most of the time, if you are putting a
register in an FPGA IO buffer, you can't have any logic between the register
and the output pin.
There was once a problem where LEC failed due to an async-set-reg, tho.
So I am not sure what the way forward should be.
> AsyncResetReg: support reset-value of '1'

- src/main/scala/rocket/DCache.scala
Having both synchronous and asynchronous reporting mechanisms is confusing,
and the synchronous reporting isn't possible for some reasonable design
points, e.g., in-order processors with nonblocking caches.
Make sure to instantiate a bus-error unit if any TL slaves can error!
> Use only bus-error unit to report TL errors

- src/main/scala/amba/axi4/SRAM.scala
- src/main/scala/amba/axi4/Xbar.scala
- src/main/scala/rocket/DCache.scala
This PR makes the following changes:
1. Upon receipt of a corrupt block, inform the BEU, potentially taking an interrupt to handle it
2. When evicting a corrupt block, poison only those beats actually corrupt
3. Maintain wcorrupt in AXI4 test RAMs for unit testing
> L1D: update how corrupt responses are handled

- src/main/scala/groundtest/TraceGen.scala
- src/main/scala/rocket/DCache.scala
- src/main/scala/rocket/HellaCache.scala
- src/main/scala/rocket/HellaCacheArbiter.scala
- src/main/scala/rocket/NBDcache.scala
- src/main/scala/rocket/PTW.scala
- src/main/scala/rocket/RocketCore.scala
- src/main/scala/rocket/ScratchpadSlavePort.scala
- src/main/scala/rocket/SimpleHellaCacheIF.scala
- src/main/scala/tile/LazyRoCC.scala
It's no longer necessary (see https://github.com/riscv/riscv-isa-manual/commit/03a5e722fc0fe7b94dd0a49f550ff7b41a63f612)
and removing it gets rid of a strange control path
> Don't invalidate load reservations on exceptions

- src/main/scala/devices/tilelink/Plic.scala
- src/main/scala/interrupts/NullIntSource.scala
- src/main/scala/subsystem/Configs.scala
- src/main/scala/subsystem/HasTiles.scala
- src/main/scala/subsystem/RocketSubsystem.scala
Allow for removal of the PLIC when the number of external or device interrupts is 0. All combinations are not yet gracefully handled:
- Some(PLIC) && IBus.intnode.sources.size > 0  => OK
- Some(PLIC) && IBus.intnode.sources.size == 0 => zero size vec error in PLIC
- None && IBus.intnode.sources.size > 0 => diplomacy error, no possible output for IBus.int_xbar
- None && IBus.intnode.sources.size == 0 => OK now
> Allow PLIC to be optional

- .travis.yml
- regression/Makefile
- src/main/scala/tile/LazyRoCC.scala
- src/main/scala/tile/RocketTile.scala
This fixes a problem where RoCC-enabled tiles would fail to build. This was due to bad inheritance where the inheriting class defined the FPU before it was used. The connections are now made more explicit by moving some code from the RoCC into the Tile.
- Creates a new `HasFpuOpt` trait that instantiates the FPU
- Mixes in the `HasFpuOpt` trait _before_ the `HasLazyRoCCModule` trait to make the `fpuOpt` member available for use inside the RoCC implementation
- Removes a kludge where the RoCC would first connect to a wire and then the core would connect to the same wire (assumedly intended to facilitate problems with trait ordering) in favor of making the connections explicit once the LHS and RHS exist
- Removes the type variable on `HasLazyRoCCModule` as this is no longer needed
- Changes …
> RoCC Build Fixes

- src/main/scala/diplomacy/FixedClockResource.scala
- src/main/scala/diplomacy/Resources.scala
- src/main/scala/subsystem/BaseSubsystem.scala
- src/main/scala/tilelink/RegisterRouter.scala
To use a UART as a console, newer linux kernels require an 'aliases/uartX' reference that links to the UART device which should be the console. This PR adds hooks to make that possible.
> Bind DTS aliases

- src/main/scala/amba/axi4/Nodes.scala
- src/main/scala/interrupts/Nodes.scala
- src/main/scala/subsystem/BaseSubsystem.scala
- src/main/scala/subsystem/CrossingWrapper.scala
- src/main/scala/subsystem/FrontBus.scala
- src/main/scala/subsystem/MemoryBus.scala
- src/main/scala/subsystem/PeripheryBus.scala
- src/main/scala/subsystem/SystemBus.scala
- src/main/scala/tile/BaseTile.scala
- src/main/scala/tile/Interrupts.scala
- src/main/scala/tilelink/Buffer.scala
- src/main/scala/tilelink/BusWrapper.scala
- src/main/scala/tilelink/Nodes.scala
I added a `CrossingHelper` class that makes it easier for multiple crossing types to be used within a single wrapper. The helper also uses `ValName` to capture a nice name for the signals created by calls to its methods.
The change is backwards compatible with the extant `HasCrossing` trait, but I also started to retire use of that trait in cases where I needed better interface signal names (tiles) or know there will soon be multiple crossing types (bus wrappers). Using individual helpers instead of `HasCrossing` also allows client code to narrow the interface of `cross` methods to ones they actually support.
I think more helper objects for concisely creating named crossings and identity nodes could be useful, but will leave that to future work.
> Clock Crossings: make API more flexible with CrossingHelper

- src/main/scala/subsystem/BaseSubsystem.scala
- src/main/scala/subsystem/FrontBus.scala
- src/main/scala/subsystem/PeripheryBus.scala
- src/main/scala/subsystem/SystemBus.scala
- src/main/scala/tile/BaseTile.scala
A diplomatic scoping oversight, caught via `.graphml`
> tile: boundary buffers ended up in wrong scope

- src/main/scala/tile/BaseTile.scala
enabling them breaks module deduplication
> tile: disable monitors in slave crossing

- src/main/scala/util/ClockDivider.scala
Adds a clock divider module which allows for an explicit clock input, and rewrites `Pow2ClockDivider` to instantiate this module for legacy compatibility
> Add a clock divider with explicit input clock

- src/main/scala/diplomacy/Resources.scala
This would fail to produce legal DTS when reg/mem was set instead of reg.
> SRAM: support reg/ naming in DTS output

- src/main/scala/rocket/RocketCore.scala
- src/main/scala/util/BundleMonitorKey.scala
This PR makes it possible to install a core monitor inside RocketCore. It does not define the actual mechanism of this monitor. Users can define their own monitors that, for example, convert instruction commits into UVM transactions, collect statistic of which opcodes were used or do something else.
This mechanism is optional - it only does something when BundleMonitorKey is passed via Parameters.
> Core monitor

- src/main/scala/rocket/CSR.scala
- src/main/scala/rocket/RocketCore.scala
This was erroneously masking id_csr_en by id_ctrl.fp; these control
signals are mutually exclusive.  Fix that, and also optimize the stall
logic to avoid stalling on unrelated CSR accesses.
> Interlock FCSR reads (but not other CSRs) when FPU is busy

- src/main/scala/diplomacy/Resources.scala
This makes it possible to output several DTS snippets we can cat together.
> DTS: support skipping some label indexes

- src/main/scala/rocket/TLB.scala
Using SFENCE with rs1 != x0 relies on reusing the TLB hit path, but it's
not possible to hit when VM is disabled, so the logic did the wrong thing.
The simple fix is to flush the whole TLB when using SFENCE when VM is
disabled.  This shouldn't be an important performance case, because SFENCE
is nearly only used when VM is enabled (for obvious reasons).
> Ignore SFENCE rs1 argument when VM is disabled

- src/main/resources/vsrc/AsyncResetReg.v
- src/main/resources/vsrc/SimJTAG.v
This fixes a reset race condition caused when the reset of an AsyncResetReg_1 is driven by another AsyncResetReg_2. In that case, the AsyncResetReg_2's initialization behavior could cause AsyncResetReg_1 to be undefined
> Fix AsyncResetReg

- src/main/resources/vsrc/AsyncResetReg.v
This is a follow-on update to https://github.com/freechipsproject/rocket-chip/commit/8e7ad59189b53d8a9c098207ac7e508a0be552a5, which made changes to AsyncResetreg
The previous update did not model AsyncResetReg as level-sensitive to reset, as the unit would be in real silicon. This PR allows modeling of this behavior without introducing unneeded `posedge reset` events
> Model AsyncResetReg's init reset behavior as level-sensitive

- src/main/scala/devices/debug/DMI.scala
- src/main/scala/devices/debug/Debug.scala
one small step in Reducing the monolithic nature of Debug.scala
> Debug: Move DMI-specific code to a seperate file

- src/main/scala/rocket/CSR.scala
- src/main/scala/rocket/DCache.scala
This doesn't matter for the usual Linux use case, but it doesn't match
Spike, so it should be fixed.
The ISA spec is a little ambiguous about the correct behavior here, but
at least this way, the sip and sie CSRs behave the same as each other.
> sip.ssip should only be writable when delegated

- src/main/scala/rocket/PMP.scala
- src/main/scala/rocket/RocketCore.scala
This bug doesn't affect Rocket, because it has 4-byte-granularity PMPs.
> Fix support for PMP granularity > 4 bytes

- src/main/scala/tile/BaseTile.scala
**Related issue**: #1189 , #1245 
According to #1245 , `fLen` is used by FPU to determine whether it is going to generate double precision floating point instructions or not. The DTS generation should keep consistent with such behavior.
> tile,BaseTile: generate 'd' according to fpu.fLen

- src/main/scala/util/Misc.scala
Meant to address, https://github.com/freechipsproject/rocket-chip/issues/1616, written by Jack. Also helps to catch other errors that are made when using DecoupledHelper.
> DecoupledHelper require Excluded Bool is actually contained

- src/main/scala/regmapper/RegField.scala
- src/main/scala/regmapper/RegMapper.scala
They have no semantic value, but supporting and ignoring them reduces the corner-case-handling burden on RegMapper users.
Tested by adding some zero-width RegFields to the CLINT and verifying that the Firrtl was unchanged.
> Support (i.e. ignore) zero-width RegFields

- src/main/scala/devices/tilelink/Zero.scala
- src/main/scala/subsystem/PeripheryBus.scala
- src/main/scala/tilelink/Filter.scala
- src/main/scala/tilelink/Parameters.scala
If a PeripheryBus provides atomic support, it now does so for any number of masters coupled to the bus, rather than just failing a diplomatic check. The crossbar architecture reflects this narrow waist. The intended use case continues to be this type of bus having only a single master.
> Periphery bus atomics for multiple masters

- src/main/scala/rocket/PMP.scala
There was a flaw in the spec and the current proposed fix is https://github.com/riscv/riscv-isa-manual/commit/693ad48fc347bb613b95f6ebafc2e062428c5bd5
> Change coarse-grained NAPOT PMPs to match spec

- src/main/resources/csrc/emulator.cc
- src/main/resources/vsrc/TestDriver.v
- src/main/scala/system/RocketTestSuite.scala
Update run-*  recipes to or-reduce failures across a suite. Additionally, print the assertion name in the summary of a failing test. 
I'm not sure to what extent these are really used. It's also not clear to me how dangerous changing the success message of emulator.cc and TestDriver.v, though, with the previous message and regex no summary is printed when running simulations out of `vsim` or `emulator`.  I could contain the changes to the to generated Makefrag is that's prefered.
> Improve generated run-* recipes

- src/main/scala/util/Misc.scala
Adding a no-argument fire() to DecoupledHelper that doesn't exclude anything. The previous way of doing this, which was fire(false.B), was broken by the previous change of requiring all excluded to be included, and forced a further hack of adding a dummy value. Since excluding false.B was a hack in itself, this avoids the issue entirely by providing a straightforward and safe way of excluding nothing.
**Related issue**: [R1616](https://github.com/freechipsproject/rocket-chip/issues/1616)
**Impact**: API addition (no impact on existing code) | API modification
Allows code broken by previous change to be written in a more natural way.
**Development Phase**: Implementation
Added a no-argument fire() to DecoupledHelper when the user …
> Adding no exclude fire() to DecoupledHelper

- src/main/scala/regmapper/RegisterRouter.scala
For now, register router devices must have a pow2 size. This was a (still-applicable) requirement of the soon-to-be-deprecated `TLRegisterRouter` API that did not get transferred to the new, more generic `RegisterRouter`.
> registerrouter: require pow2 size

- src/main/scala/rocket/IDecode.scala
- src/main/scala/rocket/RocketCore.scala
- src/main/scala/scie/SCIE.scala
This enables adding custom instructions that operate on the x-registers
(i.e., no additional architectural state).
This version on supports combinational units (which fit in the pipeline in
the same place as the integer ALU), but it can be extended to support 2-stage
pipelines, or multi-cycle operations.
> Add Simple Custom Instruction Extension

- src/main/scala/amba/axi4/Test.scala
- src/main/scala/devices/tilelink/BusBypass.scala
- src/main/scala/devices/tilelink/Deadlock.scala
- src/main/scala/devices/tilelink/DevNull.scala
- src/main/scala/devices/tilelink/Error.scala
- src/main/scala/devices/tilelink/Zero.scala
- src/main/scala/diplomacy/LazyModule.scala
- src/main/scala/subsystem/BaseSubsystem.scala
- src/main/scala/subsystem/Configs.scala
- src/main/scala/subsystem/MemoryBus.scala
- src/main/scala/subsystem/PeripheryBus.scala
- src/main/scala/system/ExampleRocketSystem.scala
- src/main/scala/tilelink/Fragmenter.scala
DevNullDevices don't obey standard memory operation semantics. They may discard writes, refuse to respond to requests, issue error responses, or otherwise violate 'expected' memory behavior. The existing DevNullDevice subclasses were TLError and TLDeadlock, TLZero has now been refactored to extend it as well.
I also add the capability to add some such devices directly into the `PeripheryBus` and `MemoryBus` clock domain wrappers. Further wrappers may have similar devices added to them in future PRs.
> Refactor DevNullDevices and provide some within TLBusWrappers

- src/main/scala/tilelink/Arbiter.scala
- src/main/scala/tilelink/HintHandler.scala
- src/main/scala/tilelink/Xbar.scala
- src/main/scala/unittest/Configs.scala
The old HintHandler was buggy because it reordered responses despite claiming that it would not. It was also grossly inefficient due to the use of Arbiters and Queues. This new HintHandler transforms Hints into empty PutPartials, avoiding the need to recombine the response stream. It can be placed between a device and it's Fragmenter as a very cheap stateless adapter, or higher up the tree like the old HintHandler, in which case it will use flops to hold the address steady.
> Better HintHandler

- src/main/scala/rocket/RocketCore.scala
Every time we bless a release of rocket-chip, we'll set mimpid to
the current date as a BCD string, e.g., 0x20181004 for today.
> Establish mimpid scheme; set to initial value

- src/main/scala/amba/axi4/Test.scala
- src/main/scala/devices/tilelink/BusBypass.scala
- src/main/scala/devices/tilelink/Deadlock.scala
- src/main/scala/devices/tilelink/DevNull.scala
- src/main/scala/devices/tilelink/Error.scala
- src/main/scala/devices/tilelink/Zero.scala
- src/main/scala/diplomacy/LazyModule.scala
- src/main/scala/subsystem/BaseSubsystem.scala
- src/main/scala/subsystem/Configs.scala
- src/main/scala/subsystem/MemoryBus.scala
- src/main/scala/subsystem/PeripheryBus.scala
- src/main/scala/system/ExampleRocketSystem.scala
- src/main/scala/tilelink/Arbiter.scala
- src/main/scala/tilelink/ErrorEvaluator.scala
- src/main/scala/tilelink/Fragmenter.scala
- src/main/scala/tilelink/HintHandler.scala
- src/main/scala/tilelink/ToAHB.scala
- src/main/scala/tilelink/Xbar.scala
- src/main/scala/unittest/Configs.scala
The old HintHandler was buggy because it reordered responses despite claiming that it would not. It was also grossly inefficient due to the use of Arbiters and Queues. This new HintHandler transforms Hints into empty PutPartials or Gets, avoiding the need to recombine the response stream. It can be placed between a device and it's Fragmenter as a very cheap stateless adapter, or higher up the tree like the old HintHandler, in which case it will use flops to hold the address steady.
This is a rebased version of #1654.
> A better HintHandler

- src/main/scala/groundtest/Configs.scala
- src/main/scala/subsystem/BaseSubsystem.scala
- src/main/scala/subsystem/Configs.scala
- src/main/scala/subsystem/MemoryBus.scala
- src/main/scala/subsystem/Ports.scala
- src/main/scala/subsystem/SystemBus.scala
- src/main/scala/system/Configs.scala
- src/main/scala/tilelink/BankBinder.scala
- src/main/scala/tilelink/Monitor.scala
- src/main/scala/tilelink/Parameters.scala
- src/main/scala/tilelink/ProbePicker.scala
- src/main/scala/tilelink/Xbar.scala
This PR adds the BankBinder and ProbePicker which can be combined with an enhanced TLXbar to create a multi-bank interconnect between cache layers.
This removes memBuses and replaces it with a singular 'mbus'. This affects memory bus attachments in other repositories. The change is necessary because now the singular Xbar in the mbus now links multi-channel memory with variable bank-count masters.
> Banked TileLink

- src/main/scala/subsystem/BaseSubsystem.scala
- src/main/scala/subsystem/MemoryBus.scala
- src/main/scala/subsystem/PeripheryBus.scala
- src/main/scala/subsystem/Ports.scala
- src/main/scala/subsystem/SystemBus.scala
- src/main/scala/tilelink/BusWrapper.scala
> Subsystem bus tweaks

- src/main/scala/devices/debug/Periphery.scala
- src/main/scala/devices/tilelink/BootROM.scala
- src/main/scala/devices/tilelink/CLINT.scala
- src/main/scala/devices/tilelink/MaskROM.scala
- src/main/scala/devices/tilelink/Plic.scala
- src/main/scala/subsystem/BaseSubsystem.scala
- src/main/scala/subsystem/Configs.scala
- src/main/scala/subsystem/HasTiles.scala
- src/main/scala/subsystem/PeripheryBus.scala
- src/main/scala/subsystem/SystemBus.scala
- src/main/scala/tilelink/Fragmenter.scala
- src/main/scala/tilelink/WidthWidget.scala
- Moves `sbus.control_bus` to subsystem level
- Renames it to `cbus`
- Adds `ControlBusKey` which is a `Field[PeripheryBusParams]`
- Depend less on the `tilelink.CanAttachTLSlaves` API
> Move sbus.control_bus to subsystem level

- src/main/scala/groundtest/GroundTestSubsystem.scala
- src/main/scala/subsystem/BaseSubsystem.scala
- src/main/scala/subsystem/Configs.scala
- src/main/scala/subsystem/FrontBus.scala
- src/main/scala/subsystem/MemoryBus.scala
- src/main/scala/subsystem/PeripheryBus.scala
- src/main/scala/subsystem/SystemBus.scala
- src/main/scala/system/ExampleRocketSystem.scala
- src/main/scala/tilelink/BusWrapper.scala
- src/main/scala/tilelink/Fragmenter.scala
`BaseSubsystem` no longer mandates how its tilelink buses are to be interconnected to one another. Creating these connections are now the responsibility of child classes, e.g. `ExampleRocketSystem`, `GroundtestSubsystem`. I also added some helper functions for cross-connecting the buses.
> Handle subsystem bus interconnectivity in child classes of BaseSubsystem

- src/main/scala/devices/tilelink/CanHaveBuiltInDevices.scala
- src/main/scala/subsystem/FrontBus.scala
- src/main/scala/subsystem/MemoryBus.scala
- src/main/scala/subsystem/PeripheryBus.scala
- src/main/scala/subsystem/SystemBus.scala
- Hack-ily use WidthWidgets to optionally support atomics wider than the bus width
- Make the case where no atomics are required more streamlined
> subsystem: allow PeripheryBuses to support wider atomics

- README.md
fpga-zynq is now deprecated, move reference to sifive/freedom.
> Update README reference to fpga-zynq.

- src/main/scala/amba/axi4/Fragmenter.scala
When the entire AXI4 address space is small (for example, a 4kB test
device), it is possible for a single AXI burst to be larger than the
available address bits on the bus. Handle this case gracefully.
Fixes #1683
> AXI4Fragmenter: support tiny AXI4 address space

- src/main/scala/subsystem/PeripheryBus.scala
It's more expensive to have the master side be narrowed, and doesn't buy you much benefit when the mastering bus is almost always going to re-widen it anyways.
> subsystem: keep pbus frontside wide if atomics widened it

- .gitmodules
- README.md
- regression/Makefile
- riscv-tools.hash
Removed riscv-tools from rocket-chip
The software ecosystem is now mostly stable. There are work-arounds to avoid bringing the giant riscv-tools into the tree for most projects using rocket. This PR makes their life easier.
> Remove riscv tools

- src/main/scala/diplomaticobjectmodel/DiplomaticObjectModelUtils.scala
- src/main/scala/diplomaticobjectmodel/model/OMAddressing.scala
- src/main/scala/diplomaticobjectmodel/model/OMCLINT.scala
- src/main/scala/diplomaticobjectmodel/model/OMCaches.scala
- src/main/scala/diplomaticobjectmodel/model/OMDebug.scala
- src/main/scala/diplomaticobjectmodel/model/OMISA.scala
- src/main/scala/diplomaticobjectmodel/model/OMInterrupts.scala
- src/main/scala/diplomaticobjectmodel/model/OMMemory.scala
- src/main/scala/diplomaticobjectmodel/model/OMMulDiv.scala
- src/main/scala/diplomaticobjectmodel/model/OMPLIC.scala
- src/main/scala/diplomaticobjectmodel/model/OMPMP.scala
- src/main/scala/diplomaticobjectmodel/model/OMPerformanceMonitor.scala
- src/main/scala/diplomaticobjectmodel/model/OMRegFieldAccessType.scala
- src/main/scala/diplomaticobjectmodel/model/OMRegFieldRdAction.scala
- src/main/scala/diplomaticobjectmodel/model/OMRegFieldWrType.scala
- src/main/scala/diplomaticobjectmodel/model/OMRocketCore.scala
- src/main/scala/diplomaticobjectmodel/model/OMSpecification.scala
/cc @john-sifive
This adds some hardcoded type names to the OM classes, at least until we can properly autogenerate them. There are a few tricky things we're running into w.r.t. automatically generating the serialized and linearized list of types, some of which have to do with Json4s's custom serializer API, so hardcoding a subset of the expected results will at least get us working data.
This is broken up into two commits:
- https://github.com/freechipsproject/rocket-chip/commit/bb3e2b7c216acf0221dd84a35fc234e8b8599aab, which is heavily adapted from some code @john-sifive handed me to automatically get all parent types and serialize them. I …
> Add hardcoded Object Model types

- src/main/scala/util/RationalCrossing.scala
RationalIO: set directions so it works inside chisel3 aggregates
> RationalIO: set directions so it works inside chisel3 aggregates

- src/main/scala/diplomaticobjectmodel/model/OMCore.scala
- src/main/scala/groundtest/Tile.scala
- src/main/scala/groundtest/TraceGen.scala
- src/main/scala/interrupts/Xbar.scala
- src/main/scala/rocket/RocketCore.scala
- src/main/scala/subsystem/Configs.scala
- src/main/scala/subsystem/HasTiles.scala
- src/main/scala/subsystem/MemoryBus.scala
- src/main/scala/tile/BaseTile.scala
- src/main/scala/tile/BusErrorUnit.scala
- src/main/scala/tile/Core.scala
- src/main/scala/tile/Interrupts.scala
- src/main/scala/tile/RocketTile.scala
- src/main/scala/tilelink/SRAM.scala
- src/main/scala/util/ECC.scala
Various changes to the Tile APIs related to notifying external observers of tile status. Tile notifications are expressed as outward-going interrupts, but are handled differently (not routed to PLIC, not clock crossed). The nodes emitting these interrupts unconditionally exist, but their wire values may be driven low for tile configurations for which no such notification could ever be emitted.
The three current types of notifications are:
- `halt`: an unrecoverable error occurred (e.g. uncorrectable ECC error in a cache)
- `cease`: the tile has temporarily ceased to retire instructions
- `wfi`: the tile is waiting to receive an external interrupt
Other miscellaneous API changes to tile parameterization:
- the BEU is now in package `tile` and is enabled via a `TileParam` called `beuAddr`
- …
> Tile Notification Nodes

- src/main/scala/groundtest/Tile.scala
- src/main/scala/rocket/DCache.scala
- src/main/scala/rocket/HellaCache.scala
- src/main/scala/subsystem/RocketSubsystem.scala
This prevents livelock in a multi-master system with NoCrossing.  Resolves #1722
> Provide a modicum of TL.A buffering in the NoCrossing case

- src/main/scala/subsystem/BaseSubsystem.scala
- src/main/scala/subsystem/RocketSubsystem.scala
The logic which called getOMSubSystem components did not work because of a diamond problem. This PR gets rid of the abstract def and creates an explicit getRocketOMSubsystem call.
> fixing diamond problem

- src/main/scala/tilelink/SRAM.scala
SRAM ECC notifications are only valid when the SRAM has actually been accessed.
> tilelink: sram ecc notifications only on sram access

- src/main/scala/rocket/CSR.scala
- src/main/scala/util/package.scala
This addresses a simulation-pessimism problem.  The synthesis result will be the same either way.  Before, in simulation, the value held in these registers prior to the first write might not have had the appropriate bits zapped, because of random initialization.
Resolves #1752
**Related issue**: #1752 
> Move tvec bit-zapping from D to Q

- src/main/scala/diplomacy/BundleBridge.scala
- src/main/scala/tile/BaseTile.scala
Add suggestName functionality to BundleBroadcast and use it to name trace nodes
> Trace: suggestName trace node

- src/main/scala/amba/axi4/Fragmenter.scala
This bug could cause incorrect resource allocation by downstream AXI4 adapters.
> AXI4Fragmenter: splitting up bursts impacts the inflight transactions

- src/main/scala/devices/debug/Debug.scala
This PR relaxes one of the assertions in Debug module. This assertion was  causing RTL simulation to crash when dmactive was used to reset DM from Abstract Command Busy condition. This PR does not introduce any hardware changes.
> Relax assertion in Debug.scala, allow dmactive to be used to exit from Busy state

- src/main/scala/amba/axi4/Parameters.scala
- src/main/scala/diplomacy/Parameters.scala
- src/main/scala/tilelink/Parameters.scala
It is useful to be able to classify buffering on channels for multichannel protocols.
> added per channel BufferParams case classes for TL, AXI4

- regression/Makefile
This increases the miscellaneous regression suite to additional test all top-level System configurations. Miscellaneous is a build-only regression suite currently clocking in at 25--28 minutes. So, this, assuming enough Travis parallelism (not a good assumption), won't increase wall-clock build times. However, this does head off issues like https://github.com/freechipsproject/rocket-chip/issues/1788.
This is a follow-on to #1789. 
**Related issue**: https://github.com/freechipsproject/rocket-chip/issues/1788
- Adds all example system configurations to Travis build-only regression suite
> Build all Example System Configs in Miscellaneous Regression Suite

- src/main/scala/subsystem/HasTiles.scala
This was accidental removed in the cbus coupling refactor
> subsystem: add a fragmenter to tile slave port bus blocker control

- src/main/resources/vsrc/AsyncResetReg.v
When simulating with iverilog, we get an error message for the
assignment to _RAND in the module's initial block:
"Variable declaration in unnamed block requires SystemVerilog."
Provide a name (":B0") for the initial block, which should be a
syntac no-op for already supported simulators, and allow also
running simulations under iverilog.
Signed-off-by: Gabriel Somlo <gsomlo@gmail.com>
> AsyncReset: iverilog requires named initial block with `RANDOMIZE

- .travis.yml
- emulator/Makefrag-verilator
Bump verilator to v4.008 which support multi-threading simulation
Usage in emulator dir
```bash
make VERILATOR_THREADS=4 run-fast
```
> Bump verilator to v4.008

- src/main/scala/diplomaticobjectmodel/model/OMMulDiv.scala
div min latency is now hardcoded to 2
> muldiv min div latency fix

- src/main/scala/devices/debug/Debug.scala
- src/main/scala/devices/debug/Periphery.scala
- src/main/scala/devices/debug/dm_registers.scala
Halt Groups are a new feature in the [latest draft version of the RISC-V Debug Spec](https://github.com/riscv/riscv-debug-spec/commit/aeee8f3227cbfe9c11ebb1991476f65cc760b223).  They are used to synchronize execution of hart(s) with other harts or external entities connected through external trigger in/out signals.  When any hart in a group halts or any external trigger input assigned to a group fires, then all harts and external trigger outputs assigned to that group are halted/fired.
Most changes are in Debug.scala to implement the DMCS2 register and to implement the halt group logic.  External triggers are connected through Periphery.scala. …
> Debug: added halt groups.

- src/main/scala/tilelink/Parameters.scala
- src/main/scala/util/package.scala
`groupBy` considered harmful.
`groupByIntoSeq` considered wonderful.
Follow on to https://github.com/freechipsproject/rocket-chip/pull/1713
**Type of change**: [non-determinism] bug fix
> Add utility groupByIntoSeq and use instead of groupBy for determinism

- src/main/scala/rocket/DCache.scala
**Related issue**: #1817
**Type of change**: bugfix
Fix incompability with Chisel3 master by not importing from `chisel3.core`
> Avoid import from chisel3.core

- src/main/scala/devices/debug/Periphery.scala
New ExportDisableDebug flag allows an implementation to add an additional input to the debug interface, disableDebug, which disables JTAG debug access.
> Added ExportDisableDebug flag to enable optional disable input

- src/main/scala/devices/debug/DebugTransport.scala
This PR fixes the following problem:
Transition throgh JTAG DR Capture state accepts DMI response even when sticky DMI busy bit is set.
This causes subsequent transaction to accept DMI response even after DMI Busy error, which, in turn, loses DMI Read data from previous transaction. It makes it difficult to recover from DMI Busy error in some cases.
Additionally, this PR removes duplicate code in DTM.
**Release Notes**: None.
> DTM: Don't accept DMI response when busy

- src/main/scala/amba/axi4/RegisterRouter.scala
Adds a trait that allows for register-mapped devices to be created of the form:
```
class AXI4Device(busWidthBytes: Int, params: DeviceParams)(implicit p: Parameters)
extends RegisterRouter(...) with HasAXI4ControlRegMap
```
> axi4: add HasAXI4ControlRegMap

- src/main/scala/tile/BaseTile.scala
This is one step towards eventually replacing the awkward `TLSharedMemoryEdge`.
> tile: add support to view unified managers

- scripts/vlsi_mem_gen
**Related issue**: Vivado cannot properly infer large Block Rams
> Vivado bram fix

- src/main/scala/rocket/RocketCore.scala
- src/main/scala/util/CoreMonitor.scala
This PR adds clock and reset signals to CoreMonitorBundle, which is used in verification environments to sample core commits. Using core and clock signals from the core itself allows to have cores with clock speeds different that the verification environment clock speed.
> Extend CoreMonitorBundle with Clocked trait.

- src/main/scala/diplomacy/Resources.scala
- src/main/scala/diplomaticobjectmodel/DiplomaticObjectModelUtils.scala
This PR adds support for generating the object model global external interrupts in the DiplomaticObjectModelAddressing object.
> Add external global interrupts

- src/main/scala/tile/FPU.scala
This avoids having to clock the FPU during MMIO loads, right up until the load comes back.
> Move FPU load pipeline register into ungated clock domain

- src/main/scala/diplomaticobjectmodel/DiplomaticObjectModelUtils.scala
Added an additional gating condition to the  getOMMemoryRegions memory region creation function. This condition fixes a bug where certain memories were not included in the memory regions.
> adding rangefilter to the getOMMemoryRegions gating expression

- build.sbt
Invoking `sbt` normally will preserve the current behavior. Invoking `sbt -DROCKET_USE_MAVEN` will use maven deps.
@jackkoenig 
> Add flag for rocket to conditionally use maven deps

- src/main/scala/rocket/DCache.scala
- src/main/scala/rocket/PMP.scala
This is a new feature that's disabled by default, so it probably doesn't affect anyone.
> For per-address cache flushing, don't evict same line twice

- Makefrag
- build.sbt
Hardfloat used to require Chisel 2 for testing, which is only published for Scala 2.11. Rocket uses Scala 2.12, which meant the build system needed a workaround to make hardfloat use Scala 2.12 when being used as a part of rocket.
Hardfloat's tests have been updated to use Chisel 3, so the workaround is no longer needed. This commit bumps the hardfloat submodule and cleans up build.sbt to use Scala 2.12 only and Makefrag to not use `++2.12.4`.
> Bump hardfloat, clean up build.

- src/main/scala/groundtest/GroundTestSubsystem.scala
- src/main/scala/groundtest/Tile.scala
- src/main/scala/groundtest/TraceGen.scala
- src/main/scala/subsystem/HasTiles.scala
- src/main/scala/subsystem/RocketSubsystem.scala
- src/main/scala/tile/BaseTile.scala
- src/main/scala/tile/L1Cache.scala
- src/main/scala/tile/LookupByHartId.scala
- src/main/scala/tile/RocketTile.scala
This PR makes a number of modifications to the BaseTile class, with the goal of encapsulating all the legacy weirdness around propagating the keys from `augmentedTileParameters` through all tile submodules.
Specific changes:
- adds `BaseTile.visibilityNode`
- adds `HasNonDiplomaticTileParameters` trait
- replace `SharedMemoryTLEdge` with `TileVisibilityNodeKey`
- encapsulate tile Parameter augmentation within `BaseTile`
- simplify tile input constants
- provide some `LookupByHartImpl` implementations
- remove `subsystem.augmentedTileParams`
The main trick to getting the legacy key/values set inside the tile is to use a public constructor that captures and alters the implicit parameters to contain them, before handing it off to a private constructor that in turn propagates the altered …
> Refactor BaseTile again (to obviate augmentedTileParameters)

- src/main/scala/tile/L1Cache.scala
**Type of change**: code clarification
**Release Notes**: split the "untagBits min pgIdxBits" sub-term from "tagBits" into its own variable "pgUntagBits"
> trait HasL1CacheParameters def pgUntagBits

- src/main/scala/groundtest/GroundTestSubsystem.scala
- src/main/scala/tilelink/SRAM.scala
This modifies the TLSRAM API to add a new positional argument which enables support for atomics. This should only break bad code which did not use key=value in the constructor.
> TLSRAM: add support for integrated atomic ALU

- src/main/scala/groundtest/TraceGen.scala
- src/main/scala/rocket/CSR.scala
- src/main/scala/rocket/Consts.scala
- src/main/scala/rocket/DCache.scala
- src/main/scala/rocket/HellaCache.scala
- src/main/scala/rocket/HellaCacheArbiter.scala
- src/main/scala/rocket/IDecode.scala
- src/main/scala/rocket/NBDcache.scala
- src/main/scala/rocket/PTW.scala
- src/main/scala/rocket/RocketCore.scala
- src/main/scala/rocket/ScratchpadSlavePort.scala
- src/main/scala/rocket/TLB.scala
- src/main/scala/tile/BaseTile.scala
- src/main/scala/tile/LazyRoCC.scala
- Optionally have the D$ send MMIO responses to the processor over a separate channel.  This allows MMIO loads to run at full throughput.
- Support no-allocate loads and stores.  There are no opcodes for these, so they aren't currently used.
- Support dynamic selection between Sv39 and Sv48.  Default is still Sv39 only; enable Sv48 by changing PgLevels from 3 to 4.
> Memory system features

- src/main/scala/util/Property.scala
The CrossProperty Library is changed to not create cover properties for crosses that are excluded. This removes false cover points.
> Do not create covers for crosses that are excluded

- src/main/scala/rocket/HellaCache.scala
- src/main/scala/rocket/ScratchpadSlavePort.scala
- src/main/scala/tile/RocketTile.scala
The power-of-2 constraint on the number of sets only fundamentally applies to the cache indexing scheme; it doesn't matter for scratchpads.
> Support non-power-of-2 data scratchpads

- src/main/scala/tile/BusErrorUnit.scala
In principle, clients should not reference `chisel3.core` directly. In the case of `DontCare`, we want to force references to its definition in the chisel3 package to avoid having `DontCare` defined as a user node.
Replace reference to `chisel3.core.DontCare` with `chisel3.DontCare`
> Replace chisel3.core.DontCare with chisel3.DontCare

- src/main/scala/diplomacy/BundleBridge.scala
- src/main/scala/diplomacy/Nodes.scala
- src/main/scala/groundtest/TraceGen.scala
- src/main/scala/interrupts/Nodes.scala
- src/main/scala/tile/BaseTile.scala
- src/main/scala/tilelink/Nodes.scala
- src/main/scala/util/PSDTestMode.scala
This PR introduces a new category of Node types: EphemeralNodes. These nodes act like IdentityNodes in the sense that anything connected to their inputs and outputs are just connected to each other pass-through. They differ, however, in that the node disappears from the final node graph. This makes it possible to define a logical connection point that can be used to interconnect pieces all around the design, and yet have the eventual connections be point-to-point.
**Related issue**: Remove wires plumbed in and out of tiles
Added Ephemeral Node type.
> Ephemeral nodes

- emulator/Makefrag-verilator
**Related issue**: #1762
Add `-Wno-UNOPTTHREADS` to stop verilator complaining about its inability _to provide requested parallelism_ and subsequently failing the UnittestSuite regression tests.
> Add -Wno-UNOPTTHREADS to verilator --threads

- README.md
- README_TRAVIS.md
- regression/Makefile
Update pointers and READMEs accordingly.
> riscv/riscv-tools is now at freechipsproject/rocket-tools

- src/main/scala/diplomacy/Nodes.scala
- src/main/scala/tile/BaseTile.scala
- src/main/scala/util/PSDTestMode.scala
They don't go anywhere, so don't plumb them uselessly to the top!
Ephemeral nodes should not create wires
> diplomacy: don't auto-punch ephemeral node wires

- src/main/scala/diplomaticobjectmodel/model/OMCaches.scala
- src/main/scala/diplomaticobjectmodel/model/OMRocketCore.scala
nTLBEntries is only applicable to L1 caches
make nTLBEntries optional
> nTLBEntries is only applicable to L1 caches

- src/main/scala/rocket/PMP.scala
The pmp cover points were using the default signal to check for setting of cfg register. This was removed and a new cover point for matching of different modes with lock bit was added
> PMP cover points modification

- src/main/scala/tilelink/AtomicAutomata.scala
The TLAtomicAutomata uses a diplomatic graph search to ensure that it is at the root of a tree of nodes. This property is necessary but not sufficient for correct behavior; no other master should be able to intervene between the AA's read and write operations. However, this check should actually only check tree violations for managers to which the AA is actually adding atomics support. For example, if a manager natively supports atomics, and `passthru` is enabled, then the AA does not have to be at the root of a tree with respect to that manager. This change makes the check handled on a per-manager basis.
**Impact**: no RTL change, only further specificity of a diplomatic safeguard
> tilelink: improve specificity of AtomicAutomata graph check

- src/main/scala/amba/axi4/SRAM.scala
- src/main/scala/diplomacy/SRAM.scala
- src/main/scala/diplomaticobjectmodel/DiplomaticObjectModelUtils.scala
- src/main/scala/diplomaticobjectmodel/model/OMMemory.scala
- src/main/scala/subsystem/Ports.scala
- src/main/scala/util/Annotations.scala
- src/main/scala/util/DescribedSRAM.scala
I would like to be able to enable ExtMem sizes larger than 2GB. Currently this only fails in the simulation memory. Now that chisel and firrtl support BigInt depth on memories we can support this cleanly.
**Type of change**: bug report / feature request.
Certain configs being invalid straddles the line between bug and feature request
**Impact**: API modification.
Certain internal(-only?) interfaces now use BigInt rather than Int
**Development Phase**: implementation.
I'm using this downstream and have tested it with 1,2,4,8,16GB ExtMem sizes. Note that past 1GB ExtMem sizes you will need special handling of the testharness memory in some simulators such as vcs
Enable ExtMem sizes greater than 2GB by including BigInt memories from a recent chisel3 and …
> Move SeqMems to BigInts and plumb through test mems

- src/main/scala/diplomacy/Parameters.scala
- src/main/scala/tilelink/AtomicAutomata.scala
- src/main/scala/tilelink/Bundles.scala
- src/main/scala/tilelink/Edges.scala
- src/main/scala/tilelink/Parameters.scala
- src/main/scala/tilelink/UserUser.scala
- src/main/scala/unittest/Configs.scala
This PR makes it possible to add arbitrary meta-data to TileLink requests. The additional bit fields are described by case-class-based elaboration-time meta-data. There are helper methods to add a bitfield to an existing port in a TLAdapter and inject/extract the wire values to/from a Tilelink bundle.
**Release Notes** User bits added to TileLink
> Tilelink user bits

- src/main/scala/diplomaticobjectmodel/logicaltree/LogicalTrees.scala
- src/main/scala/diplomaticobjectmodel/model/OMPLIC.scala
The existing implementation of the OMPLIC object model was missing the `targets` attribute, since it was just being hardcoded to `Nil`. This PR actually fills in the implementation using information available via Diplomacy.
In the object model, the PLIC InterruptTargets are essentially a tuple of (core, privilege mode), and I realized that we can infer the privilege mode by using the interrupt number, which is available in Diplomacy. The RISC-V Privileged spec states that `mcause` values 8, 9, and 11 map to User, Supervisor, and Machine mode external interrupts respectively, so I use those to create the object model InterruptTargets.
I've run this on several …
> Set object model PLIC InterruptTargets

- src/main/scala/diplomaticobjectmodel/model/OMDebug.scala
The OMDebug schema was significantly changed. 
The new version of the OMDebug was missing the type field. 
This PR adds the missing type field to the OMDebug
This is the PR that broke that OMDebug.
[https://github.com/freechipsproject/rocket-chip/pull/1935](https://github.com/freechipsproject/rocket-chip/pull/1935)
> added type field

- src/main/scala/rocket/CSR.scala
Previously, it returned lower 32 bits (though writes were correct).
Affects RV32 cores with nPerfCounters > 0.  Doesn't affect cycle/instret.
> In RV32, make mhpmcounterXh return upper 32 bits of counter

- src/main/scala/amba/ahb/Bundles.scala
- src/main/scala/amba/ahb/Parameters.scala
- src/main/scala/amba/ahb/Protocol.scala
- src/main/scala/tilelink/ToAHB.scala
This PR builds upon the work done in https://github.com/freechipsproject/rocket-chip/pull/1931 which adds add arbitrary meta-data to TileLink requests, and sends these out on the new AHB HAUSER port which has been added to the ToAHB module. 
**Related issue**: https://github.com/freechipsproject/rocket-chip/pull/1931 
UserBits added to the AHB port.
> Added the HAUSER field to the ToAHB

- src/main/scala/util/Annotations.scala
- src/main/scala/util/DescribedSRAM.scala
* `SRAMAnnotation`s have the target type `ReferenceTarget` to allow for unique path generation
* `DescribedSRAM`s generate a unique ID that can be correlated to the OM
@derekpappas @jackkoenig
> Modifying SRAMAnnotations for OM purposes

- src/main/scala/rocket/CSR.scala
See #1761 for explanation.  Fixes same issue for *deleg and *counteren.
> Fix simulation pessimism by moving WARL masks from D to Q

- src/main/scala/rocket/CSR.scala
**Related issue**:  Cover properties for machine mode traps should take into account that the trap is not being delegated to supervisor mode.
> Fix covers for machine mode traps

- src/main/scala/diplomacy/Resources.scala
- src/main/scala/diplomacy/SRAM.scala
- src/main/scala/diplomaticobjectmodel/ConstructOM.scala
- src/main/scala/diplomaticobjectmodel/DiplomaticObjectModelUtils.scala
- src/main/scala/diplomaticobjectmodel/logicaltree/LogicalTreeNode.scala
- src/main/scala/diplomaticobjectmodel/logicaltree/LogicalTrees.scala
- src/main/scala/diplomaticobjectmodel/logicaltree/RocketLogicalTreeNode.scala
- src/main/scala/diplomaticobjectmodel/model/OMRocketCore.scala
- src/main/scala/groundtest/GroundTestSubsystem.scala
- src/main/scala/rocket/ScratchpadSlavePort.scala
- src/main/scala/subsystem/BaseSubsystem.scala
- src/main/scala/subsystem/RocketSubsystem.scala
1. Changes the getOMComponents signature - ResourceBindingsMap is now ResourceBindings
2. Registers the ResourceBindingsMaps for each BindingScope 
3. Modified the LogicalModuleTree bind function to look up the ResourceBindings for each device in the list of BindingScopes
> refactored the getOMComponents ResourceBindingsMap to ResourceBindings

- src/main/scala/diplomaticobjectmodel/model/OMDebug.scala
The fact that there was a name conflict in APB implies that in the future there may be name conflicts in other debug interface types, so be explicit about it.
> OMDebug: be consistent about the interface type

- src/main/scala/amba/apb/ToTL.scala
APB2TL Converter was not checking for address legality. Tile Link protocol forbids illegal addresses, so they need to be diverted at the source.
> APB2TL: Check for address legality

- scripts/vlsi_rom_gen
**Related issue**: #951
- reduce the length of the `path` that can be assigned by `+maskromhex=%s` in order to support compilation by `verilator`.
- also make variables local to the `initial`-block
> Verilator support for +maskromhex=%s (from vlsi_rom_gen)

- src/main/scala/diplomacy/SRAM.scala
- src/main/scala/diplomaticobjectmodel/model/OMDebug.scala
**Impact**:  bug fix
SRAM's were not generating a memory region after the LTN refactor
This PR fixes the problem.
Also reverts the Debug module debug interface names - removes the Debug prefix
> fix sram memory regions

- src/main/scala/rocket/CSR.scala
- src/main/scala/rocket/RocketCore.scala
- src/main/scala/tile/BaseTile.scala
- src/main/scala/tile/Core.scala
Right now, the DTS generator unconditionally prints RVxxI.  Make it so that it knows how to print RVxxE, too.
> Teach DTS generator about RV32E

- src/main/scala/tile/BaseTile.scala
Adds the hardware breakpoint count to the DTS entry for every CPU.
**Impact**:API addition (no impact on existing code)
> Base Tile: add the hardware breakpoint count to DTS

- src/main/scala/subsystem/SystemBus.scala
The policy parameter to the `SystemBus` was being ignored.
Be careful changing the policy away from the default round-robin; the index of clients depends on the order of diplomacy connections and you can cause starvation with certain tile and front port configurations.
> sbus: actually use policy param

- src/main/scala/diplomaticobjectmodel/DiplomaticObjectModelUtils.scala
- src/main/scala/diplomaticobjectmodel/logicaltree/LogicalTreeNode.scala
- src/main/scala/diplomaticobjectmodel/logicaltree/LogicalTrees.scala
There was a change in the LogicalTreeNode (LTN) API. 
In the LogicalTreeNode’s getOMComponents() function, we replaced the ResourceBindingsMap argument with ResourceBindings and a device was added the LTN constructor. 
Since the ResourceBindings is now being passed into the getOMComponentHelper, the device is no longer needed in the getOMComponentHelper to look up the ResourceBindings in the ResourceBindingsMap. 
The LTN device conditions the lookup of the ResourceBindingsMap associated with the device in the ResourceBindingsMaps during the traversal of the parent child …
> refactoring the getOMComponentHelper - removed device

- src/main/scala/diplomaticobjectmodel/logicaltree/RocketLogicalTreeNode.scala
- src/main/scala/rocket/Frontend.scala
- src/main/scala/tile/RocketTile.scala
After the refactoring done in https://github.com/freechipsproject/rocket-chip/pull/1956, we accidentally introduced a regression that caused the memory addresses reported in the object model to be incorrect for the memories inside of the Rocket Tile. The cause of the bug is that the same set of resource bindings that is associated with the Rocket Core itself were getting passed in to the code that generates the Object Model for the ICache/DCache/DTIM. However, the resource bindings for the Rocket Core uses the `reg` field — which is normally used to represent a memory address — in order to represent the hart id. Hence, when passed to the …
> Fix logical tree node for Rocket memories

- src/main/resources/vsrc/plusarg_reader.v
- src/main/scala/util/PlusArg.scala
- PlusArgs can now have explicitly specified widths wider than 32b.
- `PlusArg` still parses a %d decimal
- The default value is passed with a `RawParam` that sets the width (this could be turned back into an `IntParam` if FIRRTL correctly output BigInt literals)
- The default width is 32b
- Updated to use chisel3 apis and imports
> util: add width param to PlusArg and update it to chisel3

- src/main/scala/diplomaticobjectmodel/model/OMBusMemory.scala
Adding a types field to `OMBusMemory` so that object model parsers can recognize the component.
> Add types to OMBusMemory

- regression/Makefile
In particular, riscv-qemu (which currently can't build at all, due to a missing dependence).
> Make rocket-tools build faster by skipping some submodules

- src/main/scala/diplomaticobjectmodel/logicaltree/LogicalTreeNode.scala
- src/main/scala/subsystem/BaseSubsystem.scala
The notion of a global "root" logical tree node causes issues with putting another layer of logical tree nodes above the previous "root". If a node attaches itself to the global root, then it no longer becomes possible to insert a different node in between the root and the previous node. In order to ensure that it is always possible to add another layer above, we remove the concept of a static, global "root" and require the next layer to attach the child nodes.
> Remove root logical tree node.

- src/main/scala/diplomaticobjectmodel/DiplomaticObjectModelUtils.scala
- src/main/scala/diplomaticobjectmodel/logicaltree/LogicalTrees.scala
- src/main/scala/diplomaticobjectmodel/model/OMBusMemory.scala
- src/main/scala/diplomaticobjectmodel/model/OMCaches.scala
- src/main/scala/diplomaticobjectmodel/model/OMRocketCore.scala
- src/main/scala/tilelink/SRAM.scala
For some reason the type of the OMECC (Identity, Parity, SEC, SECDED) was not in the OMECC. The type hierarchy starting with "OMECC", ... was present in the _types field. I removed the val's from the  object OMECC and created a case class hierarchy with the ECC type set in the overridden _types field.
The names of the helper functions were also changed to make the purpose of each helper function clearer.
> Rewrote OMECC to fix type issues

- src/main/resources/vsrc/AsyncResetReg.v
```
Lint-[WMIA-L] Width mismatch in assignment
.../AsyncResetReg.v, 69
Width mismatch between LHS and RHS is found in assignment:
The following 32-bit wide expression is assigned to a 1-bit LHS target:
Source info: q = RESET_VALUE;
Expression: q
Lint-[WMIA-L] Width mismatch in assignment
.../AsyncResetReg.v, 77
Width mismatch between LHS and RHS is found in assignment:
The following 32-bit wide expression is assigned to a 1-bit LHS target:
Source info: q <= RESET_VALUE;
Expression: q
```
> lint width mismatch

- src/main/scala/util/Annotations.scala
- src/main/scala/util/DescribedSRAM.scala
This reverts commit 0efc0aa06add44e2cafc4b3eebedd00ab6c3eacc.
Currently there are issues where the new annotations prevent deduplication. I'm not sure what the best way to do this is. This revert conflicted with https://github.com/freechipsproject/rocket-chip/pull/1969 so I just set the `uid` to `0` which is being passed to `DiplomaticObjectModelAddressing.makeOMSRAM`, is this okay @derekpappas?
> Revert "Modifying SRAMAnnotations for OM purposes (#1944)"

- src/main/scala/subsystem/MemoryBus.scala
The AXI4 converter thinks the TLBroadcast wants lots of concurrency because it uses lots of IDs.  But its concurrency is much lower (limited by nTrackers), so shrink the ID space to that amount.
> Instantiate a TLSourceShrinker after the TLBroadcast

- src/main/scala/diplomaticobjectmodel/logicaltree/LogicalTrees.scala
There's an unused call to `DiplomaticObjectModelAddressing.describeInterrupts` in the `BusMemoryLogicalTreeNode`. This is actually causing an issue because it depends on having the `name` field destructured from the `Description` that `device.describe()` returns, and `device.describe()` may actually fail if the bus memory has multiple address ranges. Without going into a whole lot of detail, that call fails because there is an assertion that requires the number of elements in the DTS `reg-names` field to be equal to the number of `reg` elements, which are 1-1 with an address range.
This call to `device.describe()` is not even currently being used because we only call it to get …
> Remove unused call to describeInterrupts.

- src/main/scala/rocket/DCache.scala
Prevents propagation of stale data when C channel isn't FIFO
> Don't accept probes while waiting for release ack

- src/main/scala/rocket/CSR.scala
- src/main/scala/rocket/RocketCore.scala
Conditionalize the generation of coverpoints for page faults at various stages of pipeline on the basis of the core having Virtual Memory support. I have tested that this builds the right covers in Verilog.
> Conditionalize generation of page fault covers

- src/main/scala/subsystem/Configs.scala
Add an intermediate, "medium" config option, with only the FPU
disabled, that still provides an MMU and thus supports VM.
> subsystem: add 'WithNMedCores' config w. only FPU disabled

- src/main/resources/vsrc/TestDriver.v
- vsim/Makefrag
This adds a Verilog define holding the model name to TestDriver.v and
passes the model name (defined in the top level Makefrag) into a VCS
compilation pass.
This fixes a bug where deviating from the default model of
"TestHarness" would cause VCS to (rightly) not find the model.
- Enable vsim/vcs to work with models other than "TestHarness"
> Genericize TestDriver.v in terms of Model

- src/main/scala/subsystem/BusTopology.scala
- src/main/scala/subsystem/RocketSubsystem.scala
- src/main/scala/system/ExampleRocketSystem.scala
Unify the addition of MaskROMs to all subsystem classes that inherit from `RocketSubsystem`
Factor out bus interconnections in `HasHierarchicalBusTopology`
> subsystem: add MaskROM to RocketSubsystem

- src/main/scala/devices/debug/Periphery.scala
When debug interface was APB, this was not getting connected up to the top level I/Os. Now this is connected up so that Post-Silicon-Debug controls can fully control the internal reset generated by `dmactive`.
> PSD: Ensure that PSD is connected to dmactive-derived reset 

- src/main/scala/amba/apb/Bundles.scala
- src/main/scala/amba/apb/Parameters.scala
- src/main/scala/tilelink/Fragmenter.scala
- src/main/scala/tilelink/ToAPB.scala
This PR adds a `pauser` optional field in APB bundles to propagate `UserBits` metadata from TileLink to APB dongles.
- Added `pauser` in `APBBundle`, and relevant support in APB port parameters
- Added support for userbits in `TLToAPB` adapter
- Added support for userbits in `TLFragmenter` node
- Verified propagation of userbits in waveform
**Related issue**:  #1931, #1939 
**Type of change**: feature add
**Impact**: no functional change | API addition (no impact on existing code)
Added `UserBits` support in APB and `TLFragmenter`.
> APB userbits support

- src/main/resources/vsrc/RoccBlackBox.v
- src/main/scala/subsystem/Configs.scala
- src/main/scala/tile/LazyRoCC.scala
This adds a `BlackBoxExample` RoCC with a backing Verilog BlackBox resource in `vsrc/RoccBlackBox.v`. Rocket Chip parameters are passed as Verilog parameters. Nothing with diplomatic parameters / TL is dealt with here.
The backing example RoCC implements a simple accumulation of rs1 and rs2 into a persistent register that is returned if `xd` is set.
**Related Issue**: https://github.com/freechipsproject/rocket-chip/issues/1195#issuecomment-488546441chip/issues/1195
> BlackBox RoCC Example

- src/main/scala/tilelink/BankBinder.scala
The way BankBinder is currently written, it won't work if you connect it to managers which themselves have the blocks striped across them. You would get a requirement failure because the addresses of some of the managers would be empty, as the bank and channel would be for a mutually exclusive set of blocks. This commit makes the bank skip over managers with which it has no address range in common.
> BankBinder should skip addresses with no intersecting address ranges

- src/main/scala/devices/debug/Debug.scala
CDC checking tools require that external trigger outputs feeding into a clock-crossing synchronizer be driven directly from a register in the source clock domain.
> Drive extTrigger.out.req directly from register

- src/main/scala/tilelink/ToAHB.scala
In non-flow mode, the following sequence of events could occur:
1. a.valid goes high with a request => hbusreq goes high
2. hgrant goes high (in the same cycle as 1 or much later)
3. granted goes high causing a.ready to go high
... and also lowers the hbusreq cause (a.valid && !granted)
4. the output request causes hbusreq to go high again
This change shortens the behaviour of the non-flow pipeline:
1. a.valid goes high with a request => hbusreq goes high
2. hgrant goes high ***causing a.ready to go high***
3. the output request keeps hbusreq high, despite granted high
@jchang0 Please run some VIP against this modified adapter...
The adapter still does not support the AHB SPLIT or RETRY response codes.
**Development Phase**: …
> ToAHB: fix a bug where a non-flow AHB adapter lowers hbusreq

- src/main/scala/rocket/CSR.scala
The CSR address from the wrong pipeline stage was used when detecting whether the DRET instruction was valid, causing spurious exceptions.
> Fix regression introduced by #2029

- src/main/scala/amba/ahb/Parameters.scala
- src/main/scala/tilelink/Fragmenter.scala
- src/main/scala/tilelink/UserUniformer.scala
- src/main/scala/tilelink/UserUser.scala
`TLUserUniformer` adapter allows a default value of a particular type of TileLink user bits to be applied to all clients that were not supplying values for those types themselves. If a client does supply a value, this is passed through the adapter. As a result, all clients appear to supply the same number of the specified type of user bits. For clients that supply their own user bits, those bits will appear at the highest indexes, and any default values will appear at lower indexes.
The adapter currently requires the widths of all UserBits of the specified type to be the same, because I didn't want to have to handle all the cases where different clients have different subsets of the same type of user bits. This restriction could probably be relaxed with sufficient effort.
Other …
> TileLink: UserUniformer
